Repository openzfs/zfs, pull requests merged in 2018-11, with the labels that each got.

#8057 Update zfs-events.5 with info from PSARC 2009/497
  man/man5/zfs-events.5
Labels: Status: Accepted

#8080 ztest: reduce gangblock creation
  cmd/ztest/ztest.c
  module/zfs/metaslab.c
Labels: Status: Code Review Needed

#8079 zpool: bogus error for invalid dedupditto value
  lib/libzfs/libzfs_pool.c
Labels: Status: Code Review Needed

#8097 Fix libudev dependency in libzutil
  include/libzutil.h
  lib/libzutil/zutil_import.c
Labels: Status: Code Review Needed

#8082 Make vdev_set_deferred_resilver() recursive
  module/zfs/vdev.c
Labels: Status: Code Review Needed

#8083 Fix vdev removal finishing race
  module/zfs/vdev_removal.c
Labels: Status: Code Review Needed

#8084 Replay logs before starting ztest workers
  cmd/ztest/ztest.c
  module/zfs/dsl_crypt.c
Labels: Status: Code Review Needed

#8085 Fix dirtying vdev config on with RO spa
  module/zfs/vdev.c
Labels: Status: Accepted

#8086 Fix divide by zero during indirect split damage
  module/zfs/vdev_indirect.c
Labels: Status: Accepted

#8094 Fix !zilog_is_dirty() assert during ztest
  cmd/ztest/ztest.c
Labels: Status: Accepted

#8102 Add BuildRequires: gcc, make, elfutils-libelf-devel
  rpm/generic/zfs-kmod.spec.in
  rpm/generic/zfs.spec.in
Labels: Status: Code Review Needed, Type: Building

#8081 Fix test zfs_mount_006_pos
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_006_pos.ksh
Labels: Status: Accepted

#8088 Fix and reenable zfs_rename tests
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/cli_root/zfs_rename/zfs_rename_006_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_rename/zfs_rename_009_neg.ksh
Labels: Status: Code Review Needed

#8045 Update zfs_admin_snapshot default value (disabled)
  module/zfs/zfs_ctldir.c
  tests/zfs-tests/tests/functional/delegate/cleanup.ksh
  tests/zfs-tests/tests/functional/delegate/delegate_common.kshlib
  tests/zfs-tests/tests/functional/delegate/setup.ksh
  tests/zfs-tests/tests/functional/snapshot/cleanup.ksh
  tests/zfs-tests/tests/functional/snapshot/setup.ksh
Labels: Status: Accepted

#7756 Add zpool status -d (delays) and -p (parseable)
  cmd/zpool/zpool_main.c
  include/sys/fm/fs/zfs.h
  include/sys/fs/zfs.h
  include/sys/spa.h
  include/sys/zio.h
  man/man5/zfs-events.5
  man/man5/zfs-module-parameters.5
  man/man8/zpool.8
  module/zfs/vdev.c
  module/zfs/vdev_label.c
  module/zfs/zfs_fm.c
  module/zfs/zio.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/fault/Makefile.am
  tests/zfs-tests/tests/functional/fault/zpool_status_-s.ksh
  tests/zfs-tests/tests/perf/perf.shlib
Labels: Status: Accepted

#8114 dracut needs ENCRYPTIONROOT quoted with loading key
  contrib/dracut/90zfs/mount-zfs.sh.in
Labels: Status: Code Review Needed

#8093 Make initramfs-tools script encryption aware
  contrib/initramfs/scripts/zfs.in
Labels: Status: Accepted

#8119 Fix systemd spec file macros
  config/user-systemd.m4
  rpm/generic/zfs-dkms.spec.in
  rpm/generic/zfs-kmod.spec.in
  rpm/generic/zfs.spec.in
  rpm/redhat/zfs-kmod.spec.in
Labels: Status: Code Review Needed

#8120 Fix coverity defects: CID 184285
  module/zfs/vdev_label.c
Labels: Status: Accepted

#8139 ZTS: "checksum" test group needs "lscpu"
  tests/zfs-tests/include/commands.cfg
Labels: Status: Accepted

#8136 Fix parsing of zpool status in checksum test
  tests/zfs-tests/tests/functional/checksum/filetest_001_pos.ksh
Labels: Status: Accepted

#8134 man/zfs.8: document 'received' property source
  man/man8/zfs.8
Labels: Status: Accepted

#8133 zpool: allow split of whole-disk devices
  cmd/zpool/zpool_vdev.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zpool_split/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_cliargs.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_devices.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_encryption.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_props.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_resilver.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_vdevs.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_wholedisk.ksh
Labels: Status: Accepted

#8153 Fix typo in update to zfs-module-parameters(5)
  man/man5/zfs-module-parameters.5
Labels: Status: Accepted

#8152 ZTS: fix "not found" errors
  tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh
  tests/zfs-tests/tests/functional/alloc_class/alloc_class_013_pos.ksh
  tests/zfs-tests/tests/functional/alloc_class/cleanup.ksh
  tests/zfs-tests/tests/functional/channel_program/lua_core/tst.exists.ksh
  tests/zfs-tests/tests/functional/channel_program/lua_core/tst.nvlist_to_lua.ksh
  tests/zfs-tests/tests/functional/channel_program/lua_core/tst.return_nvlist_neg.ksh
  tests/zfs-tests/tests/functional/channel_program/lua_core/tst.return_nvlist_pos.ksh
  tests/zfs-tests/tests/functional/channel_program/lua_core/tst.return_recursive_table.ksh
  tests/zfs-tests/tests/functional/channel_program/lua_core/tst.timeout.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.destroy_fs.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.destroy_snap.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_shared_device.ksh
  tests/zfs-tests/tests/functional/cli_user/misc/setup.ksh
  tests/zfs-tests/tests/functional/cli_user/misc/zpool_upgrade_001_neg.ksh
Labels: Status: Accepted

#8111 Remove races from scrub / resilver tests
  module/zfs/dsl_scan.c
  module/zfs/vdev_removal.c
  tests/zfs-tests/tests/functional/cli_root/zpool_import/cleanup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_device_replaced.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_rewind_device_replaced.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_resilver/zpool_resilver.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_resilver/zpool_resilver_restart.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_scrub/cleanup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_scrub/zpool_scrub_002_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_scrub/zpool_scrub_003_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_scrub/zpool_scrub_004_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_resilver.ksh
  tests/zfs-tests/tests/functional/removal/removal.kshlib
Labels: Status: Accepted

#8150 zfs_dbgmsg() is not safe from every context
  module/zfs/vdev_disk.c
Labels: Status: Accepted

#8105 Fix consistency of ztest_device_removal_active
  cmd/ztest/ztest.c
  module/zfs/spa_checkpoint.c
  module/zfs/vdev_removal.c
Labels: Status: Accepted
