Repository openzfs/zfs, pull requests merged in 2018-10, with the labels that each got.

#7934 Refine split block reconstruction
  cmd/ztest/ztest.c
  man/man5/zfs-module-parameters.5
  module/zfs/vdev_indirect.c
Labels: Status: Accepted

#7968 remove duplicate macro in dsl_dir.h
  include/sys/dsl_dir.h
Labels: Status: Accepted

#7963 Prefix all refcount functions with zfs_
  cmd/ztest/ztest.c
  include/sys/refcount.h
  include/sys/trace_dbuf.h
  module/zfs/abd.c
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dbuf_stats.c
  module/zfs/dmu_tx.c
  module/zfs/dnode.c
  module/zfs/dnode_sync.c
  module/zfs/dsl_crypt.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_destroy.c
  module/zfs/dsl_scan.c
  module/zfs/metaslab.c
  module/zfs/refcount.c
  module/zfs/rrwlock.c
  module/zfs/sa.c
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/zfs_ctldir.c
  module/zfs/zfs_znode.c
  module/zfs/zio.c
Labels: Status: Accepted

#7962 ZTS: Fix snapshot_009_pos, snapshot_010_pos
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/snapshot/snapshot_009_pos.ksh
  tests/zfs-tests/tests/functional/snapshot/snapshot_010_pos.ksh
Labels: Status: Accepted

#7967 changelist should be able to iter on mounts
  include/libzfs.h
  lib/libzfs/libzfs_changelist.c
  lib/libzfs/libzfs_iter.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zfs_unmount/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_unmount/zfs_unmount_nested.ksh
Labels: Status: Accepted

#7949 Refcounted DSL Crypto Key Mappings
  cmd/ztest/ztest.c
  include/sys/dsl_crypt.h
  include/sys/dsl_dataset.h
  module/zfs/dmu_objset.c
  module/zfs/dsl_crypt.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_pool.c
  module/zfs/spa.c
  module/zfs/zil.c
Labels: Status: Accepted

#7977 Add new fnvlist_lookup_* functions
  include/sys/nvpair.h
  module/nvpair/fnvpair.c
Labels: Status: Accepted

#7884 Fix ASSERT macros to not over-expand
  include/spl/sys/debug.h
  lib/libspl/include/assert.h
Labels: Status: Accepted

#7985 add codecheck make target
  Makefile.am
Labels: Status: Code Review Needed

#7984 Warn if checking programs are not installed
  Makefile.am
Labels: Status: Code Review Needed

#7965 create /proc/sys/kernel/spl/gitrev with git hash
  Makefile.am
  copy-builtin
  include/.gitignore
  include/spl/sys/sysmacros.h
  module/spl/spl-generic.c
  module/spl/spl-proc.c
  module/zfs/spa_history.c
  scripts/Makefile.am
  scripts/make_gitrev.sh
Labels: Status: Accepted

#7982 Refactor dmu_recv into its own file
  include/sys/Makefile.am
  include/sys/dmu_recv.h
  include/sys/dmu_send.h
  include/sys/dsl_bookmark.h
  lib/libzpool/Makefile.am
  module/zfs/Makefile.in
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/dmu_send.c
  module/zfs/dnode_sync.c
  module/zfs/dsl_dataset.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#7978 Print "(repairing)" in zpool status again
  cmd/zpool/zpool_main.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zpool_scrub/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_scrub/zpool_scrub_print_repairing.ksh
Labels: Status: Accepted

#8004 Check scheduler for "noop" before setting "noop"
  contrib/initramfs/scripts/zfs.in
Labels: Status: Accepted

#7991 restrict changelist mounted-dataset iteration
  include/libzfs_impl.h
  lib/libzfs/libzfs_changelist.c
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_mount.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zfs_inherit/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_inherit/zfs_inherit_mountpoint.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_rename/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_rename/zfs_rename_mountpoint.ksh
Labels: Status: Accepted

#8014 Define timestruc_t for Lustre compatibility
  include/spl/sys/time.h
Labels: Status: Accepted

#7979 OpenZFS 9847 - leaking dd_clones (DMU_OT_DSL_CLONES) objects
  cmd/zdb/zdb.c
  module/zfs/dsl_destroy.c
  module/zfs/vdev_indirect_mapping.c
Labels: Status: Accepted

#8020 Add zts-report.py to python shebang exclusion
  rpm/generic/zfs.spec.in
Labels: Status: Accepted, Type: Packaging

#7939 deadlock between mm_sem and tx assign in zfs_write() and page fault
  include/spl/sys/uio.h
  include/sys/uio_impl.h
  module/zcommon/zfs_uio.c
  module/zfs/zfs_vnops.c
  tests/zfs-tests/cmd/mmapwrite/mmapwrite.c
  tests/zfs-tests/tests/functional/mmap/mmap_write_001_pos.ksh
Labels: Status: Accepted

#7981 Add types to featureflags in zfs
  cmd/zdb/zdb.c
  include/sys/dsl_dataset.h
  include/zfeature_common.h
  module/zcommon/zfeature_common.c
  module/zfs/dmu_object.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_send.c
  module/zfs/dnode_sync.c
  module/zfs/dsl_crypt.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_destroy.c
Labels: Status: Accepted

#8031 Linux does not HAVE_DNLC
  Makefile.am
  module/zfs/zfs_dir.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#8032 Linux does not HAVE_SMB_SHARE
  include/sys/zfs_znode.h
  module/zfs/zfs_ioctl.c
  module/zfs/zfs_znode.c
Labels: Status: Accepted

#8025 Allow copy-builtin to work with modified sources.
  copy-builtin
  scripts/make_gitrev.sh
Labels: Status: Accepted

#7732 Defer new resilvers until the current one ends
  cmd/zpool/zpool_main.c
  configure.ac
  include/sys/fs/zfs.h
  include/sys/spa_impl.h
  include/sys/vdev.h
  include/sys/vdev_impl.h
  include/zfeature_common.h
  include/zfs_gitrev.h
  man/man5/zpool-features.5
  man/man8/zpool.8
  module/zcommon/zfeature_common.c
  module/zfs/dsl_scan.c
  module/zfs/spa.c
  module/zfs/vdev.c
  module/zfs/vdev_label.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_reopen/zpool_reopen.shlib
  tests/zfs-tests/tests/functional/cli_root/zpool_reopen/zpool_reopen_004_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_reopen/zpool_reopen_005_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_resilver/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_resilver/cleanup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_resilver/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_resilver/zpool_resilver.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_resilver/zpool_resilver_bad_args.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_resilver/zpool_resilver_restart.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_scrub/zpool_scrub_offline_device.ksh
Labels: Status: Accepted

#8043 ZTS: Update project quota tests
  tests/zfs-tests/tests/functional/projectquota/projectid_001_pos.ksh
  tests/zfs-tests/tests/functional/projectquota/projecttree_001_pos.ksh
Labels: Status: Accepted

#8052 Allow to use pool GUID as root pool in initram script
  contrib/initramfs/scripts/zfs.in
Labels: Status: Accepted

#8054 Remove zfs_gitrev.h
  include/zfs_gitrev.h
Labels: Status: Accepted

#8051 ZTS: Fix auto_replace_001_pos test
  cmd/zed/agents/zfs_mod.c
  tests/zfs-tests/tests/functional/fault/auto_replace_001_pos.ksh
  tests/zfs-tests/tests/functional/fault/fault.cfg
Labels: Status: Accepted

#8058 Added additional column definitions to arcstat.py
  cmd/arcstat/arcstat.py
Labels: Status: Accepted

#8001 zdb -k does not work on Linux when used with -e
  cmd/zdb/zdb.c
  tests/zfs-tests/tests/functional/pool_checkpoint/checkpoint_zdb.ksh
  tests/zfs-tests/tests/functional/pool_checkpoint/pool_checkpoint.kshlib
Labels: Status: Accepted

#8047 Improve snapshot listing error message
  lib/libzfs/libzfs_dataset.c
Labels: Status: Accepted

#8074 Linux 4.20 compat: current_kernel_time()
  include/spl/sys/time.h
Labels: Status: Accepted

#8053 bpobj_enqueue_subobj() should copy small subobj's
  module/zfs/bpobj.c
Labels: Status: Accepted

#8071 tests: change `$(cat)` to `$(<)` for speedup
  tests/zfs-tests/callbacks/zfs_mmp.ksh
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/channel_program/channel_common.kshlib
  tests/zfs-tests/tests/functional/pool_checkpoint/pool_checkpoint.kshlib
  tests/zfs-tests/tests/functional/privilege/cleanup.ksh
  tests/zfs-tests/tests/functional/privilege/privilege_001_pos.ksh
  tests/zfs-tests/tests/functional/privilege/privilege_002_pos.ksh
  tests/zfs-tests/tests/functional/procfs/pool_state.ksh
  tests/zfs-tests/tests/functional/procfs/procfs_list_stale_read.ksh
  tests/zfs-tests/tests/functional/removal/removal_multiple_indirection.ksh
  tests/zfs-tests/tests/functional/removal/removal_sanity.ksh
  tests/zfs-tests/tests/functional/removal/removal_with_dedup.ksh
  tests/zfs-tests/tests/functional/removal/removal_with_ganging.ksh
  tests/zfs-tests/tests/functional/removal/remove_mirror_sanity.ksh
  tests/zfs-tests/tests/perf/perf.shlib
Labels: Status: Accepted

#8069 Fix zfstest posix tests that should pass.
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/acl/posix/posix_001_pos.ksh
  tests/zfs-tests/tests/functional/acl/posix/posix_002_pos.ksh
Labels: Status: Accepted
