Repository openzfs/zfs, pull requests merged in 2018-12, with the labels that each got.

#8161 Detect IO errors during device removal
  man/man5/zfs-module-parameters.5
  man/man8/zpool.8
  module/zfs/vdev_removal.c
  tests/runfiles/linux.run
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/removal/Makefile.am
  tests/zfs-tests/tests/functional/removal/removal.kshlib
  tests/zfs-tests/tests/functional/removal/removal_with_errors.ksh
  tests/zfs-tests/tests/functional/removal/removal_with_faulted.ksh
Labels: Status: Accepted

#8121 Fix ASSERT in zfs_receive_one()
  cmd/zfs/zfs_main.c
  lib/libzfs/libzfs_sendrecv.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_-e.ksh
Labels: Status: Accepted

#8154 Fix ztest assert in ztest_zil_remount()
  cmd/ztest/ztest.c
Labels: Status: Accepted

#8162 Fix ztest deadlock in spa_vdev_remove()
  module/zfs/vdev_removal.c
Labels: Status: Accepted

#8151 zfs-functions.in: Fix bug in is_mounted() where the return value is always 1
  etc/init.d/zfs-functions.in
Labels: Status: Revision Needed

#8147 Fix 'zpool list -v' alignment
  cmd/zpool/zpool_main.c
  module/zcommon/zprop_common.c
Labels: Status: Accepted

#8171 Move assert in dump_dir() in zdb
  cmd/zdb/zdb.c
Labels: Status: Accepted

#8180 Use autoconf variable for C preprocessor
  config/kernel.m4
Labels: Status: Accepted, Type: Building

#8167 Fix 'zfs receive -F' message when destination has snapshots
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#8178 Ensure dsl scan prefetch queue is emptied
  module/zfs/dsl_scan.c
Labels: Status: Code Review Needed

#8173 Do not enable stack tracer for ZFS performance test
  scripts/zfs-tests.sh
  scripts/zfs.sh
Labels: Status: Accepted

#8187 Fix error message when zfs module is not loaded
  lib/libzfs/libzfs_util.c
Labels: Status: Accepted

#8198 Issue 8131: Seeing negative values for wlentime
  module/spl/spl-kstat.c
Labels: Status: Accepted

#8193 Fix resilver writes in vdev_indirect_io_start
  module/zfs/vdev_indirect.c
Labels: Status: Accepted

#8197 Add `cut` binary to the initramfs
  contrib/dracut/90zfs/module-setup.sh.in
  contrib/dracut/90zfs/parse-zfs.sh.in
Labels: Status: Accepted

#8206 ztest: ENOSPC in ztest_objset_destroy_cb()
  cmd/ztest/ztest.c
Labels: Status: Accepted

#8209 Fix zap_update() ASSERT from ztest
  module/zfs/zap_micro.c
Labels: Status: Accepted

#8210 ZTS: fix wait_scrubbed()
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/fault/scrub_after_resilver.ksh
Labels: Status: Accepted

#8212 Fix zfs_dirty_data_sync_percent documentation
  module/zfs/dsl_pool.c
Labels: Status: Accepted

#8220 Minor tweaks to zfs.8 man page for POSIX ACLs
  man/man8/zfs.8
Labels: Status: Accepted, Type: Documentation
