Repository openzfs/zfs, pull requests merged in 2018-08, with the labels that each got.

#7103 Check for AES-NI on non-Intel processors
  cmd/ztest/ztest.c
  config/toolchain-simd.m4
  include/linux/simd_x86.h
  include/sys/crypto/icp.h
  lib/libicp/Makefile.am
  module/icp/Makefile.in
  module/icp/algs/aes/aes_impl.c
  module/icp/algs/aes/aes_impl_aesni.c
  module/icp/algs/aes/aes_impl_generic.c
  module/icp/algs/aes/aes_impl_x86-64.c
  module/icp/algs/modes/gcm.c
  module/icp/algs/modes/gcm_generic.c
  module/icp/algs/modes/gcm_pclmulqdq.c
  module/icp/asm-x86_64/aes/aes_aesni.S
  module/icp/asm-x86_64/modes/gcm_pclmulqdq.S
  module/icp/include/aes/aes_impl.h
  module/icp/include/modes/gcm_impl.h
  module/icp/io/aes.c
Labels: Ready to Push, Reviewed

#7761 Add missing checks to zpl_xattr_* functions
  include/sys/zfs_znode.h
  module/zfs/zpl_xattr.c
Labels: Ready to Push, Reviewed

#7736 reduce taskq and context-switch cost of zio pipe
  include/sys/zio.h
  module/zfs/zio.c
Labels: Performance, Ready to Push, Reviewed

#7759 zfs_ioc_unload_key can drop extra spa ref
  module/zfs/dsl_crypt.c
  module/zfs/dsl_dir.c
Labels: Ready to Push, Reviewed

#7757 Allow inherited properties in zfs_check_settable()
  module/zfs/zfs_ioctl.c
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/receive-o-x_props_override.ksh
Labels: Ready to Push, Reviewed

#7766 ZTS: Test case reliability
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/replacement/replacement_001_pos.ksh
Labels: Ready to Push, Reviewed

#7776 MMP should not suspend pool in ztest
  cmd/ztest/ztest.c
Labels: Ready to Push, Reviewed

#7774 ZTS: projectquota_002 path cleanup
  tests/zfs-tests/tests/functional/projectquota/projectquota_002_pos.ksh
Labels: Ready to Push, Reviewed

#7775 ZTS: inuse_004 path cleanup
  tests/zfs-tests/tests/functional/inuse/inuse_004_pos.ksh
Labels: Ready to Push, Reviewed

#7768 Fix comment on calculating blkid at level n within dnode's blkptrs
  module/zfs/dbuf.c
Labels: Ready to Push, Reviewed

#7791 Fix traverse_impl() kmem leak
  module/zfs/dmu_traverse.c
Labels: Ready to Push, Reviewed

#7796 ZTS: Fix reservation_001_pos
  tests/zfs-tests/tests/functional/reservation/reservation_001_pos.sh
Labels: Ready to Push, Reviewed

#7799 Fix arcstat.py handling of unsupported options
  cmd/arcstat/arcstat.py
Labels: Reviewed

#7798 'zfs holds' scripted mode is not documented
  cmd/zfs/zfs_main.c
  man/man8/zfs.8
Labels: Ready to Push, Reviewed

#7802 ZTS: Fix import_cache_device_replaced
  tests/runfiles/linux.run
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/cli_root/zpool_import/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_device_added.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_device_removed.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_device_replaced.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_mirror_attached.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_mirror_detached.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_shared_device.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import.cfg
Labels: Ready to Push, Reviewed

#7705 Introduce read/write kstats per dataset
  include/sys/Makefile.am
  include/sys/dataset_kstats.h
  include/sys/fs/zfs.h
  include/sys/zfs_vfsops.h
  man/man8/zfs.8
  man/man8/zpool.8
  module/zcommon/zfs_prop.c
  module/zcommon/zpool_prop.c
  module/zfs/Makefile.in
  module/zfs/dataset_kstats.c
  module/zfs/spa.c
  module/zfs/zfs_vfsops.c
  module/zfs/zfs_vnops.c
  module/zfs/zpl_file.c
  module/zfs/zvol.c
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
Labels: Ready to Push, Reviewed

#7760 Don't modify argv[] in user tools
  cmd/zfs/zfs_main.c
  cmd/zpool/zpool_main.c
Labels: Ready to Push, Reviewed

#7801 Fix zdb failure with EREMOTEIO when examining live pool
  cmd/zdb/zdb.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/mmp/Makefile.am
  tests/zfs-tests/tests/functional/mmp/mmp_on_zdb.ksh
Labels: Ready to Push, Reviewed

#7800 pyzfs: add missing libzfs_core functions
  contrib/pyzfs/libzfs_core/__init__.py
  contrib/pyzfs/libzfs_core/_constants.py
  contrib/pyzfs/libzfs_core/_error_translation.py
  contrib/pyzfs/libzfs_core/_libzfs_core.py
  contrib/pyzfs/libzfs_core/bindings/libzfs_core.py
  contrib/pyzfs/libzfs_core/exceptions.py
  contrib/pyzfs/libzfs_core/test/test_libzfs_core.py
Labels: Ready to Push, Reviewed

#7701 Fix issues with raw sends and receive_write_byref()
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_send.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/rsend/Makefile.am
  tests/zfs-tests/tests/functional/rsend/send-wDR_encrypted_zvol.ksh
Labels: Ready to Push, Reviewed

#7810 Stack overflow when destroying deeply nested clones
  module/zfs/dsl_destroy.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zfs_clone/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_clone/zfs_clone_deeply_nested.ksh
Labels: Ready to Push, Reviewed

#7831 Fix libaio-devel requirement for Debian-based distributions
  rpm/generic/zfs.spec.in
Labels: Ready to Push, Reviewed

#7830 Fedora 28: Fix misc bounds check compiler warnings
  lib/libshare/smb.c
  module/icp/core/kcf_mech_tabs.c
  tests/zfs-tests/tests/functional/ctime/ctime.c
Labels: Ready to Push, Reviewed

#7827 Remove %changelog from spec file
  rpm/generic/zfs-dkms.spec.in
  rpm/generic/zfs-kmod.spec.in
  rpm/generic/zfs.spec.in
Labels: Ready to Push, Reviewed

#7823 Direct IO support
  config/kernel-vfs-direct_IO.m4
  config/kernel.m4
  configure.ac
  module/zfs/zpl_file.c
  scripts/commitcheck.sh
  tests/runfiles/linux.run
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/Makefile.am
  tests/zfs-tests/tests/functional/io/Makefile.am
  tests/zfs-tests/tests/functional/io/cleanup.ksh
  tests/zfs-tests/tests/functional/io/io.cfg
  tests/zfs-tests/tests/functional/io/libaio.ksh
  tests/zfs-tests/tests/functional/io/mmap.ksh
  tests/zfs-tests/tests/functional/io/posixaio.ksh
  tests/zfs-tests/tests/functional/io/psync.ksh
  tests/zfs-tests/tests/functional/io/setup.ksh
  tests/zfs-tests/tests/functional/io/sync.ksh
Labels: Ready to Push, Reviewed

#7854 ZTS: Fix EBUSY volume destroy failures
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.destroy_fs.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.destroy_snap.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.get_count_and_limit.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.get_index_props.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.get_mountpoint.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.get_neg.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.get_number_props.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.get_type.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.get_userquota.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.get_written.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.list_children.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.list_clones.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.list_snapshots.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.list_system_props.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.promote_conflict.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.promote_multiple.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.promote_simple.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.rollback_mult.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.rollback_one.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.snapshot_destroy.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.snapshot_neg.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.snapshot_recursive.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.snapshot_simple.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_002_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/receive-o-x_props_override.ksh
Labels: Ready to Push, Reviewed
