Repository openzfs/zfs, pull requests merged in 2019-09, with the labels that each got.

#9237 Fix typos in lib/
  lib/libefi/rdwr_efi.c
  lib/libshare/smb.c
  lib/libspl/asm-generic/atomic.c
  lib/libspl/include/atomic.h
  lib/libspl/include/sys/kstat.h
  lib/libspl/include/sys/param.h
  lib/libspl/include/sys/uio.h
  lib/libspl/include/sys/vtoc.h
  lib/libspl/mkdirp.c
  lib/libtpool/thread_pool.c
  lib/libzfs/THIRDPARTYLICENSE.openssl
  lib/libzfs/libzfs_crypto.c
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs_core/libzfs_core.c
  lib/libzutil/zutil_import.c
Labels: Status: Accepted

#9240 Fix typos in module/zfs/
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_send.c
  module/zfs/dmu_zfetch.c
  module/zfs/dnode.c
  module/zfs/dsl_bookmark.c
  module/zfs/dsl_crypt.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_destroy.c
  module/zfs/dsl_dir.c
  module/zfs/dsl_scan.c
  module/zfs/dsl_synctask.c
  module/zfs/dsl_userhold.c
  module/zfs/fm.c
  module/zfs/metaslab.c
  module/zfs/mmp.c
  module/zfs/policy.c
  module/zfs/qat.h
  module/zfs/sa.c
  module/zfs/spa.c
  module/zfs/spa_checkpoint.c
  module/zfs/spa_errlog.c
  module/zfs/spa_history.c
  module/zfs/spa_log_spacemap.c
  module/zfs/txg.c
  module/zfs/vdev.c
  module/zfs/vdev_cache.c
  module/zfs/vdev_initialize.c
  module/zfs/vdev_mirror.c
  module/zfs/vdev_queue.c
  module/zfs/vdev_raidz.c
  module/zfs/vdev_raidz_math_aarch64_neon_common.h
  module/zfs/zcp.c
  module/zfs/zcp_get.c
  module/zfs/zcp_iter.c
  module/zfs/zfs_acl.c
  module/zfs/zfs_byteswap.c
  module/zfs/zfs_ctldir.c
  module/zfs/zfs_dir.c
  module/zfs/zfs_ioctl.c
  module/zfs/zfs_vfsops.c
  module/zfs/zfs_vnops.c
  module/zfs/zfs_znode.c
  module/zfs/zil.c
  module/zfs/zio_checksum.c
  module/zfs/zio_compress.c
  module/zfs/zio_crypt.c
  module/zfs/zio_inject.c
  module/zfs/zpl_super.c
  module/zfs/zvol.c
Labels: Status: Accepted

#9242 Fix typos in tests/
  tests/zfs-tests/tests/functional/slog/slog_015_neg.ksh
  tests/zfs-tests/tests/functional/snapshot/snapshot_002_pos.ksh
  tests/zfs-tests/tests/functional/snapshot/snapshot_006_pos.ksh
  tests/zfs-tests/tests/functional/trim/trim.kshlib
  tests/zfs-tests/tests/functional/userquota/userquota_005_neg.ksh
  tests/zfs-tests/tests/functional/userquota/userquota_010_pos.ksh
  tests/zfs-tests/tests/functional/userquota/userquota_012_neg.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_003_neg.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_011_pos.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_swap/zvol_swap_003_pos.ksh
Labels: Status: Accepted

#9243 Fix typos in tests/
  tests/zfs-tests/tests/functional/rsend/rsend_008_pos.ksh
  tests/zfs-tests/tests/functional/rsend/rsend_011_pos.ksh
  tests/zfs-tests/tests/functional/rsend/rsend_012_pos.ksh
  tests/zfs-tests/tests/functional/rsend/rsend_022_pos.ksh
  tests/zfs-tests/tests/functional/rsend/rsend_024_pos.ksh
  tests/zfs-tests/tests/functional/rsend/send-cD.ksh
  tests/zfs-tests/tests/functional/rsend/send-c_resume.ksh
  tests/zfs-tests/tests/functional/rsend/send-c_stream_size_estimate.ksh
  tests/zfs-tests/tests/functional/rsend/send_realloc_encrypted_files.ksh
  tests/zfs-tests/tests/functional/rsend/send_realloc_files.ksh
Labels: Status: Accepted

#9244 Fix typos in tests/
  tests/zfs-tests/tests/functional/pool_checkpoint/checkpoint_removal.ksh
  tests/zfs-tests/tests/functional/pool_checkpoint/pool_checkpoint.kshlib
  tests/zfs-tests/tests/functional/projectquota/projectid_001_pos.ksh
  tests/zfs-tests/tests/functional/projectquota/projectid_002_pos.ksh
  tests/zfs-tests/tests/functional/projectquota/projectquota_004_neg.ksh
  tests/zfs-tests/tests/functional/projectquota/projectspace_004_pos.ksh
  tests/zfs-tests/tests/functional/projectquota/projecttree_002_pos.ksh
  tests/zfs-tests/tests/functional/projectquota/projecttree_003_neg.ksh
  tests/zfs-tests/tests/functional/pyzfs/Makefile.am
  tests/zfs-tests/tests/functional/raidz/raidz_001_neg.ksh
Labels: Status: Code Review Needed

#9246 Fix typos in tests/
  tests/zfs-tests/tests/functional/delegate/zfs_allow_009_neg.ksh
  tests/zfs-tests/tests/functional/fault/auto_online_001_pos.ksh
  tests/zfs-tests/tests/functional/fault/auto_spare_multiple.ksh
  tests/zfs-tests/tests/functional/history/history_005_neg.ksh
  tests/zfs-tests/tests/functional/history/history_006_neg.ksh
  tests/zfs-tests/tests/functional/history/history_007_pos.ksh
  tests/zfs-tests/tests/functional/history/history_common.kshlib
  tests/zfs-tests/tests/functional/inuse/inuse_001_pos.ksh
  tests/zfs-tests/tests/functional/inuse/inuse_004_pos.ksh
  tests/zfs-tests/tests/functional/inuse/inuse_008_pos.ksh
  tests/zfs-tests/tests/functional/large_files/large_files_001_pos.ksh
  tests/zfs-tests/tests/functional/mmap/mmap_write_001_pos.ksh
  tests/zfs-tests/tests/functional/mmp/mmp_on_uberblocks.ksh
  tests/zfs-tests/tests/functional/no_space/enospc_df.ksh
  tests/zfs-tests/tests/functional/nopwrite/nopwrite_sync.ksh
Labels: Status: Accepted

#9247 Fix typos in tests/
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add.kshlib
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create.shlib
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_005_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_016_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_events/zpool_events_clear.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_history/zpool_history_001_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_rewind_config_changed.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import_missing_002_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_labelclear/zpool_labelclear_active.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_labelclear/zpool_labelclear_exported.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_upgrade/zpool_upgrade_007_pos.ksh
  tests/zfs-tests/tests/functional/cli_user/misc/setup.ksh
  tests/zfs-tests/tests/functional/cli_user/misc/zpool_online_001_neg.ksh
  tests/zfs-tests/tests/functional/cli_user/zpool_iostat/zpool_iostat_005_pos.ksh
  tests/zfs-tests/tests/functional/cli_user/zpool_status/zpool_status_003_pos.ksh
Labels: Status: Accepted

#9249 Fix typos in tests/
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_016_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_clone_livelist.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_common.kshlib
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_dev_removal_condense.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_get/zfs_get_004_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_inherit/zfs_inherit_002_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_inherit/zfs_inherit_003_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_007_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_008_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_010_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_remount.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_property/zfs_written_property_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_004_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_from_encrypted.ksh
Labels: Status: Accepted

#9250 Fix typos in tests/
  tests/zfs-tests/cmd/mmapwrite/mmapwrite.c
  tests/zfs-tests/include/blkdev.shlib
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/acl/acl_common.kshlib
  tests/zfs-tests/tests/functional/cachefile/cachefile_004_pos.ksh
  tests/zfs-tests/tests/functional/casenorm/insensitive_formd_lookup.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.list_user_props.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.terminate_by_signal.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_clone/zfs_clone_010_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_copies/zfs_copies_002_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_011_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_005_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_014_pos.ksh
Labels: Status: Accepted

#9251 Fix typos
  .github/CONTRIBUTING.md
  scripts/kmodtool
  tests/README.md
  tests/test-runner/bin/Makefile.am
  tests/test-runner/bin/test-runner.py
  tests/test-runner/man/test-runner.1
Labels: Status: Accepted

#9272 maxinflight can overflow in spa_load_verify_cb()
  module/zfs/spa.c
Labels: Status: Accepted

#9269 Fix Intel QAT / ZFS compatibility on v4.7.1+ kernels
  module/zfs/qat_compress.c
  module/zfs/qat_crypt.c
Labels: Status: Accepted

#9259 Fix removal cancel
  tests/zfs-tests/tests/functional/removal/removal_cancel.ksh
Labels: Status: Accepted, Type: Test Suite

#9252 always refuse receving non-resume stream when resume state exists
  lib/libzfs/libzfs_sendrecv.c
  module/zfs/dmu_recv.c
Labels: Status: Accepted

#9260 zvol_wait script should ignore partially received zvols
  cmd/zvol_wait/zvol_wait
Labels: Status: Accepted

#9254 9151 fix panic on DilOS with kstat per dataset statistics
  module/zfs/dataset_kstats.c
Labels: Status: Accepted

#9264 Use the right booleans
  tests/zfs-tests/cmd/libzfs_input_check/libzfs_input_check.c
Labels: Status: Accepted

#9271 Fix zfs-dkms .deb package warning in prerm script
  rpm/generic/zfs-dkms.spec.in
Labels: Status: Accepted

#9270 Fix zpool subcommands error message with some unsupported options
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#9280 ZTS: Refactor checksum operations in tests
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_from_encrypted.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_raw.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_raw_incremental.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_cachefile_shared_device.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import.kshlib
  tests/zfs-tests/tests/functional/cli_root/zpool_reopen/zpool_reopen_003_pos.ksh
  tests/zfs-tests/tests/functional/history/history_003_pos.ksh
  tests/zfs-tests/tests/functional/rsend/rsend.kshlib
  tests/zfs-tests/tests/functional/rsend/send-c_volume.ksh
  tests/zfs-tests/tests/functional/rsend/send-wDR_encrypted_zvol.ksh
  tests/zfs-tests/tests/functional/rsend/send_encrypted_props.ksh
  tests/zfs-tests/tests/functional/slog/slog_replay_fs_001.ksh
  tests/zfs-tests/tests/functional/slog/slog_replay_volume.ksh
Labels: Status: Accepted

#9282 9185 metaslab_verify_weight_and_frag() shouldn't cause side-effects
  module/zfs/metaslab.c
Labels: Status: Accepted

#9230 Make module tunables cross platform
  include/os/linux/kernel/linux/mod_compat.h
  include/sys/zfs_context.h
  module/zcommon/zfs_namecheck.c
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dbuf_stats.c
  module/zfs/ddt.c
  module/zfs/dmu.c
  module/zfs/dmu_object.c
  module/zfs/dmu_recv.c
  module/zfs/dmu_send.c
  module/zfs/dmu_traverse.c
  module/zfs/dmu_zfetch.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_deadlist.c
  module/zfs/dsl_pool.c
  module/zfs/dsl_scan.c
  module/zfs/metaslab.c
  module/zfs/mmp.c
  module/zfs/multilist.c
  module/zfs/qat_compress.c
  module/zfs/qat_crypt.c
  module/zfs/spa.c
  module/zfs/spa_checkpoint.c
  module/zfs/spa_config.c
  module/zfs/spa_log_spacemap.c
  module/zfs/spa_misc.c
  module/zfs/txg.c
  module/zfs/vdev.c
  module/zfs/vdev_cache.c
  module/zfs/vdev_disk.c
  module/zfs/vdev_indirect.c
  module/zfs/vdev_initialize.c
  module/zfs/vdev_mirror.c
  module/zfs/vdev_queue.c
  module/zfs/vdev_raidz_math.c
  module/zfs/vdev_removal.c
  module/zfs/vdev_trim.c
  module/zfs/zap.c
  module/zfs/zcp.c
  module/zfs/zfs_log.c
  module/zfs/zil.c
  module/zfs/zio.c
Labels: Status: Accepted

#9284 ZTS: Clean up zfs_clone_010_pos
  tests/zfs-tests/tests/functional/cli_root/zfs_clone/zfs_clone_010_pos.ksh
Labels: Status: Accepted

#9221 Fix noop receive of raw send stream
  lib/libzfs/libzfs_sendrecv.c
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_raw.ksh
Labels: Status: Accepted

#9289 BuildRequires libtirpc-devel needed for RHEL 8
  rpm/generic/zfs.spec.in
Labels: Status: Accepted

#9286 ZTS: Clean up do_vol_test in zfs_copies tests
  tests/zfs-tests/tests/functional/cli_root/zfs_copies/zfs_copies.kshlib
Labels: Status: Accepted

#9288 ZTS: Introduce targeted corruption in file blocks
  tests/zfs-tests/include/blkdev.shlib
  tests/zfs-tests/tests/functional/checksum/filetest_001_pos.ksh
Labels: Status: Accepted

#9296 Enable SIMD for encryption
  include/sys/zio_crypt.h
  module/os/linux/zfs/zio_crypt.c
  module/zfs/arc.c
  module/zfs/dsl_crypt.c
Labels: Status: Accepted

#9277 Add/generalize abstractions in arc_summary2
  cmd/arc_summary/arc_summary2
Labels: Status: Accepted

#9279 Add/generalize abstractions in arc_summary3
  cmd/arc_summary/arc_summary3
Labels: Status: Accepted

#9285 Fix /etc/hostid on root pool deadlock
  include/sys/spa.h
  include/sys/spa_impl.h
  module/zfs/spa.c
  module/zfs/spa_config.c
  module/zfs/spa_misc.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/mmp/Makefile.am
  tests/zfs-tests/tests/functional/mmp/mmp_hostid.ksh
Labels: Status: Accepted

#9308 copy-builtin: SPL must be in Kbuild first (again)
  copy-builtin
Labels: Status: Accepted, Type: Regression

#9310 kmodtool: depmod path
  scripts/kmodtool
Labels: Status: Accepted

#9300 Fix stalled txg with repeated noop scans
  module/zfs/dsl_scan.c
Labels: Status: Accepted

#9290 Move Linux specific tracing headers and source to platform directories
  include/os/linux/spl/sys/Makefile.am
  include/os/linux/spl/sys/trace.h
  include/os/linux/zfs/sys/Makefile.am
  include/os/linux/zfs/sys/trace_acl.h
  include/os/linux/zfs/sys/trace_arc.h
  include/os/linux/zfs/sys/trace_common.h
  include/os/linux/zfs/sys/trace_dbgmsg.h
  include/os/linux/zfs/sys/trace_dbuf.h
  include/os/linux/zfs/sys/trace_defs.h
  include/os/linux/zfs/sys/trace_dmu.h
  include/os/linux/zfs/sys/trace_dnode.h
  include/os/linux/zfs/sys/trace_multilist.h
  include/os/linux/zfs/sys/trace_rrwlock.h
  include/os/linux/zfs/sys/trace_txg.h
  include/os/linux/zfs/sys/trace_vdev.h
  include/os/linux/zfs/sys/trace_zil.h
  include/os/linux/zfs/sys/trace_zio.h
  include/os/linux/zfs/sys/trace_zrlock.h
  include/sys/Makefile.am
  lib/libspl/include/sys/Makefile.am
  lib/libspl/include/sys/trace_defs.h
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/trace.c
  module/zfs/Makefile.in
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_tx.c
  module/zfs/dnode.c
  module/zfs/dsl_pool.c
  module/zfs/multilist.c
  module/zfs/rrwlock.c
  module/zfs/txg.c
  module/zfs/vdev_removal.c
  module/zfs/zil.c
  module/zfs/zio.c
  module/zfs/zrlock.c
Labels: Status: Accepted

#9321 Scrubbing root pools may deadlock on kernels without elevator_change()
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#9294 Fix clone handling with encryption roots
  module/zfs/dsl_crypt.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zfs_change-key/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_change-key/zfs_change-key_clones.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_promote/zfs_promote_encryptionroot.ksh
Labels: Status: Accepted

#9325 ZTS: Fix /usr/bin/env: 'python2': No such file or directory
  tests/zfs-tests/include/commands.cfg
Labels: Status: Accepted

#9326 Prevent gcc -Werror=maybe-uninitialized warnings in spa_wait_common()
  module/zfs/spa.c
Labels: Status: Accepted

#9327 Device removal of indirect vdev panics the kernel
  module/zfs/vdev_removal.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/removal/Makefile.am
  tests/zfs-tests/tests/functional/removal/remove_indirect.ksh
Labels: Status: Accepted

#9163 fix dsl_scan_ds_clone_swapped logic
  module/zfs/dsl_scan.c
Labels: Status: Accepted, Type: Defect

#9330 Refactor libzfs_error_init newlines
  cmd/mount_zfs/mount_zfs.c
  cmd/zfs/zfs_main.c
  cmd/zinject/zinject.c
  cmd/zpool/zpool_main.c
  lib/libzfs/libzfs_util.c
Labels: Status: Accepted

#9338 disabled resilver_defer feature leads to looping resilvers
  module/zfs/dsl_scan.c
Labels: Status: Accepted

#9335 Use signed types to prevent subtraction overflow
  cmd/zpool/zpool_vdev.c
Labels: Status: Accepted

#9343 diff_cb() does not handle encrypted large dnodes
  module/zfs/dmu_diff.c
  tests/zfs-tests/tests/functional/cli_root/zfs_diff/zfs_diff_encrypted.ksh
Labels: Status: Accepted

#9295 Refactor zvol in to platform and platform independent bits
  include/sys/Makefile.am
  include/sys/dmu.h
  include/sys/zvol.h
  include/sys/zvol_impl.h
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/zvol_os.c
  module/zfs/dmu_objset.c
  module/zfs/zfs_ioctl.c
  module/zfs/zvol.c
Labels: Status: Accepted

#9317 Remove zfs_vdev_elevator module option
  man/man5/zfs-module-parameters.5
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#9358 ZTS: harden xattr/cleanup.ksh
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/xattr/cleanup.ksh
Labels: Status: Accepted, Type: Test Suite

#9362 ZTS: Fix typos in zfs_destroy tests cleanup
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_dev_removal.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_dev_removal_condense.ksh
Labels: Status: Accepted, Type: Test Suite

#9309 Fix encryption hierarchy issues with zfs recv -d
  include/libzfs.h
  lib/libzfs/libzfs_sendrecv.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_raw_-d.ksh
Labels: Status: Accepted

#9350 adding slack notifier #9076
  cmd/zed/zed.d/zed-functions.sh
  cmd/zed/zed.d/zed.rc
Labels: Status: Accepted

#9301 Refactor zfs_ioctl
  include/os/linux/zfs/sys/zfs_vfsops.h
  include/sys/Makefile.am
  include/sys/rrwlock.h
  include/sys/zfs_ioctl.h
  include/sys/zfs_ioctl_impl.h
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/zfs_ioctl_os.c
  module/zfs/zfs_ioctl.c
  tests/zfs-tests/cmd/libzfs_input_check/libzfs_input_check.c
Labels: Status: Accepted

#9333 Factor Linux specific functions out of zpool command
  cmd/zpool/Makefile.am
  cmd/zpool/os/linux/zpool_vdev_os.c
  cmd/zpool/zpool_main.c
  cmd/zpool/zpool_util.c
  cmd/zpool/zpool_util.h
  cmd/zpool/zpool_vdev.c
  include/libzutil.h
  lib/libzutil/zutil_nicenum.c
Labels: Status: Accepted
