Repository openzfs/zfs, pull requests merged in 2019-08, with the labels that each got.

#9101 Test cancelling a removal in ZTS
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/removal/Makefile.am
  tests/zfs-tests/tests/functional/removal/removal_cancel.ksh
Labels: Status: Accepted

#9091 Don't wakeup unnecessarily in 'zpool events -f'
  module/zfs/fm.c
Labels: Status: Accepted

#9055 Metaslab max_size should be persisted while unloaded
  cmd/zdb/zdb.c
  include/sys/metaslab.h
  include/sys/metaslab_impl.h
  include/sys/range_tree.h
  man/man5/zfs-module-parameters.5
  module/zfs/metaslab.c
  module/zfs/range_tree.c
Labels: Status: Accepted

#9143 Sort log spacemap tunables in alphabetical order
  module/zfs/spa_log_spacemap.c
Labels: Status: Accepted

#7902 Introduce getting holds and listing bookmarks through ZCP
  man/man8/zfs-program.8
  module/zfs/zcp_iter.c
  tests/runfiles/linux.run
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/channel_program/synctask_core/Makefile.am
  tests/zfs-tests/tests/functional/channel_program/synctask_core/cleanup.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/setup.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.list_bookmarks.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.list_holds.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.list_user_props.ksh
Labels: Status: Accepted, Type: Feature

#9119 Drop KMC_NOEMERGENCY
  include/spl/sys/kmem_cache.h
  module/spl/spl-zlib.c
Labels: Status: Accepted

#9092 znode_t::z_{unlinked,zn_prefetch} are not boolean
  include/sys/zfs_znode.h
  module/zfs/zfs_ctldir.c
  module/zfs/zfs_vnops.c
  module/zfs/zfs_znode.c
Labels: Status: Accepted

#9146 spa_load_verify() may consume too much memory
  cmd/zdb/zdb.c
  include/sys/spa_impl.h
  man/man5/zfs-module-parameters.5
  module/zfs/spa.c
Labels: Status: Accepted

#9154 Mark dsl_livelist_should_disable() static
  module/zfs/dsl_dataset.c
Labels: Status: Accepted

#9111 Fix device expansion when VM is powered off
  lib/libefi/rdwr_efi.c
Labels: Status: Accepted

#9061 Fix out-of-order ZIL txtype lost on hardlinked files
  include/sys/zfs_znode.h
  module/zfs/zfs_log.c
  module/zfs/zfs_vnops.c
  module/zfs/zil.c
  tests/zfs-tests/tests/functional/slog/slog_replay_fs.ksh
Labels: Status: Accepted

#9112 Prevent race in blkptr_verify against device removal
  include/sys/refcount.h
  include/sys/spa.h
  module/zfs/refcount.c
  module/zfs/spa_misc.c
  module/zfs/zio.c
Labels: Status: Accepted

#9115 Make txg_wait_synced conditional in zfsvfs_teardown
  module/zfs/zfs_vfsops.c
Labels: Status: Accepted, Type: Performance

#8348 Assert that a dnode's bonuslen never exceeds its recorded size
  module/zfs/dbuf.c
  module/zfs/dnode.c
Labels: Status: Accepted

#9156 Improve write performance by using dmu_read_by_dnode()
  module/zfs/zfs_log.c
Labels: Status: Accepted

#9137 dmu_tx_wait() hang likely due to cv_signal() in dsl_pool_dirty_delta()
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_objset.c
  module/zfs/dsl_pool.c
Labels: Status: Accepted

#9089 initramfs fixes
  contrib/initramfs/Makefile.am
  contrib/initramfs/hooks/zfs.in
  etc/systemd/system/Makefile.am
  rpm/generic/zfs.spec.in
Labels: Status: Accepted

#9128 Cap metaslab memory usage
  include/sys/arc.h
  include/sys/metaslab.h
  include/sys/metaslab_impl.h
  man/man5/zfs-module-parameters.5
  module/zfs/arc.c
  module/zfs/metaslab.c
  module/zfs/spa.c
  module/zfs/spa_log_spacemap.c
  module/zfs/vdev.c
  module/zfs/vdev_initialize.c
  module/zfs/vdev_trim.c
Labels: Status: Accepted

#9139 Add more refquota tests
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/refquota/Makefile.am
  tests/zfs-tests/tests/functional/refquota/refquota_007_neg.ksh
  tests/zfs-tests/tests/functional/refquota/refquota_008_neg.ksh
Labels: Status: Accepted, Type: Test Suite

#9042 Set "none" scheduler if available (initramfs)
  contrib/initramfs/scripts/zfs.in
Labels: Status: Accepted

#9169 Linux 5.3 compat: Makefile subdir-m no longer supported.
  .gitignore
  module/Makefile.in
Labels: Status: Accepted

#9110 Fix lockdep circular locking false positive involving sa_lock
  module/zfs/sa.c
Labels: Status: Accepted

#8744 add fast path for zfs_ioc_space_snaps() handling of empty_bpobj
  include/sys/dsl_deadlist.h
  module/zfs/dsl_deadlist.c
  module/zfs/dsl_destroy.c
Labels: Status: Accepted, Type: Performance

#9168 Fix bug in in_mtab() where the return value is always 1
  etc/init.d/zfs-functions.in
Labels: Status: Accepted

#9189 Minor cleanup in Makefile.am
  Makefile.am
Labels: Status: Accepted

#9170 Linux 5.3: Fix switch() fall though compiler errors
  module/lua/llex.c
  module/zfs/abd.c
  module/zfs/vdev_raidz_math_scalar.c
Labels: Status: Accepted

#9199 ZTS: Fix vdev_zaps_005_pos on CentOS 6
  tests/zfs-tests/tests/functional/vdev_zaps/vdev_zaps_005_pos.ksh
Labels: Status: Accepted

#9187 Enhance ioctl number checks
  tests/zfs-tests/cmd/libzfs_input_check/libzfs_input_check.c
Labels: Status: Accepted

#9188 Dedup IOC reference constants in libzfs_input_check
  tests/zfs-tests/cmd/libzfs_input_check/libzfs_input_check.c
Labels: Status: Accepted

#9191 Document ZFS_DKMS_ENABLE_DEBUGINFO in userland configuration
  etc/init.d/zfs.in
Labels: Status: Accepted

#9190 Fix automake program name transformations
  cmd/arc_summary/Makefile.am
Labels: Status: Accepted

#9195 ZTS: Use decimal values when setting tunables
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_clone_livelist_condense_and_disable.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_clone_livelist_condense_races.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_clone_livelist.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_dev_removal_condense.ksh
Labels: Status: Accepted

#9174 zfs-mount-genrator: dependencies should be space-separated
  etc/systemd/system-generators/zfs-mount-generator.in
Labels: Status: Accepted

#9194 Make slog test setup more robust
  tests/zfs-tests/tests/functional/slog/setup.ksh
  tests/zfs-tests/tests/functional/slog/slog.kshlib
  tests/zfs-tests/tests/functional/slog/slog_001_pos.ksh
  tests/zfs-tests/tests/functional/slog/slog_002_pos.ksh
  tests/zfs-tests/tests/functional/slog/slog_003_pos.ksh
  tests/zfs-tests/tests/functional/slog/slog_004_pos.ksh
  tests/zfs-tests/tests/functional/slog/slog_005_pos.ksh
  tests/zfs-tests/tests/functional/slog/slog_006_pos.ksh
  tests/zfs-tests/tests/functional/slog/slog_007_pos.ksh
  tests/zfs-tests/tests/functional/slog/slog_008_neg.ksh
  tests/zfs-tests/tests/functional/slog/slog_009_neg.ksh
  tests/zfs-tests/tests/functional/slog/slog_010_neg.ksh
  tests/zfs-tests/tests/functional/slog/slog_011_neg.ksh
  tests/zfs-tests/tests/functional/slog/slog_012_neg.ksh
  tests/zfs-tests/tests/functional/slog/slog_013_pos.ksh
  tests/zfs-tests/tests/functional/slog/slog_014_pos.ksh
  tests/zfs-tests/tests/functional/slog/slog_015_neg.ksh
  tests/zfs-tests/tests/functional/slog/slog_replay_fs.ksh
  tests/zfs-tests/tests/functional/slog/slog_replay_volume.ksh
Labels: Status: Accepted

#9205 Fix install error introduced by #9089
  etc/systemd/system/Makefile.am
Labels: Status: Accepted

#9196 ZTS: Fix in-tree dbufstats test case
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/arc/Makefile.am
  tests/zfs-tests/tests/functional/arc/dbufstats_003_pos.ksh
  tests/zfs-tests/tests/functional/cli_user/misc/Makefile.am
Labels: Status: Accepted, Type: Test Suite

#9212 Satisfy shellcheck SC2086, split argument list
  scripts/zfs-tests.sh
Labels: Status: Accepted

#9134 add regression test for "zpool list -p"
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zpool_get/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get_005_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get_parsable.cfg
Labels: Status: Accepted, Type: Test Suite

#9225 ZTS: Temporarily disable several upgrade tests
  tests/runfiles/linux.run
Labels: Status: Accepted

#9217 Use smaller default slack/delta value for schedule_hrtimeout_range()
  module/spl/spl-condvar.c
  module/zfs/mmp.c
Labels: Status: Accepted, Type: Performance

#9165 zfs_handle used after being closed/freed in change_one() callback
  lib/libzfs/libzfs_changelist.c
Labels: Status: Accepted

#9197 keep more metaslabs loaded
  include/sys/metaslab_impl.h
  man/man5/zfs-module-parameters.5
  module/zfs/metaslab.c
Labels: Status: Accepted, Type: Performance

#9228 ZTS: Use compatible arg order in tests
  tests/zfs-tests/tests/functional/alloc_class/alloc_class_004_pos.ksh
  tests/zfs-tests/tests/functional/alloc_class/alloc_class_005_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_program/zfs_program_json.ksh
Labels: Status: Accepted

#9224 Simplify deleting partitions in libtest
  tests/zfs-tests/include/libtest.shlib
Labels: Status: Accepted

#9177 etc/init.d/zfs-functions.in: remove arch warning
  etc/init.d/zfs-functions.in
Labels: Status: Accepted

#9231 Prevent metaslab_sync panic due to spa_final_dirty_txg
  module/zfs/metaslab.c
  tests/runfiles/linux.run
Labels: Status: Accepted

#9257 fix refquota_007_neg.ksh
  tests/zfs-tests/tests/functional/refquota/refquota_007_neg.ksh
Labels: Status: Accepted

#9232 Fix typos in config/
  config/ax_code_coverage.m4
  config/kernel-dentry-operations.m4
  config/kernel-mkdir-umode-t.m4
  config/kernel-timer.m4
  config/lib-link.m4
  config/pkg.m4
  config/user.m4
  config/zfs-build.m4
Labels: Status: Accepted

#9233 Fix typos in man/
  man/man1/cstyle.1
  man/man1/ztest.1
  man/man5/vdev_id.conf.5
  man/man5/zfs-events.5
  man/man5/zfs-module-parameters.5
  man/man5/zpool-features.5
  man/man8/zdb.8
  man/man8/zfs.8
Labels: Status: Accepted

#9234 Fix typos in cmd/
  cmd/arc_summary/arc_summary3
  cmd/arcstat/Makefile.am
  cmd/dbufstat/Makefile.am
  cmd/fsck_zfs/fsck.zfs
  cmd/vdev_id/vdev_id
  cmd/zdb/zdb.c
  cmd/zed/agents/fmd_api.c
  cmd/zed/agents/fmd_serd.c
  cmd/zed/agents/zfs_mod.c
  cmd/zed/zed.d/statechange-led.sh
  cmd/zfs/zfs_main.c
  cmd/zinject/translate.c
  cmd/zpool/zpool_vdev.c
  cmd/zstreamdump/zstreamdump.c
  cmd/ztest/ztest.c
Labels: Status: Accepted

#9235 Fix typos in contrib/
  contrib/initramfs/scripts/zfs.in
  contrib/pyzfs/docs/source/conf.py
  contrib/pyzfs/libzfs_core/_libzfs_core.py
  contrib/pyzfs/libzfs_core/_nvlist.py
  contrib/pyzfs/libzfs_core/exceptions.py
  contrib/pyzfs/libzfs_core/test/test_libzfs_core.py
Labels: Status: Accepted

#9236 Fix typos in etc/
  etc/init.d/zfs-functions.in
  etc/init.d/zfs-import.in
  etc/zfs/vdev_id.conf.sas_direct.example
Labels: Status: Accepted

#9238 Fix typos in include/
  include/linux/vfs_compat.h
  include/spl/sys/kmem_cache.h
  include/sys/arc.h
  include/sys/arc_impl.h
  include/sys/avl.h
  include/sys/dmu.h
  include/sys/efi_partition.h
  include/sys/fs/zfs.h
  include/sys/lua/luaconf.h
  include/sys/sa.h
  include/sys/trace.h
  include/sys/trace_vdev.h
  include/sys/txg_impl.h
  include/sys/vdev_raidz_impl.h
  include/sys/zcp.h
  include/sys/zfs_acl.h
  include/sys/zfs_vfsops.h
  include/sys/zil.h
  include/sys/zio_crypt.h
  include/sys/zio_impl.h
Labels: Status: Accepted

#9239 Fix typos in modules/icp/
  module/icp/algs/skein/skein_block.c
  module/icp/api/kcf_ctxops.c
  module/icp/asm-x86_64/aes/THIRDPARTYLICENSE.openssl
  module/icp/asm-x86_64/aes/aesopt.h
  module/icp/core/kcf_mech_tabs.c
  module/icp/core/kcf_sched.c
  module/icp/illumos-crypto.c
  module/icp/include/sys/crypto/impl.h
  module/icp/include/sys/crypto/sched_impl.h
  module/icp/include/sys/crypto/spi.h
  module/icp/os/modhash.c
  module/icp/spi/kcf_spi.c
Labels: Status: Accepted

#9241 Fix typos in module/
  module/avl/avl.c
  module/lua/llimits.h
  module/nvpair/nvpair.c
  module/spl/spl-condvar.c
  module/spl/spl-generic.c
  module/spl/spl-kmem-cache.c
  module/spl/spl-tsd.c
  module/zcommon/zfeature_common.c
  module/zcommon/zfs_namecheck.c
  module/zcommon/zpool_prop.c
Labels: Status: Accepted

#9245 Fix typos in tests/
  tests/zfs-tests/tests/functional/redacted_send/redacted_contents.ksh
  tests/zfs-tests/tests/functional/redacted_send/redacted_deleted.ksh
  tests/zfs-tests/tests/functional/redacted_send/redacted_disabled_feature.ksh
  tests/zfs-tests/tests/functional/redundancy/redundancy_001_pos.ksh
  tests/zfs-tests/tests/functional/refreserv/refreserv_003_pos.ksh
  tests/zfs-tests/tests/functional/refreserv/refreserv_multi_raidz.ksh
  tests/zfs-tests/tests/functional/removal/removal_nopwrite.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_001_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_008_pos.ksh
  tests/zfs-tests/tests/functional/rsend/rsend.kshlib
Labels: Status: Accepted

#9248 Fix typos in tests/
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_raw.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_rollback/zfs_rollback_common.kshlib
  tests/zfs-tests/tests/functional/cli_root/zfs_send/zfs_send_004_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_set/cache_002_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_set/canmount_002_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_set/mountpoint_002_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_set/zfs_set_common.kshlib
  tests/zfs-tests/tests/functional/cli_root/zfs_snapshot/zfs_snapshot_002_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_snapshot/zfs_snapshot_008_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_snapshot/zfs_snapshot_009_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_unmount/zfs_unmount_009_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_unshare/zfs_unshare_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_unshare/zfs_unshare_004_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_upgrade/zfs_upgrade_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool/zpool_001_neg.ksh
Labels: Status: Accepted
