Repository openzfs/zfs, pull requests merged in 2019-02, with the labels that each got.

#8368 flake8 pass
  tests/test-runner/bin/test-runner.py
  tests/test-runner/bin/zts-report.py
Labels: Status: Accepted

#8367 shellcheck pass
  cmd/zed/zed.d/statechange-led.sh
  cmd/zed/zed.d/zed-functions.sh
  cmd/zpool/zpool.d/smart
  scripts/zimport.sh
Labels: Status: Accepted

#8369 zstreamdump: -d option is not documented in manpage
  man/man8/zstreamdump.8
Labels: Status: Accepted

#8319 Fix ARC stats for embedded blkptrs
  module/zfs/arc.c
Labels: Status: Accepted

#8361 Pool allocation classes misplacing small file blocks
  man/man8/zfs.8
  module/zfs/spa_misc.c
  tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh
Labels: Status: Accepted

#8181 ZVOLs should not be allowed to have children
  contrib/pyzfs/libzfs_core/_constants.py
  contrib/pyzfs/libzfs_core/_error_translation.py
  contrib/pyzfs/libzfs_core/_libzfs_core.py
  contrib/pyzfs/libzfs_core/exceptions.py
  contrib/pyzfs/libzfs_core/test/test_libzfs_core.py
  include/libzfs.h
  include/sys/fs/zfs.h
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs/libzfs_util.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/dsl_dir.c
  module/zfs/zfs_ioctl.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/zvol/zvol_misc/Makefile.am
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_hierarchy.ksh
Labels: Status: Accepted

#8328 Get rid of space_map_update() for ms_synced_length
  cmd/zdb/zdb.c
  include/sys/metaslab.h
  include/sys/metaslab_impl.h
  include/sys/space_map.h
  module/zfs/metaslab.c
  module/zfs/spa_checkpoint.c
  module/zfs/space_map.c
  module/zfs/vdev.c
  module/zfs/vdev_indirect.c
  module/zfs/vdev_indirect_mapping.c
  module/zfs/vdev_initialize.c
  module/zfs/vdev_removal.c
Labels: Status: Accepted

#8142 port async unlinked drain from illumos-nexenta
  include/sys/dataset_kstats.h
  include/sys/dsl_pool.h
  include/sys/zfs_dir.h
  include/sys/zfs_vfsops.h
  man/man5/zfs-module-parameters.5
  module/zfs/dataset_kstats.c
  module/zfs/dsl_pool.c
  module/zfs/zfs_dir.c
  module/zfs/zfs_vfsops.c
  module/zfs/zfs_znode.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/mount/Makefile.am
  tests/zfs-tests/tests/functional/mount/umount_unlinked_drain.ksh
Labels: Status: Accepted, Type: Feature

#7888 freeing threshold should account for holes
  man/man5/zfs-module-parameters.5
  module/zfs/dmu.c
Labels: Status: Accepted

#8397 zdb: replace label_t to zdb_label_t for reduce collisions
  cmd/zdb/zdb.c
Labels: Status: Code Review Needed

#8408 Fix obsolete comment on rangelock
  module/zfs/zvol.c
Labels: Status: Accepted

#8389 Linux 4.20: Fix VERIFY(RW_READ_HELD(&hash->mh_contents)) assert
  include/spl/sys/rwlock.h
Labels: Status: Accepted

#7513 zfs should optionally send holds
  cmd/zfs/zfs_main.c
  include/libzfs.h
  include/sys/zfs_ioctl.h
  lib/libzfs/libzfs_sendrecv.c
  man/man8/zfs.8
  module/zfs/dmu_send.c
  module/zfs/dsl_userhold.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/rsend/Makefile.am
  tests/zfs-tests/tests/functional/rsend/send_holds.ksh
Labels: Status: Accepted, Type: Feature

#8362 zio_deadman_impl() fix and enhancement
  man/man5/zfs-module-parameters.5
  module/zfs/zio.c
Labels: Status: Accepted

#8409 clone_001_pos fails in cleanup on busy dataset
  tests/zfs-tests/tests/functional/snapshot/clone_001_pos.ksh
Labels: Status: Accepted

#8398 ZFS mounted NFSv3 shares fail lock reclaims
  etc/systemd/system/zfs-share.service.in
Labels: Component: Packaging, Component: Share, Status: Accepted

#8404 Delay injection can cause indefinitely hung zios
  module/zfs/zio.c
Labels: Status: Accepted

#8414 zfs mount man page should document legacy behaviour
  man/man8/zfs.8
Labels: Status: Accepted, Type: Documentation

#8422 ZTS: user_property_002_pos fails to destroy volume
  tests/zfs-tests/tests/functional/cli_root/zfs_set/user_property_002_pos.ksh
Labels: Status: Accepted

#8402 fix zdb crash
  lib/libzpool/util.c
Labels: Status: Accepted

#8424 Prevent user accounting on readonly pool
  module/zfs/dmu_objset.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/upgrade/Makefile.am
  tests/zfs-tests/tests/functional/upgrade/upgrade_readonly_pool.ksh
Labels: Status: Accepted

#8358 Introduce auxiliary metaslab histograms
  include/sys/metaslab.h
  include/sys/metaslab_impl.h
  include/sys/space_map.h
  module/zfs/metaslab.c
  module/zfs/vdev.c
Labels: Status: Accepted

#8428 add diffutils dependency for dkms build
  rpm/generic/zfs-dkms.spec.in
Labels: Component: Packaging, Status: Accepted, Type: Building

#8401 Don't enter zvol's rangelock for read bio with size 0 (#8379)
  module/zfs/zvol.c
Labels: Status: Accepted

#8438 Fix '-T u|d' descriptions in zpool(8)
  man/man8/zpool.8
Labels: Status: Code Review Needed

#8417 document pecularity about zpool iostat statistics reporting IOs as submitted to the block layer
  man/man8/zpool.8
Labels: Status: Accepted, Type: Documentation

#8433 Fix dnode_hold_impl() soft lockup
  include/sys/zfs_context.h
  module/zfs/dnode.c
Labels: Status: Accepted

#8391 zpool reports 16E expandsize on disks with oddball number of sectors
  module/zfs/vdev.c
  module/zfs/vdev_disk.c
Labels: Status: Accepted

#8371 zvol: allow rename of in use ZVOL dataset
  module/zfs/zvol.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/zvol/zvol_misc/Makefile.am
  tests/zfs-tests/tests/functional/zvol/zvol_misc/cleanup.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/setup.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_002_pos.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_rename_inuse.ksh
Labels: Status: Accepted

#8444 Error path in metaslab_load_impl() forgets to drop ms_sync_lock
  module/zfs/metaslab.c
Labels: Status: Accepted

#8423 zfs(8): improve document of compression behaviours
  man/man8/zfs.8
Labels: Status: Accepted

#8352 improve error message for zfs create with @ or # in name
  lib/libzfs/libzfs_dataset.c
Labels: Status: Accepted

#8440 sort by full path name instead of by GUID when updating cachefile
  lib/libzutil/zutil_import.c
Labels: Status: Accepted

#8410 zfs.8 has wrong description of "zfs program -t"
  cmd/zfs/zfs_main.c
  man/man8/zfs-program.8
  man/man8/zfs.8
  tests/zfs-tests/tests/functional/cli_root/zfs_program/zfs_program_json.ksh
Labels: Status: Accepted

#8445 Fix overly broad spa config lock
  module/zfs/spa_stats.c
  module/zfs/vdev.c
Labels: Status: Accepted

#8430 zstreamdump: include embedded writes when dumping raw data (-d)
  cmd/zstreamdump/zstreamdump.c
Labels: Status: Accepted

#8448 initramfs/debian: use panic() instead of directly calling /bin/sh
  contrib/initramfs/scripts/zfs.in
Labels: Status: Accepted

#8447 Remove zfs-zed hard dep from zfs-share init script
  etc/init.d/zfs-share.in
Labels: Status: Accepted
