Repository openzfs/zfs, pull requests merged in 2019-10, with the labels that each got.

#9380 Timeout waiting for ZVOL device to be created
  module/os/linux/zfs/zvol_os.c
  module/zfs/zvol.c
Labels: Status: Accepted

#9379 Fix-for-zfs-dracut-regression-#8913
  contrib/dracut/90zfs/zfs-load-key.sh.in
Labels: Component: Dracut, Status: Accepted

#9385 Enable clang to use intrinsics for lz4
  module/zfs/lz4.c
Labels: Status: Accepted

#9386 Make arc_stats visible to platform code
  include/sys/arc_impl.h
  module/zfs/arc.c
Labels: Status: Accepted

#9389 Add inode accessors to common code
  include/sys/zfs_znode.h
  module/zfs/sa.c
  module/zfs/zfs_fuid.c
  module/zfs/zfs_log.c
  module/zfs/zfs_sa.c
Labels: Status: Accepted

#9360 Workaround to avoid a race when /var/lib is a persistent dataset
  etc/systemd/system/zfs-mount.service.in
Labels: Status: Accepted

#9400 ZTS: Fix upgrade_readonly_pool
  tests/zfs-tests/tests/functional/upgrade/upgrade_common.kshlib
Labels: Status: Accepted, Type: Test Suite

#9356 Factor Linux specific functionality out of libzutil
  cmd/zed/agents/zfs_mod.c
  include/libzutil.h
  lib/libzutil/Makefile.am
  lib/libzutil/os/linux/zutil_device_path_os.c
  lib/libzutil/os/linux/zutil_import_os.c
  lib/libzutil/zutil_device_path.c
  lib/libzutil/zutil_import.c
  lib/libzutil/zutil_import.h
Labels: Status: Accepted

#9377 OpenZFS refactor - factor platform specific bits out of libzfs
  include/libzfs_impl.h
  lib/libzfs/Makefile.am
  lib/libzfs/libzfs_diff.c
  lib/libzfs/libzfs_mount.c
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs/libzfs_util.c
  lib/libzfs/os/linux/libzfs_mount_os.c
  lib/libzfs/os/linux/libzfs_pool_os.c
  lib/libzfs/os/linux/libzfs_sendrecv_os.c
  lib/libzfs/os/linux/libzfs_util_os.c
Labels: Status: Accepted

#9351 dbuf_hold_impl() cleanup to improve cached read performance
  module/zfs/dbuf.c
Labels: Status: Accepted

#9402 Rename rangelock_ functions to zfs_rangelock_
  include/sys/zfs_rlock.h
  module/os/linux/zfs/zfs_vnops.c
  module/os/linux/zfs/zfs_znode.c
  module/os/linux/zfs/zvol_os.c
  module/zfs/zfs_rlock.c
  module/zfs/zvol.c
Labels: Status: Accepted

#9384 Fix automount for root filesystems
  module/os/linux/zfs/zfs_ctldir.c
Labels: Status: Accepted

#9399 ZTS: Fix trim/trim_config and trim/autotrim_config
  tests/zfs-tests/tests/functional/trim/autotrim_config.ksh
  tests/zfs-tests/tests/functional/trim/trim_config.ksh
Labels: Status: Accepted, Type: Test Suite

#9418 module/Makefile.in: don't run xargs if empty
  module/Makefile.in
Labels: Status: Accepted

#9349 fix mmp_hostid test
  tests/zfs-tests/tests/functional/mmp/mmp_hostid.ksh
Labels: Status: Accepted

#9181 Reduce loaded range tree memory usage
  cmd/zdb/zdb.c
  include/sys/Makefile.am
  include/sys/avl.h
  include/sys/bitops.h
  include/sys/btree.h
  include/sys/metaslab.h
  include/sys/metaslab_impl.h
  include/sys/range_tree.h
  include/sys/spa.h
  include/sys/space_reftree.h
  include/sys/vdev.h
  include/sys/vdev_impl.h
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_iter.c
  lib/libzfs/libzfs_sendrecv.c
  lib/libzpool/Makefile.am
  lib/libzutil/zutil_import.c
  module/os/linux/zfs/zfs_znode.c
  module/zfs/Makefile.in
  module/zfs/arc.c
  module/zfs/btree.c
  module/zfs/ddt.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/dmu_send.c
  module/zfs/dnode.c
  module/zfs/dsl_bookmark.c
  module/zfs/dsl_deadlist.c
  module/zfs/dsl_deleg.c
  module/zfs/dsl_scan.c
  module/zfs/metaslab.c
  module/zfs/range_tree.c
  module/zfs/sa.c
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/space_map.c
  module/zfs/space_reftree.c
  module/zfs/unique.c
  module/zfs/vdev.c
  module/zfs/vdev_cache.c
  module/zfs/vdev_initialize.c
  module/zfs/vdev_label.c
  module/zfs/vdev_queue.c
  module/zfs/vdev_raidz.c
  module/zfs/vdev_removal.c
  module/zfs/vdev_trim.c
  module/zfs/zap_micro.c
  module/zfs/zfs_fuid.c
  module/zfs/zfs_rlock.c
  module/zfs/zil.c
Labels: Status: Accepted, Type: Performance

#9391 Move platform independent tests to a shared runfile
  scripts/zfs-tests.sh
  tests/README.md
  tests/runfiles/Makefile.am
  tests/runfiles/common.run
  tests/runfiles/linux.run
  tests/test-runner/bin/test-runner.py
Labels: Status: Accepted

#9426 Sort list of generated files in configure.ac
  configure.ac
Labels: Status: Accepted

#9434 Make clang happy with vdev_raidz_ code
  module/zfs/vdev_raidz_math_avx512f.c
  module/zfs/vdev_raidz_math_sse2.c
Labels: Status: Accepted

#9433 Fix strdup signature conflict on other platforms
  cmd/ztest/ztest.c
  include/os/linux/spl/sys/kmem.h
  include/sys/zfs_context.h
  module/icp/spi/kcf_spi.c
  module/os/linux/spl/spl-kmem.c
  module/os/linux/spl/spl-kstat.c
  module/os/linux/spl/spl-taskq.c
  module/os/linux/zfs/spa_stats.c
  module/os/linux/zfs/vdev_disk.c
  module/os/linux/zfs/zfs_ctldir.c
  module/os/linux/zfs/zfs_vfsops.c
  module/os/linux/zfs/zpl_xattr.c
  module/zfs/dmu_objset.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_pool.c
  module/zfs/dsl_prop.c
  module/zfs/dsl_userhold.c
  module/zfs/spa_history.c
  module/zfs/zcp_get.c
  module/zfs/zfs_ioctl.c
  module/zfs/zvol.c
Labels: Status: Accepted

#9428 Update `zfs program` command usage
  man/man8/zfs.8
Labels: Status: Accepted, Type: Documentation

#9440 Make `zil_async_to_sync` visible to platform code.
  include/sys/zil.h
  module/zfs/zil.c
Labels: Status: Accepted

#9404 Add kmem cache accessors
  include/os/linux/spl/sys/kmem_cache.h
  module/os/linux/spl/spl-kmem-cache.c
  module/zfs/metaslab.c
Labels: Status: Accepted

#9401 Move get_temporary_prop to platform code
  include/os/linux/zfs/sys/zfs_vfsops.h
  module/os/linux/zfs/zfs_vfsops.c
  module/zfs/zcp_get.c
Labels: Status: Accepted

#9429 Fix pool creation with feature@allocation_classes disabled
  include/zfs_comutil.h
  module/zcommon/zfs_comutil.c
  module/zfs/spa.c
  tests/zfs-tests/tests/functional/alloc_class/alloc_class_001_pos.ksh
Labels: Status: Accepted

#9447 ZTS: Fix some style nits in tests
  tests/zfs-tests/tests/functional/cli_root/zfs/zfs_002_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_send/zfs_send_006_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_unmount/zfs_unmount_008_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create.shlib
  tests/zfs-tests/tests/functional/history/history_001_pos.ksh
  tests/zfs-tests/tests/functional/history/history_common.kshlib
  tests/zfs-tests/tests/functional/inheritance/inherit_001_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#9445 ZTS: Clarify loop variable name in zfs copies test
  tests/zfs-tests/tests/functional/cli_root/zfs_copies/zfs_copies_006_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#9431 Expose dmu_buf_hold_array_by_dnode to platform code
  include/sys/dmu.h
  module/zfs/dmu.c
Labels: Status: Accepted

#9449 Remove linux/mod_compat.h from common code.
  module/icp/algs/aes/aes_impl.c
  module/icp/algs/modes/gcm.c
  module/zcommon/zfs_fletcher.c
Labels: Status: Accepted

#9441 Function name and comment updates
  include/sys/btree.h
  module/zfs/btree.c
  module/zfs/dsl_scan.c
  module/zfs/range_tree.c
Labels: Status: Accepted

#9451 ZTS: Fix zpool_status_-s
  tests/zfs-tests/tests/functional/fault/scrub_after_resilver.ksh
  tests/zfs-tests/tests/functional/fault/zpool_status_-s.ksh
Labels: Status: Accepted, Type: Test Suite

#9452 Typo fix in comment: dso_dryrun
  module/zfs/dmu_send.c
Labels: Status: Accepted

#9425 Modify sharenfs=on default behavior
  lib/libshare/nfs.c
  man/man8/zfs.8
Labels: Component: Share, Status: Accepted

#9439 Move zio_delay_interrupt to platform code
  lib/libzpool/Makefile.am
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/zio_os.c
  module/zfs/zio.c
Labels: Status: Accepted

#9442 move zfs_onexit_fd_hold to platform code
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/zfs_onexit_os.c
  module/zfs/zfs_onexit.c
Labels: Status: Accepted

#9455 Fix small btree-related errors
  include/sys/range_tree.h
  module/zfs/dsl_scan.c
Labels: Status: Accepted

#9432 Remove dead code and cleanup scoping in dmu_send.c
  module/zfs/dmu_send.c
Labels: Status: Code Review Needed

#9467 Fix signature for private functions without header declarations
  module/zfs/btree.c
  module/zfs/dsl_destroy.c
Labels: Status: Accepted

#9450 Add default case to lua kernel code.
  module/lua/ldo.c
Labels: Status: Accepted

#9465 Move linux specific mmp module_param_call handler to platform code
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/mmp_os.c
  module/zfs/mmp.c
Labels: Status: Accepted

#9466 Make zfsdev_getminor signature cross platform
  include/sys/zfs_ioctl.h
  module/os/linux/zfs/zfs_ioctl_os.c
  module/os/linux/zfs/zfs_onexit_os.c
  module/zfs/fm.c
Labels: Status: Accepted

#9463 Detect if sed supports --in-place
  cmd/arcstat/Makefile.am
  cmd/dbufstat/Makefile.am
  config/always-sed.m4
  config/zfs-build.m4
  tests/test-runner/bin/Makefile.am
Labels: Status: Accepted

#9472 Factor platform specific memory pressure handling out of arc
  include/sys/arc_impl.h
  lib/libzpool/Makefile.am
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/arc_os.c
  module/zfs/arc.c
Labels: Status: Accepted

#9474 Update skc_obj_alloc for spl kmem caches that are backed by Linux
  module/os/linux/spl/spl-kmem-cache.c
  module/os/linux/spl/spl-proc.c
Labels: Status: Accepted

#9478 Name anonymous enum of KMC_BIT constants
  include/os/linux/spl/sys/kmem_cache.h
Labels: Status: Accepted

#9477 ZTS: Written props test fails with 4k disks
  tests/zfs-tests/tests/functional/cli_root/zfs_property/zfs_written_property_001_pos.ksh
Labels: Status: Accepted

#9486 Use correct format string when printing int8
  lib/libnvpair/libnvpair_json.c
Labels: Status: Accepted

#9493 Use platform independent error code for libzfs_run_process_impl
  lib/libzfs/libzfs_util.c
Labels: Status: Accepted

#9453 Don't call arc_buf_destroy on unallocated arc_buf
  module/zfs/dmu_send.c
Labels: Status: Accepted

#9492 Use zfs_ioctl with zfs_cmd_t in libzfs
  lib/libzfs/libzfs_config.c
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_diff.c
  lib/libzfs/libzfs_import.c
  lib/libzfs/libzfs_iter.c
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#9406 Linux 4.14, 4.19, 5.0+ compat: SIMD save/restore
  config/kernel-fpu.m4
  include/os/linux/kernel/linux/simd.h
  include/os/linux/kernel/linux/simd_aarch64.h
  include/os/linux/kernel/linux/simd_x86.h
  include/sys/zio_crypt.h
  lib/libspl/include/sys/simd.h
  module/icp/algs/aes/aes_impl.c
  module/icp/algs/modes/gcm.c
  module/icp/include/aes/aes_impl.h
  module/icp/include/modes/gcm_impl.h
  module/icp/io/aes.c
  module/os/linux/spl/spl-taskq.c
  module/os/linux/spl/spl-thread.c
  module/os/linux/zfs/zio_crypt.c
  module/zcommon/zfs_fletcher.c
  module/zcommon/zfs_prop.c
  module/zfs/arc.c
  module/zfs/dsl_crypt.c
  module/zfs/vdev_raidz_math.c
Labels: Status: Accepted

#9502 ZTS: Consistency pass for .ksh extensions
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_test_race.ksh
Labels: Status: Accepted, Type: Test Suite

#9503 ZTS: Move tmpfile tests to linux.run
  tests/runfiles/common.run
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/Makefile.am
Labels: Status: Accepted, Type: Test Suite

#9494 Fix incremental recursive encrypted receive
  lib/libzfs/libzfs_sendrecv.c
  tests/zfs-tests/tests/functional/rsend/send_encrypted_props.ksh
Labels: Status: Accepted

#9497 Remove sdt.h
  include/os/linux/spl/sys/sysmacros.h
  include/sys/Makefile.am
  include/sys/sdt.h
  include/sys/zfs_context.h
  include/sys/zfs_debug.h
  lib/libspl/include/sys/trace_defs.h
  module/os/linux/zfs/zfs_acl.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#9498 Move platform dependent errno aliases
  include/os/linux/spl/sys/errno.h
  include/sys/zio.h
  lib/libspl/include/os/linux/sys/Makefile.am
  lib/libspl/include/os/linux/sys/errno.h
  lib/libspl/include/sys/Makefile.am
Labels: Status: Accepted

#9505 Move final zvol_remove_minors to common code
  module/os/linux/zfs/zvol_os.c
  module/zfs/zvol.c
Labels: Status: Accepted

#9506 Remove non-portable pointer is valid assert
  module/zfs/dnode.c
Labels: Status: Accepted

#9507 Use zfs_ioctl() in zinject.c
  cmd/zinject/zinject.c
Labels: Status: Accepted

#9509 Remove unused headers from uu_string.c
  lib/libuutil/uu_string.c
Labels: Status: Accepted

#9512 ZTS: Move more tests to linux.run
  tests/runfiles/common.run
  tests/runfiles/linux.run
Labels: Status: Accepted, Type: Test Suite

#9514 Fix botched header guard
  lib/libspl/include/sys/trace_defs.h
Labels: Status: Accepted

#9510 Remove unneeded header from libzpool/kernel.c
  lib/libspl/include/sys/signal.h
  lib/libzpool/kernel.c
Labels: Status: Accepted

#9489 Sysctls for ARC min/max ignored at runtime
  include/os/linux/kernel/linux/mod_compat.h
  include/sys/arc_impl.h
  include/sys/zfs_context.h
  module/os/linux/zfs/arc_os.c
  module/zfs/arc.c
  module/zfs/spa_misc.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/arc/Makefile.am
  tests/zfs-tests/tests/functional/arc/arcstats_runtime_tuning.ksh
  tests/zfs-tests/tests/perf/perf.shlib
Labels: Status: Accepted

#9516 Fix zpool history unbounded memory usage
  cmd/zpool/zpool_main.c
  include/libzfs.h
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#9499 spa portability fixes
  include/sys/spa.h
  module/zfs/spa.c
Labels: Status: Accepted, Status: Code Review Needed

#9508 Add wrapper for Linux BLKFLSBUF ioctl
  cmd/zdb/zdb.c
  cmd/zpool/zpool_main.c
  include/libzutil.h
  lib/libzutil/os/linux/zutil_import_os.c
Labels: Status: Accepted

#9517 Add AVX512BW variant of fletcher
  include/zfs_fletcher.h
  man/man5/zfs-module-parameters.5
  module/zcommon/zfs_fletcher.c
  module/zcommon/zfs_fletcher_avx512.c
Labels: Status: Accepted

#9527 Fix contrib/zcp/Makefile.am
  contrib/zcp/Makefile.am
Labels: Status: Accepted, Type: Building

#9520 dracut/zfs-load-key.sh: properly remove prefixes
  contrib/dracut/90zfs/zfs-load-key.sh.in
Labels: Status: Accepted

#9457 Factor Linux specific code out of spa_misc.c
  include/os/linux/kernel/linux/mod_compat.h
  include/sys/spa.h
  include/sys/spa_impl.h
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/spa_misc_os.c
  module/zfs/spa_misc.c
Labels: Status: Accepted

#9535 include prototypes for vdev_initialize
  module/zfs/vdev_initialize.c
Labels: Status: Accepted

#9533 Don't cast away const in rangetree
  include/sys/range_tree.h
Labels: Status: Accepted

#9528 ZTS: Fix removal_with_errors
  tests/zfs-tests/tests/functional/removal/removal_with_errors.ksh
Labels: Status: Accepted, Type: Test Suite

#9530 Move sha2.h to platform code
  include/os/linux/zfs/sys/Makefile.am
  include/os/linux/zfs/sys/sha2.h
  include/sys/Makefile.am
  lib/libspl/include/sys/Makefile.am
  lib/libspl/include/sys/sha2.h
Labels: Status: Accepted
