Repository openzfs/zfs, pull requests merged in 2019-11, with the labels that each got.

#9541 Return an error code from zfs_acl_chmod_setattr
  include/sys/zfs_acl.h
  module/os/linux/zfs/zfs_acl.c
  module/os/linux/zfs/zfs_vnops.c
Labels: Status: Accepted

#9538 Fix icp build on FreeBSD
  module/icp/algs/sha1/sha1.c
  module/icp/include/sys/modctl.h
Labels: Status: Accepted

#9537 Remove Linux specific ECKSUM alias in zinject
  cmd/zinject/zinject.c
Labels: Status: Accepted

#9534 Scope struct rangelock
  cmd/ztest/ztest.c
  include/sys/dmu.h
  include/sys/zfs_rlock.h
  include/sys/zfs_znode.h
  include/sys/zvol_impl.h
  module/os/linux/zfs/zfs_vnops.c
  module/os/linux/zfs/zfs_znode.c
  module/os/linux/zfs/zvol_os.c
  module/zfs/zfs_rlock.c
Labels: Status: Accepted

#9542 Wrap Linux module macros
  include/os/linux/kernel/linux/mod_compat.h
  include/os/linux/spl/sys/Makefile.am
  include/os/linux/spl/sys/mod_os.h
  include/sys/Makefile.am
  include/sys/mod.h
  include/sys/zfs_context.h
  module/avl/avl.c
  module/lua/lapi.c
  module/nvpair/nvpair.c
  module/os/linux/spl/spl-generic.c
  module/os/linux/zfs/zfs_ioctl_os.c
  module/unicode/u8_textprep.c
  module/zcommon/zfs_prop.c
Labels: Status: Accepted

#9545 zvol_wait should ignore redacted zvols
  cmd/zvol_wait/zvol_wait
Labels: Status: Accepted

#9536 Move kernel defines in zfs_znode.h to platform code.
  include/os/linux/zfs/sys/Makefile.am
  include/os/linux/zfs/sys/zfs_znode_impl.h
  include/sys/zfs_znode.h
  module/os/linux/zfs/zfs_acl.c
  module/zfs/zfs_rlock.c
Labels: Status: Accepted

#9540 Preliminary support for RV64G (RISC-V)
  include/os/linux/spl/sys/isa_defs.h
  lib/libefi/rdwr_efi.c
  lib/libspl/include/sys/isa_defs.h
  module/lua/ldo.c
  module/lua/setjmp/setjmp.S
  module/lua/setjmp/setjmp_rv64g.S
Labels: Status: Accepted

#9544 Add a notice in /etc/defaults/zfs for systemd users.
  etc/init.d/zfs.in
Labels: Status: Accepted, Type: Documentation

#9529 zfs-mount-generator: Skip loading already loaded key
  contrib/dracut/90zfs/mount-zfs.sh.in
  contrib/dracut/90zfs/zfs-load-key.sh.in
  contrib/initramfs/scripts/zfs.in
  etc/systemd/system-generators/zfs-mount-generator.in
Labels: Status: Accepted

#9561 Isolate code specific to Linux in cmd/
  cmd/Makefile.am
  cmd/arc_summary/arc_summary2
  cmd/arc_summary/arc_summary3
  cmd/arcstat/arcstat
Labels: Component: Userspace, Status: Accepted

#9409 Improve logging of 128KB writes.
  module/zfs/zil.c
Labels: Status: Accepted

#9549 Remove zpl_revalidate
  config/kernel-dentry-operations.m4
  include/os/linux/zfs/sys/zfs_vfsops.h
  include/os/linux/zfs/sys/zfs_znode_impl.h
  include/os/linux/zfs/sys/zpl.h
  module/os/linux/zfs/zfs_vfsops.c
  module/os/linux/zfs/zpl_inode.c
Labels: Status: Accepted

#9565 Allow platform dependent path stripping for vdevs
  include/libzutil.h
  lib/libzfs/libzfs_pool.c
  lib/libzutil/os/linux/zutil_device_path_os.c
Labels: Status: Accepted

#9511 Add wrapper stub for zfs_cmd ioctl to libzpool
  include/libzutil.h
  lib/libzfs_core/Makefile.am
  lib/libzfs_core/libzfs_core.c
  lib/libzpool/util.c
  lib/libzutil/Makefile.am
  lib/libzutil/os/linux/zutil_compat.c
Labels: Status: Code Review Needed

#9559 Reorganize zfs(8) man page into sections
  man/man8/Makefile.am
  man/man8/zfs-allow.8
  man/man8/zfs-bookmark.8
  man/man8/zfs-change-key.8
  man/man8/zfs-clone.8
  man/man8/zfs-create.8
  man/man8/zfs-destroy.8
  man/man8/zfs-diff.8
  man/man8/zfs-get.8
  man/man8/zfs-groupspace.8
  man/man8/zfs-hold.8
  man/man8/zfs-inherit.8
  man/man8/zfs-list.8
  man/man8/zfs-load-key.8
  man/man8/zfs-mount.8
  man/man8/zfs-project.8
  man/man8/zfs-projectspace.8
  man/man8/zfs-promote.8
  man/man8/zfs-receive.8
  man/man8/zfs-recv.8
  man/man8/zfs-redact.8
  man/man8/zfs-release.8
  man/man8/zfs-rename.8
  man/man8/zfs-rollback.8
  man/man8/zfs-send.8
  man/man8/zfs-set.8
  man/man8/zfs-share.8
  man/man8/zfs-snapshot.8
  man/man8/zfs-unallow.8
  man/man8/zfs-unload-key.8
  man/man8/zfs-unmount.8
  man/man8/zfs-upgrade.8
  man/man8/zfs-userspace.8
  man/man8/zfs.8
  man/man8/zfsconcepts.8
  man/man8/zfsprops.8
Labels: Status: Accepted, Type: Documentation

#9564 Sectional zpool manpage
  man/man8/Makefile.am
  man/man8/fsck.zfs.8
  man/man8/zed.8.in
  man/man8/zpool-add.8
  man/man8/zpool-attach.8
  man/man8/zpool-checkpoint.8
  man/man8/zpool-clear.8
  man/man8/zpool-create.8
  man/man8/zpool-destroy.8
  man/man8/zpool-detach.8
  man/man8/zpool-events.8
  man/man8/zpool-export.8
  man/man8/zpool-get.8
  man/man8/zpool-history.8
  man/man8/zpool-import.8
  man/man8/zpool-initialize.8
  man/man8/zpool-iostat.8
  man/man8/zpool-labelclear.8
  man/man8/zpool-list.8
  man/man8/zpool-offline.8
  man/man8/zpool-online.8
  man/man8/zpool-reguid.8
  man/man8/zpool-remove.8
  man/man8/zpool-reopen.8
  man/man8/zpool-replace.8
  man/man8/zpool-resilver.8
  man/man8/zpool-scrub.8
  man/man8/zpool-set.8
  man/man8/zpool-split.8
  man/man8/zpool-status.8
  man/man8/zpool-sync.8
  man/man8/zpool-trim.8
  man/man8/zpool-upgrade.8
  man/man8/zpool-wait.8
  man/man8/zpool.8
  man/man8/zpoolconcepts.8
  man/man8/zpoolprops.8
Labels: Status: Accepted, Type: Documentation

#9568 Fix `zpool create -o <property>` error message
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#9577 Prevent NULL pointer dereference in blkg_tryget() on EL8 kernels
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#9581 Change zed.service to zfs-zed.service in man page (fixed)
  man/man8/zfs-mount-generator.8.in
Labels: Status: Accepted

#9574 Remove inappropiate error message suggesting to apply '-r'
  lib/libzfs/libzfs_dataset.c
Labels: Status: Accepted

#9583 [RFC] Break out of zfs_zget early if unlinked znode
  module/os/linux/zfs/zfs_znode.c
Labels: Status: Accepted

#9592 Partially revert 5a6ac4c
  config/kernel-dentry-operations.m4
  include/os/linux/zfs/sys/zpl.h
  module/os/linux/zfs/zfs_vfsops.c
  module/os/linux/zfs/zpl_inode.c
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/snapshot/rollback_003_pos.ksh
Labels: Status: Accepted

#9589 Remove requirement for -d 1 for zfs list and zfs get with bookmarks
  cmd/zfs/zfs_main.c
  tests/zfs-tests/tests/functional/cli_root/zfs_get/zfs_get_009_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_get/zfs_get_list_d.kshlib
Labels: Status: Accepted

#8812 Casenorm tests: enable backslash interpretation
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/casenorm/casenorm.cfg
  tests/zfs-tests/tests/functional/casenorm/casenorm.kshlib
Labels: Status: Work in Progress

#9601 ZTS: tst.terminate_by_signal increase test threshold
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.terminate_by_signal.ksh
Labels: Status: Accepted, Type: Test Suite

#9556 Factor out non-portable vnode_t usage
  cmd/raidz_test/raidz_test.c
  cmd/zdb/zdb.c
  cmd/zhack/zhack.c
  cmd/ztest/ztest.c
  include/os/linux/spl/sys/Makefile.am
  include/os/linux/spl/sys/kobj.h
  include/os/linux/spl/sys/mode.h
  include/os/linux/spl/sys/vnode.h
  include/os/linux/zfs/sys/policy.h
  include/os/linux/zfs/sys/zfs_vnops.h
  include/sys/Makefile.am
  include/sys/dmu.h
  include/sys/dmu_recv.h
  include/sys/spa.h
  include/sys/spa_impl.h
  include/sys/vdev_file.h
  include/sys/vdev_impl.h
  include/sys/zfs_context.h
  include/sys/zfs_file.h
  include/sys/zil.h
  lib/libspl/include/os/linux/sys/Makefile.am
  lib/libspl/include/os/linux/sys/file.h
  lib/libzpool/kernel.c
  module/os/linux/spl/Makefile.in
  module/os/linux/spl/spl-generic.c
  module/os/linux/spl/spl-kobj.c
  module/os/linux/spl/spl-vnode.c
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/mmp_os.c
  module/os/linux/zfs/policy.c
  module/os/linux/zfs/spa_misc_os.c
  module/os/linux/zfs/vdev_disk.c
  module/os/linux/zfs/vdev_file.c
  module/os/linux/zfs/zfs_acl.c
  module/os/linux/zfs/zfs_dir.c
  module/os/linux/zfs/zfs_file_os.c
  module/os/linux/zfs/zfs_ioctl_os.c
  module/os/linux/zfs/zfs_onexit_os.c
  module/os/linux/zfs/zfs_vnops.c
  module/os/linux/zfs/zfs_znode.c
  module/os/linux/zfs/zpl_file.c
  module/zfs/arc.c
  module/zfs/dmu_diff.c
  module/zfs/dmu_recv.c
  module/zfs/dsl_crypt.c
  module/zfs/fm.c
  module/zfs/spa.c
  module/zfs/spa_config.c
  module/zfs/spa_misc.c
  module/zfs/vdev_label.c
  module/zfs/zfs_ioctl.c
  module/zfs/zfs_log.c
  module/zfs/zfs_replay.c
Labels: Status: Accepted

#9602 Check for unlinked znodes after igrab()
  module/os/linux/zfs/zfs_znode.c
Labels: Status: Accepted

#9607 zdb -R should be able to display checksums
  cmd/zdb/zdb.c
  man/man8/zdb.8
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zdb/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_checksum.ksh
Labels: Status: Accepted

#9588 Prevent unnecessary resilver restarts
  configure.ac
  include/sys/dsl_scan.h
  include/sys/spa.h
  include/sys/vdev.h
  module/zfs/dsl_scan.c
  module/zfs/spa.c
  module/zfs/vdev.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/Makefile.am
  tests/zfs-tests/tests/functional/resilver/Makefile.am
  tests/zfs-tests/tests/functional/resilver/cleanup.ksh
  tests/zfs-tests/tests/functional/resilver/resilver.cfg
  tests/zfs-tests/tests/functional/resilver/resilver_restart_001.ksh
  tests/zfs-tests/tests/functional/resilver/setup.ksh
Labels: Status: Accepted

#9609 Remove zfs_vdev_elevator module option
  config/kernel-elevator-change.m4
  config/kernel.m4
  include/os/linux/kernel/linux/blkdev_compat.h
  man/man5/zfs-module-parameters.5
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#9610 Implement -A (ignore ASSERTs) for zdb
  lib/libspl/include/assert.h
  lib/libzpool/kernel.c
Labels: Status: Accepted

#9615 Minor diff reduction with ZoF in include/sys
  include/os/linux/spl/sys/uio.h
  include/sys/abd.h
  include/sys/dmu.h
  include/sys/zfs_project.h
  include/sys/zio.h
Labels: Status: Accepted

#9636 fix attach-o_ashift.ksh for multiplatforms
  tests/zfs-tests/tests/functional/cli_root/zpool_attach/attach-o_ashift.ksh
Labels: Status: Accepted

#9625 Resolve ZoF differences in zfs_ioctl.h
  include/sys/zfs_ioctl.h
  module/os/linux/zfs/zfs_ioctl_os.c
Labels: Status: Accepted

#9631 Add FreeBSD support to zio_crypto.h
  include/sys/zio_crypt.h
Labels: Status: Accepted

#9633 Mark Linux fallocate extensions as specific to Linux
  lib/libzpool/kernel.c
  module/os/linux/zfs/vdev_file.c
Labels: Status: Accepted

#9634 make asm-x86_64/atomic.S build on FreeBSD
  lib/libspl/asm-x86_64/atomic.S
Labels: Status: Accepted

#9641 Add FreeBSD code to arc_summary and arcstat
  cmd/arc_summary/arc_summary2
  cmd/arc_summary/arc_summary3
  cmd/arcstat/arcstat
Labels: Component: Userspace, Status: Accepted

#9643 Restructure nvlist_nv_alloc to work on FreeBSD
  module/nvpair/nvpair.c
Labels: Status: Accepted

#9632 Add FreeBSD required defines to mntent.h
  include/sys/mntent.h
Labels: Status: Accepted
