Repository openzfs/zfs, pull requests merged in 2019-03, with the labels that each got.

#8455 abd_alloc should use scatter for <=4K allocations
  man/man5/zfs-module-parameters.5
  module/zfs/abd.c
Labels: Status: Accepted

#8457 Warn user about accidentally sharing devices
  man/man8/zpool.8
Labels: Status: Accepted, Type: Documentation

#8460 Do not resume a pool if multihost is enabled
  cmd/ztest/ztest.c
  man/man8/zpool.8
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#8459 fix style of spl_kmem_cache_create()
  module/spl/spl-kmem-cache.c
Labels: Status: Accepted

#8313 config: amend libtirpc detection for opensuse
  config/ax_restore_flags.m4
  config/ax_save_flags.m4
  config/find_system_library.m4
  config/pkg.m4
  config/user-libtirpc.m4
  configure.ac
  lib/libnvpair/Makefile.am
  lib/libspl/Makefile.am
  lib/libspl/include/rpc/xdr.h
Labels: Status: Accepted, Type: Building

#8461 Fix race in vdev_initialize_thread
  module/zfs/vdev_initialize.c
Labels: Status: Accepted

#7675 bpobj_iterate overflows the stack
  include/sys/dmu.h
  module/zfs/bpobj.c
  module/zfs/dbuf.c
Labels: Status: Accepted

#8363 kernel_fpu fixes
  config/kernel-fpu.m4
  include/linux/simd_x86.h
Labels: Status: Accepted, Type: Building

#8479 Linux 5.1 compat: get_ds() removed
  module/spl/spl-vnode.c
Labels: Status: Accepted, Type: Building

#8484 Reorder ZFS ioctls to fix cross-version compatibility
  include/sys/fs/zfs.h
  tests/zfs-tests/cmd/libzfs_input_check/libzfs_input_check.c
Labels: Status: Accepted

#8413 zfs: Fix lockdep between ds_lock and dd_lock in dsl_dataset_namelen()
  module/zfs/dsl_dataset.c
Labels: Status: Accepted

#8486 zfs does not honor NFS sync write semantics
  module/zfs/zpl_file.c
Labels: Status: Accepted

#7953 rotate over leaves for mmp writes
  include/sys/mmp.h
  include/sys/spa_impl.h
  include/sys/vdev_impl.h
  module/zfs/mmp.c
  module/zfs/spa_misc.c
  module/zfs/vdev.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/mmp/Makefile.am
  tests/zfs-tests/tests/functional/mmp/mmp_write_distribution.ksh
Labels: Status: Accepted

#8477 Fix vdev_initialize_restart / removal race
  module/zfs/vdev_initialize.c
Labels: Status: Accepted

#8077 avoid retrieving unused snapshot props
  cmd/zfs/zfs_iter.c
  cmd/zfs/zfs_main.c
  include/libzfs.h
  include/sys/fs/zfs.h
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_iter.c
  lib/libzfs/libzfs_sendrecv.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted, Type: Feature

#8463 Fix most zfs_arc_* mod params not actually being modifiable at runtime
  module/zfs/arc.c
Labels: Status: Accepted

#8495 Increase default zfs_multihost_fail_intervals and import_intervals
  include/sys/mmp.h
  man/man5/zfs-module-parameters.5
Labels: Status: Accepted

#8499 Fix typo in arc_summary3
  cmd/arc_summary/arc_summary3
Labels: Status: Accepted

#8487 Fix handling of maxblkid for raw sends
  include/sys/dmu.h
  include/sys/dnode.h
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_recv.c
  module/zfs/dnode.c
  module/zfs/dnode_sync.c
  module/zfs/dsl_crypt.c
  tests/zfs-tests/cmd/xattrtest/xattrtest.c
  tests/zfs-tests/tests/functional/rsend/send_encrypted_files.ksh
Labels: Status: Accepted

#8493 Make zstreamdump -v more greppable
  cmd/zstreamdump/zstreamdump.c
  tests/zfs-tests/tests/functional/rsend/rsend.kshlib
  tests/zfs-tests/tests/functional/rsend/send-c_zstreamdump.ksh
Labels: Status: Accepted

#8466 point users to IRC as well as mailing list in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Status: Accepted

#8494 Add separate aggregation limit for non-rotating media.
  man/man5/zfs-module-parameters.5
  module/zfs/vdev_queue.c
Labels: Status: Accepted

#8501 use 'printf %s' instead of 'echo -n' for compatibility with others platforms
  tests/zfs-tests/tests/functional/cli_root/zfs_change-key/zfs_change-key_format.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_crypt_combos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_crypt_combos.ksh
Labels: Status: Accepted

#8498 make zed.rc values reflect their default value
  cmd/zed/zed.d/zed.rc
Labels: Component: ZED, Status: Accepted, Type: Documentation

#8502 zfs-import: should be before swap
  etc/init.d/zfs-import.in
Labels: Status: Code Review Needed

#8490 Fix memory leaks in zfsvfs_create_impl()
  module/zfs/zfs_vfsops.c
Labels: Status: Accepted

#7817 Make zpool status counters match err events count
  module/zfs/vdev.c
  module/zfs/vdev_raidz.c
  module/zfs/zio.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zpool_events/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_events/zpool_events_errors.ksh
Labels: Status: Accepted

#8453 Multiple DVA Scrubbing Fix
  cmd/zinject/zinject.c
  include/sys/zfs_ioctl.h
  man/man8/zinject.8
  module/zfs/dsl_scan.c
  module/zfs/vdev_mirror.c
  module/zfs/zio_inject.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zpool_scrub/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_scrub/zpool_scrub_multiple_copies.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_scrub/zpool_scrub_offline_device.ksh
Labels: Status: Code Review Needed

#8144 Fix l2arc_evict() destroy race
  module/zfs/arc.c
Labels: Status: Code Review Needed

#8514 Add space in error message.
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#8500 Additional safe guards for `zpool labelclear`
  cmd/zpool/zpool_main.c
  lib/libzfs/libzfs_import.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zpool_attach/attach-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_labelclear/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_labelclear/labelclear.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_labelclear/zpool_labelclear_active.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_labelclear/zpool_labelclear_exported.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_labelclear/zpool_labelclear_removed.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_labelclear/zpool_labelclear_valid.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_replace/replace-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_replace/replace_prop_ashift.ksh
Labels: Status: Accepted

#8505 Report holes when there are only metadata changes
  module/zfs/dmu.c
Labels: Status: Accepted

#8521 Fix digest_buffer allocation in qat_checksum
  module/zfs/qat_crypt.c
Labels: Status: Accepted

#7842 MMP should specify wait time in uberblock
  cmd/zdb/zdb.c
  include/sys/fs/zfs.h
  include/sys/mmp.h
  include/sys/uberblock_impl.h
  man/man5/zfs-module-parameters.5
  module/zfs/mmp.c
  module/zfs/spa.c
  module/zfs/uberblock.c
  module/zfs/vdev_label.c
  tests/zfs-tests/tests/functional/mmp/cleanup.ksh
  tests/zfs-tests/tests/functional/mmp/mmp.cfg
  tests/zfs-tests/tests/functional/mmp/mmp.kshlib
  tests/zfs-tests/tests/functional/mmp/mmp_active_import.ksh
  tests/zfs-tests/tests/functional/mmp/mmp_inactive_import.ksh
  tests/zfs-tests/tests/functional/mmp/mmp_on_uberblocks.ksh
  tests/zfs-tests/tests/functional/mmp/mmp_reset_interval.ksh
  tests/zfs-tests/tests/functional/mmp/setup.ksh
Labels: Status: Accepted

#8523 ZFS reads may result in unnecessary calls to zil_commit
  include/spl/sys/vnode.h
  lib/libspl/include/sys/file.h
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#7856 Panic when running 'zpool split'
  module/zfs/spa.c
Labels: Status: Accepted

#8522 Fix `vd_path` use after `spa_vdev_exit()`
  module/zfs/vdev_removal.c
Labels: Status: Accepted

#8525 git ignore python virtual environment directories
  .gitignore
Labels: Status: Accepted

#8534 ZTS: Detect e2fsprogs verity issue
  tests/zfs-tests/tests/functional/projectquota/projectid_001_pos.ksh
  tests/zfs-tests/tests/functional/projectquota/projecttree_001_pos.ksh
Labels: Status: Accepted

#8532 Update valid vdev types for ZTS get_disklist
  tests/zfs-tests/include/libtest.shlib
Labels: Status: Accepted, Type: Test Suite

#8533 Send stream should only list included snaps
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#8544 Update raw send documentation
  man/man8/zfs.8
Labels: Status: Accepted
