Repository openzfs/zfs, pull requests merged in 2019-01, with the labels that each got.

#8222 Add missing MMP status code to libzfs_status
  include/libzfs.h
  lib/libzfs/libzfs_status.c
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import_errata3.ksh
Labels: Status: Accepted

#8231 Add zfs module feature and property compatibility
  module/zcommon/zfeature_common.c
Labels: Status: Accepted

#8241 zfs.8 uses wrong snapshot names in Example 15
  man/man8/zfs.8
Labels: Status: Accepted, Type: Documentation

#8250 Bump commit subject length to 72 characters
  .github/CONTRIBUTING.md
  scripts/commitcheck.sh
Labels: Status: Accepted

#8232 zfs receive and rollback can skew filesystem_count
  configure.ac
  module/zfs/dsl_destroy.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/Makefile.am
  tests/zfs-tests/tests/functional/limits/Makefile.am
  tests/zfs-tests/tests/functional/limits/cleanup.ksh
  tests/zfs-tests/tests/functional/limits/filesystem_count.ksh
  tests/zfs-tests/tests/functional/limits/filesystem_limit.ksh
  tests/zfs-tests/tests/functional/limits/setup.ksh
  tests/zfs-tests/tests/functional/limits/snapshot_count.ksh
  tests/zfs-tests/tests/functional/limits/snapshot_limit.ksh
Labels: Status: Accepted

#8243 Use ZFS version for pyzfs and remove unused requirements.txt
  configure.ac
  contrib/pyzfs/Makefile.am
  contrib/pyzfs/requirements.txt
  contrib/pyzfs/setup.py.in
Labels: Status: Accepted

#8247 Removed suggestion to use root dataset as bootfs
  contrib/dracut/README.dracut.markdown
Labels: Status: Accepted, Type: Documentation

#8249 Don't allow dnode allocation if dn_holds != 0
  module/zfs/dnode.c
Labels: Status: Accepted

#8015 Add dmu_object_alloc_hold() and zap_create_hold()
  include/sys/dmu.h
  include/sys/zap.h
  module/zfs/dmu.c
  module/zfs/dmu_object.c
  module/zfs/dmu_recv.c
  module/zfs/zap_micro.c
Labels: Status: Accepted

#8273 ZTS: zpool_resilver_restart
  tests/zfs-tests/tests/functional/cli_root/zpool_resilver/zpool_resilver.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_resilver/zpool_resilver_restart.ksh
Labels: Status: Accepted

#8265 Add pyzfs BuildRequires for mock(1)
  rpm/generic/zfs.spec.in
Labels: Status: Accepted, Type: Packaging

#8268 Add contrib/pyzfs/setup.py to .gitignore
  contrib/pyzfs/.gitignore
Labels: Status: Accepted

#8254 zfs filesystem skipped by df -h
  module/zfs/zfs_vfsops.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/no_space/Makefile.am
  tests/zfs-tests/tests/functional/no_space/enospc_df.ksh
Labels: Status: Accepted

#8229 Eliminate ZTHR races by serializing ZTHR operations.
  include/sys/spa_checkpoint.h
  include/sys/zthr.h
  module/zfs/arc.c
  module/zfs/spa.c
  module/zfs/spa_checkpoint.c
  module/zfs/vdev_indirect.c
  module/zfs/zthr.c
Labels: Status: Accepted

#8272 Minor spelling corrections
  cmd/ztest/ztest.c
  module/zfs/zio.c
Labels: Status: Accepted

#8281 Verify .gitignore entries
  .gitignore
  Makefile.am
Labels: Status: Code Review Needed

#8267 Fix zio leak in dbuf_read()
  module/zfs/dbuf.c
Labels: Status: Accepted

#8292 Make zdb results for checkpoint tests consistent
  tests/zfs-tests/tests/functional/pool_checkpoint/pool_checkpoint.kshlib
Labels: Status: Accepted

#8271 ztest: split block reconstruction
  cmd/zdb/zdb.c
  cmd/ztest/ztest.c
  man/man5/zfs-module-parameters.5
  man/man8/zdb.8
  module/zfs/vdev_indirect.c
Labels: Status: Code Review Needed

#8286 Update vdev_is_spacemap_addressable() for new spacemap encoding
  module/zfs/vdev.c
  tests/zfs-tests/tests/functional/pool_checkpoint/checkpoint_sm_scale.ksh
Labels: Status: Accepted

#8285 Remove unused vdev_t fields
  include/sys/vdev_impl.h
  module/zfs/vdev.c
Labels: Status: Accepted

#8291 Fix error handling incallers of dbuf_hold_level()
  cmd/ztest/ztest.c
  include/sys/dmu.h
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_recv.c
  module/zfs/zfs_vnops.c
Labels: Status: Code Review Needed

#8269 ztest: scrub verification
  cmd/ztest/ztest.c
Labels: Status: Code Review Needed

#8293 Simplify spa_sync by breaking it up to smaller functions
  module/zfs/spa.c
  module/zfs/vdev_removal.c
Labels: Status: Accepted

#8278 Off-by-one in zap_leaf_array_create()
  module/zfs/zap_leaf.c
  tests/zfs-tests/tests/functional/cli_root/zfs_set/user_property_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_set/user_property_003_neg.ksh
Labels: Status: Accepted

#8304 dkms: Enable debuginfo option to be set with zfs sysconfig file
  scripts/dkms.mkconf
Labels: Status: Accepted, Type: Building

#8299 Document guidelines for usage of zfs_dbgmsg
  include/sys/zfs_debug.h
Labels: Status: Accepted

#8266 Fix 0 byte memory leak in zfs receive
  module/zfs/dmu_recv.c
Labels: Status: Accepted

#8290 Factor metaslab_load_wait() in metaslab_load()
  cmd/zdb/zdb.c
  include/sys/metaslab.h
  include/sys/metaslab_impl.h
  module/zfs/metaslab.c
  module/zfs/vdev_initialize.c
Labels: Status: Accepted

#8297 Remove zfs_sync() panicking kernel check
  module/zfs/zfs_vfsops.c
Labels: Status: Accepted

#8277 ztest creates partially initialized root dataset
  module/zfs/dsl_pool.c
Labels: Status: Code Review Needed

#8307 Fix bad kmem_free() in zvol_rename_minors_impl()
  module/zfs/zvol.c
Labels: Status: Accepted

#8279 zfs userspace dumps core when used on ZVOLs
  cmd/zfs/zfs_main.c
Labels: Status: Accepted

#8326 Use proper tag for spa config refcounts in mmp_write_uberblock()
  module/zfs/mmp.c
Labels: Status: Accepted

#8327 Rename range_tree_verify to range_tree_verify_not_present
  cmd/zdb/zdb.c
  include/sys/range_tree.h
  module/zfs/metaslab.c
  module/zfs/range_tree.c
Labels: Status: Accepted

#8324 Change target size of metaslabs from 256GB to 16GB
  man/man5/zfs-module-parameters.5
  module/zfs/vdev.c
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_rewind_config_changed.ksh
Labels: Status: Accepted

#8335 zdb -L should skip leak detection altogether
  cmd/zdb/zdb.c
  man/man8/zdb.8
Labels: Status: Accepted

#8333 Don't acquire zthr_request_lock in zthr_wakeup
  module/zfs/zthr.c
Labels: Status: Accepted

#8298 vs_alloc can underflow in L2ARC vdevs
  module/zfs/arc.c
  module/zfs/vdev.c
Labels: Status: Accepted

#8347 Simplify log vdev removal code
  module/zfs/vdev.c
  module/zfs/vdev_removal.c
Labels: Status: Accepted

#8338 Fix zpool iostat -w header names
  cmd/zpool/zpool_main.c
Labels: Status: Accepted
