Repository openzfs/zfs, pull requests merged in 2019-06, with the labels that each got.

#8752 Wait in 'S' state when send/recv pipe is blocking
  module/zfs/bqueue.c
Labels: Status: Accepted

#8731 Make Python detection optional and more portable
  cmd/Makefile.am
  config/always-python.m4
  config/always-pyzfs.m4
Labels: Status: Accepted

#8820 allow CONFIG_TRIM_UNUSED_KSYM to be enabled when build as a builtin-module
  config/kernel.m4
Labels: Status: Code Review Needed, Type: Building

#8855 Fixed a small typo in man/man1/raidz_test.1
  man/man1/raidz_test.1
Labels: Status: Accepted

#8841 Drop objid argument in zfs_znode_alloc() (sync with OpenZFS)
  module/zfs/zfs_znode.c
Labels: Status: Code Review Needed

#8850 hkdf_test binary should only have one icp instance
  tests/zfs-tests/tests/functional/hkdf/Makefile.am
Labels: Status: Accepted

#8858 Fix integer overflow of ZTOI(zp)->i_generation
  module/zfs/zfs_znode.c
Labels: Status: Accepted

#8356 Search and replace GUID in initramfs script
  contrib/initramfs/scripts/zfs.in
Labels: Status: Accepted

#8859 IOPS take a hit when all vdevs are in the zfs_mg_fragmentation_threshold
  man/man5/zfs-module-parameters.5
  module/zfs/metaslab.c
Labels: Status: Accepted, Type: Performance

#8822 l2arc_apply_transforms: Fix typo in comment
  module/zfs/arc.c
Labels: Status: Accepted, Type: Documentation

#8857 Reinstate raw receive check when truncating
  module/zfs/dnode_sync.c
Labels: Status: Accepted

#8860 Avoid updating zfs_gitrev.h when rev is unchanged.
  scripts/make_gitrev.sh
Labels: Status: Accepted

#8837 Allow metaslab to be unloaded even when not freed from
  include/sys/metaslab.h
  module/zfs/metaslab.c
  module/zfs/vdev.c
Labels: Status: Accepted

#8866 Fix %post and %postun generation in kmodtool
  scripts/kmodtool
Labels: Component: Packaging, Status: Accepted

#8851 arc_summary: prefer python3 version and install when there is no python
  cmd/arc_summary/Makefile.am
Labels: Status: Accepted, Type: Building

#8863 Fix incorrect error message for raw receive
  module/zfs/dmu_recv.c
Labels: Status: Accepted

#8873 Fix comparison signedness in arc_is_overflowing()
  module/zfs/arc.c
Labels: Status: Accepted

#8865 make zil max block size tunable
  cmd/ztest/ztest.c
  include/sys/zil.h
  include/sys/zil_impl.h
  man/man5/zfs-module-parameters.5
  module/zfs/zfs_log.c
  module/zfs/zil.c
  module/zfs/zvol.c
Labels: Status: Accepted

#8580 single-chunk scatter ABDs can be treated as linear
  include/sys/abd.h
  module/zfs/abd.c
  module/zfs/arc.c
  module/zfs/zio.c
Labels: Status: Accepted, Type: Performance

#8880 fix typo in vdev_raidz_math.c
  module/zfs/vdev_raidz_math.c
Labels: Status: Accepted

#8864 Target ARC size can get reduced to arc_c_min
  module/zfs/arc.c
Labels: Status: Accepted, Type: Performance

#8862 fat zap should prefetch when iterating
  include/sys/zap.h
  man/man5/zfs-module-parameters.5
  module/zfs/ddt_zap.c
  module/zfs/dmu.c
  module/zfs/zap.c
  module/zfs/zap_micro.c
Labels: Status: Accepted, Type: Performance

#8884 Fix lockdep warning on insmod
  module/zfs/zfs_sysfs.c
Labels: Status: Accepted

#8889 ztest: dmu_tx_assign() gets ENOSPC in spa_vdev_remove_thread()
  module/zfs/vdev_removal.c
Labels: Status: Accepted, Type: Defect

#8842 Restrict filesystem creation if path referred either '.' or '..'
  include/zfs_namecheck.h
  lib/libzfs/libzfs_dataset.c
  module/zcommon/zfs_namecheck.c
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_009_neg.ksh
Labels: Status: Accepted

#8877 looping in metaslab_block_picker impacts performance on fragmented pools
  man/man5/zfs-module-parameters.5
  module/zfs/metaslab.c
Labels: Status: Accepted, Type: Performance

#8890 Move write aggregation memory copy out of vq_lock
  module/zfs/vdev_queue.c
Labels: Status: Accepted, Type: Performance

#8892 compress metadata in later sync passes
  man/man5/zfs-module-parameters.5
  module/zfs/zio.c
Labels: Status: Accepted

#8893 panic in removal_remap test on 4K devices
  include/sys/vdev_removal.h
  man/man5/zfs-module-parameters.5
  module/zfs/vdev_label.c
  module/zfs/vdev_removal.c
Labels: Status: Accepted, Type: Defect

#8894 lz4_decompress_abd declared but not defined
  include/sys/zio_compress.h
Labels: Status: Accepted

#8895 Python config cleanup
  config/always-python.m4
  config/always-pyzfs.m4
Labels: Status: Accepted, Type: Building

#8901 Minimize aggsum_compare(&arc_size, arc_c) calls
  module/zfs/arc.c
Labels: Status: Accepted

#8906 ZTS: Fix mmp_interval failure
  tests/zfs-tests/include/libtest.shlib
Labels: Status: Accepted, Type: Test Suite

#8930 kmod-zfs-devel rpm should provide kmod-spl-devel
  rpm/redhat/zfs-kmod.spec.in
Labels: Component: Packaging, Status: Accepted

#8911 fix memory leak
  cmd/zpool/zpool_vdev.c
Labels: Status: Accepted

#8310 Remove dedupditto functionality
  cmd/ztest/ztest.c
  include/sys/ddt.h
  include/sys/spa_impl.h
  include/sys/zio.h
  lib/libzfs/libzfs_pool.c
  man/man8/zpool.8
  module/zcommon/zpool_prop.c
  module/zfs/ddt.c
  module/zfs/spa.c
  module/zfs/zio.c
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_props.ksh
Labels: Status: Accepted

#8938 Update zfs-lib.sh.in Issue #8920
  contrib/dracut/90zfs/zfs-lib.sh.in
Labels: Status: Accepted

#8870 Allow unencrypted children of encrypted datasets
  include/sys/dsl_crypt.h
  lib/libzfs/libzfs_crypto.c
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_sendrecv.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/dsl_crypt.c
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_encrypted.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_to_encrypted.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_rename/zfs_rename_to_encrypted.ksh
Labels: Status: Accepted

#8925 update vdev_ops_t from illumos
  module/zfs/vdev_disk.c
  module/zfs/vdev_file.c
  module/zfs/vdev_indirect.c
  module/zfs/vdev_mirror.c
  module/zfs/vdev_missing.c
  module/zfs/vdev_raidz.c
  module/zfs/vdev_root.c
Labels: Status: Accepted

#8936 dedup=verify doesn't clear the blkptr's dedup flag
  module/zfs/zio.c
Labels: Status: Accepted

#8940 Prevent pointer to an out-of-scope local variable
  module/zfs/zfs_sysfs.c
Labels: Status: Accepted

#8942 Redacted Send/Receive broke zfs(8) help message
  cmd/zfs/zfs_main.c
Labels: Status: Accepted

#8933 Add SCSI_PASSTHROUGH to zvols to enable UNMAP support
  module/zfs/zvol.c
Labels: Status: Accepted

#8939 Fix build break by "Implement Redacted Send/Receive"
  tests/zfs-tests/cmd/libzfs_input_check/libzfs_input_check.c
Labels: Status: Accepted

#8945 fix comments on zfs_bookmark_phys
  include/sys/dsl_bookmark.h
Labels: Status: Accepted

#8432 zstreamdump: add per-record-type counters and an overhead counter
  cmd/zstreamdump/zstreamdump.c
  tests/zfs-tests/tests/functional/rsend/rsend.kshlib
Labels: Status: Accepted

#8881 Let zfs mount all tolerate in-progress mounts
  cmd/zfs/zfs_main.c
Labels: Status: Accepted

#8919 Add libnvpair to libzfs pkg-config
  lib/libzfs/libzfs.pc.in
Labels: Status: Code Review Needed

#8914 Remove arch and zfs version dependency
  rpm/generic/zfs.spec.in
Labels: Status: Accepted

#8929 dn_struct_rwlock can not be held in dmu_tx_try_assign()
  module/zfs/dmu_tx.c
Labels: Status: Accepted

#8904 OpenZFS 9425 - channel programs can be interrupted
  include/spl/sys/condvar.h
  include/sys/dsl_synctask.h
  include/sys/txg.h
  include/sys/zcp.h
  include/sys/zfs_context.h
  lib/libzpool/kernel.c
  module/spl/spl-condvar.c
  module/zfs/dsl_synctask.c
  module/zfs/txg.c
  module/zfs/zcp.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/channel_program/synctask_core/Makefile.am
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.terminate_by_signal.ksh
Labels: Status: Accepted

#8950 Add missing .gitignore from "Implement Redacted Send/Receive"
  tests/zfs-tests/cmd/get_diff/.gitignore
Labels: Status: Accepted

#8943 Fix out-of-tree build failures
  Makefile.am
  cmd/zed/Makefile.am
  cmd/zed/zed.d/Makefile.am
  configure.ac
  contrib/initramfs/Makefile.am
  contrib/pyzfs/Makefile.am
  module/Makefile.in
  scripts/Makefile.am
  tests/runfiles/Makefile.am
  tests/zfs-tests/tests/functional/checksum/Makefile.am
  tests/zfs-tests/tests/functional/hkdf/Makefile.am
Labels: Status: Accepted, Type: Building

#8935 Fix error message on promoting encrypted dataset
  lib/libzfs/libzfs_dataset.c
  module/zfs/dsl_crypt.c
Labels: Status: Accepted

#8944 remove code for zfs remap
  cmd/zfs/zfs_main.c
  configure.ac
  contrib/pyzfs/libzfs_core/__init__.py
  contrib/pyzfs/libzfs_core/_error_translation.py
  contrib/pyzfs/libzfs_core/_libzfs_core.py
  contrib/pyzfs/libzfs_core/bindings/libzfs_core.py
  contrib/pyzfs/libzfs_core/test/test_libzfs_core.py
  include/libzfs.h
  include/libzfs_core.h
  include/sys/dbuf.h
  include/sys/dmu.h
  include/sys/dnode.h
  include/sys/dsl_deleg.h
  include/sys/dsl_dir.h
  include/sys/fs/zfs.h
  include/zfs_deleg.h
  lib/libzfs/libzfs_dataset.c
  lib/libzfs_core/libzfs_core.c
  module/zcommon/zfs_deleg.c
  module/zcommon/zfs_prop.c
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_tx.c
  module/zfs/dsl_dir.c
  module/zfs/zfs_ioctl.c
  tests/runfiles/linux.run
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_remap/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_remap/cleanup.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_remap/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_remap/zfs_remap_cliargs.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_remap/zfs_remap_obsolete_counts.ksh
  tests/zfs-tests/tests/functional/removal/Makefile.am
  tests/zfs-tests/tests/functional/removal/removal_condense_export.ksh
  tests/zfs-tests/tests/functional/removal/removal_remap.ksh
  tests/zfs-tests/tests/functional/removal/removal_remap_deadlists.ksh
  tests/zfs-tests/tests/functional/removal/removal_with_remap.ksh
Labels: Status: Accepted

#8926 -Y option in zdb is valid after update #8271
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_001_neg.ksh
Labels: Status: Code Review Needed

#8951 Fix bp_embedded_type enum definition
  include/sys/spa.h
  module/zfs/zio.c
Labels: Status: Accepted

#8948 Redacted Send/Receive causes zdb to dump core
  cmd/zdb/zdb.c
Labels: Status: Accepted

#8909 Avoid extra taskq_dispatch() calls by DMU.
  include/sys/multilist.h
  module/zfs/dmu_objset.c
  module/zfs/multilist.c
Labels: Status: Accepted

#8947 zdb -vvvvv on ztest pool dies with "out of memory"
  cmd/zdb/zdb.c
Labels: Status: Accepted

#8843 Concurrent small allocation defeats large allocation
  module/zfs/metaslab.c
Labels: Status: Accepted

#8952 Add 'zfs umount -u' for encrypted datasets
  cmd/zfs/zfs_main.c
  lib/libzfs/libzfs_mount.c
  man/man8/zfs.8
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zfs_unmount/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_unmount/zfs_unmount_unload_keys.ksh
Labels: Status: Code Review Needed

#8957 nopwrites on dmu_sync-ed blocks can result in a panic
  module/zfs/zio.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/removal/Makefile.am
  tests/zfs-tests/tests/functional/removal/removal_nopwrite.ksh
Labels: Status: Accepted
