Repository openzfs/zfs, pull requests merged in 2019-05, with the labels that each got.

#8692 Correct snprintf() size argument
  lib/libzfs/libzfs_sendrecv.c
  module/spl/spl-err.c
  module/zfs/zfs_ctldir.c
Labels: Status: Accepted

#8699 Remove incorrect (and inappropriate) comment in dprintf_dnode
  include/sys/dnode.h
Labels: Status: Accepted

#8687 Fix estimated scrub completion time
  cmd/zpool/zpool_main.c
  man/man8/zpool.8
Labels: Status: Accepted

#8700 Add feature check for 'zpool resilver' command
  include/libzfs.h
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_util.c
  man/man8/zpool.8
  module/zfs/spa.c
  tests/zfs-tests/tests/functional/cli_root/zpool_resilver/zpool_resilver_bad_args.ksh
Labels: Status: Accepted

#8703 Reword comment in lz4_compress_zfs
  module/zfs/lz4.c
Labels: Status: Accepted

#8683 Clearer wording on Errata #4 for non-destructive remedy
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#8615 Improve rate at which new zvols are processed
  module/zfs/vdev_disk.c
  module/zfs/zvol.c
Labels: Status: Accepted

#8701 Linux 5.0 compat: Use totalhigh_pages()
  config/kernel-totalhigh_pages.m4
  config/kernel.m4
  include/spl/sys/vmsystm.h
  module/zfs/arc.c
Labels: Status: Accepted

#8707 Fix typo/etc in module/zfs/zfs_ctldir.c
  module/zfs/zfs_ctldir.c
Labels: Status: Accepted

#8711 OpenZFS 10473 - zfs(1M) missing cross-reference to zfs-program(1M)
  man/man8/zfs.8
Labels: Status: Accepted

#8718 Fix zfs-mount-generator for datasets with spaces
  etc/systemd/system-generators/zfs-mount-generator.in
Labels: Status: Accepted

#8713 Cleanup special/dedup language
  man/man8/zpool.8
Labels: Status: Accepted

#8714 Linux 5.1 compat: Drop ULLONG_MAX and LLONG_MAX definitions
  include/spl/sys/types.h
Labels: Status: Accepted

#8675 Fix `zfs set atime=off|on` behavior on inherited datasets
  include/linux/vfs_compat.h
  include/sys/zfs_vfsops.h
  include/sys/zfs_znode.h
  module/zfs/zfs_vfsops.c
  module/zfs/zfs_znode.c
  module/zfs/zpl_file.c
  tests/runfiles/linux.run
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/atime/Makefile.am
  tests/zfs-tests/tests/functional/atime/atime_common.kshlib
  tests/zfs-tests/tests/functional/atime/root_atime_off.ksh
  tests/zfs-tests/tests/functional/atime/root_atime_on.ksh
  tests/zfs-tests/tests/functional/atime/root_relatime_on.ksh
  tests/zfs-tests/tests/functional/atime/setup.ksh
Labels: Status: Accepted

#8668 Fix send/recv lost spill block
  include/sys/dmu.h
  include/sys/dmu_impl.h
  include/sys/dmu_recv.h
  include/sys/dnode.h
  include/sys/fs/zfs.h
  include/sys/zfs_ioctl.h
  lib/libzfs/libzfs_sendrecv.c
  man/man5/zfs-module-parameters.5
  module/zfs/dbuf.c
  module/zfs/dmu_object.c
  module/zfs/dmu_recv.c
  module/zfs/dmu_send.c
  module/zfs/dnode.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/rsend/Makefile.am
  tests/zfs-tests/tests/functional/rsend/rsend.kshlib
  tests/zfs-tests/tests/functional/rsend/send_realloc_encrypted_files.ksh
  tests/zfs-tests/tests/functional/rsend/send_realloc_files.ksh
  tests/zfs-tests/tests/functional/rsend/send_spill_block.ksh
Labels: Status: Accepted

#8706 Make zfs_special_class_metadata_reserve_pct into a parameter
  man/man5/zfs-module-parameters.5
  module/zfs/spa_misc.c
Labels: Status: Accepted

#8719 Fix errant EFAULT during writes
  module/zfs/zfs_vnops.c
  module/zfs/zpl_file.c
  module/zfs/zpl_inode.c
  module/zfs/zvol.c
Labels: Status: Accepted

#8725 Linux 5.0 compat: ASM_BUG macro
  module/zfs/vdev_raidz_math_aarch64_neon_common.h
  module/zfs/vdev_raidz_math_avx2.c
  module/zfs/vdev_raidz_math_avx512bw.c
  module/zfs/vdev_raidz_math_ssse3.c
Labels: Status: Code Review Needed, Type: Building

#8721 fix typesetting of Errata #4
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#8727 Fix link count of root inode when snapdir is visible
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#8723 Fix dataset name comparison in zfs_compare().
  cmd/zfs/zfs_iter.c
Labels: Status: Accepted

#8726 Add missing trailing '\n' in printk() messages
  module/spl/spl-generic.c
  module/zfs/zfs_vfsops.c
Labels: Status: Accepted

#8696 zpool import progress kstat
  include/sys/spa.h
  module/zfs/spa.c
  module/zfs/spa_misc.c
Labels: Status: Accepted

#8745 Fix incorrect assertion in dnode_dirty_l1range
  module/zfs/dnode.c
Labels: Status: Accepted

#8743 Fix wrong assertion in libzfs diff error handling
  lib/libzfs/libzfs_diff.c
Labels: Status: Accepted

#8730 Linux 5.2 compat: rwsem_tryupgrade()
  include/spl/sys/rwlock.h
  module/spl/spl-rwlock.c
  module/zfs/dmu_zfetch.c
Labels: Status: Accepted, Type: Building

#8746 fix kstat state update during pool transition
  module/zfs/spa_misc.c
Labels: Status: Accepted

#8647 kernel timer API rework
  config/kernel-timer.m4
  config/kernel.m4
  include/spl/sys/timer.h
  module/spl/spl-condvar.c
  module/spl/spl-taskq.c
Labels: Status: Accepted, Type: Building

#8729 rename reservation tests from *.sh to *.ksh
  tests/zfs-tests/tests/functional/reservation/Makefile.am
  tests/zfs-tests/tests/functional/reservation/reservation_001_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_002_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_003_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_004_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_005_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_006_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_007_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_008_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_009_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_010_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_011_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_012_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_013_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_014_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_015_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_016_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_017_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_018_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_019_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_020_pos.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_021_neg.ksh
  tests/zfs-tests/tests/functional/reservation/reservation_022_pos.ksh
Labels: Status: Accepted

#8788 Fix coverity defects: CID 186143
  module/zfs/spa_misc.c
Labels: Status: Accepted

#8781 zpool: trim -p is not a valid option
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#8790 Device removal panics on 32-bit systems
  module/zfs/vdev_indirect.c
Labels: Status: Accepted

#8761 Linux 2.6.39 compat: Test if kstrtoul() exists
  config/kernel-kstrtoul.m4
  config/kernel.m4
  include/spl/sys/strings.h
Labels: Status: Accepted

#8779 Fix ksh-path for random_readwrite_fixed.ksh
  tests/zfs-tests/tests/perf/regression/random_readwrite_fixed.ksh
Labels: Status: Accepted

#8783 zfs: missing newline character in zfs_do_channel_program() error message
  cmd/zfs/zfs_main.c
Labels: Status: Accepted

#8784 zfs: don't pretty-print objsetid property
  lib/libzfs/libzfs_dataset.c
Labels: Status: Accepted

#8785 zfs-tests: verify zfs(8) and zpool(8) help message is under 80 columns
  tests/zfs-tests/tests/functional/cli_user/misc/zfs_001_neg.ksh
  tests/zfs-tests/tests/functional/cli_user/misc/zpool_001_neg.ksh
Labels: Status: Accepted

#8786 VERIFY3P() message is missing a space character
  include/spl/sys/debug.h
Labels: Status: Accepted

#8787 zfs-tests: fix warnings when packaging some .shlib files
  Makefile.am
  tests/zfs-tests/include/zpool_script.shlib
  tests/zfs-tests/tests/functional/cli_root/zpool_reopen/zpool_reopen.shlib
Labels: Status: Accepted

#8782 zpool: status -t is not documented in help message
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#8765 Drop local definition of MOUNT_BUSY
  module/zfs/zfs_ctldir.c
Labels: Status: Accepted

#8777 Linux 5.2 compat: Remove config/kernel-set-fs-pwd.m4
  config/kernel-set-fs-pwd.m4
  config/kernel.m4
  module/spl/spl-vnode.c
Labels: Status: Code Review Needed, Type: Building

#8776 Linux 5.2 compat: Fix config/kernel-shrink.m4 test failure
  config/kernel-shrink.m4
Labels: Status: Code Review Needed, Type: Building

#8794 Linux 5.2 compat: Define wait_on_page_writeback() if GPL-only exported
  module/zfs/zfs_vnops.c
Labels: Status: Code Review Needed, Type: Building

#8811 Disable parallel processing for 'zfs mount -l'
  cmd/zfs/zfs_main.c
Labels: Status: Accepted

#8766 Fix embedded bp accounting in count_block()
  module/zfs/dsl_scan.c
Labels: Status: Accepted

#8767 Update descriptions for vnops
  module/zfs/zfs_vnops.c
  module/zfs/zfs_znode.c
Labels: Status: Accepted

#8789 Endless loop in zpool_do_remove() on platforms with unsigned char
  cmd/zfs/zfs_main.c
  cmd/zpool/zpool_main.c
  cmd/zstreamdump/zstreamdump.c
Labels: Status: Accepted

#8759 Update comments to match code
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#8791 Double-free of encryption wrapping key due to invalid pool properties
  module/zfs/zfs_ioctl.c
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_encrypted.ksh
Labels: Status: Accepted

#8815 Refactor parent dataset handling in libzfs zfs_rename()
  lib/libzfs/libzfs_dataset.c
Labels: Status: Accepted

#8818 grammar: it is
  cmd/zfs/zfs_main.c
Labels: Status: Accepted, Type: Documentation

#8797 Fix integer overflow in get_next_chunk()
  module/zfs/dmu.c
Labels: Status: Accepted

#8735 Exclude log device ashift from normal class
  module/zfs/vdev.c
Labels: Status: Accepted

#8826 Remove vn_set_fs_pwd()/vn_set_pwd() (no need to be at / during insmod)
  config/kernel-spinlock.m4
  config/kernel.m4
  include/spl/sys/vnode.h
  module/spl/spl-vnode.c
  module/zfs/spa_config.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#8732 Add link count test for root inode (97aa3ba44)
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/link_count/Makefile.am
  tests/zfs-tests/tests/functional/link_count/link_count_root_inode.ksh
Labels: Status: Accepted, Type: Test Suite

#8834 Revert "Report holes when there are only metadata changes"
  module/zfs/dmu.c
Labels: Status: Accepted
