Repository openzfs/zfs, pull requests merged in 2020-12, with the labels that each got.

#11262 CI: simplify checkstyle runner
  .github/workflows/checkstyle.yaml
Labels: Status: Accepted

#11255 Make zpool status "remove:" label print in bold
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#11256 avoid unneccessary zio allocation and wait
  module/zfs/dmu.c
Labels: Status: Accepted

#11260 Notify userspace when a vdev is removed
  cmd/zed/agents/zfs_agents.c
  module/zfs/spa.c
Labels: Status: Accepted

#11269 Add compatibility for busybox mktemp to sed --in-place check
  config/always-sed.m4
  config/deb.am
  scripts/zfs-tests.sh
Labels: Status: Accepted

#11261 Fix for "Reduce latency effects of non-interactive I/O".
  module/zfs/vdev_queue.c
Labels: Status: Accepted

#11272 Fix trivial typo in zfs-diff.8
  man/man8/zfs-diff.8
Labels: Status: Accepted, Type: Documentation

#11271 Add sanity.run file
  tests/runfiles/Makefile.am
  tests/runfiles/common.run
  tests/runfiles/sanity.run
Labels: Component: Test Suite, Status: Accepted

#11254 Add -u option to 'zfs create'
  cmd/zfs/zfs_main.c
  man/man8/zfs-create.8
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zfs_create/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_nomount.ksh
Labels: Status: Accepted

#11167 zpool: Dryrun fails to list some devices
  cmd/zpool/zpool_main.c
  lib/libzfs/libzfs_pool.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zpool_add/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_003_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_dryrun_output.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_dryrun_output.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_split/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_dryrun_output.ksh
Labels: Component: Userspace, Status: Accepted

#11221 Fix raw sends on encrypted datasets when copying back snapshots
  module/os/freebsd/zfs/zio_crypt.c
  module/os/linux/zfs/zio_crypt.c
  module/zfs/dsl_crypt.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/userquota/userspace_send_encrypted.ksh
Labels: Status: Accepted

#11283 ZTS: Update zfs_share_concurrent_shares.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_share/zfs_share_concurrent_shares.ksh
Labels: Component: Test Suite, Status: Accepted

#11286 ZTS: adjust zpool_import_012_pos timeout
  tests/runfiles/common.run
Labels: Status: Accepted

#11287 Enable ABI checks for the checkstyle workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/checkstyle.yaml
Labels: Status: Accepted

#11279 Bring consistency to ABD chunk count types.
  module/os/freebsd/zfs/abd_os.c
  module/os/linux/zfs/abd_os.c
Labels: Status: Accepted

#11280 Avoid some spa_has_pending_synctask() calls.
  module/zfs/vdev_queue.c
Labels: Status: Accepted

#11282 Reduce fletcher4 and raidz benchmark times
  module/zcommon/zfs_fletcher.c
  module/zfs/vdev_raidz_math.c
Labels: Status: Accepted

#11296 zpool_trim tests: throttle trim process
  tests/zfs-tests/tests/functional/cli_root/zpool_trim/zpool_trim.kshlib
  tests/zfs-tests/tests/functional/cli_root/zpool_trim/zpool_trim_online_offline.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_trim/zpool_trim_start_and_cancel_neg.ksh
Labels: Status: Accepted

#11304 CI: add new zfs-tests workflow
  .github/workflows/zfs-tests.yml
  tests/runfiles/sanity.run
Labels: Status: Accepted

#11284 Fix optional "force" arg handing in zfs_ioc_pool_sync()
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#11232 Decouple arc_read_done callback from arc buf instantiation
  include/sys/arc.h
  module/zfs/arc.c
  module/zfs/dbuf.c
Labels: Status: Accepted

#11309 Delete rw_semaphore.wait_lock configure check
  config/kernel-rwsem.m4
Labels: Status: Accepted, Type: Building

#11295 Drop path prefix workaround
  cmd/mount_zfs/mount_zfs.c
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_013_pos.ksh
Labels: Status: Accepted

#11303 mount_zfs: print strerror instead of errno for reporting errors.
  cmd/mount_zfs/mount_zfs.c
Labels: Status: Accepted

#11311 zpool: Three small fixes for #11167
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_dryrun_output.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_dryrun_output.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_dryrun_output.ksh
Labels: Status: Accepted

#11302 FreeBSD: Do zcommon_init sooner to avoid FPU panic
  include/os/freebsd/spl/sys/mod_os.h
  include/os/linux/kernel/linux/mod_compat.h
  module/zcommon/zfs_prop.c
Labels: Status: Accepted

#11319 CI: add zloop workflow
  .github/workflows/zloop.yml
Labels: Status: Accepted

#11212 Implement memory and CPU hotplug
  config/kernel-hotplug.m4
  config/kernel.m4
  include/os/linux/spl/sys/taskq.h
  include/sys/arc.h
  include/sys/arc_impl.h
  module/os/freebsd/zfs/arc_os.c
  module/os/linux/spl/spl-taskq.c
  module/os/linux/zfs/arc_os.c
  module/zfs/aggsum.c
  module/zfs/arc.c
  module/zfs/dsl_pool.c
  module/zfs/multilist.c
  module/zfs/spa.c
  module/zfs/txg.c
Labels: Status: Accepted

#11306 Fix possibly uninitialized 'root_inode' variable warning
  module/os/linux/zfs/zfs_vfsops.c
Labels: Status: Accepted

#11105 Improve zfs receive performance with lightweight write
  include/sys/dbuf.h
  include/sys/dmu_objset.h
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/dnode.c
  module/zfs/dnode_sync.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_pool.c
Labels: Component: Send/Recv, Status: Accepted, Type: Performance

#11326 Remove draid.d symlink from zfs_helpers.sh
  scripts/zfs-helpers.sh
Labels: Status: Accepted

#11277 Fix reporting of CKSUM errors in indirect vdevs
  module/zfs/vdev_indirect.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/removal/Makefile.am
  tests/zfs-tests/tests/functional/removal/remove_attach_mirror.ksh
Labels: Status: Accepted

#11324 dmu_zfetch: fix memory leak
  include/sys/arc_impl.h
  module/zfs/arc.c
Labels: Status: Accepted

#11336 spa: avoid type narrowing warning
  include/sys/spa_impl.h
Labels: Status: Accepted

#11337 lua: avoid gcc -Wreturn-local-addr bug
  module/lua/ldo.c
Labels: Status: Accepted

#11335 DKMS: Disable weak modules
  scripts/dkms.mkconf
Labels: Status: Accepted

#11288 Make metaslab class rotor and aliquot per-allocator.
  cmd/zdb/zdb.c
  cmd/ztest/ztest.c
  include/sys/metaslab_impl.h
  module/zfs/metaslab.c
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/zio.c
Labels: Status: Accepted

#11327 Only examine best metaslabs on each vdev
  include/sys/metaslab.h
  man/man5/zfs-module-parameters.5
  module/zfs/metaslab.c
  module/zfs/zio.c
Labels: Status: Accepted

#11359 Use the correct return type for getopt
  cmd/zfs/zfs_main.c
  cmd/zfs_ids_to_path/zfs_ids_to_path.c
  cmd/zpool/zpool_main.c
  cmd/zstream/zstream_redup.c
  tests/zfs-tests/cmd/btree_test/btree_test.c
Labels: Status: Accepted

#11237 Avoid extra work updating ARC kstats and tunables
  module/zfs/arc.c
Labels: Status: Accepted

#11329 special device removal space accounting fixes
  module/zfs/spa_misc.c
  module/zfs/vdev_removal.c
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh
Labels: Status: Accepted

#11365 ZTS: Simplify zpool_initialize_verify_initialized
  tests/zfs-tests/tests/functional/cli_root/zpool_initialize/zpool_initialize_verify_initialized.ksh
Labels: Status: Accepted

#11351 Linux 5.10 compat: use iov_iter in uio structure
  config/kernel-vfs-iov_iter.m4
  config/kernel.m4
  include/os/linux/spl/sys/uio.h
  include/os/linux/zfs/sys/zpl.h
  lib/libspl/include/sys/uio.h
  lib/libzfs/Makefile.am
  lib/libzpool/Makefile.am
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/zfs_uio.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zpl_file.c
  module/os/linux/zfs/zpl_inode.c
  module/os/linux/zfs/zpl_xattr.c
  module/os/linux/zfs/zvol_os.c
  module/zcommon/Makefile.in
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#11347 ZED: log history_events by default again
  cmd/zed/zed.d/history_event-zfs-list-cacher.sh.in
Labels: Status: Accepted

#11358 Linux 5.10 compat: also zvol_revalidate_disk()
  module/os/linux/zfs/zvol_os.c
Labels: Status: Accepted

#11372 backport to 2.0: ZED/zfs-list-cacher.sh: don't exit on ignored event type
  cmd/zed/zed.d/history_event-zfs-list-cacher.sh.in
Labels: Status: Accepted

#11370 dsl_pool: extend comment on DSL Pool Configuration Lock
  module/zfs/dsl_pool.c
Labels: Status: Accepted

#11378 Remove iov_iter_advance() from iter_read
  module/os/linux/zfs/zpl_file.c
Labels: Status: Accepted

#11373 Fix maybe uninitialized variable warning
  module/os/linux/zfs/zpl_file.c
Labels: Status: Accepted

#11374 Linux 4.18.0-257.el8 compat: blk_alloc_queue()
  config/kernel-make-request-fn.m4
  include/os/linux/kernel/linux/blkdev_compat.h
Labels: Status: Accepted

#11368 Dangling reference from dmu_objset_upgrade
  module/zfs/dmu_objset.c
Labels: Status: Accepted

#11383 Forward questions to github discussions
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/question.md
Labels: Status: Accepted

#11381 zfs-kmods: install to /lib/modules instead of /usr/lib/modules
  rpm/generic/zfs-kmod.spec.in
Labels: Component: Dracut, Status: Accepted

#11384 Remove unused check from dmu_tx_count_write()
  module/zfs/dmu_tx.c
Labels: Status: Code Review Needed

#11391 Linux 5.10 compat: META
  META
Labels: Status: Code Review Needed

#11394 dbufstat: Fix warnings with Python 3.8
  cmd/dbufstat/dbufstat.in
Labels: Status: Accepted

#11406 implicit conversion from 'boolean_t' to 'ds_hold_flags_t'
  include/sys/dsl_dataset.h
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/dmu_send.c
  tests/zfs-tests/cmd/libzfs_input_check/libzfs_input_check.c
Labels: Status: Accepted

#11411 Virtuozzo 7 kernel compat: support HAVE_VFS_DIRECT_IO_ITER_RW_OFFSET …
  module/os/linux/zfs/zpl_file.c
Labels: Status: Accepted
