Repository openzfs/zfs, pull requests merged in 2020-05, with the labels that each got.

#10269 zdb: Fix ignored zfs_arc_max tuning
  cmd/zdb/zdb.c
Labels: Component: Userspace, Status: Accepted

#10271 ZTS: Count CKSUM for all vdevs in verify_pool
  tests/zfs-tests/include/libtest.shlib
Labels: Status: Accepted, Type: Test Suite

#10250 Update FreeBSD SPL atomics
  include/os/freebsd/spl/sys/atomic.h
  module/os/freebsd/spl/spl_atomic.c
Labels: Status: Accepted

#10270 Avoid the GEOM topology lock recursion when we...
  module/os/freebsd/zfs/vdev_geom.c
Labels: Status: Accepted

#10281 config/kernel-inode-times: initialize timespec
  config/kernel-inode-times.m4
Labels: Status: Accepted, Type: Building

#10292 taskq: Don't leak system_delay_taskq on FreeBSD
  module/os/freebsd/spl/spl_taskq.c
Labels: Status: Accepted

#10283 Enable splitting mirrors with indirect vdevs
  lib/libzfs/libzfs_pool.c
  module/zfs/spa.c
  module/zfs/vdev_root.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zpool_split/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_indirect.ksh
Labels: Status: Accepted

#10247 Fix column width calculation issue with certain terminal widths.
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#10009 Add support for boot environment data to be stored in the label
  cmd/zinject/translate.c
  include/libzfs.h
  include/libzfs_core.h
  include/sys/fs/zfs.h
  include/sys/vdev.h
  include/sys/vdev_impl.h
  lib/libzfs/libzfs_pool.c
  lib/libzfs_core/libzfs_core.c
  module/os/freebsd/zfs/vdev_label_os.c
  module/zfs/vdev.c
  module/zfs/vdev_label.c
  module/zfs/zfs_ioctl.c
  tests/zfs-tests/cmd/libzfs_input_check/libzfs_input_check.c
Labels: Status: Accepted

#10228 Improvements on persistent L2ARC
  cmd/zdb/zdb.c
  include/sys/arc_impl.h
  man/man8/zdb.8
  module/zfs/arc.c
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_001_pos.ksh
Labels: Status: Accepted

#10305 ZTS: refreserv_005_pos.ksh
  tests/zfs-tests/tests/functional/refreserv/refreserv_005_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#10304 Fixed LDADD library links in Makefiles for cross compilation builds.
  cmd/mount_zfs/Makefile.am
  cmd/raidz_test/Makefile.am
  cmd/zed/Makefile.am
  cmd/zinject/Makefile.am
  cmd/zpool/Makefile.am
  cmd/zstream/Makefile.am
  tests/zfs-tests/cmd/btree_test/Makefile.am
  tests/zfs-tests/tests/functional/hkdf/Makefile.am
  tests/zfs-tests/tests/functional/libzfs/Makefile.am
Labels: Status: Accepted

#10293 Combine OS-independent ABD code into common source file
  include/sys/Makefile.am
  include/sys/abd.h
  include/sys/abd_impl.h
  lib/libzpool/Makefile.am
  module/Makefile.bsd
  module/os/freebsd/zfs/abd_os.c
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/abd.c
  module/os/linux/zfs/abd_os.c
  module/zfs/Makefile.in
  module/zfs/abd.c
  module/zfs/vdev_indirect.c
Labels: Status: Accepted

#10307 Change zfsunlock for better busybox compatibility
  contrib/initramfs/zfsunlock
Labels: Status: Accepted

#10291 Resilver restarts unnecessarily when it encounters errors
  module/zfs/dsl_scan.c
  module/zfs/vdev.c
  tests/runfiles/common.run
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/functional/resilver/Makefile.am
  tests/zfs-tests/tests/functional/resilver/resilver_restart_002.ksh
Labels: Status: Accepted

#10324 ZTS: zpool_split_indirect deletes zfstest log file
  tests/zfs-tests/tests/functional/cli_root/zpool_split/zpool_split_indirect.ksh
Labels: Status: Accepted, Type: Test Suite

#10323 flake8 E741 variable name warning
  tests/test-runner/bin/zts-report.py
Labels: Status: Accepted, Type: Test Suite

#10319 remove unneeded member drc_err of dmu_recv_cookie_t
  include/sys/dmu_recv.h
  module/zfs/dmu_recv.c
Labels: Status: Accepted

#10314 Upstream: add missing thread_exit()
  include/os/freebsd/spl/sys/proc.h
  module/zfs/dmu_send.c
  module/zfs/vdev_initialize.c
  module/zfs/vdev_removal.c
  module/zfs/vdev_trim.c
Labels: Status: Accepted

#10332 Fix abd_enter/exit_critical wrappers
  include/sys/abd_impl.h
  module/os/freebsd/zfs/abd_os.c
  module/os/linux/zfs/abd_os.c
  module/zfs/abd.c
Labels: Status: Accepted, Type: Defect

#10322 VN_OPEN_INVFS typo
  module/os/freebsd/zfs/zfs_vnops.c
Labels: Status: Accepted

#10320 fix error handling in receive_writer_thread()
  module/zfs/dmu_recv.c
Labels: Status: Accepted, Type: Defect

#10327 RPM: Fix regex so old versions of DKMS modules are removed on upgrade
  rpm/generic/zfs-dkms.spec.in
Labels: Component: Packaging, Status: Accepted

#10337 Fix ZVOL_DIR
  include/sys/fs/zfs.h
  module/os/freebsd/zfs/zvol_os.c
Labels: Component: ZVOL, Status: Accepted

#10338 freebsd: return EISDIR for read(2) on directories
  module/os/freebsd/zfs/zfs_vnops.c
Labels: Status: Accepted

#10346 fix gcc 10.1 stringop-truncation error
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#10344 freebsd: Correct the order of arguments to copyin() for Q_SETQUOTA
  module/os/freebsd/zfs/zfs_vfsops.c
Labels: Status: Code Review Needed

#10204 Small program that converts a dataset id and an object id to a path
  cmd/Makefile.am
  cmd/zfs_ids_to_path/.gitignore
  cmd/zfs_ids_to_path/Makefile.am
  cmd/zfs_ids_to_path/zfs_ids_to_path.c
  configure.ac
  include/libzfs.h
  lib/libzfs/libzfs_pool.c
  man/man8/Makefile.am
  man/man8/zfs_ids_to_path.8
  tests/runfiles/common.run
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/functional/cli_root/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_ids_to_path/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_ids_to_path/cleanup.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_ids_to_path/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_ids_to_path/zfs_ids_to_path_001_pos.ksh
Labels: Status: Accepted

#10282 Use online CPUs rather than max_ncpus for taskq thread count
  module/zfs/arc.c
  module/zfs/dsl_pool.c
  module/zfs/txg.c
Labels: Status: Accepted

#10294 mount: use the mount syscall directly
  cmd/mount_zfs/mount_zfs.c
  cmd/zfs/zfs_main.c
  include/libzfs.h
  include/libzfs_impl.h
  lib/libzfs/libzfs_mount.c
  lib/libzfs/os/freebsd/libzfs_zmount.c
  lib/libzfs/os/linux/libzfs_mount_os.c
  man/man8/zfs.8
  tests/zfs-tests/tests/functional/rsend/rsend.kshlib
Labels: Status: Accepted

#10069 Gang ABD Type
  include/sys/abd.h
  include/sys/abd_impl.h
  module/os/freebsd/zfs/abd_os.c
  module/os/linux/zfs/abd_os.c
  module/os/linux/zfs/vdev_disk.c
  module/zfs/abd.c
  module/zfs/vdev_queue.c
Labels: Status: Accepted, Type: Performance

#10358 ZTS: Fix zfs_mount.kshlib cleanup
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount.kshlib
Labels: Status: Accepted, Type: Test Suite

#10369 Fix dead links
  .github/CONTRIBUTING.md
Labels: Status: Accepted

#10364 Revert "Let zfs mount all tolerate in-progress mounts"
  cmd/zfs/zfs_main.c
Labels: Component: Userspace, Status: Accepted

#10366 Upstream: Memory leak in dsl_destroy_snapshots_nvl error case
  module/zfs/dsl_destroy.c
Labels: Status: Accepted

#10380 ZTS: Retry export/destroy when busy in zpool_import_012
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import_012_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#10376 etc/zfs/Makefile.am: set initconfdir
  etc/zfs/Makefile.am
Labels: Status: Accepted

#10372 Rework error handling in zpool_trim()
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#10382 Update zfs-functions.in
  etc/zfs/zfs-functions.in
Labels: Status: Accepted

#10385 ztest: Fix ztest_run_zdb() failure
  cmd/ztest/ztest.c
Labels: Status: Accepted, Type: Test Suite

#10198 Add bootfs.snapshot and bootfs.rollback kernel parameters
  contrib/dracut/90zfs/.gitignore
  contrib/dracut/90zfs/Makefile.am
  contrib/dracut/90zfs/module-setup.sh.in
  contrib/dracut/90zfs/zfs-rollback-bootfs.service.in
  contrib/dracut/90zfs/zfs-snapshot-bootfs.service.in
  contrib/dracut/README.dracut.markdown
Labels: Status: Accepted

#10384 Fix crypto build on FreeBSD HEAD
  module/os/freebsd/zfs/crypto_os.c
Labels: Status: Work in Progress
