Repository openzfs/zfs, pull requests merged in 2020-01, with the labels that each got.

#9790 Add FreeBSD core handling in zloop.sh
  scripts/Makefile.am
  scripts/zloop.sh
Labels: Status: Accepted

#9791 Static symbols exported by ICP
  module/icp/api/kcf_cipher.c
Labels: Status: Accepted, Type: Building

#9794 ZTS: Move dumpdev tests to sunos.run
  tests/runfiles/common.run
  tests/runfiles/sunos.run
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/include/default.cfg.in
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add.kshlib
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_005_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create.shlib
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_011_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_016_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/setup.ksh
  tests/zfs-tests/tests/functional/inuse/inuse_001_pos.ksh
  tests/zfs-tests/tests/functional/inuse/inuse_003_pos.ksh
  tests/zfs-tests/tests/functional/inuse/inuse_006_pos.ksh
  tests/zfs-tests/tests/functional/inuse/inuse_007_pos.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_common.shlib
Labels: Status: Accepted, Type: Test Suite

#9795 ZTS: Add helper for disk device check
  tests/zfs-tests/include/blkdev.shlib
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/cli_root/zpool_trim/setup.ksh
  tests/zfs-tests/tests/functional/redacted_send/redacted_mounts.ksh
  tests/zfs-tests/tests/functional/redacted_send/redacted_volume.ksh
  tests/zfs-tests/tests/functional/trim/setup.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_common.kshlib
Labels: Status: Accepted, Type: Test Suite

#9803 Fix ZPOOL_VDEV_NAME_PATH option description
  man/man8/zpool.8
Labels: Status: Accepted, Type: Documentation

#9806 ZTS: Cleanup partition tables
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/inuse/inuse_008_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#9788 Fix QAT allocation failure return value
  module/os/linux/zfs/qat_compress.c
Labels: Status: Accepted

#9783 Fix "zpool add -n" for dedup, special and log devices
  cmd/zpool/zpool_main.c
  include/zfs_comutil.h
  module/zcommon/zfs_comutil.c
  module/zfs/spa.c
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_003_pos.ksh
Labels: Status: Accepted

#9815 ZTS: Add sunos.run to dist data
  tests/runfiles/Makefile.am
Labels: Status: Accepted

#9809 zfs-module-parameters(5): add all missing items
  man/man5/zfs-module-parameters.5
Labels: Status: Accepted, Type: Documentation

#9802 Avoid here-documents in systemd mount generator
  etc/systemd/system-generators/zfs-mount-generator.in
Labels: Status: Accepted

#9820 ZTS: Eliminate functions named 'random'
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/include/math.shlib
  tests/zfs-tests/tests/functional/cli_root/zfs_diff/zfs_diff_timestamp.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_upgrade/zpool_upgrade.kshlib
  tests/zfs-tests/tests/functional/cli_root/zpool_upgrade/zpool_upgrade_008_pos.ksh
  tests/zfs-tests/tests/functional/redacted_send/redacted.kshlib
  tests/zfs-tests/tests/functional/redundancy/redundancy_001_pos.ksh
  tests/zfs-tests/tests/functional/redundancy/redundancy_002_pos.ksh
  tests/zfs-tests/tests/functional/redundancy/redundancy_003_pos.ksh
  tests/zfs-tests/tests/functional/redundancy/redundancy_004_neg.ksh
Labels: Status: Accepted

#9821 Remove parameter names from libzfs.h signatures
  include/libzfs.h
Labels: Status: Accepted

#9824 ZTS: Provide an alternative to shuf for FreeBSD
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/include/properties.shlib
  tests/zfs-tests/tests/functional/mv_files/random_creation.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_swap/zvol_swap_005_pos.ksh
Labels: Status: Accepted

#9827 ZTS: Improve zts-auto_offline_001_pos
  tests/zfs-tests/tests/functional/fault/auto_offline_001_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#9007 Add 'zfs send --saved' flag
  cmd/zfs/zfs_main.c
  include/libzfs.h
  include/libzfs_core.h
  include/sys/dmu_send.h
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs_core/libzfs_core.c
  man/man8/zfs-send.8
  module/zfs/dmu_recv.c
  module/zfs/dmu_send.c
  module/zfs/zfs_ioctl.c
  tests/runfiles/common.run
  tests/zfs-tests/cmd/libzfs_input_check/libzfs_input_check.c
  tests/zfs-tests/tests/functional/redacted_send/redacted_resume.ksh
  tests/zfs-tests/tests/functional/rsend/Makefile.am
  tests/zfs-tests/tests/functional/rsend/rsend.kshlib
  tests/zfs-tests/tests/functional/rsend/send_partial_dataset.ksh
Labels: Status: Accepted, Type: Feature

#9826 ZTS: Create xattr helpers to hide platform
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/rsend/rsend.kshlib
  tests/zfs-tests/tests/functional/rsend/send_encrypted_files.ksh
  tests/zfs-tests/tests/functional/rsend/send_realloc_dnode_size.ksh
  tests/zfs-tests/tests/functional/rsend/send_spill_block.ksh
  tests/zfs-tests/tests/functional/slog/slog_replay_fs_001.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_003_neg.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_004_pos.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_007_neg.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_011_pos.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_013_pos.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_common.kshlib
Labels: Status: Accepted, Type: Test Suite

#9834 ZTS: Clean up properties.shlib a bit
  tests/zfs-tests/include/properties.shlib
Labels: Status: Accepted, Type: Test Suite

#9828 ZTS: Remove obsolete zts-report.py exceptions
  tests/test-runner/bin/zts-report.py
Labels: Status: Accepted, Type: Test Suite

#9837 Change http://zfsonlinux.org links to https://zfsonlinux.org
  README.md
  cmd/zpool/zpool_main.c
  copy-builtin
  include/sys/fs/zfs.h
  lib/libzfs/libzfs.pc.in
  lib/libzfs/libzfs_core.pc.in
  lib/libzfs/libzfs_sendrecv.c
  man/man8/zed.8.in
  module/os/linux/spl/README.md
  rpm/generic/zfs-dkms.spec.in
  rpm/generic/zfs-kmod.spec.in
  rpm/generic/zfs.spec.in
  rpm/redhat/zfs-kmod.spec.in
Labels: Status: Accepted, Type: Documentation

#9833 libzfs: add zfs_mount_at() function
  include/libzfs.h
  lib/libzfs/libzfs_mount.c
Labels: Component: Userspace, Status: Accepted, Type: Feature

#9813 KMC_KVMEM disrupts kv_alloc() memory alignment expectations
  module/os/linux/spl/spl-kmem-cache.c
Labels: Status: Accepted, Type: Regression

#9819 Document zfs change-key caveats
  man/man8/zfs-load-key.8
Labels: Component: Encryption, Status: Accepted, Type: Documentation

#9829 Fix errata #4 handling for resuming streams
  include/sys/dmu_recv.h
  module/zfs/dmu_recv.c
Labels: Status: Accepted

#9839 ZTS: Remove some path workarounds for FreeBSD
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_004_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#9840 ZTS: Fix is_physical_device on FreeBSD
  tests/zfs-tests/include/blkdev.shlib
Labels: Status: Accepted, Type: Test Suite

#9841 ZTS: Avoid using PCRE with grep in zdb tests
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_checksum.ksh
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_decompress.ksh
Labels: Status: Accepted, Type: Test Suite

#9845 ZTS: Fix ksh path in btree tests
  tests/zfs-tests/tests/functional/btree/btree_negative.ksh
  tests/zfs-tests/tests/functional/btree/btree_positive.ksh
Labels: Status: Accepted, Type: Test Suite

#9847 ZFS performance suite should use JSON fio output
  tests/zfs-tests/tests/perf/perf.shlib
Labels: Status: Accepted

#9733 zdb -d should accept the numeric objset id
  cmd/zdb/zdb.c
  man/man8/zdb.8
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zdb/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_objset_id.ksh
Labels: Status: Accepted

#9844 ZTS: Fix incorrect is_physical_device usage
  tests/zfs-tests/include/blkdev.shlib
  tests/zfs-tests/tests/functional/cli_root/zpool_add/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_destroy/zpool_destroy_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_export/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/setup.ksh
  tests/zfs-tests/tests/functional/write_dirs/setup.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_001_neg.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_003_neg.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_004_pos.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_005_neg.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_006_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#9853 ZTS: Enable zpool_create_008_pos.ksh
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_008_pos.ksh
Labels: Status: Accepted

#9848 Unify target_cpu handling
  config/always-arch.m4
  lib/libicp/Makefile.am
  lib/libspl/Makefile.am
  lib/libspl/asm-generic/.gitignore
  module/icp/Makefile.in
  module/os/linux/zfs/Makefile.in
  module/zcommon/Makefile.in
  module/zfs/Makefile.in
Labels: Status: Accepted

#9851 ZTS: Make DVA pattern in zdb tests more robust
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_checksum.ksh
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_decompress.ksh
Labels: Status: Accepted, Type: Test Suite

#9854 ZTS: Eliminate partitioning in zpool_import setup
  tests/zfs-tests/tests/functional/cli_root/zpool_import/cleanup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import.cfg
Labels: Status: Accepted, Type: Test Suite

#9860 Re-consolidate zio_delay_interrupt
  lib/libzpool/Makefile.am
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/zio_os.c
  module/zfs/zio.c
Labels: Status: Accepted

#9861 Update tunable macro usage for disable_ivset_guid_check
  module/zfs/dsl_crypt.c
Labels: Status: Accepted

#9862 Disable get_numeric_property for xattr on FreeBSD.
  lib/libzfs/libzfs_dataset.c
Labels: Status: Accepted

#9863 Order zfs-import-*.service after multipathd
  etc/systemd/system/zfs-import-cache.service.in
  etc/systemd/system/zfs-import-scan.service.in
Labels: Status: Accepted

#9738 Support inheriting properties in channel programs
  include/sys/dsl_prop.h
  man/man8/zfs-program.8
  module/zfs/dsl_prop.c
  module/zfs/zcp_synctask.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/channel_program/synctask_core/Makefile.am
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.inherit.ksh
Labels: Status: Accepted, Type: Feature

#9865 Simplify FreeBSD's locking requirements in zfs_replay.c
  module/zfs/zfs_replay.c
Labels: Status: Accepted

#9873 ZTS: Add missing export for DEV_DSKDIR default
  tests/zfs-tests/include/default.cfg.in
Labels: Status: Accepted, Type: Test Suite

#9539 First go at AltiVec RAID-Z
  cmd/raidz_test/raidz_test.h
  include/os/linux/kernel/linux/Makefile.am
  include/os/linux/kernel/linux/simd.h
  include/os/linux/kernel/linux/simd_powerpc.h
  include/sys/vdev_raidz_impl.h
  lib/libspl/include/sys/simd.h
  lib/libzpool/Makefile.am
  man/man5/zfs-module-parameters.5
  module/zfs/Makefile.in
  module/zfs/vdev_raidz_math.c
  module/zfs/vdev_raidz_math_powerpc_altivec.c
  module/zfs/vdev_raidz_math_powerpc_altivec_common.h
Labels: Status: Accepted, Type: Architecture, Type: Performance

#9872 ZTS: Get xattr tests running on FreeBSD
  tests/runfiles/common.run
  tests/runfiles/linux.run
  tests/runfiles/sunos.run
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/xattr/xattr_003_neg.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_004_pos.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_007_neg.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_008_pos.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_009_neg.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_010_neg.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_011_pos.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_012_pos.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_013_pos.ksh
  tests/zfs-tests/tests/functional/xattr/xattr_common.kshlib
Labels: Status: Accepted, Type: Test Suite

#9878 scripts/zfs-test.sh: example for -t
  scripts/zfs-tests.sh
Labels: Status: Accepted

#9879 entity_namecheck: doc comment: include space as allowed character
  module/zcommon/zfs_namecheck.c
Labels: Status: Accepted

#9880 dsl_bookmark_create_check: fix NULL pointer deref if dbca_errors == NULL
  module/zfs/dsl_bookmark.c
Labels: Status: Accepted

#9876 ZTS: zpool offline requires whole disk name
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_004_pos.ksh
Labels: Status: Accepted

#9877 Performance tests, some variables missing PERF_ prefix
  tests/zfs-tests/tests/perf/fio/mkfiles.fio
  tests/zfs-tests/tests/perf/regression/random_reads.ksh
  tests/zfs-tests/tests/perf/regression/random_readwrite.ksh
  tests/zfs-tests/tests/perf/regression/random_readwrite_fixed.ksh
  tests/zfs-tests/tests/perf/regression/random_writes.ksh
  tests/zfs-tests/tests/perf/regression/random_writes_zil.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads_arc_cached.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads_arc_cached_clone.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads_dbuf_cached.ksh
  tests/zfs-tests/tests/perf/regression/sequential_writes.ksh
Labels: Status: Accepted

#9832 zdb: add support for object ranges for zdb -d
  cmd/zdb/zdb.c
  man/man8/zdb.8
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zdb/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_object_range_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_object_range_pos.ksh
Labels: Status: Accepted

#9871 ZTS: Move more tests out of common.run
  tests/runfiles/common.run
  tests/runfiles/linux.run
  tests/runfiles/sunos.run
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/zvol/zvol_swap/zvol_swap_002_pos.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_swap/zvol_swap_003_pos.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_swap/zvol_swap_005_pos.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_swap/zvol_swap_006_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#9892 Add an .editorconfig; document git whitespace settings
  .editorconfig
  .github/CONTRIBUTING.md
Labels: Status: Accepted

#9900 ZTS: Eliminate random and shuf, consolidate code
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/include/libtest.shlib
Labels: Status: Accepted, Type: Test Suite

#9901 ZTS: Don't use edonr on FreeBSD
  tests/zfs-tests/include/properties.shlib
  tests/zfs-tests/tests/functional/checksum/default.cfg
  tests/zfs-tests/tests/functional/checksum/filetest_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
  tests/zfs-tests/tests/functional/removal/removal_nopwrite.ksh
Labels: Status: Accepted, Type: Test Suite

#9906 ZTS: Reverse constrained path search order
  scripts/zfs-tests.sh
Labels: Status: Accepted, Type: Test Suite

#9908 ZTS: Simplify zero_partitions on FreeBSD
  tests/zfs-tests/include/libtest.shlib
Labels: Status: Accepted, Type: Test Suite

#9907 ZTS: FreeBSD tunable for DISABLE_IVSET_GUID_CHECK
  tests/zfs-tests/include/tunables.cfg
Labels: Status: Accepted, Type: Test Suite

#9898 ZTS: Fix a few defaults
  tests/zfs-tests/include/blkdev.shlib
  tests/zfs-tests/include/default.cfg.in
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_destroy/zpool_destroy.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_remove/zpool_remove.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_reopen/zpool_reopen.cfg
  tests/zfs-tests/tests/functional/fault/fault.cfg
  tests/zfs-tests/tests/functional/inuse/inuse.cfg
  tests/zfs-tests/tests/functional/migration/migration.cfg
  tests/zfs-tests/tests/functional/write_dirs/write_dirs.cfg
  tests/zfs-tests/tests/functional/zvol/zvol_ENOSPC/zvol_ENOSPC.cfg
  tests/zfs-tests/tests/functional/zvol/zvol_cli/zvol_cli.cfg
Labels: Status: Accepted, Type: Test Suite

#9899 ZTS: Use the correct spelling of 'jailed' in tests
  tests/zfs-tests/tests/functional/cli_root/zfs/zfs_001_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_create/properties.kshlib
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_008_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_inherit/zfs_inherit_002_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_set/ro_props_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_set/zfs_set_001_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_set/zfs_set_002_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_snapshot/zfs_snapshot_007_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_021_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_023_neg.ksh
  tests/zfs-tests/tests/functional/delegate/zfs_allow_010_pos.ksh
  tests/zfs-tests/tests/functional/delegate/zfs_allow_012_neg.ksh
  tests/zfs-tests/tests/functional/history/history_002_pos.ksh
  tests/zfs-tests/tests/functional/rsend/rsend.kshlib
Labels: Status: Accepted, Type: Test Suite

#9912 Left-align index props
  module/zcommon/zprop_common.c
Labels: Status: Accepted

#9914 ZTS: Don't use ext4 unless on Linux
  tests/zfs-tests/tests/functional/rsend/send-wDR_encrypted_zvol.ksh
Labels: Status: Accepted, Type: Test Suite
