Repository openzfs/zfs, pull requests merged in 2020-11, with the labels that each got.

#11142 Introduce CPU_SEQID_UNSTABLE
  include/os/freebsd/spl/sys/sysmacros.h
  include/os/linux/spl/sys/sysmacros.h
  include/sys/zfs_context.h
  module/icp/core/kcf_sched.c
  module/zfs/aggsum.c
  module/zfs/dmu_object.c
  module/zfs/txg.c
  module/zfs/zio.c
Labels: Status: Accepted

#10979 zfs_vnops: make zfs_get_data OS-independent
  include/os/freebsd/zfs/sys/zfs_znode_impl.h
  include/os/linux/zfs/sys/zfs_znode_impl.h
  include/sys/zfs_vnops.h
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#11126 optimize locking checks in mempool allocator
  module/zstd/zfs_zstd.c
Labels: Status: Accepted

#11147 ZTS: Wait on all events in events_001_pos.ksh
  tests/zfs-tests/tests/functional/events/events_common.kshlib
Labels: Component: Test Suite, Status: Accepted

#11148 ZTS: zdb_block_size_histogram increase variance
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_block_size_histogram.ksh
Labels: Status: Accepted

#11146 FreeBSD: zvol_os: Use SET_ERROR more judiciously
  module/os/freebsd/zfs/zvol_os.c
Labels: Status: Accepted

#11149 FreeBSD: Prevent NULL pointer dereference of resid
  module/os/freebsd/zfs/zfs_file_os.c
Labels: Status: Accepted

#11152 FreeBSD: Intialize zlog in zvol_first_open, this prevents a NULL reference later.
  module/os/freebsd/zfs/zvol_os.c
Labels: Status: Accepted

#11184 Fix dnode refcount tracking
  module/zfs/dmu_redact.c
  module/zfs/zvol.c
Labels: Status: Accepted

#11178 Fix dmu_tx_dirty_throttle after initial arc_c reduction.
  module/zfs/arc.c
Labels: Status: Accepted

#11162 initramfs: zfsunlock hook breaks /usr/bin
  contrib/initramfs/hooks/zfsunlock.in
Labels: Status: Accepted

#11186 G/C struct znode -> z_moved
  include/os/linux/zfs/sys/trace_acl.h
  include/sys/zfs_znode.h
  module/os/freebsd/zfs/zfs_znode.c
  module/os/linux/zfs/zfs_ctldir.c
  module/os/linux/zfs/zfs_znode.c
Labels: Status: Accepted

#11158 zpoolprops.8: clarify vdev expansion rules
  man/man8/zpoolprops.8
Labels: Status: Accepted

#11098 Fix memleak in cmd/mount_zfs.c
  cmd/mount_zfs/mount_zfs.c
  tests/runfiles/linux.run
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_013_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_014_neg.ksh
Labels: Status: Accepted

#11188 G/C data_alloc_arena
  module/zfs/zio.c
Labels: Status: Accepted

#11187 Linux: Fix mount/unmount when dataname name has a space
  module/os/linux/zfs/zpl_super.c
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_001_pos.ksh
Labels: Status: Accepted

#11190 channel program may spuriously fail with "memory limit exhausted"
  module/zfs/zcp.c
Labels: Status: Accepted

#11193 Return EFAULT at the end of zfs_write if set
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#11194 assertion failure when logging large output of channel program
  cmd/zpool/zpool_main.c
  include/sys/fs/zfs.h
  man/man5/zfs-module-parameters.5
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#11201 Linux: Fix ZFS_ENTER/ZFS_EXIT/ZFS_VERFY_ZP usage
  include/os/linux/zfs/sys/zfs_znode_impl.h
  module/os/linux/zfs/zpl_ctldir.c
  module/os/linux/zfs/zpl_file.c
  module/os/linux/zfs/zpl_super.c
Labels: Status: Accepted

#11205 Fix ASSERT logic in l2arc_evict()
  module/zfs/arc.c
Labels: Status: Accepted

#9596 Fix 'zfs userspace' for received datasets in encrypted root
  include/sys/dmu_objset.h
  module/zfs/dmu_objset.c
  module/zfs/zfs_ioctl.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/userquota/Makefile.am
  tests/zfs-tests/tests/functional/userquota/userspace_encrypted.ksh
Labels: Status: Accepted

#11199 Fix problems in zvol_set_volmode_impl
  include/sys/zvol_impl.h
  module/os/freebsd/zfs/zvol_os.c
  module/os/linux/zfs/zvol_os.c
  module/zfs/zvol.c
Labels: Status: Accepted

#11215 Enable ABI checks for the checkstyle workflow
  .github/workflows/checkstyle.yaml
Labels: Status: Accepted

#11191 Reduce confusion in zfs_write
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#11219 Track SONAME version bump in packaging
  config/deb.am
  rpm/generic/zfs.spec.in
Labels: Status: Accepted

#11218 Correct missing zil_claim() DTL updates
  module/zfs/vdev.c
Labels: Status: Accepted

#11225 Include the ABI with dist tarball
  lib/libnvpair/Makefile.am
  lib/libuutil/Makefile.am
  lib/libzfs/Makefile.am
  lib/libzfs_core/Makefile.am
  lib/libzfsbootenv/Makefile.am
Labels: Status: Accepted, Type: Building

#11165 Allow different name for user data
  contrib/pam_zfs_key/pam_zfs_key.c
Labels: Status: Accepted

#11227 libzfsbootenv: do not depend on libnvpair
  lib/libzfsbootenv/libzfsbootenv.pc.in
Labels: Status: Accepted, Type: Building

#11229 Update dRAID short feature description
  module/zcommon/zfeature_common.c
Labels: Status: Accepted, Type: Documentation

#11213 [FreeBSD] decouple ZFS_DEBUG from kernel debug settings
  module/Makefile.bsd
Labels: Status: Accepted

#11233 Obsolete earlier packages due to version bump
  rpm/generic/zfs.spec.in
Labels: Component: Packaging, Status: Accepted

#11166 Reduce latency effects of non-interactive I/O.
  include/sys/vdev_impl.h
  man/man5/zfs-module-parameters.5
  module/zfs/vdev_queue.c
Labels: Status: Accepted

#11235 Remove incorrect assertion
  module/zfs/zfs_vnops.c
Labels: Status: Code Review Needed

#11244 dracut: use /bin/sh instead of bash as the intepreter
  Makefile.am
  contrib/dracut/90zfs/export-zfs.sh.in
  contrib/dracut/90zfs/mount-zfs.sh.in
  contrib/dracut/90zfs/parse-zfs.sh.in
  contrib/dracut/90zfs/zfs-generator.sh.in
  contrib/dracut/90zfs/zfs-lib.sh.in
  contrib/dracut/90zfs/zfs-load-key.sh.in
  contrib/dracut/90zfs/zfs-needshutdown.sh.in
Labels: Status: Accepted

#11243 Verify zfs module loaded before starting services
  etc/systemd/system/zfs-share.service.in
  etc/systemd/system/zfs-volume-wait.service.in
  etc/systemd/system/zfs-zed.service.in
Labels: Status: Accepted

#11224 zpool_influxdb: move to libexec dir
  cmd/zpool_influxdb/Makefile.am
  cmd/zpool_influxdb/README.md
  cmd/zpool_influxdb/telegraf.d/exec_zpool_influxdb.conf
  cmd/zpool_influxdb/telegraf.d/execd_zpool_influxdb.conf
  rpm/generic/zfs.spec.in
  scripts/Makefile.am
  scripts/common.sh.in
  scripts/zfs-tests.sh
Labels: Status: Accepted
