Repository openzfs/zfs, pull requests merged in 2020-02, with the labels that each got.

#9921 Disable "-fipa-sra" when using "--enable-debuginfo"
  config/zfs-build.m4
Labels: Status: Accepted

#9885 async zvol minor node creation interferes with receive
  include/sys/zcp.h
  include/sys/zvol.h
  lib/libzpool/kernel.c
  module/os/linux/zfs/zvol_os.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/dsl_crypt.c
  module/zfs/dsl_dataset.c
  module/zfs/spa.c
  module/zfs/zcp.c
  module/zfs/zcp_synctask.c
  module/zfs/zfs_ioctl.c
  module/zfs/zvol.c
Labels: Component: ZVOL, Status: Accepted

#9917 Fix const-correctness in raidz math
  module/zfs/vdev_raidz_math_impl.h
Labels: Status: Accepted

#9913 Restore aclmode and remove acltype on FreeBSD
  include/sys/fs/zfs.h
  man/man8/zfsprops.8
  module/zcommon/zfs_prop.c
Labels: Status: Accepted

#9927 Use -Werror to check if the compiler supports specific options
  config/always-compiler-options.m4
Labels: Status: Accepted, Type: Building

#9933 Prepare ks_data before calling kstat_install().
  module/os/linux/zfs/abd.c
  module/zfs/dbuf.c
Labels: Status: Accepted

#9902 Convert dbuf dirty record record list to a list_t
  include/sys/dbuf.h
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_objset.c
  module/zfs/dnode.c
  module/zfs/dnode_sync.c
Labels: Status: Accepted

#9931 Few microoptimizations to dbuf layer.
  include/sys/dbuf.h
  module/zfs/dbuf.c
Labels: Status: Accepted

#9918 Suggest using visudo to edit
  etc/sudoers.d/zfs
Labels: Status: Accepted, Type: Documentation

#9946 Check for cc flag -fno-ipa-sra
  config/always-compiler-options.m4
  config/zfs-build.m4
Labels: Status: Accepted, Type: Building

#9943 Fix static data to link with -fno-common.
  cmd/zfs/zfs_util.h
  cmd/zpool/zpool_main.c
  cmd/zpool/zpool_util.h
  lib/libshare/smb.c
  lib/libshare/smb.h
Labels: Status: Accepted

#9942 Replace static per-cpu with dynamic per-cpu data.
  module/os/linux/spl/spl-generic.c
Labels: Status: Accepted

#9930 Reduce number of atomic_add() calls in aggsum.
  include/sys/aggsum.h
  module/zfs/aggsum.c
Labels: Status: Accepted

#9963 ZTS: Use wc -c instead of --bytes for portability
  tests/zfs-tests/tests/functional/redacted_send/redacted_size.ksh
Labels: Status: Accepted, Type: Test Suite

#9960 Add is_dilos for future ZTS updates
  tests/zfs-tests/include/libtest.shlib
Labels: Status: Accepted

#9909 Factor out dbuf_sync_bonus
  module/zfs/dbuf.c
Labels: Status: Accepted

#9749 ICP: Improve AES-GCM performance
  COPYRIGHT
  config/toolchain-simd.m4
  include/os/linux/kernel/linux/simd_x86.h
  include/sys/zio.h
  lib/libicp/Makefile.am
  lib/libspl/include/sys/simd.h
  man/man8/zfsprops.8
  module/icp/Makefile.in
  module/icp/algs/modes/gcm.c
  module/icp/asm-x86_64/modes/THIRDPARTYLICENSE.cryptogams
  module/icp/asm-x86_64/modes/THIRDPARTYLICENSE.cryptogams.descrip
  module/icp/asm-x86_64/modes/THIRDPARTYLICENSE.openssl
  module/icp/asm-x86_64/modes/THIRDPARTYLICENSE.openssl.descrip
  module/icp/asm-x86_64/modes/aesni-gcm-x86_64.S
  module/icp/asm-x86_64/modes/ghash-x86_64.S
  module/icp/include/aes/aes_impl.h
  module/icp/include/modes/modes.h
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_crypt_combos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_crypt_combos.ksh
  tests/zfs-tests/tests/functional/rsend/send_encrypted_props.ksh
Labels: Component: Encryption, Status: Accepted, Type: Performance

#9953 ZTS: Test zvol I/O in different volmodes
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_volmode.ksh
Labels: Status: Accepted, Type: Test Suite

#9964 Share some code for spa deadman tunables
  include/sys/spa_impl.h
  module/os/linux/zfs/spa_misc_os.c
  module/zfs/spa_misc.c
Labels: Status: Accepted

#9893 bash scripts: use /usr/bin/env for bash shebangs
  cmd/zgenhostid/zgenhostid
  contrib/dracut/02zfsexpandknowledge/module-setup.sh.in
  contrib/dracut/90zfs/module-setup.sh.in
  contrib/dracut/90zfs/zfs-generator.sh.in
  copy-builtin
  scripts/commitcheck.sh
  scripts/kmodtool
  scripts/zimport.sh
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/perf/scripts/prefetch_io.sh
Labels: Status: Accepted

#9729 Fix zdb -R with 'b' flag
  cmd/zdb/zdb.c
  include/sys/zio.h
  man/man8/zdb.8
  module/zfs/zio.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zdb/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_display_block.ksh
Labels: Status: Accepted

#9968 Add missing dmu_buf_unlock_parent() calls to dbuf_read_impl()
  module/zfs/dbuf.c
Labels: Status: Accepted

#9962 Address Coverity warnings in #9902
  module/zfs/dbuf.c
Labels: Status: Accepted

#9925 zdb: Print symlink target when dump_znode() is called
  cmd/zdb/zdb.c
Labels: Status: Accepted

#9984 ZTS: Move zpool_split_wholedisks to linux.run
  tests/runfiles/common.run
  tests/runfiles/linux.run
Labels: Status: Accepted, Type: Test Suite

#9978 Move zfs_version_kernel to platform code
  lib/libzfs/libzfs_util.c
  lib/libzfs/os/linux/libzfs_util_os.c
Labels: Component: Userspace, Status: Accepted

#9980 ZTS: Fix zdb_display_block on FreeBSD
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_display_block.ksh
Labels: Status: Accepted, Type: Test Suite

#9981 ZTS: Interpret env vars in faketty on FreeBSD
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/include/libtest.shlib
Labels: Status: Accepted, Type: Test Suite

#9982 ZTS: Move user_namespace test to linux.run
  tests/runfiles/common.run
  tests/runfiles/linux.run
Labels: Status: Accepted, Type: Test Suite

#9949 Remove duplicate dbufs accounting.
  include/sys/dnode.h
  module/zfs/dbuf.c
  module/zfs/dnode.c
Labels: Status: Accepted

#9989 missed wakeup when growing kmem cache
  module/os/linux/spl/spl-kmem-cache.c
Labels: Status: Accepted

#9983 fix zstreamdump -C
  cmd/zstreamdump/zstreamdump.c
Labels: Component: Send/Recv, Status: Accepted

#9970 Fix zfs-mount-generator escaping
  etc/systemd/system-generators/zfs-mount-generator.in
Labels: Status: Accepted

#9992 ZTS: Use ECKSUM instead of EBADE in libzfs test
  tests/zfs-tests/cmd/libzfs_input_check/libzfs_input_check.c
Labels: Status: Accepted, Type: Test Suite

#9991 ZTS: Fix a typo/whitespace in tests README
  tests/README.md
Labels: Status: Accepted, Type: Documentation, Type: Test Suite

#9993 ZTS: Cleanup some cleanup functions
  tests/zfs-tests/tests/functional/cli_root/zpool_add/add-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_attach/attach-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/create-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_003_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_004_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_005_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_006_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_010_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_012_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_014_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_015_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_016_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_017_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_018_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_019_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_020_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_022_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_023_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_tempname.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_replace/replace-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_replace/replace_prop_ashift.ksh
  tests/zfs-tests/tests/functional/no_space/enospc_003_pos.ksh
Labels: Status: Accepted

#9995 ZTS: Eliminate partitioning from write_dirs
  tests/zfs-tests/tests/functional/write_dirs/Makefile.am
  tests/zfs-tests/tests/functional/write_dirs/cleanup.ksh
  tests/zfs-tests/tests/functional/write_dirs/setup.ksh
  tests/zfs-tests/tests/functional/write_dirs/write_dirs.cfg
  tests/zfs-tests/tests/functional/write_dirs/write_dirs_001_pos.ksh
  tests/zfs-tests/tests/functional/write_dirs/write_dirs_002_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#9996 ZTS: Eliminate partitioning from zpool_remove
  tests/zfs-tests/tests/functional/cli_root/zpool_remove/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_remove/zpool_remove.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_remove/zpool_remove_001_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_remove/zpool_remove_002_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_remove/zpool_remove_003_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#9997 ZTS: Don't include zpool_create.shlib in zpool_add
  tests/zfs-tests/tests/functional/cli_root/zpool_add/add-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/add_nested_replacing_spare.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/add_prop_ashift.ksh
Labels: Status: Accepted, Type: Test Suite

#9994 ZTS: Misc test fixes for FreeBSD
  tests/zfs-tests/tests/functional/cli_root/zfs_rollback/zfs_rollback_common.kshlib
  tests/zfs-tests/tests/functional/cli_root/zpool/zpool_003_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_012_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_015_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_trim/setup.ksh
  tests/zfs-tests/tests/functional/pool_checkpoint/checkpoint_capacity.ksh
  tests/zfs-tests/tests/functional/rsend/rsend_012_pos.ksh
  tests/zfs-tests/tests/functional/rsend/send_realloc_encrypted_files.ksh
  tests/zfs-tests/tests/functional/rsend/send_realloc_files.ksh
  tests/zfs-tests/tests/functional/trim/setup.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_common.kshlib
  tests/zfs-tests/tests/perf/perf.shlib
Labels: Status: Accepted, Type: Test Suite

#9998 Use POSIX stdout/stderr redirect in configure macro [issue #9990]
  config/kernel.m4
Labels: Status: Accepted, Type: Building

#9979 Make zpool.d/iostat work on FreeBSD
  cmd/zpool/zpool.d/iostat
Labels: Component: Userspace, Status: Accepted

#10000 Remove limit on number of async zio_frees of non-dedup blocks
  include/sys/dsl_scan.h
  man/man5/zfs-module-parameters.5
  module/zfs/dsl_scan.c
Labels: Status: Accepted, Type: Performance

#9950 Support setting user properties in a channel program
  include/sys/Makefile.am
  include/sys/zcp_set.h
  lib/libzpool/Makefile.am
  man/man8/zfs-program.8
  module/zfs/Makefile.in
  module/zfs/zcp_set.c
  module/zfs/zcp_synctask.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/channel_program/synctask_core/Makefile.am
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.set_props.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.set_props.zcp
Labels: Status: Accepted

#10005 Honour sync=disabled when relinking tmpfiles
  module/os/linux/zfs/zfs_vnops.c
Labels: Status: Accepted

#10007 ZTS: Move cksum to common system commands
  tests/zfs-tests/include/commands.cfg
Labels: Status: Accepted, Type: Test Suite

#10003 Prefer org.openzfs for features and properties
  include/sys/fs/zfs.h
  man/man5/zpool-features.5
  module/zcommon/zfeature_common.c
  tests/zfs-tests/tests/functional/cli_root/zfs_send/zfs_send-b.ksh
Labels: Status: Accepted, Type: Documentation

#9923 Factor out some dbuf subroutines and add state change tracing
  include/os/linux/zfs/sys/trace_dbuf.h
  module/zfs/dbuf.c
Labels: Status: Accepted

#10008 Enable zpool events tunables and tests on FreeBSD
  include/os/linux/kernel/linux/mod_compat.h
  module/zfs/fm.c
  tests/runfiles/common.run
  tests/runfiles/linux.run
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_events/zpool_events_clear.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_events/zpool_events_errors.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_events/zpool_events_follow.ksh
Labels: Status: Accepted, Type: Test Suite

#10011 ZTS: Move free to Linux commands list
  tests/zfs-tests/include/commands.cfg
Labels: Status: Accepted, Type: Test Suite

#10013 Add notice that forcefully unmount is not supported on Linux.
  man/man8/zfs-mount.8
  man/man8/zpool-export.8
Labels: Status: Accepted

#10024 ZTS: Avoid nonportable cmp flag
  tests/zfs-tests/tests/functional/cli_root/zpool_labelclear/zpool_labelclear_valid.ksh
Labels: Status: Accepted, Type: Test Suite

#10023 ZTS: Fix zpool_create/create-o_ashift on FreeBSD
  tests/zfs-tests/tests/functional/cli_root/zpool_create/create-o_ashift.ksh
Labels: Status: Accepted, Type: Test Suite

#10002 ZTS: Eliminate partitioning from zpool_create etc
  tests/zfs-tests/tests/functional/cli_root/zpool_attach/attach-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/cleanup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/create-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create.shlib
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_002_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_003_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_004_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_007_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_008_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_009_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_010_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_011_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_014_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_015_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_016_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_017_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_018_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_019_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_020_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_tempname.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_replace/replace-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_replace/replace_prop_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_set/zpool_set_ashift.ksh
  tests/zfs-tests/tests/functional/inuse/inuse.cfg
  tests/zfs-tests/tests/functional/inuse/inuse_001_pos.ksh
  tests/zfs-tests/tests/functional/inuse/inuse_003_pos.ksh
  tests/zfs-tests/tests/functional/inuse/inuse_005_pos.ksh
  tests/zfs-tests/tests/functional/inuse/inuse_006_pos.ksh
  tests/zfs-tests/tests/functional/inuse/inuse_007_pos.ksh
  tests/zfs-tests/tests/functional/inuse/inuse_008_pos.ksh
  tests/zfs-tests/tests/functional/inuse/inuse_009_pos.ksh
  tests/zfs-tests/tests/functional/no_space/enospc_003_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#10021 Fix icp include directories for in-tree build
  module/icp/Makefile.in
Labels: Status: Accepted

#10022 ZTS: Fix faulty slog_replay_fs_001 test
  tests/zfs-tests/tests/functional/slog/slog_replay_fs_001.ksh
Labels: Status: Accepted, Type: Test Suite

#10028 ZTS: Check the right mount options on FreeBSD
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_007_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#10032 ZTS: Fix userquota_006_pos on FreeBSD
  tests/zfs-tests/tests/functional/userquota/userquota_006_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#10033 ZTS: Don't use lsblk on FreeBSD
  tests/zfs-tests/tests/functional/refreserv/refreserv_multi_raidz.ksh
  tests/zfs-tests/tests/functional/refreserv/refreserv_raidz.ksh
Labels: Status: Accepted, Type: Test Suite

#10035 ZTS: Move privilege tests to sunos.run
  tests/runfiles/common.run
  tests/runfiles/sunos.run
  tests/zfs-tests/tests/functional/privilege/setup.ksh
Labels: Status: Accepted, Type: Test Suite

#10037 ZTS: Refactor is_shared, fix impl on FreeBSD
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/cli_root/zfs_unshare/zfs_unshare_007_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#10036 ZTS: Eliminate partitioning from zpool_destroy
  tests/zfs-tests/tests/functional/cli_root/zpool_destroy/zpool_destroy.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_destroy/zpool_destroy_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_destroy/zpool_destroy_002_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#10039 Remove unused structs and members in dmu_send.c
  module/zfs/dmu_send.c
Labels: Status: Accepted

#10038 ZTS: Misc fixes for FreeBSD
  tests/zfs-tests/tests/functional/cli_root/zfs_rollback/zfs_rollback_common.kshlib
  tests/zfs-tests/tests/functional/cli_root/zfs_set/canmount_004_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_unmount/zfs_unmount_nested.ksh
  tests/zfs-tests/tests/functional/delegate/delegate_common.kshlib
  tests/zfs-tests/tests/functional/delegate/setup.ksh
  tests/zfs-tests/tests/functional/delegate/zfs_allow_002_pos.ksh
  tests/zfs-tests/tests/functional/delegate/zfs_allow_010_pos.ksh
  tests/zfs-tests/tests/functional/xattr/setup.ksh
Labels: Status: Accepted, Type: Test Suite

#10006 Remove zfs_getattr and convoff dead code
  include/os/linux/zfs/sys/zfs_vnops.h
  include/sys/dmu.h
  module/os/linux/zfs/zfs_vnops.c
  module/zfs/dmu.c
Labels: Status: Code Review Needed

#10053 Update README for OpenZFS
  README.md
Labels: Type: Documentation

#10046 ZTS: Move atime_003 to linux.run
  tests/runfiles/common.run
  tests/runfiles/linux.run
Labels: Status: Accepted, Type: Test Suite

#10031 Remove dead code error handling from dsl_crypt.c
  module/zfs/dsl_crypt.c
Labels: Status: Accepted

#9974 [WIP] zed_start should not fail if zed is already running
  tests/zfs-tests/include/libtest.shlib
Labels: Status: Accepted

#10045 Add missing newline after zfs redact help message
  cmd/zfs/zfs_main.c
Labels: Component: Userspace, Status: Accepted

#10047 ZTS: Misc fixes for FreeBSD
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/atime/atime_common.kshlib
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_008_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_023_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import_013_neg.ksh
  tests/zfs-tests/tests/functional/cli_user/misc/zdb_001_neg.ksh
  tests/zfs-tests/tests/functional/cli_user/misc/zfs_001_neg.ksh
  tests/zfs-tests/tests/functional/inheritance/inherit_001_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#10050 ZTS: Adapt casenorm tests for FreeBSD
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/casenorm/casenorm.kshlib
Labels: Status: Accepted, Type: Test Suite

#10059 ZTS: Fix zfs_copies_002_pos
  tests/zfs-tests/tests/functional/cli_root/zfs_copies/zfs_copies_002_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#9924 dnode: refactor dnode dirty context from dbuf_dirty
  include/sys/dnode.h
  module/os/linux/zfs/zfs_vfsops.c
  module/zfs/dbuf.c
  module/zfs/ddt_zap.c
  module/zfs/dmu_send.c
  module/zfs/dmu_tx.c
  module/zfs/dnode.c
  module/zfs/dsl_bookmark.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_dir.c
  module/zfs/dsl_prop.c
  module/zfs/dsl_scan.c
  module/zfs/spa_checkpoint.c
  module/zfs/vdev.c
  module/zfs/zap_leaf.c
  module/zfs/zcp.c
  module/zfs/zcp_get.c
  module/zfs/zcp_synctask.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#10055 fix zfs_receive_004_neg
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_004_neg.ksh
Labels: Status: Accepted, Type: Test Suite

#10054 ZTS: More misc. fixes for FreeBSD
  tests/zfs-tests/include/blkdev.shlib
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/functional/checksum/filetest_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_rewind_device_replaced.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import.kshlib
  tests/zfs-tests/tests/functional/history/history.cfg
  tests/zfs-tests/tests/functional/large_files/large_files_002_pos.ksh
  tests/zfs-tests/tests/functional/removal/removal_cancel.ksh
  tests/zfs-tests/tests/functional/resilver/resilver_restart_001.ksh
Labels: Status: Accepted, Type: Test Suite

#10057 Consolidate arc_buf allocation checks
  module/zfs/dbuf.c
Labels: Status: Accepted

#10061 pyzfs: Add constants for platform-specific errnos
  contrib/pyzfs/libzfs_core/_constants.py
  contrib/pyzfs/libzfs_core/_error_translation.py
  contrib/pyzfs/libzfs_core/exceptions.py
Labels: Status: Accepted

#10062 arc_summary: Make get_descriptions per platform
  cmd/arc_summary/arc_summary3
Labels: Status: Accepted

#10072 Linux 5.5 compat: blkg_tryget()
  config/kernel-bio.m4
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted, Type: Building

#10063 Fix CONFIG_MODULES=no Linux kernel config
  config/kernel.m4
Labels: Status: Accepted, Type: Building

#10060 ZTS: Eliminate partitioning from zpool_add
  tests/zfs-tests/tests/functional/cli_root/zpool_add/cleanup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add.kshlib
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_002_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_004_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_005_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_006_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_007_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_008_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_009_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_010_pos.ksh
Labels: Status: Accepted, Type: Test Suite

#10051 ZTS: Fixup shebang in rsend_016, add to common.run
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/rsend/rsend_016_neg.ksh
Labels: Status: Accepted, Type: Test Suite

#10034 Improve zfs destroy performance with zio_t-free zio_free()
  cmd/zdb/zdb.c
  module/zfs/arc.c
  module/zfs/dmu_objset.c
  module/zfs/mmp.c
  module/zfs/spa.c
  module/zfs/zio.c
Labels: Status: Accepted, Type: Performance

#10073 Re-share zfsdev_getminor and zfs_onexit_fd_hold
  include/sys/zfs_file.h
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/zfs_file_os.c
  module/os/linux/zfs/zfs_ioctl_os.c
  module/os/linux/zfs/zfs_onexit_os.c
  module/zfs/zfs_ioctl.c
  module/zfs/zfs_onexit.c
Labels: Status: Accepted

#10076 Don't open zfs control device exclusively
  lib/libzfs/libzfs_diff.c
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted
