Repository openzfs/zfs, pull requests merged in 2020-08, with the labels that each got.

#10651 ZTS: Use POSIX-compatible space character class
  tests/zfs-tests/tests/functional/cli_root/zpool/zpool_colors.ksh
Labels: Status: Accepted, Type: Test Suite

#10655 ZTS: zvol_misc_volmode is flaky on FreeBSD
  tests/test-runner/bin/zts-report.py.in
Labels: Status: Accepted, Type: Test Suite

#10600 Revise ARC shrinker algorithm
  include/os/linux/spl/sys/shrinker.h
  include/os/linux/zfs/sys/trace_arc.h
  include/sys/arc_impl.h
  man/man5/zfs-module-parameters.5
  module/os/freebsd/zfs/arc_os.c
  module/os/linux/zfs/arc_os.c
  module/zfs/arc.c
Labels: Component: Memory Management, Status: Accepted

#10633 ZTS: FreeBSD does have a l2arc.trim_ahead tunable
  tests/zfs-tests/include/tunables.cfg
Labels: Status: Code Review Needed, Type: Test Suite

#10647 Convert Linux-isms to FreeBSD-isms in platform zfs_debug.c
  module/os/freebsd/zfs/zfs_debug.c
Labels: Status: Accepted

#10635 Changes to make openzfs build within FreeBSD buildworld
  cmd/zpool/zpool_vdev.c
  include/os/freebsd/spl/sys/byteorder.h
  include/os/freebsd/spl/sys/ccompile.h
  include/os/freebsd/spl/sys/kmem.h
  include/os/freebsd/spl/sys/simd_x86.h
  include/os/freebsd/spl/sys/types.h
  include/os/freebsd/spl/sys/vnode.h
  include/os/freebsd/zfs/sys/sha2.h
  include/os/freebsd/zfs/sys/zfs_context_os.h
  lib/libspl/asm-i386/atomic.S
  lib/libspl/include/os/freebsd/sys/param.h
  lib/libspl/include/rpc/xdr.h
  lib/libspl/include/sys/isa_defs.h
  lib/libspl/include/sys/uio.h
  module/os/freebsd/spl/spl_vm.c
  module/os/freebsd/zfs/arc_os.c
  module/os/freebsd/zfs/kmod_core.c
  module/os/freebsd/zfs/sysctl_os.c
  module/os/freebsd/zfs/zfs_ioctl_compat.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/zfs/arc.c
Labels: Status: Accepted

#10631 Change the error handling for invalid property values during receive
  contrib/pyzfs/libzfs_core/_constants.py
  contrib/pyzfs/libzfs_core/_error_translation.py
  include/sys/fs/zfs.h
  lib/libzfs/libzfs_util.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#10656 FreeBSD: fix page fault in zfsctl_snapdir_getattr
  module/os/freebsd/zfs/zfs_ctldir.c
Labels: Status: Accepted

#10658 FreeBSD: Fix `zfs jail` and add a test
  configure.ac
  lib/libzfs/os/freebsd/libzfs_compat.c
  tests/runfiles/freebsd.run
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/functional/cli_root/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_jail/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_jail/cleanup.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_jail/jail.conf
  tests/zfs-tests/tests/functional/cli_root/zfs_jail/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_jail/zfs_jail_001_pos.ksh
Labels: Component: Userspace, Status: Accepted

#10659 Fix logging in l2arc_rebuild()
  module/zfs/arc.c
Labels: Status: Accepted

#10663 Fix verify zfs module loaded before starting services for --enable-linux-builtin (using ConditionPathIsDirectory)
  etc/systemd/system/zfs-import-cache.service.in
  etc/systemd/system/zfs-import-scan.service.in
  etc/systemd/system/zfs-mount.service.in
Labels: Status: Accepted

#10669 Fix arc__wait__for__eviction tracepoint
  include/os/linux/zfs/sys/trace_arc.h
Labels: Status: Accepted

#10668 Add missed thread_exit() to vdev_{autotrim,rebuild}_thread
  module/zfs/vdev_rebuild.c
  module/zfs/vdev_trim.c
Labels: Status: Accepted

#10657 FreeBSD: add support for lockless lookup
  include/os/freebsd/spl/sys/ccompat.h
  include/os/freebsd/zfs/sys/zfs_znode_impl.h
  module/os/freebsd/spl/spl_vfs.c
  module/os/freebsd/zfs/zfs_acl.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/freebsd/zfs/zfs_vnops.c
  module/os/freebsd/zfs/zfs_znode.c
Labels: Status: Accepted

#10643 fix i/o error handling of livelists and zap iteration
  module/zfs/dsl_deadlist.c
  module/zfs/dsl_destroy.c
  module/zfs/dsl_dir.c
  module/zfs/spa.c
Labels: Status: Accepted

#10640 ZTS: Remove bashisms from zfs-tests.sh
  scripts/zfs-tests.sh
  tests/zfs-tests/include/default.cfg.in
Labels: Status: Accepted, Type: Test Suite

#10654 Clarify error message when a range-tree double-add occurs
  module/zfs/range_tree.c
Labels: Status: Accepted

#10682 FreeBSD: update vaccess signature on most recent HEAD
  module/os/freebsd/zfs/zfs_vnops.c
Labels: Status: Accepted

#10685 Move ZVOL_DIR back to zfs.h
  include/sys/fs/zfs.h
  module/os/freebsd/zfs/zvol_os.c
Labels: Status: Accepted

#10694 Fix whitespace in l2arc_write_buffers()
  module/zfs/arc.c
Labels: Status: Accepted

#10699 FreeBSD: Fix module autoloading when built in base
  lib/libzfs/os/freebsd/libzfs_compat.c
Labels: Status: Accepted

#10688 'zfs share -a' should handle 'canmount=noauto'
  cmd/zfs/zfs_main.c
  tests/zfs-tests/tests/functional/cli_root/zfs_set/canmount_002_pos.ksh
Labels: Status: Accepted

#10618 Restore ARC MFU/MRU pressure
  module/zfs/arc.c
Labels: Status: Accepted

#10683 use zfs_dbgmsg to log metaslab_load/unload
  module/zfs/metaslab.c
Labels: Status: Accepted

#10704 Remove stale .travis.yml
  .travis.yml
Labels: Status: Accepted

#10700 Upstream: Release onexit/events with any missed zfsdev_state
  module/os/freebsd/zfs/kmod_core.c
  module/os/linux/zfs/zfs_ioctl_os.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#10693 Fix L2ARC reads when compressed ARC disabled
  module/zfs/arc.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/compression/Makefile.am
  tests/zfs-tests/tests/functional/compression/l2arc_compressed_arc.ksh
  tests/zfs-tests/tests/functional/compression/l2arc_compressed_arc_disabled.ksh
Labels: Status: Accepted

#10715 FreeBSD: Create taskq threads in appropriate proc
  include/os/freebsd/spl/sys/proc.h
  module/os/freebsd/spl/spl_sysevent.c
  module/os/freebsd/spl/spl_taskq.c
  module/os/freebsd/zfs/zvol_os.c
Labels: Status: Accepted

#10716 Fix l2arc_dev_rebuild_start thread name
  module/zfs/arc.c
Labels: Status: Accepted

#10717 Fix reporting of L2ARC writes in arc_summary3
  cmd/arc_summary/arc_summary3
Labels: Status: Accepted

#10720 FreeBSD: fallback to /boot/ to look for zpool.cache
  include/sys/fs/zfs.h
  module/zfs/spa_config.c
Labels: Status: Accepted

#10721 FreeBSD: fix merge error in zfs_acl_ids_create
  module/os/freebsd/zfs/zfs_acl.c
Labels: Status: Accepted

#10723 FreeBSD: fix the build with Clang 11
  module/zfs/dsl_dataset.c
  module/zfs/vdev_raidz_math_aarch64_neon_common.h
  module/zfs/vdev_raidz_math_avx2.c
  module/zfs/vdev_raidz_math_avx512f.c
  module/zfs/vdev_raidz_math_powerpc_altivec_common.h
  module/zfs/vdev_raidz_math_sse2.c
Labels: Status: Accepted

#10673 remove KMC_KMEM and KMC_VMEM
  include/os/linux/spl/sys/kmem_cache.h
  include/sys/zfs_context.h
  man/man5/spl-module-parameters.5
  module/os/linux/spl/spl-kmem-cache.c
  module/os/linux/spl/spl-proc.c
Labels: Status: Accepted

#10701 include scatter_chunk_waste in arc_size
  cmd/arcstat/arcstat.in
  include/sys/arc.h
  include/sys/arc_impl.h
  module/os/freebsd/zfs/abd_os.c
  module/os/linux/zfs/abd_os.c
  module/zfs/arc.c
Labels: Status: Accepted

#10726 ZTS: ztest may cause mmp tests failures
  tests/test-runner/bin/zts-report.py.in
Labels: Status: Code Review Needed, Type: Test Suite

#8627 Remove grub special-casing
  lib/libzfs/libzfs_pool.c
  man/man5/zpool-features.5
  man/man8/zfsprops.8
  module/zfs/spa.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#10734 Remove unused `zpool_is_bootable`
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#10706 Make zc_nvlist_src_size limit tunable
  include/os/freebsd/spl/sys/ccompile.h
  include/sys/zfs_ioctl_impl.h
  man/man5/zfs-module-parameters.5
  module/os/freebsd/zfs/zfs_ioctl_os.c
  module/os/linux/zfs/zfs_ioctl_os.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#10719 Add define to enable autotrim to default to on
  include/sys/spa.h
  module/zcommon/zpool_prop.c
Labels: Status: Accepted

#10729 libzfs_core: Initialize fail_ioc_cmd to ZFS_IOC_LAST
  lib/libzfs_core/libzfs_core.c
Labels: Status: Accepted

#10739 Fix ARC aggsum access after arc_state_fini()
  module/zfs/arc.c
Labels: Status: Accepted

#10730 ZED: Do not offline a missing device if no spare is available
  cmd/zed/agents/zfs_retire.c
  tests/zfs-tests/tests/functional/fault/auto_offline_001_pos.ksh
Labels: Status: Accepted

#10731 Add ARMv7 longjmp bugfix
  module/lua/setjmp/setjmp_arm.S
Labels: Status: Code Review Needed

#10738 FreeBSD: Add option to rewind checkpoint while importing root pool.
  include/os/freebsd/zfs/sys/zfs_context_os.h
  module/os/freebsd/zfs/spa_os.c
  module/os/freebsd/zfs/zfs_vfsops.c
Labels: Status: Accepted

#10745 FreeBSD: 11.x arc_stats compatibility
  include/sys/arc_impl.h
  module/Makefile.bsd
  module/zfs/arc.c
Labels: Status: Accepted

#10744 fix indentation in dnode_free_range()
  module/zfs/dnode.c
Labels: Status: Accepted

#10747 'zfs share -a' should clean noauto exports
  cmd/zfs/zfs_main.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/cli_root/zfs_share/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_share/zfs_share_012_pos.ksh
Labels: Status: Accepted

#10755 Silence 'make checkbashisms'
  Makefile.am
  cmd/vdev_id/vdev_id
  contrib/dracut/90zfs/export-zfs.sh.in
  contrib/dracut/90zfs/mount-zfs.sh.in
  contrib/dracut/90zfs/parse-zfs.sh.in
  contrib/dracut/90zfs/zfs-lib.sh.in
  contrib/dracut/90zfs/zfs-load-key.sh.in
  contrib/dracut/90zfs/zfs-needshutdown.sh.in
  contrib/initramfs/zfsunlock
  scripts/dkms.mkconf
  scripts/dkms.postbuild
Labels: Status: Accepted

#10773 libzstd: Don't warn about stack frame size in userspace
  lib/libzstd/Makefile.am
Labels: Status: Accepted, Type: Building

#10779 Add separate issue for questions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: Status: Accepted

#10767 ZFS performance tests should clean up NFS mount
  tests/zfs-tests/tests/perf/perf.shlib
Labels: Status: Accepted

#10784 CI checkstyle: add linter + rename job + install latest flake8
  .github/workflows/checkstyle.yaml
Labels: Status: Code Review Needed

#10771 Improve documentation of zpool import -d/-c vs -s
  man/man8/zpool-import.8
Labels: Status: Accepted

#10768 ZTS: Improve block_device_wait on FreeBSD
  tests/zfs-tests/include/blkdev.shlib
Labels: Status: Accepted, Type: Test Suite

#10766 Avoid snprintf warnings on gcc 7.1+
  include/sys/ddt.h
  lib/libspl/include/os/freebsd/sys/mnttab.h
  lib/libspl/include/os/linux/sys/mnttab.h
Labels: Status: Accepted

#10778 Add Stale-Bot support
  .github/stale.yml
Labels: Status: Accepted

#10775 avoid symbol collision with in-kernel zstdlib
  include/sys/zstd/zstd.h
  lib/libzstd/Makefile.am
  module/zfs/zio_compress.c
  module/zstd/Makefile.in
  module/zstd/README.md
  module/zstd/include/zstd_compat_wrapper.h
  module/zstd/zfs_zstd.c
Labels: Status: Accepted

#10783 Fix inability to destroy snapshot used over NFS
  module/os/linux/zfs/zfs_ctldir.c
Labels: Status: Accepted

#10792 man: Canonicalize .TH usage
  man/man1/arcstat.1
  man/man1/cstyle.1
  man/man1/raidz_test.1
  man/man1/zhack.1
  man/man1/ztest.1
  man/man5/spl-module-parameters.5
  man/man5/vdev_id.conf.5
  man/man5/zfs-events.5
  man/man5/zfs-module-parameters.5
  man/man5/zpool-features.5
  man/man8/fsck.zfs.8
  man/man8/mount.zfs.8
  man/man8/vdev_id.8
  man/man8/zed.8.in
  man/man8/zfs-mount-generator.8.in
  man/man8/zinject.8
  man/man8/zpool-iostat.8
  man/man8/zstreamdump.8
Labels: Status: Accepted, Type: Documentation

#10796 Export dmu_offset_next() symbol
  module/zfs/dmu.c
Labels: Status: Accepted

#10795 Mark lua setjmp/longjmp for powerpc weak
  module/lua/setjmp/setjmp_ppc.S
Labels: Status: Accepted, Type: Building

#9616 Don't assert on nvlists larger than SPA_MAXBLOCKSIZE
  include/libzfs_impl.h
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs/libzfs_util.c
Labels: Status: Accepted

#10765 Introduce limit on size of L2ARC headers.
  man/man5/zfs-module-parameters.5
  module/zfs/arc.c
Labels: Component: Memory Management, Status: Accepted

#10813 StaleBot Tweaks
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/stale.yml
Labels: Status: Accepted

#10811 Github CI: Enable checkbashism
  .github/workflows/checkstyle.yaml
Labels: Status: Accepted

#10809 FreeBSD: disable neon usage
  module/zcommon/zfs_fletcher.c
  module/zfs/vdev_raidz_math.c
Labels: Status: Accepted

#10810 remove pragma ident lines
  include/os/freebsd/spl/sys/acl_impl.h
  include/os/freebsd/spl/sys/cmn_err.h
  include/os/freebsd/spl/sys/extdirent.h
  include/os/freebsd/spl/sys/list.h
  include/os/freebsd/spl/sys/list_impl.h
  include/os/freebsd/spl/sys/zmod.h
  module/os/freebsd/spl/list.c
Labels: Status: Accepted

#10821 [High Priority] Fix broken bug report form.
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Status: Accepted

#10791 Always track temporary fses and snapshots for accounting
  module/zfs/dsl_dir.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_new_props.ksh
Labels: Status: Accepted

#10819 Remove duplicate dnode.h include
  module/zfs/sa.c
Labels: Status: Accepted

#10820 zpool: Change base URL for ZFS messages to openzfs-docs
  cmd/zpool/zpool_main.c
  include/sys/fs/zfs.h
  lib/libzfs/libzfs_sendrecv.c
  module/zfs/spa.c
Labels: Status: Accepted

#10824 Fix NEWS file
  NEWS
Labels: Status: Accepted

#10823 dnode_sync is careless with range tree
  module/zfs/dnode_sync.c
Labels: Status: Accepted

#10589 add the Xr's to the SEE ALSO as well
  man/man8/zfs.8
  man/man8/zpool.8
Labels: Status: Accepted, Type: Documentation

#10829 module/zstd: pass -U__BMI__
  module/Makefile.bsd
  module/zstd/Makefile.in
Labels: Status: Code Review Needed

#10818 Fix definition of BLKGETSIZE64 on FreeBSD
  lib/libspl/include/os/freebsd/sys/mount.h
Labels: Status: Accepted

#10835 config/zfs-build.m4: add --with-vendor flag
  config/zfs-build.m4
Labels: Status: Accepted

#10834 Linux 5.9 compat: NR_SLAB_RECLAIMABLE
  config/kernel-global_page_state.m4
  include/os/linux/kernel/linux/page_compat.h
  include/os/linux/spl/sys/vmsystm.h
  module/os/linux/zfs/arc_os.c
Labels: Status: Accepted, Type: Building

#10836 FreeBSD: add support for KSTAT_TYPE_RAW
  module/os/freebsd/spl/spl_kstat.c
Labels: Status: Accepted

#10808 Auto close "Status: Feedback requested" after a month
  .github/no-response.yml
Labels: Status: Accepted

#10841 FreeBSD: fix spurious failure in zvol_geom_open
  module/os/freebsd/zfs/zvol_os.c
Labels: Status: Accepted

#10842 WIP: Move spa_stats.c to common code
  module/os/freebsd/zfs/spa_stats.c
  module/os/linux/zfs/Makefile.in
  module/zfs/Makefile.in
  module/zfs/spa_stats.c
Labels: Status: Accepted

#10850 Corrected the typo in zfs/cmd/zfs/zfs_main.c line number 404 pbkfd2it…
  cmd/zfs/zfs_main.c
Labels: Status: Accepted
