Repository openzfs/zfs, pull requests merged in 2020-04, with the labels that each got.

#10148 Bugfix/fix uio partial copies
  module/os/linux/zfs/zfs_vnops.c
  module/zcommon/zfs_uio.c
Labels: Status: Accepted

#9707 Add a mechanism to wait for delete queue to drain
  cmd/zfs/zfs_main.c
  configure.ac
  include/libzfs.h
  include/libzfs_core.h
  include/sys/dsl_dir.h
  include/sys/fs/zfs.h
  lib/libzfs/libzfs_dataset.c
  lib/libzfs_core/libzfs_core.c
  man/man8/Makefile.am
  man/man8/zfs-wait.8
  man/man8/zfs.8
  module/os/linux/zfs/zfs_dir.c
  module/os/linux/zfs/zfs_vfsops.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_destroy.c
  module/zfs/dsl_dir.c
  module/zfs/zfs_ioctl.c
  tests/runfiles/common.run
  tests/zfs-tests/cmd/libzfs_input_check/libzfs_input_check.c
  tests/zfs-tests/tests/functional/cli_root/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_wait/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_wait/cleanup.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_wait/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_wait/zfs_wait.kshlib
  tests/zfs-tests/tests/functional/cli_root/zfs_wait/zfs_wait_deleteq.ksh
Labels: Status: Accepted, Type: Feature

#10170 ZTS: Fix non-portable date format
  tests/zfs-tests/tests/functional/delegate/delegate_common.kshlib
  tests/zfs-tests/tests/functional/delegate/zfs_allow_009_neg.ksh
Labels: Status: Accepted, Type: Test Suite

#10173 libzfs_pool: Remove unused check for ENOTBLK
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#10179 Finish refactoring for ZFS_MODULE_PARAM_CALL
  include/os/linux/kernel/linux/mod_compat.h
  include/sys/arc_impl.h
  include/sys/spa.h
  include/sys/zfs_context.h
  module/zfs/spa_misc.c
Labels: Status: Accepted

#10177 Use vn_io_fault_uiomove on FreeBSD to avoid potential deadlock
  module/zfs/dmu.c
Labels: Status: Accepted

#10187 Linux 5.7 compat: blk_alloc_queue()
  META
  config/kernel-make-request-fn.m4
  include/os/linux/kernel/linux/blkdev_compat.h
  module/os/linux/zfs/zvol_os.c
Labels: Status: Accepted, Type: Building

#10178 Add separate field for indicating that spa is in middle of split
  include/sys/spa_impl.h
  module/zfs/spa.c
Labels: Status: Accepted

#10158 Don't ignore zfs_arc_max below allmem/32
  include/sys/arc_impl.h
  module/os/linux/zfs/arc_os.c
  module/zfs/arc.c
Labels: Status: Accepted

#9582 Persistent L2ARC
  cmd/zdb/zdb.c
  configure.ac
  include/sys/arc.h
  include/sys/arc_impl.h
  include/sys/fs/zfs.h
  include/sys/spa.h
  lib/libzfs/libzfs_import.c
  man/man5/zfs-module-parameters.5
  man/man8/zdb.8
  man/man8/zpool-labelclear.8
  man/man8/zpoolconcepts.8
  module/os/linux/zfs/zfs_sysfs.c
  module/zfs/arc.c
  module/zfs/spa.c
  module/zfs/vdev.c
  tests/runfiles/linux.run
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/functional/Makefile.am
  tests/zfs-tests/tests/functional/persist_l2arc/Makefile.am
  tests/zfs-tests/tests/functional/persist_l2arc/cleanup.ksh
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc.cfg
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_001_pos.ksh
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_002_pos.ksh
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_003_neg.ksh
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_004_pos.ksh
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_005_pos.ksh
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_006_pos.ksh
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_007_pos.ksh
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_008_pos.ksh
  tests/zfs-tests/tests/functional/persist_l2arc/setup.ksh
Labels: Status: Accepted, Type: Feature

#10156 Add `zstream redup` command to convert deduplicated send streams
  cmd/Makefile.am
  cmd/zstream/.gitignore
  cmd/zstream/Makefile.am
  cmd/zstream/zstream.c
  cmd/zstream/zstream.h
  cmd/zstream/zstream_dump.c
  cmd/zstream/zstream_redup.c
  cmd/zstreamdump/Makefile.am
  cmd/zstreamdump/zstreamdump
  configure.ac
  lib/libzfs/libzfs_sendrecv.c
  man/man8/Makefile.am
  man/man8/zstream.8
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_013_pos.ksh
  tests/zfs-tests/tests/functional/rsend/send-cD.ksh
Labels: Component: Send/Recv, Status: Accepted

#10192 Minor `zstream redup` command fixes
  cmd/zstream/zstream_redup.c
  cmd/zstreamdump/.gitignore
Labels: Status: Accepted

#10184 zvol_write() can use dmu_tx_hold_write_by_dnode()
  module/os/linux/zfs/zvol_os.c
Labels: Component: ZVOL, Status: Accepted, Type: Performance

#10172 zts: Fix and change testcase cache_010_neg
  tests/runfiles/common.run
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/tests/functional/cache/Makefile.am
  tests/zfs-tests/tests/functional/cache/cache_010_pos.ksh
  tests/zfs-tests/tests/functional/cache/setup.ksh
Labels: Status: Accepted, Type: Test Suite

#10189 Disable user space reference tracking
  module/zfs/refcount.c
Labels: Status: Accepted

#10193 Fix allocation error, detected using ASAN
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#10195 sys/mnttab.h: include sys/stat.h for stat64
  lib/libspl/include/os/linux/sys/mnttab.h
Labels: Status: Accepted, Type: Building

#10194 Fix SC2086 note in zpool.d/smart
  cmd/zpool/zpool.d/smart
Labels: Status: Accepted

#10206 Don't delete freebsd.run in distclean
  tests/runfiles/freebsd.run
Labels: Status: Accepted, Type: Test Suite

#10203 Update FreeBSD tunables
  include/os/linux/kernel/linux/mod_compat.h
  module/os/freebsd/zfs/arc_os.c
  module/os/freebsd/zfs/sysctl_os.c
  module/zfs/ddt.c
  module/zfs/txg.c
  tests/zfs-tests/include/tunables.cfg
Labels: Status: Accepted

#10210 persistent L2ARC minor fixes
  cmd/zdb/zdb.c
  module/zfs/arc.c
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_007_pos.ksh
Labels: Status: Accepted

#10205 use new FreeBSD API to largely eliminate object locking
  include/os/freebsd/spl/sys/vm.h
  module/os/freebsd/zfs/dmu_os.c
  module/os/freebsd/zfs/zfs_vnops.c
Labels: Status: Code Review Needed

#10216 fix zfs send progress reporting
  include/os/freebsd/spl/sys/proc.h
  include/os/linux/spl/sys/proc.h
  module/zfs/zfs_ioctl.c
Labels: Component: Send/Recv, Status: Accepted, Type: Defect

#10227 Don't attempt trimming "hole" vdevs
  cmd/zpool/zpool_main.c
Labels: Status: Code Review Needed

#10213 use a struct to organize metaslab-group-allocator fields
  include/sys/metaslab_impl.h
  module/zfs/metaslab.c
  module/zfs/spa.c
Labels: Status: Accepted

#10219 Fix more leaks detected by ASAN
  lib/libzfs/libzfs_dataset.c
Labels: Status: Accepted

#10212 remove deduplicated send/receive code
  cmd/zfs/zfs_main.c
  include/libzfs.h
  include/libzfs_impl.h
  include/sys/dmu.h
  include/sys/dmu_recv.h
  include/sys/zfs_ioctl.h
  include/sys/zfs_onexit.h
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs_core/libzfs_core.c
  man/man8/zfs-receive.8
  man/man8/zfs-send.8
  module/zfs/dmu.c
  module/zfs/dmu_recv.c
  module/zfs/zfs_ioctl.c
  module/zfs/zfs_onexit.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/rsend/Makefile.am
  tests/zfs-tests/tests/functional/rsend/dedup.zsend.bz2
  tests/zfs-tests/tests/functional/rsend/dedup_encrypted_zvol.bz2
  tests/zfs-tests/tests/functional/rsend/dedup_encrypted_zvol.zsend.bz2
  tests/zfs-tests/tests/functional/rsend/fs.tar.gz
  tests/zfs-tests/tests/functional/rsend/recv_dedup.ksh
  tests/zfs-tests/tests/functional/rsend/recv_dedup_encrypted_zvol.ksh
  tests/zfs-tests/tests/functional/rsend/send-cD.ksh
  tests/zfs-tests/tests/functional/rsend/send-wR_encrypted_zvol.ksh
  tests/zfs-tests/tests/functional/rsend/send_partial_dataset.ksh
Labels: Component: Send/Recv, Status: Accepted, Type: Feature

#10236 change libspl list member names to match kernel
  lib/libspl/include/sys/list_impl.h
  lib/libspl/list.c
Labels: Status: Accepted

#10244 Fix unitialized variable in `zstream redup` command
  cmd/zstream/zstream_redup.c
Labels: Status: Accepted, Type: Building

#10239 Fix missing ivset guid with resumed raw base recv
  module/zfs/dmu_recv.c
Labels: Component: Send/Recv, Status: Accepted

#10196 [WIP] zfs_create: round up volume size to multiple of bs
  cmd/zfs/zfs_main.c
  man/man8/zfs-create.8
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create.cfg
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_002_pos.ksh
Labels: Status: Accepted

#10252 Fix zlib leak on FreeBSD
  module/os/freebsd/spl/spl_zlib.c
Labels: Status: Code Review Needed

#10246 Add missing zfs_refcount_destroy() in key_mapping_rele()
  module/zfs/dsl_crypt.c
Labels: Status: Accepted

#10243 Add more sanity testing for zdb input args
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zdb/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_pos.ksh
Labels: Status: Accepted

#10218 Support custom URI schemes for the keylocation property
  include/libzfs_impl.h
  lib/libzfs/libzfs_crypto.c
  lib/libzfs/libzfs_util.c
Labels: Status: Accepted

#9967 Add longjmp support for Thumb-2
  module/lua/setjmp/setjmp_arm.S
Labels: Status: Accepted, Type: Architecture, Type: Building

#10265 Fix issue#10264 'zfs load-key broken for keyformat=passphrase'
  lib/libzfs/libzfs_crypto.c
Labels: Status: Accepted
