Repository openzfs/zfs, pull requests merged in 2020-06, with the labels that each got.

#10390 Upstream: add macOS calls to AVL
  include/sys/avl.h
  module/avl/avl.c
Labels: Status: Accepted

#10371 arc: Periodically update ARC kstats
  module/zfs/arc.c
Labels: Status: Accepted

#10381 FreeBSD: Simplify zvol and fix locking
  module/os/freebsd/zfs/zvol_os.c
Labels: Component: ZVOL, Status: Accepted

#10395 Update wiki links with new address
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: Status: Accepted

#10374 Fix double mutex_init bug in send code
  module/zfs/dmu_send.c
Labels: Status: Accepted

#10386 Connect dataset_kstats for FreeBSD
  include/os/freebsd/zfs/sys/zfs_vfsops.h
  include/sys/zvol_impl.h
  module/os/freebsd/spl/spl_kstat.c
  module/os/freebsd/zfs/zfs_dir.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/freebsd/zfs/zfs_vnops.c
  module/os/freebsd/zfs/zvol_os.c
  module/os/linux/zfs/zvol_os.c
Labels: Status: Accepted

#10398 zfsvfs_setup(): zap_stats_t may have undefined content when accessed
  module/os/linux/zfs/zfs_vfsops.c
Labels: Status: Accepted

#10406 mkfile: include missing headers
  tests/zfs-tests/cmd/mkfile/mkfile.c
Labels: Status: Accepted

#10407 ztest: Fix spa_open() ENOENT failures
  cmd/ztest/ztest.c
Labels: Status: Accepted, Type: Test Suite

#10409 Improve compatibility with C++ consumers
  include/libzfs.h
  include/os/freebsd/spl/sys/ccompile.h
  include/sys/abd.h
  include/sys/arc.h
  include/sys/ddt.h
  include/sys/dsl_dataset.h
  include/sys/range_tree.h
  include/sys/spa.h
  include/sys/vdev.h
  include/sys/zfs_context.h
  include/sys/zio.h
  lib/libspl/include/assert.h
  lib/libspl/include/umem.h
  lib/libzfs/os/freebsd/libzfs_compat.c
  lib/libzfs/os/linux/libzfs_pool_os.c
  module/os/linux/zfs/spa_stats.c
Labels: Status: Accepted

#10400 Upstream: Replace sprintf()->snprintf() strcpy()->strlcpy()
  include/sys/zfs_fuid.h
  module/icp/algs/aes/aes_impl.c
  module/icp/algs/modes/gcm.c
  module/icp/os/modhash.c
  module/lua/lstrlib.c
  module/os/linux/zfs/zfs_vfsops.c
  module/zfs/ddt.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_send.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_dir.c
  module/zfs/dsl_prop.c
  module/zfs/dsl_scan.c
  module/zfs/dsl_userhold.c
  module/zfs/spa.c
  module/zfs/zap.c
  module/zfs/zap_micro.c
  module/zfs/zcp_get.c
  module/zfs/zfs_fuid.c
  module/zfs/zfs_ioctl.c
  module/zfs/zfs_quota.c
  module/zfs/zio.c
Labels: Status: Accepted

#10405 Don't erase final byte of envblock
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#10415 Remove redundant includes.
  module/os/freebsd/zfs/zfs_ioctl_os.c
Labels: Status: Accepted

#10417 Restore support for in-kernel ZFS ioctls.
  include/sys/zfs_ioctl_impl.h
  module/os/freebsd/zfs/kmod_core.c
  module/os/linux/zfs/zfs_ioctl_os.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#10422 Linux 5.8 __vmalloc compat
  config/kernel-kmem.m4
  config/kernel.m4
  include/os/linux/spl/sys/kmem.h
  module/os/linux/spl/spl-kmem-cache.c
  module/os/linux/spl/spl-kmem.c
Labels: Status: Accepted

#10424 Move GFP flags kernel compatibility code
  include/os/linux/spl/sys/kmem.h
  module/os/linux/spl/spl-kmem.c
Labels: Status: Accepted

#9789 Trim L2ARC
  cmd/zdb/zdb.c
  include/sys/arc_impl.h
  include/sys/spa.h
  include/sys/vdev_impl.h
  include/sys/vdev_trim.h
  man/man5/zfs-module-parameters.5
  man/man8/zpoolprops.8
  module/os/linux/zfs/spa_stats.c
  module/zfs/arc.c
  module/zfs/spa.c
  module/zfs/vdev.c
  module/zfs/vdev_removal.c
  module/zfs/vdev_trim.c
  tests/runfiles/common.run
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/functional/trim/Makefile.am
  tests/zfs-tests/tests/functional/trim/trim.kshlib
  tests/zfs-tests/tests/functional/trim/trim_l2arc.ksh
Labels: Status: Accepted

#10426 fix add-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_add/add-o_ashift.ksh
Labels: Status: Accepted, Type: Test Suite

#10383 File incorrectly zeroed when receiving incremental stream that toggles -L
  cmd/zhack/zhack.c
  include/sys/dmu.h
  include/sys/dmu_objset.h
  include/sys/fs/zfs.h
  include/sys/zfs_ioctl.h
  include/sys/zfs_quota.h
  lib/libzfs/libzfs_sendrecv.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/linux/zfs/zfs_vfsops.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/zfs_quota.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/rsend/Makefile.am
  tests/zfs-tests/tests/functional/rsend/send-L_toggle.ksh
Labels: Component: Send/Recv, Status: Accepted, Type: Defect

#10423 Fix typos
  COPYRIGHT
  config/kernel-put-link.m4
  include/libzfs_impl.h
  include/os/freebsd/spl/rpc/xdr.h
  include/os/freebsd/spl/sys/callb.h
  include/os/freebsd/spl/sys/vnode_impl.h
  include/os/linux/spl/sys/trace.h
  include/sys/btree.h
  include/sys/zfs_ioctl.h
  include/sys/zfs_znode.h
  include/sys/zio_crypt.h
  lib/libzfs/libzfs_crypto.c
  lib/libzfs/os/freebsd/libzfs_compat.c
  lib/libzfs/os/freebsd/libzfs_fsshare.c
  man/man5/zfs-module-parameters.5
  man/man8/zdb.8
  module/lua/ldo.c
  module/os/freebsd/zfs/zfs_ctldir.c
  module/os/freebsd/zfs/zfs_dir.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/freebsd/zfs/zfs_vnops.c
  module/os/freebsd/zfs/zfs_znode.c
  module/os/freebsd/zfs/zio_crypt.c
  module/unicode/u8_textprep.c
  module/zfs/abd.c
  module/zfs/arc.c
  module/zfs/btree.c
  module/zfs/dsl_bookmark.c
  module/zfs/metaslab.c
  module/zfs/vdev_raidz.c
  module/zfs/vdev_raidz_math_powerpc_altivec.c
  module/zfs/zfs_ioctl.c
  module/zfs/zvol.c
  tests/zfs-tests/cmd/mkbusy/mkbusy.c
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.set_props.zcp
  tests/zfs-tests/tests/functional/cli_root/zfs_ids_to_path/zfs_ids_to_path_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_wait/zpool_wait_multiple.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_wait/zpool_wait_no_activity.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_wait/zpool_wait_trim_basic.ksh
  tests/zfs-tests/tests/functional/history/history_common.kshlib
  tests/zfs-tests/tests/functional/largest_pool/largest_pool_001_pos.ksh
  tests/zfs-tests/tests/functional/mmap/mmap_read_001_pos.ksh
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_002_pos.ksh
  tests/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_005_pos.ksh
  tests/zfs-tests/tests/functional/resilver/resilver_restart_001.ksh
  tests/zfs-tests/tests/functional/write_dirs/write_dirs_001_pos.ksh
  tests/zfs-tests/tests/functional/write_dirs/write_dirs_002_pos.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads_dbuf_cached.ksh
Labels: Status: Accepted

#10435 Remove unnecessary references to slavery
  cmd/zpool/Makefile.am
  cmd/zpool/zpool.d/dm-deps
  contrib/dracut/02zfsexpandknowledge/module-setup.sh.in
  include/os/freebsd/spl/sys/dkio.h
  lib/libspl/include/sys/dkio.h
  lib/libzutil/os/linux/zutil_device_path_os.c
  man/man8/zpool.8
  tests/zfs-tests/include/blkdev.shlib
Labels: Status: Accepted

#10418 bash_completion: add missing attributes
  contrib/bash_completion.d/zfs
Labels: Status: Accepted

#10419 man.8: Add bookmark to list of types.
  man/man8/zfsprops.8
Labels: Status: Accepted, Type: Documentation

#10428 Removing ZERO_PAGE abd_alloc_zero_scatter
  include/sys/abd.h
  include/sys/abd_impl.h
  module/os/linux/zfs/abd_os.c
Labels: Status: Accepted, Type: Architecture, Type: Building

#10449 FreeBSD: Don't require zeroing new locks before init
  include/os/freebsd/spl/sys/mutex.h
Labels: Status: Accepted

#10433 Fix gcc10.1 truncation error
  include/sys/ddt.h
Labels: Status: Accepted

#10445 Upstream: zil_commit_waiter() can stall forever
  module/zfs/zil.c
Labels: Status: Accepted

#10412 Upstream: Add convenience wrappers for common uio usage
  include/os/freebsd/spl/sys/uio.h
  include/os/linux/spl/sys/uio.h
  lib/libspl/include/os/freebsd/sys/Makefile.am
  lib/libspl/include/os/freebsd/sys/uio.h
  lib/libspl/include/os/linux/sys/Makefile.am
  lib/libspl/include/sys/Makefile.am
  lib/libspl/include/sys/uio.h
  module/icp/algs/modes/modes.c
  module/icp/core/kcf_prov_lib.c
  module/icp/io/sha1_mod.c
  module/icp/io/sha2_mod.c
  module/icp/io/skein_mod.c
  module/zfs/dmu.c
  module/zfs/sa.c
  module/zfs/zfs_sa.c
Labels: Status: Accepted

#10460 Fix FreeBSD condvar semantics
  include/os/freebsd/spl/sys/condvar.h
Labels: Status: Accepted

#10431 Fixing ABD struct allocation for FreeBSD
  module/os/freebsd/zfs/abd_os.c
Labels: Status: Accepted

#10457 remove refences to blacklist/whitelist
  cmd/zpool/zpool_iter.c
  cmd/zpool/zpool_util.h
  lib/libzutil/os/freebsd/zutil_import_os.c
Labels: Status: Accepted

#10452 Allow sys/vdev_disk.h to have OS fields
  include/sys/vdev_disk.h
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#10443 FreeBSD: Kernel module should depend on xdr not krpc after 1300092
  module/os/freebsd/zfs/kmod_core.c
Labels: Status: Accepted

#10453 drr_begin: can't forward declare untagged struct
  include/sys/zfs_ioctl.h
Labels: Status: Accepted

#10456 Merge bash_completions changes from upstream
  contrib/bash_completion.d/zfs
Labels: Status: Accepted

#10437 Set initial arc_c to arc_c_min instead of arc_c_max.
  module/zfs/arc.c
Labels: Status: Accepted

#10469 zfs_ioctl: saved_poolname can be truncated
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#10474 add abd_cache_reap_now for abd_chunk_cache users
  include/sys/abd.h
  module/os/freebsd/zfs/abd_os.c
  module/os/linux/zfs/abd_os.c
  module/zfs/arc.c
Labels: Status: Accepted

#10471 Disambiguate condvar API contract.
  include/os/freebsd/spl/sys/condvar.h
  include/os/linux/spl/sys/condvar.h
  include/sys/zfs_context.h
  lib/libzpool/kernel.c
  module/os/linux/spl/spl-condvar.c
  module/zfs/zil.c
Labels: Status: Accepted

#10468 Avoid adding new primitives in zpool wait
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#10408 linux: implement fallocate(mode=0) compatibility
  configure.ac
  include/os/linux/zfs/sys/zfs_vfsops.h
  man/man5/zfs-module-parameters.5
  module/os/linux/zfs/zfs_vfsops.c
  module/os/linux/zfs/zpl_file.c
  module/os/linux/zfs/zpl_super.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/Makefile.am
  tests/zfs-tests/tests/functional/fallocate/Makefile.am
  tests/zfs-tests/tests/functional/fallocate/cleanup.ksh
  tests/zfs-tests/tests/functional/fallocate/fallocate_prealloc.ksh
  tests/zfs-tests/tests/functional/fallocate/fallocate_punch-hole.ksh
  tests/zfs-tests/tests/functional/fallocate/setup.ksh
Labels: Status: Accepted

#10475 Match new vfs_checkexp KPI in FreeBSD head
  module/os/freebsd/zfs/zfs_vfsops.c
Labels: Status: Accepted

#10280 zfs allow/unallow should work with numeric uid/gid
  cmd/zfs/zfs_main.c
Labels: Component: Userspace, Status: Accepted, Type: Feature

#10480 Fix copy-paste error breaking FreeBSD head
  module/os/freebsd/zfs/zfs_vfsops.c
Labels: Status: Accepted

#10489 Update zts-report.py with additional tests
  tests/test-runner/bin/zts-report.py
Labels: Status: Accepted

#10481 Clarify comments in config/*.m4, vdev_geom.c, zfs_allow_*.ksh
  config/iconv.m4
  config/lib-link.m4
  config/lib-prefix.m4
  module/os/freebsd/zfs/vdev_geom.c
  tests/zfs-tests/tests/functional/delegate/zfs_allow_007_pos.ksh
  tests/zfs-tests/tests/functional/delegate/zfs_allow_008_pos.ksh
Labels: Status: Accepted

#10482 Remove unnecessary terminology from error-injection in ztest
  cmd/ztest/ztest.c
Labels: Status: Accepted

#10476 zed additional features
  cmd/zed/zed.c
  cmd/zed/zed_conf.c
  cmd/zed/zed_conf.h
  cmd/zed/zed_event.c
  cmd/zed/zed_event.h
  man/man8/zed.8.in
Labels: Status: Accepted

#10483 zfs -V: Print userland version even if kernel module not loaded
  lib/libzfs/libzfs_util.c
Labels: Status: Accepted

#10490 Add zfs_multihost_interval tunable handler for FreeBSD
  include/os/freebsd/spl/sys/mod_os.h
  include/sys/mmp.h
  module/os/freebsd/zfs/sysctl_os.c
  module/os/linux/zfs/mmp_os.c
  module/zfs/mmp.c
  tests/zfs-tests/include/tunables.cfg
Labels: Status: Accepted

#10491 Add trim_finish notify script for ZED
  cmd/zed/zed.d/Makefile.am
  cmd/zed/zed.d/trim_finish-notify.sh
Labels: Status: Accepted

#9903 pam: implement a zfs_key pam module
  config/user-pam.m4
  config/user.m4
  config/zfs-build.m4
  configure.ac
  contrib/Makefile.am
  contrib/pam_zfs_key/Makefile.am
  contrib/pam_zfs_key/pam_zfs_key.c
  contrib/pam_zfs_key/zfs_key
  rpm/generic/zfs.spec.in
  tests/runfiles/linux.run
  tests/test-runner/bin/zts-report.py
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/functional/Makefile.am
  tests/zfs-tests/tests/functional/pam/Makefile.am
  tests/zfs-tests/tests/functional/pam/cleanup.ksh
  tests/zfs-tests/tests/functional/pam/pam_basic.ksh
  tests/zfs-tests/tests/functional/pam/pam_nounmount.ksh
  tests/zfs-tests/tests/functional/pam/setup.ksh
  tests/zfs-tests/tests/functional/pam/utilities.kshlib
Labels: Status: Accepted

#10496 ARC shrinking blocks reads/writes
  include/sys/arc_impl.h
  module/os/linux/zfs/arc_os.c
  module/zfs/arc.c
Labels: Status: Accepted, Type: Performance

#10315 9158 - Add a binning histogram of blocks to zdb
  cmd/zdb/zdb.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zdb/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_block_size_histogram.ksh
Labels: Status: Accepted

#10494 arcstat: add 'avail', fix 'free'
  cmd/arcstat/arcstat
  man/man1/arcstat.1
Labels: Status: Accepted, Type: Feature

#10397 Use percpu_counter for obj_alloc counter of Linux-backed caches
  config/kernel-percpu.m4
  config/kernel.m4
  include/os/linux/kernel/linux/Makefile.am
  include/os/linux/kernel/linux/percpu_compat.h
  include/os/linux/spl/sys/kmem_cache.h
  module/os/linux/spl/spl-kmem-cache.c
  module/os/linux/spl/spl-proc.c
Labels: Status: Accepted

#10502 Revise SPL wrapper for shrinker callbacks
  include/os/linux/spl/sys/shrinker.h
  module/os/linux/spl/spl-kmem-cache.c
  module/os/linux/zfs/arc_os.c
Labels: Status: Accepted

#10505 Make zstreamdump output the size of the nvlist before decoding it
  cmd/zstream/zstream_dump.c
Labels: Status: Accepted

#10499 Clean up OS-specific ARC and kmem code
  include/os/freebsd/spl/sys/kmem.h
  include/os/linux/spl/sys/kmem_cache.h
  include/os/linux/spl/sys/vmem.h
  include/sys/arc_impl.h
  include/sys/zfs_context.h
  lib/libzpool/kernel.c
  module/os/freebsd/zfs/arc_os.c
  module/os/linux/spl/spl-kmem-cache.c
  module/os/linux/spl/spl-vmem.c
  module/os/linux/zfs/arc_os.c
  module/zfs/arc.c
Labels: Status: Accepted

#10509 pam: fix test usage in configure script.
  config/user-pam.m4
Labels: Status: Accepted
