Repository openzfs/zfs, pull requests merged in 2021-02, with the labels that each got.

#11565 zfs-list.8: clarify listing snapshots
  man/man8/zfs-list.8
Labels: Status: Accepted, Type: Documentation

#11564 Fixed issue with processing of EC_dev_remove event
  cmd/zed/agents/zfs_agents.c
Labels: Component: ZED, Status: Accepted

#11568 zfs-import-{cache,scan}: change condition to FileNotEmpty
  etc/systemd/system/zfs-import-cache.service.in
  etc/systemd/system/zfs-import-scan.service.in
Labels: Status: Accepted

#11576 Set file mode during zfs_write
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#11575 Add an assert to avoid null value
  module/os/freebsd/zfs/zfs_znode.c
  module/os/linux/zfs/zfs_znode.c
Labels: Status: Accepted

#11580 Rename zfs_inode_update to zfs_vm_update_size
  include/os/freebsd/zfs/sys/zfs_znode_impl.h
  include/os/linux/zfs/sys/zfs_znode_impl.h
  include/sys/zfs_znode.h
  module/os/freebsd/zfs/zfs_znode.c
  module/os/linux/zfs/zfs_vfsops.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_znode.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#11526 vdev_id: Support daisy-chained JBODs in multipath mode.
  cmd/vdev_id/vdev_id
Labels: Status: Accepted

#11586 Linux 5.11 compat: META
  META
Labels: Status: Code Review Needed

#11592 Make inline ABD predicates compatible with C++
  include/sys/abd.h
Labels: Status: Accepted

#11600 Support uClibc for the tests compilations.
  cmd/ztest/ztest.c
  tests/zfs-tests/cmd/xattrtest/xattrtest.c
Labels: Status: Accepted

#11605 FreeBSD: Disable edonr in zfs_mod_supported_feature()
  cmd/zpool/zpool_main.c
  include/zfeature_common.h
  module/zcommon/zfeature_common.c
Labels: Status: Accepted

#11468 Add "compatibility" property for zpool feature sets [2021 version]
  cmd/zpool/Makefile.am
  cmd/zpool/compatibility.d/compat-2018
  cmd/zpool/compatibility.d/compat-2019
  cmd/zpool/compatibility.d/compat-2020
  cmd/zpool/compatibility.d/compat-2021
  cmd/zpool/compatibility.d/freebsd-11.0
  cmd/zpool/compatibility.d/freebsd-11.2
  cmd/zpool/compatibility.d/freebsd-11.3
  cmd/zpool/compatibility.d/freenas-9.10.2
  cmd/zpool/compatibility.d/grub2
  cmd/zpool/compatibility.d/openzfs-2.0-freebsd
  cmd/zpool/compatibility.d/openzfs-2.0-linux
  cmd/zpool/compatibility.d/openzfsonosx-1.7.0
  cmd/zpool/compatibility.d/openzfsonosx-1.8.1
  cmd/zpool/compatibility.d/openzfsonosx-1.9.3
  cmd/zpool/compatibility.d/zol-0.6.5
  cmd/zpool/compatibility.d/zol-0.7
  cmd/zpool/compatibility.d/zol-0.8
  cmd/zpool/zpool_main.c
  config/Rules.am
  include/libzfs.h
  include/sys/fs/zfs.h
  include/sys/spa_impl.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_status.c
  lib/libzutil/zutil_import.c
  man/man5/zpool-features.5
  man/man8/zpool-create.8
  man/man8/zpool-upgrade.8
  man/man8/zpoolprops.8
  module/zcommon/zpool_prop.c
  module/zfs/spa.c
  module/zfs/spa_config.c
  rpm/generic/zfs.spec.in
  scripts/Makefile.am
  tests/runfiles/common.run
  tests/zfs-tests/include/default.cfg.in
  tests/zfs-tests/tests/functional/cli_root/zpool_create/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create.shlib
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_features_006_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_features_007_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_features_008_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_status/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_features_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_upgrade/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_upgrade/zpool_upgrade_features_001_pos.ksh
Labels: Status: Accepted

#11614 Remove unused abd_alloc_scatter_offset_chunkcnt
  module/os/freebsd/zfs/abd_os.c
Labels: Status: Accepted

#11607 fix report_mount_progress never calling set_progress_header
  cmd/zfs/zfs_main.c
Labels: Status: Accepted

#11612 FreeBSD: disable the use of hardware crypto offload drivers for now
  module/os/freebsd/zfs/crypto_os.c
Labels: Component: Encryption, Status: Accepted

#11609 Checksum errors may not be counted
  include/sys/spa.h
  module/zfs/dsl_scan.c
  module/zfs/vdev.c
  module/zfs/vdev_indirect.c
  module/zfs/vdev_raidz.c
  module/zfs/vdev_rebuild.c
  module/zfs/zfs_fm.c
  module/zfs/zio.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zpool_events/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_events/zpool_events_clear_retained.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_events/zpool_events_duplicates.ksh
Labels: Status: Accepted

#11613 Restore FreeBSD resource usage accounting
  include/sys/Makefile.am
  include/sys/zfs_racct.h
  lib/libzpool/Makefile.am
  module/Makefile.bsd
  module/os/freebsd/zfs/zfs_racct.c
  module/os/linux/zfs/Makefile.in
  module/os/linux/zfs/zfs_racct.c
  module/zfs/arc.c
  module/zfs/dmu.c
Labels: Status: Accepted

#11622 Cleaning up uio headers
  include/os/freebsd/spl/sys/uio.h
  include/os/linux/spl/sys/uio.h
  include/os/linux/zfs/sys/zfs_context_os.h
  include/sys/uio_impl.h
  include/sys/zfs_context.h
  module/os/freebsd/spl/spl_uio.c
  module/zfs/spa_config.c
  module/zfs/zfs_ioctl.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#11617 Better zfs_get_enclosure_sysfs_path() enclosure support
  lib/libzutil/os/linux/zutil_device_path_os.c
Labels: Status: Accepted

#11623 vdev_ops: don't try to call vdev_op_hold or vdev_op_rele when NULL
  module/zfs/vdev.c
Labels: Status: Accepted

#11627 Using zfs-sh -u on linux will fail with inaccurate message when a zfs module is already unloaded
  scripts/zfs.sh
Labels: Status: Accepted

#11608 send_iterate_snap : doall send without fromsnap
  configure.ac
  lib/libzfs/libzfs_sendrecv.c
  tests/runfiles/common.run
  tests/zfs-tests/cmd/Makefile.am
  tests/zfs-tests/cmd/send_doall/.gitignore
  tests/zfs-tests/cmd/send_doall/Makefile.am
  tests/zfs-tests/cmd/send_doall/send_doall.c
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/functional/rsend/Makefile.am
  tests/zfs-tests/tests/functional/rsend/send_doall.ksh
Labels: Status: Code Review Needed

#11633 Force symlink creation for zpool.d compat links
  cmd/zpool/Makefile.am
Labels: Status: Accepted, Type: Building

#11636 Wrap bare EINVAL returns with SET_ERROR
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#11023 Add upper bound for slop space calculation
  include/sys/dsl_synctask.h
  module/zfs/spa_misc.c
Labels: Status: Accepted

#11638 Linux: increase max nvlist_src size
  man/man5/zfs-module-parameters.5
  module/os/linux/zfs/zfs_ioctl_os.c
Labels: Status: Code Review Needed

#11637 vdev_id: Fix partition regular expression
  cmd/vdev_id/vdev_id
Labels: Status: Accepted

#11585 Fix overly broad locking in spa_vdev_config_exit()
  module/zfs/spa_misc.c
Labels: Status: Accepted

#11647 Fix vdev_rebuild_thread deadlock
  module/zfs/vdev_rebuild.c
Labels: Status: Accepted

#11653 Add missing checks for unsupported features
  cmd/zpool/zpool_main.c
  cmd/ztest/ztest.c
  lib/libzfs/libzfs_status.c
  module/zcommon/zfeature_common.c
Labels: Status: Accepted

#11649 ZTS: zpool_trim_start_and_cancel_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_trim/zpool_trim_start_and_cancel_pos.ksh
Labels: Status: Accepted

#11654 Fix assert in FreeBSD-specific dmu_read_pages
  module/os/freebsd/zfs/dmu_os.c
Labels: Status: Code Review Needed
