Repository openzfs/zfs, pull requests merged in 2021-08, with the labels that each got.

#12446 Allow disabling of unmapped I/O on FreeBSD
  module/os/freebsd/zfs/vdev_geom.c
Labels: Status: Accepted

#12343 Modify checksum obtain method of QAT
  module/os/linux/zfs/qat_compress.c
Labels: Status: Accepted

#12429 Man zpool-scrub.8: describe sequential scrub
  man/man8/zpool-scrub.8
Labels: Type: Documentation, Status: Accepted

#12440 Enable /proc/diskstats for zvols
  module/os/linux/zfs/zvol_os.c
Labels: Component: ZVOL, Status: Accepted

#12410 Make get_key_material_file fail more verbosely
  lib/libzfs/libzfs_crypto.c
Labels: Status: Accepted

#12397 Run arc_evict thread at higher priority
  include/sys/zthr.h
  module/zfs/arc.c
  module/zfs/spa.c
  module/zfs/vdev_indirect.c
  module/zfs/zthr.c
Labels: Status: Accepted

#12453 Fix usage of find in tests/Makefile.am
  tests/Makefile.am
Labels: Status: Accepted

#12450 Add zfs.sh -r flag to reload modules
  scripts/zfs.sh
Labels: Status: Accepted

#12442 zfs: add missed dependency of zfs module on zlib
  module/os/freebsd/zfs/kmod_core.c
Labels: Status: Accepted

#12161 Restore FreeBSD sysctl processing for arc.min and arc.max
  include/os/freebsd/spl/sys/mod_os.h
  include/sys/arc.h
  include/sys/arc_impl.h
  module/os/freebsd/zfs/sysctl_os.c
  module/os/linux/zfs/arc_os.c
  module/zfs/arc.c
Labels: Status: Accepted

#12455 ZTS: Avoid unset $tmpdir in redacted_panic
  tests/zfs-tests/tests/functional/redacted_send/redacted_panic.ksh
Labels: Component: Test Suite, Status: Accepted

#12420 Use more atomics in refcounts.
  include/sys/zfs_refcount.h
  module/zfs/refcount.c
Labels: Status: Accepted

#12297 Avoid vq_lock drop in vdev_queue_aggregate().
  module/zfs/vdev_queue.c
Labels: Type: Performance, Status: Accepted

#12422 Fix/improve dbuf hits accounting.
  include/os/linux/zfs/sys/trace_arc.h
  include/sys/arc_impl.h
  module/zfs/arc.c
Labels: Status: Accepted

#12421 Optimize arc_l2c_only lists assertions.
  module/zfs/arc.c
Labels: Status: Accepted

#12406 Increase default volblocksize from 8KB to 16KB.
  include/sys/fs/zfs.h
  man/man7/zfsprops.7
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create.cfg
  tests/zfs-tests/tests/functional/nopwrite/nopwrite_volume.ksh
  tests/zfs-tests/tests/functional/reservation/reservation.shlib
Labels: Type: Performance, Status: Accepted

#12398 Remove b_pabd/b_rabd allocation from arc_hdr_alloc().
  include/sys/arc_impl.h
  module/os/freebsd/zfs/arc_os.c
  module/os/linux/zfs/arc_os.c
  module/zfs/arc.c
Labels: Type: Performance, Status: Accepted

#12384 [2.1] Detect HAVE_LARGE_STACKS at compile time
  config/Rules.am
  config/kernel-config-defined.m4
  include/os/freebsd/zfs/sys/zfs_context_os.h
  include/os/linux/zfs/sys/zfs_context_os.h
  lib/libspl/include/os/freebsd/sys/zfs_context_os.h
  lib/libspl/include/os/linux/sys/zfs_context_os.h
Labels: Status: Accepted

#12473 Initialize parity blocks before RAID-Z reconstruction benchmarking
  module/zfs/vdev_raidz_math.c
Labels: Status: Accepted

#12472 zpool-remove.8: describe top-level vdev sector size limitation
  man/man8/zpool-remove.8
Labels: Type: Documentation, Status: Accepted

#12515 ZTS: Waiting for zvols to be available
  tests/zfs-tests/include/blkdev.shlib
  tests/zfs-tests/tests/functional/cli_root/zfs_copies/zfs_copies.kshlib
  tests/zfs-tests/tests/functional/cli_root/zfs_rename/zfs_rename_007_pos.ksh
  tests/zfs-tests/tests/functional/rsend/recv_dedup_encrypted_zvol.ksh
  tests/zfs-tests/tests/functional/rsend/send-c_stream_size_estimate.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_swap/zvol_swap_004_pos.ksh
Labels: Component: Test Suite, Status: Code Review Needed

#12022 Fix endianness issues with zstd
  cmd/zdb/zdb.c
  include/sys/zstd/zstd.h
  module/zstd/Makefile.in
  module/zstd/include/sparc_compat.h
  module/zstd/zfs_zstd.c
  module/zstd/zstd_sparc.c
Labels: Status: Accepted

#12514 FreeBSD: Don't remove SA xattr if not SA znode
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Code Review Needed

#12436 Add zpool_disable_datasets_os() / zfs_unmount_os()
  include/libzfs.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_mount.c
  lib/libzfs/os/freebsd/libzfs_zmount.c
  lib/libzfs/os/linux/libzfs_mount_os.c
Labels: Status: Code Review Needed
