Repository openzfs/zfs, pull requests merged in 2021-05, with the labels that each got.

#11986 Updated zfs_dbgmsg_enable documentation to be more accurate.
  man/man5/zfs-module-parameters.5
Labels: Status: Code Review Needed, Type: Documentation

#12003 FreeBSD: Initialize/destroy zp->z_lock
  module/os/freebsd/zfs/zfs_znode.c
Labels: Status: Accepted

#11999 undocumented libzfs API changes broke "zfs list"
  cmd/zfs/zfs_main.c
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_diff.c
  lib/libzfs/libzfs_mount.c
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#11998 Simplify/fix dnode_move() for dn_zfetch.
  module/zfs/dnode.c
Labels: Status: Accepted

#11965 zed: a lock-based pickle indeed
  cmd/zed/zed_exec.c
Labels: Status: Accepted

#11996 module/zfs: remove zfs_zevent_console and zfs_zevent_cols
  include/os/freebsd/spl/sys/Makefile.am
  include/os/freebsd/spl/sys/console.h
  include/os/linux/spl/sys/Makefile.am
  include/os/linux/spl/sys/console.h
  include/sys/fm/util.h
  man/man5/zfs-module-parameters.5
  module/zfs/fm.c
Labels: Status: Accepted

#11972 Remove unimplemented virus scanning hooks
  include/os/freebsd/spl/sys/vfs.h
  include/os/freebsd/zfs/sys/zfs_vfsops_os.h
  include/os/linux/zfs/sys/zfs_vfsops_os.h
  man/man8/zfsprops.8
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_vfsops.c
  module/os/linux/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#11977 linux 5.13 compat: bdevops->revalidate_disk() removed
  config/kernel-block-device-operations.m4
  include/os/linux/kernel/linux/blkdev_compat.h
  module/os/linux/zfs/zvol_os.c
Labels: Status: Accepted, Type: Building

#12023 ZTS: Add known exceptions
  tests/test-runner/bin/zts-report.py.in
Labels: Status: Accepted

#11956 libzfs: add keylocation=https://, backed by fetch(3) or libcurl
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  config/Substfiles.am
  config/user-libfetch.m4
  config/user.m4
  contrib/dracut/90zfs/module-setup.sh.in
  contrib/dracut/90zfs/zfs-env-bootfs.service.in
  contrib/dracut/90zfs/zfs-load-key.sh.in
  contrib/dracut/90zfs/zfs-rollback-bootfs.service.in
  contrib/dracut/90zfs/zfs-snapshot-bootfs.service.in
  contrib/initramfs/hooks/zfs.in
  contrib/initramfs/scripts/zfs
  include/libzfs_impl.h
  lib/libzfs/Makefile.am
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_crypto.c
  lib/libzfs/libzfs_util.c
  man/man8/zfsprops.8
  module/zcommon/zfs_prop.c
  tests/runfiles/common.run
  tests/runfiles/sanity.run
  tests/zfs-tests/tests/functional/cli_root/zfs_load-key/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_load-key/cleanup.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_load-key/setup.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_load-key/zfs_load-key.cfg
  tests/zfs-tests/tests/functional/cli_root/zfs_load-key/zfs_load-key_all.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_load-key/zfs_load-key_common.kshlib
  tests/zfs-tests/tests/functional/cli_root/zfs_load-key/zfs_load-key_https.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_load-key/zfs_load-key_location.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_load-key/zfs_load-key_recursive.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_set/zfs_set_keylocation.ksh
Labels: Status: Accepted

#12033 Revert "Fix raw sends on encrypted datasets when copying back snapshots"
  module/os/freebsd/zfs/zio_crypt.c
  module/os/linux/zfs/zio_crypt.c
  module/zfs/dsl_crypt.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/userquota/Makefile.am
  tests/zfs-tests/tests/functional/userquota/userspace_send_encrypted.ksh
Labels: Status: Accepted

#12012 Add Pushover notifier.
  cmd/zed/zed.d/zed-functions.sh
  cmd/zed/zed.d/zed.rc
Labels: Status: Accepted

#12034 Fix dmu_recv_stream test for resumable
  module/zfs/dmu_recv.c
Labels: Status: Accepted

#12017 i-t: rewrite hooks
  Makefile.am
  contrib/initramfs/hooks/zfs.in
  contrib/initramfs/hooks/zfsunlock.in
Labels: Status: Accepted

#12043 ZTS: Increase redundancy test timeout
  tests/runfiles/common.run
Labels: Status: Accepted

#11966 Scale worker threads and taskqs with number of CPUs.
  man/man5/zfs-module-parameters.5
  module/zfs/spa.c
Labels: Status: Accepted

#12059 Simple change to fix building in recent environments.
  module/os/linux/zfs/zfs_ioctl_os.c
Labels: Status: Accepted

#12064 zfs-allow.8: mention 'bookmark' permission
  man/man8/zfs-allow.8
Labels: Status: Accepted

#12061 Fix dRAID sequential resilver silent damage handling
  include/sys/vdev_raidz_impl.h
  module/zfs/vdev_draid.c
  module/zfs/vdev_raidz.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/redundancy/Makefile.am
  tests/zfs-tests/tests/functional/redundancy/redundancy_draid_damaged.ksh
  tests/zfs-tests/tests/functional/redundancy/redundancy_draid_spare1.ksh
  tests/zfs-tests/tests/functional/redundancy/redundancy_draid_spare3.ksh
Labels: Status: Accepted

#12087 Update tmpfile() existence detection
  config/kernel-tmpfile.m4
  module/os/linux/zfs/zpl_inode.c
Labels: Status: Accepted

#12086 raidz_test: signal handling correctness
  cmd/raidz_test/raidz_test.c
Labels: Status: Accepted

#12077 FreeBSD: Retry OCF ENOMEM errors.
  module/os/freebsd/zfs/crypto_os.c
Labels: Status: Accepted

#12092 ZTS: remove verify_slog_support helper
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/pool_names/pool_names_002_neg.ksh
  tests/zfs-tests/tests/functional/slog/cleanup.ksh
  tests/zfs-tests/tests/functional/slog/setup.ksh
Labels: Status: Accepted

#12098 zdb: dump_history needs space
  cmd/zdb/zdb.c
Labels: Status: Accepted

#12088 Propagate vdev state due to invalid label corruption.
  cmd/zpool/zpool_main.c
  module/zfs/vdev.c
Labels: Status: Accepted

#12113 Add note for printing all dbgmsg entries on FreeBSD.
  module/os/freebsd/zfs/zfs_debug.c
Labels: Status: Accepted

#12049 FreeBSD: avoid memory allocation in arc_prune_async
  module/os/freebsd/zfs/arc_os.c
Labels: Status: Accepted

#12037 Correct flaws in arc_summary[23] and their test.
  cmd/arc_summary/arc_summary2
  cmd/arc_summary/arc_summary3
  tests/zfs-tests/tests/functional/cli_user/misc/arc_summary_001_pos.ksh
Labels: Status: Accepted

#12051 freebsd/libzfs: import execvPe() from FreeBSD 13
  lib/libzfs/os/freebsd/libzfs_compat.c
Labels: Status: Accepted

#12097 FreeBSD: Update dataset_kstats for zvols in dev mode.
  module/os/freebsd/zfs/zvol_os.c
Labels: Status: Accepted

#12040 Reinstate the old zpool read label logic as a fallback.
  lib/libzutil/zutil_import.c
Labels: Status: Accepted

#12093 Bend zpl_set_acl to permit the new userns* parameter.
  config/kernel-acl.m4
  include/os/linux/zfs/sys/zpl.h
  module/os/linux/zfs/zpl_xattr.c
Labels: Status: Accepted

#12046 Improve scrub maxinflight_bytes math.
  man/man5/zfs-module-parameters.5
  module/zfs/dsl_scan.c
Labels: Status: Accepted

#12114 Introduce write-mostly sums.
  config/kernel-percpu.m4
  include/os/freebsd/spl/sys/Makefile.am
  include/os/freebsd/spl/sys/wmsum.h
  include/os/linux/spl/sys/Makefile.am
  include/os/linux/spl/sys/wmsum.h
  include/sys/dataset_kstats.h
  lib/libspl/include/sys/Makefile.am
  lib/libspl/include/sys/wmsum.h
  module/zfs/arc.c
  module/zfs/dataset_kstats.c
Labels: Status: Accepted

#12126 Minor fix to configure on s390x
  config/kernel-bdi.m4
Labels: Status: Accepted

#12124 RPM: Explicitly set the required min/max kernel version for the DKMS
  rpm/generic/zfs-dkms.spec.in
Labels: Status: Accepted

#12127 Don't direct to Freenode in issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: Status: Accepted

#12117 long options for ztest
  cmd/ztest/ztest.c
  man/man1/ztest.1
Labels: Status: Code Review Needed

#12143 zstream: force-install zstreamdump link
  cmd/zstream/Makefile.am
Labels: Status: Accepted
