Repository openzfs/zfs, pull requests merged in 2021-04, with the labels that each got.

#11825 Fixing m4 iops rename check
  config/kernel-rename.m4
Labels: Status: Accepted

#11826 CI: Increase free space in workflow
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
Labels: Status: Accepted

#11813 Allow pool names that look like Solaris disk names
  module/zcommon/zfs_namecheck.c
  tests/zfs-tests/tests/functional/pool_names/pool_names_002_neg.ksh
Labels: Status: Accepted

#11817 Bump libzfs.so revision
  config/deb.am
  lib/libzfs/Makefile.am
  lib/libzpool/Makefile.am
  rpm/generic/zfs.spec.in
Labels: Status: Accepted

#11827 FreeBSD: Fix stable/12 after AT_BENEATH removal
  module/os/freebsd/zfs/zfs_file_os.c
Labels: Status: Accepted

#11751 Lockless zfsdev state destruction
  module/os/freebsd/zfs/kmod_core.c
  module/os/linux/zfs/zfs_ioctl_os.c
Labels: Status: Accepted

#11830 ZTS: inheritance/inherit_001_pos is flaky
  tests/test-runner/bin/zts-report.py.in
Labels: Component: Test Suite, Status: Accepted

#11821 Add RELEASES.md file
  Makefile.am
  RELEASES.md
Labels: Status: Accepted, Type: Documentation

#11828 bash_completion.d: always call zfs/zpool binaries directly
  contrib/bash_completion.d/.gitignore
  contrib/bash_completion.d/Makefile.am
  contrib/bash_completion.d/zfs.in
Labels: Status: Accepted

#11832 ZTS: pool_checkpoint improvements
  tests/zfs-tests/tests/functional/pool_checkpoint/checkpoint_big_rewind.ksh
  tests/zfs-tests/tests/functional/pool_checkpoint/checkpoint_capacity.ksh
  tests/zfs-tests/tests/functional/pool_checkpoint/checkpoint_discard_busy.ksh
  tests/zfs-tests/tests/functional/pool_checkpoint/pool_checkpoint.kshlib
Labels: Status: Accepted

#11843 libzutil: zfs_isnumber(): return false if input empty
  cmd/zpool/zpool_main.c
  lib/libzutil/zutil_nicenum.c
Labels: Component: Userspace, Status: Accepted

#11845 man: fix wrong .Xr macros usages
  man/man8/zfs-wait.8
  man/man8/zpool-create.8
  man/man8/zpool-get.8
  man/man8/zpool-import.8
  man/man8/zpool-list.8
  man/man8/zpool-replace.8
  man/man8/zpool-split.8
Labels: Status: Accepted

#11461 kmem_alloc(KM_SLEEP) should use kvmalloc()
  module/os/linux/spl/spl-kmem.c
Labels: Status: Accepted

#11837 zfs get -p only outputs 3 columns if "clones" property is empty
  lib/libzfs/libzfs_dataset.c
  tests/zfs-tests/tests/functional/cli_root/zfs_get/zfs_get_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_get/zfs_get_common.kshlib
Labels: Status: Accepted

#11847 Obsolete earlier packages due to version bump
  rpm/generic/zfs.spec.in
Labels: Status: Accepted

#11851 fix misplaced quotes in kmod-preamble
  rpm/redhat/zfs-kmod.spec.in
Labels: Status: Accepted

#11836 Add kmodtool fix to detect different System.map location
  scripts/kmodtool
Labels: Status: Accepted

#11786 Ratelimit deadman zevents as with delay zevents
  include/sys/vdev_impl.h
  man/man5/zfs-module-parameters.5
  module/zfs/vdev.c
  module/zfs/zfs_fm.c
  tests/runfiles/common.run
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/deadman/Makefile.am
  tests/zfs-tests/tests/functional/deadman/deadman_ratelimit.ksh
  tests/zfs-tests/tests/functional/deadman/deadman_sync.ksh
Labels: Status: Accepted

#11855 ZTS: Tests using zhack may fail on FreeBSD
  tests/test-runner/bin/zts-report.py.in
Labels: Component: Test Suite, Status: Accepted

#11852 Fix double sha1/sha1.o line in module/icp/Makefile.in
  module/icp/Makefile.in
Labels: Status: Accepted

#11849 Use dsl_scan_setup_check() to setup a scrub
  include/sys/dsl_scan.h
  module/zfs/dsl_scan.c
  module/zfs/vdev_rebuild.c
Labels: Status: Accepted

#11850 Added check for broken alien version
  config/deb.am
  config/zfs-build.m4
Labels: Status: Accepted

#11856 ZTS: Improve cleanup in removal_with_export
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/functional/removal/removal_with_export.ksh
Labels: Component: Test Suite, Status: Accepted

#11839 zpl_inode.c: Fix SMACK interoperability
  module/os/linux/zfs/zpl_inode.c
Labels: Status: Accepted

#11865 kmod-zfs should obsolete kmod-spl as well as spl-kmod
  rpm/redhat/zfs-kmod.spec.in
Labels: Component: Packaging, Status: Accepted

#11710 Allow zfs to send replication streams with missing snapshots
  cmd/zfs/zfs_main.c
  include/libzfs.h
  lib/libzfs/libzfs_sendrecv.c
  man/man8/zfs-send.8
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zfs_send/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_send/zfs_send_skip_missing.ksh
Labels: Status: Accepted

#11890 ZTS: Add known exceptions
  tests/test-runner/bin/zts-report.py.in
Labels: Status: Accepted

#11882 Balance parentheses in parameter descriptions
  module/zfs/spa.c
  module/zfs/spa_log_spacemap.c
Labels: Status: Accepted

#11869 ZTS: fix removal_condense_export test case
  man/man5/zfs-module-parameters.5
  module/zfs/vdev_indirect.c
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/functional/removal/removal_condense_export.ksh
Labels: Status: Accepted

#11861 Improvements to the 'compatibility' property.
  cmd/zpool/zpool_main.c
  include/libzfs.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_status.c
  man/man5/zpool-features.5
  man/man8/zpool-upgrade.8
Labels: Status: Accepted

#11873 libuutil: purge vestigia
  include/libuutil.h
  include/libuutil_impl.h
  lib/libuutil/Makefile.am
  lib/libuutil/libuutil.abi
  lib/libuutil/uu_dprintf.c
  lib/libuutil/uu_misc.c
  lib/libuutil/uu_open.c
Labels: Status: Accepted

#11862 cmd/zfs receive: allow dry-run (-n) to check more
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#11883 FreeBSD: add support for lockless symlink lookup
  include/os/freebsd/zfs/sys/zfs_znode_impl.h
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/freebsd/zfs/zfs_znode.c
Labels: Status: Accepted

#11884 FreeBSD: add missing seqc write begin/end around zfs_acl_chown_setattr
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#11881 FreeBSD: use vnlru_free_vfsops if available
  module/os/freebsd/zfs/arc_os.c
Labels: Status: Accepted

#11875 libzfs: zfs_mount_at(): load key for encryption root if MS_CRYPT
  lib/libzfs/libzfs_mount.c
Labels: Status: Accepted

#11895 Obsolete earlier packages due to version bump
  rpm/generic/zfs.spec.in
Labels: Component: Packaging, Status: Code Review Needed

#11899 Fix vdev health padding in zpool list -v
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#11902 Fix 'make checkbashisms` warnings
  Makefile.am
Labels: Status: Accepted

#11801 Add SIGSTOP and SIGTSTP handling to issig
  config/kernel-siginfo.m4
  config/kernel-signal-stop.m4
  config/kernel-special-state.m4
  config/kernel.m4
  include/os/linux/spl/sys/signal.h
  include/os/linux/spl/sys/thread.h
  module/os/linux/spl/spl-thread.c
Labels: Status: Accepted

#11803 ZFS traverse_visitbp optimization to limit prefetch.
  man/man5/zfs-module-parameters.5
  module/zfs/dmu_traverse.c
Labels: Status: Accepted

#11905 zfs-send(8): Restore sorting of flags
  man/man8/zfs-send.8
Labels: Status: Accepted, Type: Documentation

#11896 Crash reporting checksum error for gang block in zio_done
  module/zfs/zio.c
Labels: Status: Accepted

#11733 ICP: Add missing stack frame info to SHA asm files
  module/icp/asm-x86_64/sha1/sha1-x86_64.S
  module/icp/asm-x86_64/sha2/sha256_impl.S
  module/icp/asm-x86_64/sha2/sha512_impl.S
Labels: Status: Accepted

#11877 Combine zio caches if possible
  module/zfs/zio.c
Labels: Status: Accepted

#11914 ICP: Silence objtool "stack pointer realignment" warnings
  module/icp/Makefile.in
Labels: Status: Accepted

#11906 ZTS: Improve redundancy/* test scripts
  tests/zfs-tests/tests/functional/redundancy/redundancy.kshlib
  tests/zfs-tests/tests/functional/redundancy/redundancy_draid3.ksh
  tests/zfs-tests/tests/functional/redundancy/redundancy_stripe.ksh
Labels: Status: Accepted

#11904 libspl: implement atomics in terms of atomics
  cmd/zed/Makefile.am
  config/user-libatomic.m4
  config/user.m4
  lib/libspl/Makefile.am
  lib/libspl/asm-generic/.gitignore
  lib/libspl/asm-i386/atomic.S
  lib/libspl/asm-x86_64/atomic.S
  lib/libspl/atomic.c
Labels: Status: Accepted

#11915 etc/systemd/zfs-mount-generator: don't fail if no cached pools
  etc/systemd/system-generators/zfs-mount-generator.in
Labels: Status: Accepted

#11918 Fixed incorrect man page reference in zfsprops(8)
  man/man8/zfsprops.8
Labels: Status: Accepted

#11928 zed: protect against wait4()/fork() races to the launched process tree
  cmd/zed/zed_exec.c
Labels: Status: Accepted

#11938 Fix AVX512BW Fletcher code on AVX512-but-not-BW machines.
  module/zcommon/zfs_fletcher_avx512.c
Labels: Status: Accepted

#11926 FreeBSD: damage control racing .. lookups in face of mkdir/rmdir
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#11864 receive: don't fail inheriting (-x) properties on wrong dataset type
  lib/libzfs/libzfs_sendrecv.c
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/receive-o-x_props_override.ksh
Labels: Status: Code Review Needed

#11947 Drop "All rights reserved" from files by trasz@FreeBSD.org
  module/os/freebsd/spl/spl_acl.c
Labels: Status: Accepted

#11949 ZTS: Add known exceptions
  tests/test-runner/bin/zts-report.py.in
Labels: Component: Test Suite, Status: Accepted

#11932 zdb: ASSERT issues when DEBUG is not defined
  cmd/zdb/zdb.c
Labels: Status: Accepted

#11931 zfs.spec.in: remove post ldconfig scriptlets
  rpm/generic/zfs.spec.in
Labels: Component: Packaging, Status: Accepted

#11930 vdev_mirror: don't scrub/resilver devices that can't be read
  module/zfs/vdev_mirror.c
Labels: Status: Accepted

#11959 vdev_id: variable not getting expanded under map_slot()
  cmd/vdev_id/vdev_id
Labels: Status: Accepted

#11955 zfs get: don't lookup mount options when using "-s local"
  cmd/zfs/zfs_main.c
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_diff.c
  lib/libzfs/libzfs_mount.c
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#11940 zdb: dump_history can be improved
  cmd/zdb/zdb.c
Labels: Status: Accepted

#11973 FreeBSD: Prune some unneeded definitions
  include/os/freebsd/spl/sys/vnode.h
  module/os/freebsd/spl/spl_vfs.c
  module/os/freebsd/zfs/zfs_vfsops.c
Labels: Status: Accepted

#11970 ZTS: Fix xattr_002_neg passing too soon
  tests/zfs-tests/tests/functional/xattr/xattr_002_neg.ksh
Labels: Component: Test Suite, Status: Accepted

#11971 FreeBSD: Clean up ASSERT/VERIFY use in module
  module/os/freebsd/spl/acl_common.c
  module/os/freebsd/spl/callb.c
  module/os/freebsd/spl/list.c
  module/os/freebsd/spl/spl_kmem.c
  module/os/freebsd/spl/spl_kstat.c
  module/os/freebsd/spl/spl_string.c
  module/os/freebsd/spl/spl_sysevent.c
  module/os/freebsd/spl/spl_uio.c
  module/os/freebsd/spl/spl_vfs.c
  module/os/freebsd/zfs/abd_os.c
  module/os/freebsd/zfs/dmu_os.c
  module/os/freebsd/zfs/spa_os.c
  module/os/freebsd/zfs/vdev_file.c
  module/os/freebsd/zfs/vdev_geom.c
  module/os/freebsd/zfs/vdev_label_os.c
  module/os/freebsd/zfs/zfs_acl.c
  module/os/freebsd/zfs/zfs_ctldir.c
  module/os/freebsd/zfs/zfs_dir.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/freebsd/zfs/zfs_znode.c
  module/os/freebsd/zfs/zio_crypt.c
  module/os/freebsd/zfs/zvol_os.c
Labels: Status: Code Review Needed

#11974 Miscellaneous code cleanup
  module/os/freebsd/zfs/zfs_znode.c
  module/os/linux/zfs/zfs_znode.c
  module/os/linux/zfs/zpl_xattr.c
Labels: Status: Accepted
