Repository openzfs/zfs, pull requests merged in 2021-06, with the labels that each got.

#12155 Remove iov_iter_advance() for iter_write
  module/os/linux/zfs/zpl_file.c
Labels: Status: Accepted

#12104 Reminder to update boot code after zpool upgrade
  cmd/zpool/os/freebsd/zpool_vdev_os.c
  cmd/zpool/os/linux/zpool_vdev_os.c
  cmd/zpool/zpool_main.c
  cmd/zpool/zpool_util.h
Labels: Component: Userspace, Status: Accepted

#12137 libzfs_core: Fix some style violations
  lib/libzfs_core/libzfs_core.c
Labels: Status: Accepted

#12160 Added another missed case to arc_summary3
  cmd/arc_summary/arc_summary3
Labels: Status: Accepted

#12165 Quick fixes for two ZTS failures
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_checksum.ksh
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_objset_id.ksh
Labels: Status: Accepted

#12156 A couple of small style cleanups.
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#12050 libspl: staticify buf and pagesize, rename aok to libspl_assert_ok
  cmd/zdb/zdb.c
  include/sys/zfs_context.h
  lib/libnvpair/libnvpair.abi
  lib/libspl/assert.c
  lib/libspl/include/assert.h
  lib/libspl/os/linux/getmntany.c
  lib/libspl/page.c
  lib/libuutil/libuutil.abi
  lib/libzfs_core/libzfs_core.abi
Labels: Status: Code Review Needed

#12152 Linux: Set spl_kmem_cache_slab_limit when page size !4K
  module/os/linux/spl/spl-kmem-cache.c
Labels: Status: Accepted, Type: Architecture

#12176 Fix error check in nvlist_print_json_string
  lib/libnvpair/libnvpair_json.c
Labels: Status: Accepted

#12052 FreeBSD: incorporate changes to the VFS_QUOTACTL(9) KPI
  module/os/freebsd/zfs/zfs_vfsops.c
Labels: Status: Accepted

#12072 Let zfs diff be more permissive.
  lib/libzfs/libzfs_diff.c
Labels: Status: Accepted

#12197 libzfs: write_inuse_diffs_one: format strerror() with "%s"
  lib/libzfs/libzfs_diff.c
Labels: Status: Accepted

#12145 More aggsum optimizations.
  include/os/linux/spl/sys/atomic.h
  include/sys/aggsum.h
  lib/libspl/atomic.c
  lib/libspl/include/atomic.h
  module/zfs/aggsum.c
Labels: Status: Accepted

#12177 Livelist logic should handle dedup blkptrs
  cmd/zdb/zdb.c
  module/zfs/dsl_deadlist.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_clone_livelist_dedup.ksh
Labels: Status: Accepted

#12185 Force --enable-debug on FreeBSD if INVARIANTS is set
  config/zfs-build.m4
Labels: Status: Accepted, Type: Building

#12169 Modernise and lint remaining manpages
  man/man5/spl-module-parameters.5
  man/man5/zfs-module-parameters.5
  man/man5/zpool-features.5
  man/man8/zfs-mount-generator.8.in
  man/man8/zfs-wait.8
  man/man8/zpool-destroy.8
  man/man8/zpool-export.8
  man/man8/zpool-history.8
  man/man8/zpool-labelclear.8
  man/man8/zpool-reguid.8
  scripts/mancheck.sh
Labels: Status: Accepted

#12091 libzfs: On FreeBSD, use MNT_NOWAIT with getfsstat
  include/sys/zfs_ioctl_impl.h
  lib/libspl/os/freebsd/mnttab.c
  module/os/freebsd/zfs/zfs_ioctl_os.c
  module/os/linux/zfs/zfs_ioctl_os.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#12073 Correct a flaw in the Python 3 version checking
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  .github/workflows/zloop.yml
  config/always-pyzfs.m4
  config/ax_python_devel.m4
  rpm/generic/zfs.spec.in
Labels: Status: Code Review Needed

#12208 Fix minor shellcheck 0.7.2 warnings
  cmd/zed/zed.d/all-syslog.sh
  scripts/make_gitrev.sh
  scripts/man-dates.sh
Labels: Status: Accepted

#11991 Added error for writing to /dev/ on Linux.
  cmd/zfs/zfs_main.c
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#12212 Remove pool io kstats
  include/os/freebsd/spl/sys/kstat.h
  include/os/linux/spl/sys/kstat.h
  include/sys/spa.h
  include/sys/zfs_context.h
  lib/libspl/include/sys/kstat.h
  lib/libzpool/kernel.c
  module/os/freebsd/spl/spl_kstat.c
  module/os/linux/spl/spl-kstat.c
  module/zfs/spa_stats.c
  module/zfs/vdev_queue.c
Labels: Status: Accepted

#12195 dracut: 90zfs: respect zfs_force=1 on systemd systems
  contrib/dracut/90zfs/.gitignore
  contrib/dracut/90zfs/Makefile.am
  contrib/dracut/90zfs/import-opts-generator.sh.in
  contrib/dracut/90zfs/module-setup.sh.in
  etc/systemd/system/zfs-import-cache.service.in
  etc/systemd/system/zfs-import-scan.service.in
Labels: Status: Accepted

#12158 Re-embed multilist_t storage.
  include/sys/arc_impl.h
  include/sys/dmu_objset.h
  include/sys/metaslab_impl.h
  include/sys/multilist.h
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu_objset.c
  module/zfs/dnode.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_pool.c
  module/zfs/metaslab.c
  module/zfs/multilist.c
Labels: Status: Accepted

#12224 ZTS: Add zfs_clone_livelist_dedup.ksh to Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_destroy/Makefile.am
Labels: Status: Code Review Needed

#12173 Added uncompress+file checks
  rpm/generic/zfs-dkms.spec.in
  rpm/generic/zfs-kmod.spec.in
  rpm/generic/zfs.spec.in
Labels: Status: Accepted

#12210 Do not hash unlinked inodes in zfs_znode_alloc
  module/os/linux/zfs/zfs_znode.c
Labels: Status: Accepted

#12221 vdev_draid_min_asize() ignores reserved space
  module/zfs/vdev_draid.c
Labels: Status: Accepted

#12231 systemd: import: expand $ZPOOL_IMPORT_OPTS correctly
  etc/systemd/system/zfs-import-cache.service.in
  etc/systemd/system/zfs-import-scan.service.in
Labels: Status: Accepted

#12238 Fix importing with symlinks
  lib/libzutil/zutil_import.c
Labels: Status: Accepted

#12054 Avoid deadlock when removing L2ARC devices under I/O
  module/zfs/arc.c
  module/zfs/zio.c
Labels: Status: Accepted

#12172 Use wmsum for arc, abd, dbuf and zfetch statistics.
  include/sys/abd_impl.h
  include/sys/arc_impl.h
  module/os/freebsd/zfs/abd_os.c
  module/os/linux/zfs/abd_os.c
  module/os/linux/zfs/arc_os.c
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu_zfetch.c
Labels: Status: Accepted

#12183 Optimize spa_get_random().
  include/os/freebsd/spl/sys/random.h
  include/os/linux/spl/sys/random.h
  include/sys/spa.h
  include/sys/zfs_context.h
  module/os/linux/zfs/arc_os.c
  module/zfs/metaslab.c
  module/zfs/mmp.c
  module/zfs/multilist.c
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/space_map.c
  module/zfs/vdev_indirect.c
  module/zfs/vdev_mirror.c
  module/zfs/zil.c
  module/zfs/zio_compress.c
  module/zfs/zio_inject.c
Labels: Status: Accepted

#12227 RFC/WIP: Revert Consolidate arc_buf allocation checks
  module/zfs/dbuf.c
Labels: Status: Accepted

#12233 A cleaner, noisier dprintf
  cmd/ztest/ztest.c
  include/sys/zfs_debug.h
  lib/libzpool/kernel.c
  module/os/freebsd/zfs/zfs_debug.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/linux/zfs/zfs_debug.c
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/dmu_tx.c
  module/zfs/dnode.c
  module/zfs/dnode_sync.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_destroy.c
  module/zfs/dsl_dir.c
  module/zfs/metaslab.c
  module/zfs/mmp.c
  module/zfs/range_tree.c
  module/zfs/sa.c
  module/zfs/spa.c
  module/zfs/spa_checkpoint.c
  module/zfs/spa_history.c
  module/zfs/spa_misc.c
  module/zfs/space_map.c
  module/zfs/txg.c
  module/zfs/vdev.c
  module/zfs/vdev_indirect.c
  module/zfs/vdev_removal.c
  module/zfs/zap.c
  module/zfs/zap_micro.c
  module/zfs/zcp.c
  module/zfs/zil.c
  module/zfs/zio.c
Labels: Status: Accepted

#12272 ZTS: Add known exceptions
  tests/test-runner/bin/zts-report.py.in
Labels: Status: Accepted

#12237 gcc 11 cleanup
  contrib/pam_zfs_key/pam_zfs_key.c
  include/sys/crypto/api.h
  include/sys/dnode.h
  module/os/linux/zfs/zio_crypt.c
Labels: Status: Accepted

#12251 Update libera webchat client URL
  .github/ISSUE_TEMPLATE/config.yml
Labels: Status: Accepted

#12277 Stop using "zstreamdump" in tests/
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/functional/redacted_send/redacted_embedded.ksh
  tests/zfs-tests/tests/functional/rsend/rsend.kshlib
  tests/zfs-tests/tests/functional/rsend/send-c_embedded_blocks.ksh
  tests/zfs-tests/tests/functional/rsend/send-c_zstreamdump.ksh
  tests/zfs-tests/tests/functional/rsend/send-cpL_varied_recsize.ksh
Labels: Status: Accepted

#12273 zfs_metaslab_mem_limit should be 25 instead of 75
  module/zfs/metaslab.c
Labels: Status: Accepted

#12266 Fix flag copying in resume case
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#12276 Update cache file when setting compatibility property
  module/zfs/spa.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zpool_create/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_features_009_pos.ksh
Labels: Status: Accepted

#12282 FreeBSD: fix compilation of FreeBSD world after 29274c9f6
  include/os/freebsd/spl/sys/random.h
  include/os/linux/spl/sys/random.h
  include/sys/zfs_context.h
Labels: Status: Accepted

#12280 Help compiller optimize out abd_verify().
  module/zfs/abd.c
Labels: Status: Accepted

#12232 Fix build with KASAN
  module/zstd/zfs_zstd.c
Labels: Status: Accepted

#12147 Fix plymouth passphrase prompt with dracut
  contrib/dracut/90zfs/zfs-lib.sh.in
Labels: Status: Code Review Needed

#12288 Avoid 64bit division in multilist index functions.
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu_objset.c
  module/zfs/metaslab.c
Labels: Status: Accepted

#12253 module/zfs: simplify ddt_stat_add() loop and fix LLVM's Polly build error
  module/zfs/ddt.c
Labels: Status: Accepted

#12292 zed: fix sending emails
  cmd/zed/zed.d/zed-functions.sh
Labels: Status: Accepted

#12217 ZED: Match added disk by pool/vdev GUID if found
  cmd/zed/agents/zfs_mod.c
  cmd/zed/zed_disk_event.c
  tests/runfiles/linux.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/functional/fault/Makefile.am
  tests/zfs-tests/tests/functional/fault/auto_online_002_pos.ksh
Labels: Component: ZED, Status: Accepted
