Repository openzfs/zfs, pull requests merged in 2021-10, with the labels that each got.

#12583 ZTS: Eliminate udev_wait in zvol_misc tests
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/include/blkdev.shlib
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_common.kshlib
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_rename_inuse.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_snapdev.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_volmode.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_zil.ksh
Labels: Component: Test Suite, Status: Accepted

#12577 Proper support for DESTDIR and INSTALL_MOD_PATH
  module/Makefile.in
Labels: Status: Accepted

#12598 ZFS: Remove a redundant if condition
  module/zfs/dmu.c
Labels: Status: Accepted

#12575 Reject zfs send -RI with nonexistent fromsnap
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#12095 Rescan enclosure sysfs path on import
  cmd/zpool/Makefile.am
  cmd/zpool/zpool_iter.c
  cmd/zpool/zpool_main.c
  cmd/zpool/zpool_util.h
  include/libzutil.h
  lib/libzutil/os/freebsd/zutil_import_os.c
  lib/libzutil/os/linux/zutil_import_os.c
  lib/libzutil/zutil_import.c
  module/zfs/vdev.c
Labels: Status: Accepted

#12570 Document additional -c caveat.
  man/man8/zfs-send.8
Labels: Type: Documentation, Status: Accepted

#12699 vdev_id: Fix PHY sorting
  cmd/vdev_id/vdev_id
Labels: Status: Accepted

#12692 Set DEFAULT_INIT_SHELL to /sbin/openrc-run for Gentoo and Alpine
  config/zfs-build.m4
Labels: Status: Accepted

#12673 Python 3.10 edge case
  config/ax_python_devel.m4
Labels: Status: Accepted

#12609 Normalize property names for zfs receive
  lib/libzfs/libzfs_sendrecv.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/receive-o-x_props_aliases.ksh
Labels: Status: Accepted

#12680 Add explicit error for device_rebuild being disabled
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#12690 Do not print UINT64_MAX value for some of zfs properties
  lib/libzfs/libzfs_dataset.c
  tests/zfs-tests/tests/functional/cli_root/zfs_get/zfs_get_001_pos.ksh
Labels: Status: Accepted

#12579 zfsprops.7: Add note about comma-separation
  man/man7/zfsprops.7
Labels: Type: Documentation, Status: Accepted

#12038 Disable normalization implicitly when setting "utf8only=off".
  lib/libzfs/libzfs_dataset.c
  tests/zfs-tests/tests/functional/casenorm/norm_all_values.ksh
Labels: Status: Accepted
