Repository openzfs/zfs, pull requests merged in 2021-01, with the labels that each got.

#11417 zfs_mount_all_mountpoints.ksh: cleanup_all should leave pool root mounted
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_all_mountpoints.ksh
Labels: Status: Accepted

#11419 Autoconf 2.70 compatibility
  config/always-python.m4
  config/always-pyzfs.m4
  config/kernel.m4
  config/mount-helper.m4
  config/user-dracut.m4
  config/user-libexec.m4
  config/user-makedev.m4
  config/user-systemd.m4
  config/user-sysvinit.m4
  config/user-udev.m4
  config/zfs-build.m4
  configure.ac
Labels: Status: Accepted

#11437 FreeBSD: minor_t needs to be signed so that -1 is recognized as such
  include/os/freebsd/spl/sys/types.h
Labels: Status: Accepted

#11397 assertion failed in arc_wait_for_eviction()
  module/zfs/arc.c
Labels: Status: Accepted

#11440 record ioctl elapsed time in zpool history
  cmd/zpool/zpool_main.c
  include/sys/fs/zfs.h
  module/zfs/spa_history.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#11441 ztest: Use fnvlist_* instead of VERIFYing nvlist_*
  cmd/ztest/ztest.c
Labels: Status: Accepted

#11456 copy-builtin: handle missing .gitignore
  copy-builtin
Labels: Status: Accepted

#11451 ZTS: avoid race to unmount in zfs_rollback_001
  tests/zfs-tests/tests/functional/cli_root/zfs_rollback/zfs_rollback_001_pos.ksh
Labels: Status: Accepted

#11454 ztest: Clean up use of ASSERT and VERIFY
  cmd/ztest/ztest.c
Labels: Status: Accepted

#11460 libzfs_sendrecv: Use fnv* to verify nvlist/nvpair*
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#11478 zts: avoid piping to special devices
  contrib/pyzfs/libzfs_core/test/test_libzfs_core.py
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_005_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_send/zfs_send-b.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_send/zfs_send_003_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_send/zfs_send_004_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_send/zfs_send_005_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_send/zfs_send_encrypted.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_send/zfs_send_encrypted_unloaded.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_send/zfs_send_raw.ksh
  tests/zfs-tests/tests/functional/redacted_send/redacted_negative.ksh
  tests/zfs-tests/tests/functional/redacted_send/redacted_resume.ksh
  tests/zfs-tests/tests/functional/removal/removal_with_send.ksh
  tests/zfs-tests/tests/functional/rsend/send_invalid.ksh
  tests/zfs-tests/tests/functional/rsend/send_partial_dataset.ksh
Labels: Status: Accepted

#11462 Re-apply path sanitizer, as mount(8) still mangles it.
  cmd/mount_zfs/mount_zfs.c
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_013_pos.ksh
Labels: Status: Accepted

#11439 allow callers to allocate and provide the abd_t struct
  cmd/raidz_test/raidz_test.c
  include/sys/abd.h
  include/sys/abd_impl.h
  include/sys/vdev_raidz_impl.h
  module/os/freebsd/zfs/abd_os.c
  module/os/linux/zfs/abd_os.c
  module/zfs/abd.c
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/vdev_draid.c
  module/zfs/vdev_indirect.c
  module/zfs/vdev_queue.c
  module/zfs/vdev_raidz.c
  module/zfs/zil.c
  module/zfs/zio.c
Labels: Status: Accepted

#11438 Extending FreeBSD UIO Struct
  include/os/freebsd/spl/sys/uio.h
  include/os/freebsd/zfs/sys/freebsd_crypto.h
  include/os/freebsd/zfs/sys/zfs_znode_impl.h
  include/os/linux/spl/sys/uio.h
  include/os/linux/zfs/sys/zfs_vnops_os.h
  include/os/linux/zfs/sys/zfs_znode_impl.h
  include/sys/crypto/common.h
  include/sys/dmu.h
  include/sys/sa.h
  include/sys/uio_impl.h
  include/sys/zfs_sa.h
  include/sys/zfs_vnops.h
  lib/libspl/include/sys/uio.h
  module/icp/algs/modes/modes.c
  module/icp/core/kcf_prov_lib.c
  module/icp/io/sha1_mod.c
  module/icp/io/sha2_mod.c
  module/icp/io/skein_mod.c
  module/os/freebsd/spl/spl_uio.c
  module/os/freebsd/zfs/crypto_os.c
  module/os/freebsd/zfs/zfs_ctldir.c
  module/os/freebsd/zfs/zfs_file_os.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/freebsd/zfs/zio_crypt.c
  module/os/freebsd/zfs/zvol_os.c
  module/os/linux/zfs/zfs_uio.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zio_crypt.c
  module/os/linux/zfs/zpl_file.c
  module/os/linux/zfs/zpl_inode.c
  module/os/linux/zfs/zpl_xattr.c
  module/os/linux/zfs/zvol_os.c
  module/zfs/dmu.c
  module/zfs/sa.c
  module/zfs/zfs_sa.c
  module/zfs/zfs_vnops.c
  tests/zfs-tests/cmd/mmapwrite/mmapwrite.c
Labels: Status: Accepted

#11484 Linux 5.10 compat: restore custom uio_prefaultpages()
  module/os/linux/zfs/zfs_uio.c
Labels: Status: Accepted

#11469 zpool: speed up importing large pools
  lib/libzfs/libzfs_import.c
Labels: Status: Accepted

#11485 Install zgenhostid to sbindir
  cmd/zgenhostid/Makefile.am
  contrib/dracut/90zfs/module-setup.sh.in
  rpm/generic/zfs.spec.in
Labels: Status: Accepted

#11487 dracut: Support /usr/bin as 'systemctl' path
  contrib/dracut/90zfs/zfs-env-bootfs.service.in
  contrib/dracut/90zfs/zfs-load-key.sh.in
Labels: Status: Accepted

#11389 Set aside a metaslab for ZIL blocks
  cmd/zdb/zdb.c
  include/sys/dmu.h
  include/sys/spa.h
  include/sys/spa_impl.h
  include/sys/vdev.h
  include/sys/vdev_impl.h
  include/sys/zfs_debug.h
  man/man5/zfs-module-parameters.5
  module/zfs/metaslab.c
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/vdev.c
  module/zfs/vdev_removal.c
  module/zfs/zio.c
Labels: Status: Accepted, Type: Performance

#11492 Only add supported features during pool creation
  cmd/zpool/zpool_main.c
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#11493 Linux 5.10 compat: restore custom uio_prefaultpages()
  module/os/linux/zfs/zfs_uio.c
Labels: Status: Code Review Needed

#11497 Add basic io_uring test
  tests/runfiles/linux.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/functional/io/Makefile.am
  tests/zfs-tests/tests/functional/io/io_uring.ksh
Labels: Status: Accepted

#11501 Relax special_small_blocks assertion.
  module/zfs/dmu_objset.c
Labels: Status: Accepted

#11507 Fix two minor lint errors (cppcheck).
  module/zfs/abd.c
  module/zfs/arc.c
Labels: Status: Accepted

#11498 vdev_id: Add error message when $CONFIG is missing
  cmd/vdev_id/vdev_id
Labels: Status: Accepted

#11503 ZTS: Use swapctl to list swap devices on FreeBSD
  tests/zfs-tests/tests/functional/zvol/zvol_swap/zvol_swap.cfg
Labels: Component: Test Suite, Status: Accepted

#11509 zfsprops.8: fix mispluralisation in "Default values is"
  man/man8/zfsprops.8
Labels: Status: Accepted, Type: Documentation

#11502 Speed up "zpool import" on FreeBSD in the presence of many zvols
  lib/libzutil/os/freebsd/zutil_import_os.c
Labels: Component: Userspace, Status: Accepted

#11512 spl-taskq: Make sure thread tsd hash entry is cleared
  module/os/linux/spl/spl-taskq.c
Labels: Status: Accepted

#11516 zfs_receive: remove duplicate check_prop_source
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_014_pos.ksh
Labels: Status: Accepted

#11514 spa_export_common: refactor common exit points
  module/zfs/spa.c
Labels: Status: Accepted

#11500 dracut: Fix race condition between load-key and import
  contrib/dracut/90zfs/zfs-generator.sh.in
Labels: Component: Dracut, Status: Accepted

#11489 RAIDZ2/3 fails to heal silently corrupted parity w/2+ bad disks
  module/zfs/vdev_raidz.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/redundancy/Makefile.am
  tests/zfs-tests/tests/functional/redundancy/redundancy_raidz.ksh
Labels: Status: Accepted

#11529 [skip ci] Fix a man page link in zfs-program.8
  man/man8/zfs-program.8
Labels: Status: Accepted

#11528 Fix a resource leak in uu_avl_pool_destroy:
  lib/libuutil/uu_avl.c
Labels: Component: Userspace, Status: Accepted

#11534 pool_state test: check for pool existence in cleanup
  tests/zfs-tests/tests/functional/procfs/pool_state.ksh
Labels: Status: Accepted

#11530 Fix zrele race in zrele_async that can cause hang
  module/os/linux/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#11464 Revert special case code from pre-hashtable nvlist era
  module/zfs/dsl_dataset.c
  module/zfs/dsl_destroy.c
Labels: Status: Accepted

#11027 Add zdb -r <dataset> <object-id | file> <output>
  cmd/zdb/zdb.c
  man/man8/zdb.8
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zdb/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_recover.ksh
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_recover_2.ksh
Labels: Status: Accepted

#11539 Removing ABD Parent Child Reference Before Freeing ABD
  module/zfs/abd.c
Labels: Status: Accepted

#11537 Avoid updating the L2ARC device header unnecessarily
  module/zfs/arc.c
Labels: Status: Accepted

#11536 fix abd_nr_pages_off for gang abd
  module/os/linux/zfs/abd_os.c
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#11541 userspace_send_encrypted.ksh: add to Makefile
  tests/zfs-tests/tests/functional/userquota/Makefile.am
Labels: Status: Accepted

#11542 Fixing Gang ABD When Adding Another Gang
  module/zfs/abd.c
Labels: Status: Accepted

#11355 Added extra check to replace Faulted VDEV with Distributed Spare.
  cmd/zed/agents/zfs_retire.c
Labels: Status: Accepted

#11535 The abd child/parent relationship does not need to be tracked
  include/sys/abd.h
  module/zfs/abd.c
Labels: Status: Accepted

#11543 Remove unused iov_iter_init_compat() wrapper
  config/kernel-vfs-iov_iter.m4
  include/os/linux/spl/sys/uio.h
Labels: Status: Accepted
