Repository openzfs/zfs, pull requests merged in 2021-07, with the labels that each got.

#12287 Remove refcount from spa_config_*().
  include/sys/spa_impl.h
  module/zfs/spa_misc.c
Labels: Status: Accepted

#12274 Optimize txg_kick() process
  include/sys/txg.h
  module/zfs/dsl_pool.c
  module/zfs/txg.c
Labels: Status: Accepted

#12294 dmu_zfetch_stream_fini leaks refcount
  module/zfs/dmu_zfetch.c
Labels: Status: Accepted

#12295 Fix abd leak, kmem_free correct size of abd_t
  include/sys/abd_impl.h
  module/os/freebsd/zfs/abd_os.c
  module/os/linux/zfs/abd_os.c
  module/zfs/abd.c
Labels: Status: Accepted

#12289 Compact dbuf/buf hashes and lock arrays.
  include/sys/dbuf.h
  module/zfs/arc.c
  module/zfs/dbuf.c
Labels: Status: Accepted

#12290 Remove avl_size field from struct avl_tree.
  include/sys/avl_impl.h
  module/avl/avl.c
Labels: Status: Accepted

#12303 Remove "compatibility" zvol symlinks (the /dev/dataset_name ones, as opposed to the /dev/zvol/dataset_name ones)
  udev/rules.d/60-zvol.rules.in
Labels: Status: Accepted

#12281 Move gethrtime() calls out of vdev queue lock.
  module/zfs/vdev_queue.c
Labels: Status: Accepted

#12328 FreeBSD: Hardcode abd_chunk_size to PAGE_SIZE.
  include/sys/abd.h
  module/os/freebsd/zfs/abd_os.c
Labels: Status: Accepted, Type: Performance

#12320 FreeBSD: Use unmapped I/O for scattered/gang ABD buffers.
  module/os/freebsd/zfs/vdev_geom.c
Labels: Status: Accepted, Type: Performance

#12312 strchrnul -> strrchr
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#12311 dprintf_dnode: strcpy -> strlcpy
  include/sys/dbuf.h
  include/sys/dnode.h
Labels: Status: Accepted

#12299 file reference counts can get corrupted
  include/sys/fm/util.h
  include/sys/zfs_file.h
  include/sys/zfs_ioctl.h
  include/sys/zfs_onexit.h
  lib/libzpool/kernel.c
  module/os/freebsd/zfs/zfs_file_os.c
  module/os/linux/zfs/zfs_file_os.c
  module/zfs/fm.c
  module/zfs/zfs_ioctl.c
  module/zfs/zfs_onexit.c
Labels: Status: Accepted

#12340 Update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Status: Code Review Needed, Type: Documentation

#12279 Fix ARC ghost states eviction accounting.
  include/sys/arc_impl.h
  man/man4/zfs.4
  module/os/freebsd/zfs/arc_os.c
  module/zfs/arc.c
Labels: Status: Accepted

#12359 config/libatomic: require -latomic iff atomic.c doesn't link without it
  config/user-libatomic.m4
Labels: Status: Accepted

#12296 pass handle to do_unmount()
  lib/libzfs/libzfs_impl.h
  lib/libzfs/libzfs_mount.c
  lib/libzfs/os/freebsd/libzfs_zmount.c
  lib/libzfs/os/linux/libzfs_mount_os.c
Labels: Status: Code Review Needed

#12300 Introduce dsl_dir_diduse_transfer_space().
  include/sys/dsl_dir.h
  module/zfs/dsl_dataset.c
  module/zfs/dsl_dir.c
Labels: Status: Accepted, Type: Performance

#12336 Correct zfs-send(8) on readonly sends
  cmd/zfs/zfs_main.c
  man/man8/zfs-send.8
Labels: Status: Accepted

#12344 zpool_influxdb: fix -Werror=stringop-truncation
  cmd/zpool_influxdb/zpool_influxdb.c
Labels: Status: Accepted

#12350 Detect HAVE_LARGE_STACKS at compile time
  config/Rules.am
  config/kernel-config-defined.m4
  include/os/freebsd/zfs/sys/zfs_context_os.h
  include/os/linux/zfs/sys/zfs_context_os.h
  lib/libspl/include/os/freebsd/sys/zfs_context_os.h
  lib/libspl/include/os/linux/sys/zfs_context_os.h
Labels: Status: Accepted

#12378 FreeBSD: Switch from MAXPHYS to maxphys on FreeBSD 13+.
  module/os/freebsd/zfs/vdev_geom.c
Labels: Status: Accepted

#12361 Remove unused fields from zvol_task_t
  module/zfs/zvol.c
Labels: Status: Accepted

#12356 Use SET_ERROR for more errors in FreeBSD vnops
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#12118 dmu_redact.c does not call bqueue_destroy
  module/zfs/dmu_redact.c
Labels: Status: Accepted

#12348 Couple minor ARC optimizations.
  include/sys/arc.h
  include/sys/arc_impl.h
  module/zfs/arc.c
Labels: Status: Accepted, Type: Performance

#12284 Add Module Parameter Regarding Log Size Limit
  include/sys/dmu_tx.h
  include/sys/dsl_pool.h
  man/man4/zfs.4
  module/zfs/arc.c
  module/zfs/dmu_tx.c
  module/zfs/dsl_pool.c
  module/zfs/zfs_log.c
  module/zfs/zvol.c
Labels: Status: Accepted

#12314 Optimize allocation throttling.
  include/sys/metaslab_impl.h
  include/sys/spa_impl.h
  module/zfs/metaslab.c
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/zio.c
Labels: Status: Accepted, Type: Performance

#12404 Remove old orig_fd variable from zfs send
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#12375 FreeBSD: Ignore make_dev_s() errors.
  module/os/freebsd/zfs/zvol_os.c
Labels: Status: Accepted

#12411 zloop: Add a max iterations option
  .github/workflows/zloop.yml
  scripts/zloop.sh
Labels: Status: Accepted

#12409 Linux 5.14 compat: blk_alloc_disk()
  config/kernel-make-request-fn.m4
  module/os/linux/zfs/zvol_os.c
Labels: Status: Accepted

#12428 Fix unfortunate NULL in spa_update_dspace
  module/zfs/spa_misc.c
Labels: Status: Accepted

#12427 5.14 compat: explicity assign set_page_dirty
  config/kernel-vfs-set_page_dirty.m4
  config/kernel.m4
  module/os/linux/zfs/zpl_file.c
Labels: Status: Accepted

#12365 Fixes in persistent L2ARC
  module/zfs/arc.c
  tests/runfiles/common.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/functional/l2arc/Makefile.am
  tests/zfs-tests/tests/functional/l2arc/l2arc_arcstats_pos.ksh
  tests/zfs-tests/tests/functional/l2arc/persist_l2arc_004_pos.ksh
  tests/zfs-tests/tests/functional/l2arc/persist_l2arc_005_pos.ksh
  tests/zfs-tests/tests/functional/l2arc/persist_l2arc_006_pos.ksh
  tests/zfs-tests/tests/functional/l2arc/persist_l2arc_007_pos.ksh
  tests/zfs-tests/tests/functional/l2arc/persist_l2arc_008_pos.ksh
Labels: Status: Code Review Needed

#12339 read past end of argv array in zpool_do_import()
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#12408 Assorted fixes for the performance tests
  scripts/zfs-tests.sh
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/perf/perf.shlib
  tests/zfs-tests/tests/perf/regression/random_reads.ksh
  tests/zfs-tests/tests/perf/regression/random_readwrite.ksh
  tests/zfs-tests/tests/perf/regression/random_readwrite_fixed.ksh
  tests/zfs-tests/tests/perf/regression/random_writes.ksh
  tests/zfs-tests/tests/perf/regression/random_writes_zil.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads_arc_cached.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads_arc_cached_clone.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads_dbuf_cached.ksh
  tests/zfs-tests/tests/perf/regression/sequential_writes.ksh
  tests/zfs-tests/tests/perf/regression/setup.ksh
Labels: Component: Test Suite, Status: Accepted, Type: Performance

#12419 Add comment on metaslab_class_throttle_reserve() locking.
  module/zfs/metaslab.c
Labels: Status: Code Review Needed

#12385 Move check_file to os/$platform section
  cmd/zpool/os/freebsd/zpool_vdev_os.c
  cmd/zpool/os/linux/zpool_vdev_os.c
  cmd/zpool/zpool_util.h
  cmd/zpool/zpool_vdev.c
Labels: Status: Accepted

#12357 macOS can also set va_type
  module/zfs/zfs_replay.c
Labels: Status: Accepted

#12425 Avoid small buffer copying on write.
  include/sys/abd.h
  include/sys/abd_impl.h
  module/os/freebsd/zfs/abd_os.c
  module/os/linux/zfs/abd_os.c
  module/zfs/abd.c
  module/zfs/arc.c
Labels: Status: Accepted
