Repository openzfs/zfs, pull requests merged in 2021-09, with the labels that each got.

#12527 ZTS: Remove exceptions for flaky zhack on FreeBSD
  tests/test-runner/bin/zts-report.py.in
Labels: Component: Test Suite, Status: Accepted

#12437 autoconf: allow Release to contain hyphen
  config/zfs-meta.m4
Labels: Status: Accepted

#12206 Detect iSCSI in the zpool cmd vdev media script
  cmd/zpool/zpool.d/media
Labels: Status: Accepted

#12532 Linux 5.15 compat: block device readahead
  config/kernel-blk-queue.m4
  include/os/linux/kernel/linux/blkdev_compat.h
Labels: Type: Building, Status: Accepted

#12531 Linux 5.15 compat: standalone <linux/stdarg.h>
  config/kernel-stdarg.m4
  config/kernel.m4
  include/os/linux/spl/sys/cmn_err.h
Labels: Type: Building, Status: Accepted

#12522 Compressed receive with different ashift can result in incorrect PSIZE on disk (#8462)
  module/zfs/zio.c
Labels: Status: Accepted

#12530 zdb inode mapping for macOS
  cmd/zdb/zdb.c
Labels: Status: Accepted

#12246 arc: Drop an incorrect assert
  module/zfs/arc.c
Labels: Status: Accepted

#12541 Allow sending corrupt snapshots even if metadata is corrupted
  module/zfs/dmu_send.c
Labels: Status: Accepted

#12548 Linux 5.15 compat: get_acl()
  config/kernel-acl.m4
  include/os/linux/zfs/sys/zpl.h
  module/os/linux/zfs/zpl_xattr.c
Labels: Type: Building, Status: Accepted

#12416 Add events to zed and minor tweaks.
  cmd/zed/agents/zfs_retire.c
  cmd/zed/zed.c
  cmd/zed/zed_conf.c
  cmd/zed/zed_exec.c
  include/sys/fm/fs/zfs.h
  include/sys/spa.h
  include/sys/zio.h
  module/zfs/zfs_fm.c
Labels: Status: Accepted

#12535 Verify embedded blkptr's in arc_read()
  module/zfs/arc.c
  module/zfs/zio.c
Labels: Status: Accepted

#12553 ZTS: Waiting for zvols to be available
  tests/zfs-tests/tests/functional/cli_root/zfs_copies/zfs_copies.kshlib
  tests/zfs-tests/tests/functional/cli_root/zfs_rename/zfs_rename_006_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import_errata3.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_volmode.ksh
Labels: Component: Test Suite, Status: Accepted

#12443 Fixed data integrity issue when underlying disk returns error to zfs
  module/zfs/zil.c
Labels: Status: Accepted

#12471 Iterate encrypted clones at zvol_create_minor
  module/zfs/zvol.c
Labels: Component: ZVOL, Status: Accepted

#12441 Use fallthrough macro
  cmd/mount_zfs/mount_zfs.c
  cmd/zdb/zdb.c
  cmd/zfs/zfs_main.c
  cmd/zpool_influxdb/zpool_influxdb.c
  config/Rules.am
  config/always-compiler-options.m4
  config/zfs-build.m4
  include/os/freebsd/linux/compiler.h
  include/os/linux/kernel/linux/compiler_compat.h
  include/os/linux/zfs/sys/zfs_context_os.h
  include/sys/zfs_context.h
  lib/libspl/include/sys/feature_tests.h
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs/libzfs_util.c
  lib/libzfsbootenv/lzbe_device.c
  lib/libzutil/zutil_import.c
  module/icp/core/kcf_prov_tabs.c
  module/icp/io/aes.c
  module/lua/lcode.c
  module/lua/lgc.c
  module/lua/llex.c
  module/lua/lstrlib.c
  module/lua/ltable.c
  module/os/freebsd/zfs/zfs_acl.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_acl.c
  module/os/linux/zfs/zfs_znode.c
  module/zfs/abd.c
  module/zfs/dsl_prop.c
  module/zfs/spa.c
  module/zfs/vdev_label.c
  module/zfs/vdev_raidz_math_scalar.c
  module/zfs/zfs_replay.c
  module/zfs/zio_compress.c
  tests/zfs-tests/cmd/mkbusy/mkbusy.c
Labels: Type: Building, Status: Accepted

#11312 Temporarily use root credentials to mount snapshots in .zfs
  module/os/freebsd/spl/spl_vfs.c
Labels: Status: Code Review Needed

#12565 Linux 5.14 compat: META
  META
Labels: Status: Code Review Needed

#12392 Avoid panic in case of pool errors and missing L2ARC
  module/zfs/arc.c
Labels: Status: Accepted

#12569 FreeBSD: Really zero the zero page.
  module/os/freebsd/zfs/abd_os.c
Labels: Status: Accepted

#12030 Added test for being able to read various variants of zstd
  tests/runfiles/sanity.run
  tests/zfs-tests/tests/functional/compression/Makefile.am
  tests/zfs-tests/tests/functional/compression/compress_zstd_bswap.ksh
  tests/zfs-tests/tests/functional/compression/testpool_zstd.tar.gz
Labels: Component: Test Suite, Status: Code Review Needed

#12550 unmount snapshots before destroying them by adding _os() functions
  include/libzfs.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/os/freebsd/libzfs_compat.c
  lib/libzfs/os/linux/libzfs_util_os.c
Labels: Status: Code Review Needed

#12516 Fix NFS and large reads on older kernels
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#12576 Assorted parameter changes for performance tests
  tests/zfs-tests/tests/perf/perf.shlib
  tests/zfs-tests/tests/perf/regression/random_reads.ksh
  tests/zfs-tests/tests/perf/regression/random_readwrite.ksh
  tests/zfs-tests/tests/perf/regression/random_readwrite_fixed.ksh
  tests/zfs-tests/tests/perf/regression/random_writes.ksh
  tests/zfs-tests/tests/perf/regression/random_writes_zil.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads_arc_cached.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads_arc_cached_clone.ksh
  tests/zfs-tests/tests/perf/regression/sequential_reads_dbuf_cached.ksh
  tests/zfs-tests/tests/perf/regression/sequential_writes.ksh
Labels: Status: Accepted

#12567 libspl: fix warning about missing spl_pagesize declaration
  lib/libspl/page.c
Labels: Type: Building, Status: Accepted
