Repository openzfs/zfs, pull requests merged in 2021-11, with the labels that each got.

#12636 Correct a flaw in the Python 3 version checking (for 2.1)
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  .github/workflows/zloop.yml
  config/always-pyzfs.m4
  config/ax_python_devel.m4
  rpm/generic/zfs.spec.in
Labels: Type: Building, Status: Code Review Needed

#12584 [2.1] Detect HAVE_LARGE_STACKS at compile time
  config/Rules.am
  config/kernel-config-defined.m4
  include/os/freebsd/zfs/sys/zfs_context_os.h
  include/os/linux/zfs/sys/zfs_context_os.h
  lib/libspl/include/os/freebsd/sys/zfs_context_os.h
  lib/libspl/include/os/linux/sys/zfs_context_os.h
Labels: Status: Code Review Needed

#12626 Let zfs diff be more permissive (for 2.0)
  lib/libzfs/libzfs_diff.c
Labels: Status: Accepted

#12703 Added error for writing to /dev/ on Linux - for 2.0
  cmd/zfs/zfs_main.c
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Code Review Needed

#12670 Workaround issue cleaning up automounted snapshots on Linux
  module/os/linux/zfs/zfs_ctldir.c
Labels: Status: Code Review Needed

#12698 Revert behavior of 59eab109 on not-Linux
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#12724 Fix lseek(SEEK_DATA/SEEK_HOLE) mmap consistency
  configure.ac
  include/os/freebsd/spl/sys/vnode.h
  include/os/freebsd/zfs/sys/zfs_znode_impl.h
  include/os/linux/zfs/sys/zfs_znode_impl.h
  include/sys/dnode.h
  man/man4/zfs.4
  module/zfs/dmu.c
  module/zfs/dnode.c
  module/zfs/zfs_vnops.c
  tests/runfiles/common.run
  tests/zfs-tests/cmd/Makefile.am
  tests/zfs-tests/cmd/mmap_seek/.gitignore
  tests/zfs-tests/cmd/mmap_seek/Makefile.am
  tests/zfs-tests/cmd/mmap_seek/mmap_seek.c
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/functional/mmap/Makefile.am
  tests/zfs-tests/tests/functional/mmap/mmap_seek_001_pos.ksh
Labels: Status: Accepted

#12733 Exclude zvol_misc_volmode for now
  tests/test-runner/bin/zts-report.py.in
Labels: Status: Accepted

#12333 Creating gang ABDs for Raidz optional IOs
  module/zfs/vdev_raidz.c
Labels: Status: Accepted

#12687 Skip spacemaps reading in case of pool readonly import
  cmd/zdb/zdb.c
  include/sys/spa_impl.h
  module/zfs/metaslab.c
  module/zfs/spa.c
  module/zfs/vdev.c
Labels: Status: Accepted

#12695 zed: Control NVMe fault LEDs
  cmd/zed/zed.d/statechange-led.sh
  cmd/zed/zed.d/zed.rc
  cmd/zpool/zpool.d/ses
  lib/libzutil/os/linux/zutil_device_path_os.c
  lib/libzutil/zutil_nicenum.c
Labels: Status: Accepted

#12685 zdb: Report bad label checksum
  cmd/zdb/zdb.c
  tests/runfiles/common.run
  tests/zfs-tests/include/blkdev.shlib
  tests/zfs-tests/tests/functional/cli_root/zdb/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_label_checksum.ksh
Labels: Status: Accepted

#12738 Exclude zfs_copies_003_pos on Linux
  tests/test-runner/bin/zts-report.py.in
Labels: Component: Test Suite, Status: Accepted

#12745 Restore dirty dnode detection logic
  module/zfs/dnode.c
Labels: Status: Code Review Needed

#12744 ZTS: zfs_list_004_neg should not check paths that belong to ZFS
  tests/zfs-tests/tests/functional/cli_user/zfs_list/zfs_list.kshlib
  tests/zfs-tests/tests/functional/cli_user/zfs_list/zfs_list_004_neg.ksh
Labels: Component: Test Suite, Status: Accepted

#12689 Check l2cache vdevs pending list inside the vdev_inuse()
  include/sys/spa.h
  module/zfs/spa.c
  module/zfs/vdev_label.c
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_009_neg.ksh
Labels: Status: Accepted

#12652 Remove basename(1). Clean up/shorten/eliminate some pipelines
  cmd/vdev_id/vdev_id
  cmd/zed/zed.d/all-syslog.sh
  cmd/zed/zed.d/generic-notify.sh
  cmd/zed/zed.d/zed-functions.sh
  cmd/zpool/zpool.d/dm-deps
  cmd/zpool/zpool.d/iostat
  cmd/zpool/zpool.d/lsblk
  cmd/zpool/zpool.d/media
  cmd/zpool/zpool.d/ses
  config/always-python.m4
  config/always-pyzfs.m4
  config/zfs-meta.m4
  contrib/bpftrace/zfs-trace.sh
  contrib/dracut/02zfsexpandknowledge/module-setup.sh.in
  contrib/dracut/90zfs/module-setup.sh.in
  contrib/dracut/90zfs/parse-zfs.sh.in
  contrib/dracut/90zfs/zfs-generator.sh.in
  contrib/initramfs/scripts/zfs
  etc/init.d/zfs-import.in
  etc/zfs/zfs-functions.in
  rpm/generic/zfs-dkms.spec.in
  scripts/kmodtool
  scripts/zfs-tests.sh
  scripts/zfs.sh
  scripts/zimport.sh
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/reservation/reservation_021_neg.ksh
Labels: Status: Code Review Needed

#12285 Exclude special allocation class buffers from L2ARC
  include/sys/arc.h
  include/sys/dbuf.h
  include/sys/dmu_objset.h
  man/man4/zfs.4
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_objset.c
Labels: Status: Accepted

#12748 Remove unused td argument from zfs_lookup().
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#12658 Fix `zfs:AUTO` autodetection in initramfs scripts
  contrib/initramfs/scripts/zfs
Labels: Status: Accepted

#12743 FreeBSD: fix world build after de198f2d9
  include/os/freebsd/spl/sys/vnode.h
Labels: Status: Accepted

#12735 Enable edonr in FreeBSD
  include/sys/zio.h
  man/man7/zfsprops.7
  man/man7/zpool-features.7
  module/Makefile.bsd
  module/zcommon/zfeature_common.c
  module/zcommon/zfs_prop.c
  module/zfs/zio_checksum.c
  tests/runfiles/common.run
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/checksum/Makefile.am
  tests/zfs-tests/tests/functional/checksum/default.cfg
  tests/zfs-tests/tests/functional/cli_root/zfs_set/checksum_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
Labels: Status: Accepted

#12771 Add notes to system_taskq
  module/os/freebsd/spl/spl_taskq.c
  module/os/linux/spl/spl-taskq.c
Labels: Status: Accepted

#12717 VOP_RENAME fixes for FreeBSD
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Code Review Needed

#12763 Fix typo in zpool.8
  man/man8/zpool.8
Labels: Type: Documentation, Status: Accepted

#11711 Introduce vdev properties
  cmd/zpool/zpool_iter.c
  cmd/zpool/zpool_main.c
  cmd/zpool/zpool_util.h
  contrib/pyzfs/libzfs_core/_constants.py
  include/libzfs.h
  include/libzfs_core.h
  include/sys/fs/zfs.h
  include/sys/spa.h
  include/sys/spa_impl.h
  include/sys/vdev.h
  include/sys/vdev_impl.h
  include/sys/zfs_sysfs.h
  include/zfs_prop.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_util.c
  lib/libzfs/os/freebsd/libzfs_compat.c
  lib/libzfs_core/libzfs_core.abi
  lib/libzfs_core/libzfs_core.c
  lib/libzutil/zutil_import.c
  man/man7/vdevprops.7
  man/man8/zpool-get.8
  module/os/linux/zfs/zfs_sysfs.c
  module/zcommon/zfs_prop.c
  module/zcommon/zpool_prop.c
  module/zcommon/zprop_common.c
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/vdev.c
  module/zfs/vdev_label.c
  module/zfs/vdev_removal.c
  module/zfs/zfs_ioctl.c
  module/zfs/zio.c
Labels: Status: Accepted

#12138 etc/systemd/zfs-mount-generator: serialise, handle keylocation=http[s]://
  etc/systemd/system-generators/zfs-mount-generator.c
  man/man8/zfs-mount-generator.8.in
Labels: Status: Accepted

#12750 Allow printing special vdev metaslab groups
  cmd/zdb/zdb.c
  man/man8/zdb.8
Labels: Status: Accepted

#12784 Replace wrong occurrences of `affect` by `effect` in the man pages.
  man/man4/zfs.4
  man/man8/zfs-receive.8
Labels: Status: Accepted

#12804 Stop segfaulting on unmount error case
  lib/libzfs/libzfs_mount.c
Labels: Status: Code Review Needed

#12746 Default to zfs_dmu_offset_next_sync=1
  man/man4/zfs.4
  module/zfs/dmu.c
Labels: Status: Accepted
