Repository openzfs/zfs, pull requests merged in 2022-07, with the labels that each got.

#13606 Avoid memory copies during mirror scrub.
  module/zfs/vdev_mirror.c
Labels: Type: Performance, Status: Accepted

#13613 Avoid memory copy when verifying raidz/draid parity.
  module/zfs/vdev_raidz.c
Labels: Type: Performance, Status: Accepted

#13638 rpm: Silence "unversioned Obsoletes" warnings on EL 9
  rpm/generic/zfs-dkms.spec.in
  rpm/generic/zfs.spec.in
Labels: Type: Building, Component: Packaging, Status: Accepted

#13632 zed: Ignore false 'atari' partitions in autoreplace
  cmd/zed/zed_disk_event.c
Labels: Component: ZED, Status: Accepted

#13646 zed: Look for NVMe DEVPATH if no ID_BUS
  cmd/zed/zed_disk_event.c
Labels: Status: Accepted

#13642 Scrub mirror children without BPs - 2.1.6 backport
  module/zfs/vdev_mirror.c
  module/zfs/vdev_raidz.c
  tests/runfiles/common.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/functional/redundancy/Makefile.am
  tests/zfs-tests/tests/functional/redundancy/redundancy_draid_damaged1.ksh
  tests/zfs-tests/tests/functional/redundancy/redundancy_draid_damaged2.ksh
Labels: Status: Accepted

#13607 Expose ZFS dataset case sensitivity setting via sb_opts
  include/sys/mntent.h
  lib/libzfs/os/linux/libzfs_mount_os.c
  module/os/linux/zfs/zpl_super.c
Labels: Status: Code Review Needed

#13670 Fix memory allocation for the checksum benchmark
  module/zfs/zfs_chksum.c
Labels: Status: Accepted

#13643 Fix scrub resume from newly created hole.
  include/sys/zio.h
  module/zfs/dsl_scan.c
  module/zfs/zio.c
Labels: Status: Accepted

#13636 ZIL kstats update
  cmd/ztest.c
  include/sys/dataset_kstats.h
  include/sys/zil.h
  include/sys/zil_impl.h
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/freebsd/zfs/zvol_os.c
  module/os/linux/zfs/zfs_vfsops.c
  module/os/linux/zfs/zvol_os.c
  module/zfs/dataset_kstats.c
  module/zfs/zil.c
Labels: Status: Code Review Needed

#13640 zdb: dump spill block pointer
  cmd/zdb/zdb.c
Labels: Status: Accepted

#13686 ZTS: Fix occasional inherit_001_pos.ksh failure
  tests/zfs-tests/tests/functional/inheritance/inherit_001_pos.ksh
Labels: Component: Test Suite, Status: Accepted

#13577 Add support for createtxg sort for simple snapshot iterator
  cmd/zfs/zfs_iter.c
  cmd/zfs/zfs_iter.h
  cmd/zfs/zfs_main.c
  lib/libzfs/libzfs_dataset.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#13661 a798b48 backport for 2.1
  include/sys/crypto/icp.h
  lib/libicp/Makefile.am
  module/icp/Makefile.in
  module/icp/algs/sha1/sha1.c
  module/icp/asm-x86_64/sha1/sha1-x86_64.S
  module/icp/illumos-crypto.c
  module/icp/include/sha1/sha1.h
  module/icp/include/sha1/sha1_consts.h
  module/icp/include/sha1/sha1_impl.h
  module/icp/io/sha1_mod.c
Labels: Status: Accepted

#13685 ZTS: Fix io_uring support check
  tests/zfs-tests/tests/functional/io/io_uring.ksh
Labels: Component: Test Suite, Status: Accepted

#13702 FreeBSD compile fix
  module/os/freebsd/zfs/zfs_ioctl_compat.c
Labels: Status: Accepted

#9372 implement corruption correcting recv
  cmd/zfs/zfs_main.c
  contrib/pyzfs/libzfs_core/__init__.py
  contrib/pyzfs/libzfs_core/_error_translation.py
  contrib/pyzfs/libzfs_core/_libzfs_core.py
  contrib/pyzfs/libzfs_core/bindings/libzfs_core.py
  contrib/pyzfs/libzfs_core/test/test_libzfs_core.py
  include/libzfs.h
  include/libzfs_core.h
  include/sys/dmu_recv.h
  include/sys/spa.h
  include/sys/spa_impl.h
  include/sys/zio.h
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs_core/libzfs_core.abi
  lib/libzfs_core/libzfs_core.c
  man/man4/zfs.4
  man/man8/zfs-receive.8
  module/zfs/dmu.c
  module/zfs/dmu_recv.c
  module/zfs/spa.c
  module/zfs/spa_errlog.c
  module/zfs/zfs_ioctl.c
  module/zfs/zio.c
  tests/runfiles/common.run
  tests/zfs-tests/cmd/libzfs_input_check.c
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_compressed_corrective.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_corrective.ksh
Labels: Type: Feature, Status: Accepted, Component: Send/Recv
