Repository openzfs/zfs, pull requests merged in 2022-06, with the labels that each got.

#13513 Remove wrong assertion in log spacemap.
  module/zfs/spa_log_spacemap.c
Labels: Status: Accepted

#12918 Add BLAKE3 hash support and chksum benchmarking to OpenZFS
  AUTHORS
  cmd/ztest.c
  config/always-arch.m4
  include/Makefile.am
  include/os/freebsd/spl/sys/ccompile.h
  include/os/linux/kernel/linux/simd_powerpc.h
  include/sys/blake3.h
  include/sys/zfs_chksum.h
  include/sys/zfs_ioctl.h
  include/sys/zio.h
  include/sys/zio_checksum.h
  include/zfeature_common.h
  lib/libicp/Makefile.am
  lib/libspl/include/sys/simd.h
  lib/libzfs/libzfs.abi
  lib/libzpool/Makefile.am
  man/man7/zfsprops.7
  man/man7/zpool-features.7
  module/Kbuild.in
  module/Makefile.bsd
  module/icp/algs/blake3/blake3.c
  module/icp/algs/blake3/blake3_generic.c
  module/icp/algs/blake3/blake3_impl.c
  module/icp/algs/blake3/blake3_impl.h
  module/icp/algs/blake3/blake3_x86-64.c
  module/icp/asm-aarch64/blake3/b3_aarch64_sse2.S
  module/icp/asm-aarch64/blake3/b3_aarch64_sse41.S
  module/icp/asm-ppc64/blake3/b3_ppc64le_sse2.S
  module/icp/asm-ppc64/blake3/b3_ppc64le_sse41.S
  module/icp/asm-x86_64/blake3/blake3_avx2.S
  module/icp/asm-x86_64/blake3/blake3_avx512.S
  module/icp/asm-x86_64/blake3/blake3_sse2.S
  module/icp/asm-x86_64/blake3/blake3_sse41.S
  module/zcommon/zfeature_common.c
  module/zcommon/zfs_prop.c
  module/zfs/blake3_zfs.c
  module/zfs/spa_misc.c
  module/zfs/zfs_chksum.c
  module/zfs/zio_checksum.c
  tests/runfiles/common.run
  tests/zfs-tests/cmd/.gitignore
  tests/zfs-tests/cmd/Makefile.am
  tests/zfs-tests/cmd/checksum/blake3_test.c
  tests/zfs-tests/cmd/checksum/edonr_test.c
  tests/zfs-tests/cmd/checksum/sha2_test.c
  tests/zfs-tests/cmd/checksum/skein_test.c
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/include/properties.shlib
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/checksum/default.cfg
  tests/zfs-tests/tests/functional/checksum/run_blake3_test.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_set/checksum_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
Labels: Type: Feature, Status: Accepted

#13540 AVL: Remove obsolete branching optimizations.
  module/avl/avl.c
Labels: Type: Performance, Status: Accepted

#13537 Improve sorted scan memory accounting
  module/zfs/dsl_scan.c
Labels: Status: Accepted

#13544 add weekly and monthly systemd timers for trimming
  etc/Makefile.am
  etc/systemd/system/zfs-trim-monthly@.timer.in
  etc/systemd/system/zfs-trim-weekly@.timer.in
  etc/systemd/system/zfs-trim@.service.in
  man/man8/zpool-trim.8
Labels: Status: Accepted, Component: Systemd

#12676 Replace ZPROP_INVAL with ZPROP_USER where it means a user property
  cmd/zfs/zfs_iter.c
  cmd/zfs/zfs_main.c
  cmd/zpool/zpool_main.c
  include/sys/fs/zfs.h
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs/libzfs_util.c
  module/zfs/dsl_prop.c
  module/zfs/vdev.c
  module/zfs/zcp_synctask.c
  module/zfs/zfs_ioctl.c
Labels: Status: Code Review Needed

#13551 Fix clang 13 compilation errors
  config/kernel-add-disk.m4
  module/os/linux/zfs/zpl_xattr.c
Labels: Status: Accepted

#13553 Reduce ZIO io_lock contention on sorted scrub.
  module/zfs/dsl_scan.c
Labels: Type: Performance, Status: Accepted

#13559 expose snapshot count via stat(2) of .zfs/snapshot
  module/os/linux/zfs/zpl_ctldir.c
Labels: Status: Accepted

#13563 FreeBSD: Improve crypto_dispatch() handling.
  module/os/freebsd/zfs/crypto_os.c
Labels: Status: Code Review Needed

#13555 Scrub mirror children without BPs
  module/zfs/vdev_mirror.c
  module/zfs/vdev_raidz.c
  tests/runfiles/common.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/redundancy/redundancy_draid_damaged1.ksh
  tests/zfs-tests/tests/functional/redundancy/redundancy_draid_damaged2.ksh
Labels: Status: Accepted

#13576 Several sorted scrub optimizations.
  include/sys/dsl_scan.h
  include/sys/range_tree.h
  module/zfs/dsl_scan.c
  module/zfs/range_tree.c
Labels: Type: Performance, Status: Accepted

#13256 Add a "zstream decompress" subcommand
  cmd/zstream/Makefile.am
  cmd/zstream/zstream.c
  cmd/zstream/zstream.h
  cmd/zstream/zstream_decompress.c
  cmd/zstream/zstream_dump.c
  cmd/zstream/zstream_redup.c
  man/man8/zstream.8
Labels: Status: Accepted

#13582 Several B-tree optimizations.
  include/sys/btree.h
  module/zfs/btree.c
Labels: Type: Performance, Status: Accepted

#13591 Avoid two 64-bit divisions per scanned block.
  module/zfs/dsl_scan.c
Labels: Type: Performance, Status: Accepted

#13579 Fix and disable blocks statistics during scrub.
  include/sys/dsl_pool.h
  module/zfs/dsl_pool.c
  module/zfs/dsl_scan.c
Labels: Type: Performance, Status: Accepted

#13596 FreeBSD: only define B_FALSE/B_TRUE if NEED_SOLARIS_BOOLEAN is not set
  include/os/freebsd/spl/sys/types.h
Labels: Status: Accepted

#13581 Fix znode group permission different from acl mask
  module/os/linux/zfs/zpl_xattr.c
Labels: Status: Accepted

#13602 dracut: fix typo in mount-zfs.sh.in
  contrib/dracut/90zfs/mount-zfs.sh.in
Labels: Component: Dracut, Status: Accepted

#13585 contrib: dracut: zfs-{rollback,snapshot}-bootfs: explicit snapname fix
  contrib/dracut/90zfs/zfs-rollback-bootfs.service.in
  contrib/dracut/90zfs/zfs-snapshot-bootfs.service.in
Labels: Component: Dracut, Status: Accepted

#13015 Fix dnode byteswapping
  module/zfs/dnode.c
Labels: Status: Accepted

#13609 contrib: dracut: README.md
  contrib/dracut/README.md
Labels: Status: Accepted

#13592 Fix boot on non-zfs-root systems
  contrib/dracut/90zfs/zfs-lib.sh.in
Labels: Component: Dracut, Status: Accepted

#13610 Re-fix -Wwrite-strings on FreeBSD
  lib/libspl/include/os/freebsd/sys/mnttab.h
  lib/libspl/os/freebsd/mnttab.c
  lib/libzfs/os/freebsd/libzfs_zmount.c
  module/os/freebsd/zfs/zfs_acl.c
Labels: Status: Accepted
