Repository openzfs/zfs, pull requests merged in 2022-08, with the labels that each got.

#13710 Fix checkstyle warning: E275 missing whitespace after keyword
  contrib/pyzfs/libzfs_core/_constants.py
Labels: Status: Accepted

#13695 Skip checksum benchmarks on systems with slow cpu
  module/zfs/zfs_chksum.c
Labels: Status: Accepted

#13715 Linux 5.19 compat: META
  META
Labels: Status: Accepted

#13719 FreeBSD: Ignore symlink to i386 includes
  module/.gitignore
Labels: Status: Accepted

#13635 Add snapshots_changed as property
  include/sys/dsl_dir.h
  include/sys/fs/zfs.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_dataset.c
  man/man7/zfsprops.7
  module/zcommon/zfs_prop.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_dir.c
  module/zfs/zcp_get.c
  tests/runfiles/common.run
  tests/runfiles/sanity.run
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/snapshot/snapshot_018_pos.ksh
Labels: Status: Accepted

#13730 Don't double-zero buffers in fault management nvlists
  module/zfs/fm.c
Labels: Status: Accepted

#13724 libzfs: Remove unused zpool_get_physpath()
  include/libzfs.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#13698 add comment on acb_zio_dummy
  module/zfs/arc.c
Labels: Status: Code Review Needed

#13726 Fix problem with zdb -d
  cmd/zdb/zdb.c
  man/man8/zdb.8
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_objset_id.ksh
Labels: Status: Accepted

#13754 Fix problem with zdb_objset_id test
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_objset_id.ksh
Labels: Status: Accepted

#13743 zts: Fix zpool_expand_001_pos
  tests/zfs-tests/tests/functional/cli_root/zpool_expand/zpool_expand_001_pos.ksh
Labels: Status: Accepted

#13614 Relatime: set on by default
  man/man7/zfsprops.7
  module/zcommon/zfs_prop.c
  tests/zfs-tests/tests/functional/atime/atime_001_pos.ksh
  tests/zfs-tests/tests/functional/atime/atime_003_pos.ksh
  tests/zfs-tests/tests/functional/atime/root_atime_on.ksh
  tests/zfs-tests/tests/functional/atime/root_relatime_on.ksh
  tests/zfs-tests/tests/functional/cache/cache_012_pos.ksh
Labels: Status: Accepted

#13767 arcstat: fix -p option
  cmd/arcstat.in
Labels: Status: Accepted

#13769 contrib: dracut: zfs-snapshot-bootfs: exit status fix
  contrib/dracut/90zfs/zfs-snapshot-bootfs.service.in
Labels: Status: Accepted

#13753 Prevent zevent list from consuming all of kernel memory
  cmd/zed/zed_conf.c
  cmd/zed/zed_conf.h
  cmd/zed/zed_event.c
  man/man8/zed.8.in
  module/zfs/dsl_dataset.c
  module/zfs/dsl_destroy.c
Labels: Component: ZED, Status: Accepted

#13717 Fix zpool status in case of unloaded keys
  include/sys/dsl_crypt.h
  man/man7/zpool-features.7
  module/zfs/dsl_crypt.c
  module/zfs/spa_errlog.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_003_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_004_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_005_pos.ksh
Labels: Status: Accepted

#13785 Updates for snapshots_changed property
  lib/libzfs/libzfs_dataset.c
  man/man7/zfsprops.7
  module/zfs/dsl_dir.c
Labels: Status: Accepted

#13799 Revert "Avoid panic with recordsize > 128k, raw sending and no large_blocks"
  include/sys/dsl_dataset.h
  lib/libzfs/libzfs_sendrecv.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_send.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_scan.c
Labels: Status: Code Review Needed

#13793 ZTS: zvol_stress: fix race condition with zinject usage
  tests/zfs-tests/tests/functional/zvol/zvol_stress/zvol_stress.ksh
Labels: Status: Accepted

#13781 importing from cachefile can trip assertion
  lib/libzutil/zutil_import.c
Labels: Status: Accepted
