Repository openzfs/zfs, pull requests merged in 2022-01, with the labels that each got.

#12857 Verify dRAID empty sectors
  include/sys/vdev_draid.h
  include/sys/vdev_raidz.h
  module/zfs/vdev_draid.c
  module/zfs/vdev_raidz.c
  tests/zfs-tests/tests/functional/cli_root/zpool_events/zpool_events_errors.ksh
Labels: Status: Accepted

#12908 zfs_prune: reset sc.nr_to_scan
  module/os/linux/zfs/zfs_vfsops.c
Labels: Status: Code Review Needed

#12818 long opts for zdb
  cmd/zdb/zdb.c
  man/man8/zdb.8
Labels: Status: Accepted

#12911 man: speling
  man/man4/zfs.4
  man/man7/vdevprops.7
  man/man7/zfsprops.7
  man/man8/zfs-load-key.8
  man/man8/zgenhostid.8
  man/man8/zpool-attach.8
  man/man8/zpool-events.8
  man/man8/zpool-replace.8
Labels: Status: Accepted

#12938 Revert "zfs list: Allow more fields in ZFS_ITER_SIMPLE mode"
  cmd/zfs/zfs_iter.c
  cmd/zfs/zfs_iter.h
  cmd/zfs/zfs_main.c
  cmd/zpool/zpool_main.c
  contrib/pam_zfs_key/pam_zfs_key.c
  include/libzfs.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_changelist.c
  lib/libzfs/libzfs_crypto.c
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_iter.c
  lib/libzfs/libzfs_mount.c
  lib/libzfs/libzfs_sendrecv.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#12905 module: zfs: freebsd: vfsops: use setgen for error case
  module/os/freebsd/zfs/zfs_vfsops.c
Labels: Status: Accepted

#12922 config: libfetch: unquote @LIBFETCH_SONAME@ subst
  config/user-libfetch.m4
  contrib/dracut/90zfs/module-setup.sh.in
  contrib/initramfs/hooks/zfs.in
Labels: Status: Accepted

#12913 Add ShellCheck's `--enable=all` inside `etc/`
  etc/Makefile.am
  etc/default/Makefile.am
  etc/default/zfs.in
  etc/init.d/Makefile.am
  etc/init.d/zfs-import.in
  etc/init.d/zfs-load-key.in
  etc/init.d/zfs-mount.in
  etc/init.d/zfs-share.in
  etc/init.d/zfs-zed.in
  etc/zfs/Makefile.am
  etc/zfs/zfs-functions.in
Labels: Status: Accepted

#12935 l2arc_write_buffers: remove redundant asserts
  module/zfs/arc.c
Labels: Status: Accepted

#12912 Add ShellCheck's `--enable=all` inside `cmd/`
  cmd/Makefile.am
  cmd/fsck_zfs/Makefile.am
  cmd/zed/Makefile.am
  cmd/zed/zed.d/Makefile.am
  cmd/zed/zed.d/all-debug.sh
  cmd/zed/zed.d/all-syslog.sh
  cmd/zed/zed.d/data-notify.sh
  cmd/zed/zed.d/generic-notify.sh
  cmd/zed/zed.d/history_event-zfs-list-cacher.sh.in
  cmd/zed/zed.d/resilver_finish-start-scrub.sh
  cmd/zed/zed.d/scrub_finish-notify.sh
  cmd/zed/zed.d/statechange-led.sh
  cmd/zed/zed.d/statechange-notify.sh
  cmd/zed/zed.d/trim_finish-notify.sh
  cmd/zed/zed.d/zed-functions.sh
  cmd/zed/zed.d/zed.rc
  cmd/zpool/Makefile.am
  cmd/zpool/zpool.d/dm-deps
  cmd/zpool/zpool.d/iostat
  cmd/zpool/zpool.d/lsblk
  cmd/zpool/zpool.d/media
  cmd/zpool/zpool.d/ses
  cmd/zpool/zpool.d/smart
  cmd/zpool/zpool.d/upath
  cmd/zvol_wait/Makefile.am
Labels: Status: Accepted

#12939 Update OpenZFS website URL in README
  README.md
Labels: Status: Accepted

#12805 Updated the lz4 decompressor to 1.9.3
  Makefile.am
  config/ax_code_coverage.m4
  lib/libzpool/Makefile.am
  module/Makefile.bsd
  module/zfs/Makefile.in
  module/zfs/lz4.c
  module/zfs/lz4_zfs.c
Labels: Status: Accepted

#12947 lz4: Cherrypick fix for CVE-2021-3520
  module/zfs/lz4.c
Labels: Status: Accepted

#12951 Remove VERIFY() in vdev_props_set_sync()
  module/zfs/vdev.c
Labels: Status: Accepted

#12925 Removed Python 2 and Python 3.5- support
  .github/workflows/checkstyle.yaml
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  .github/workflows/zloop.yml
  cmd/arc_summary/Makefile.am
  cmd/arc_summary/arc_summary2
  cmd/arc_summary/arc_summary3
  cmd/arcstat/arcstat.in
  cmd/dbufstat/dbufstat.in
  config/always-python.m4
  config/always-pyzfs.m4
  contrib/pyzfs/setup.py.in
  rpm/generic/zfs.spec.in
  tests/test-runner/bin/test-runner.py.in
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/functional/cli_root/zfs_program/zfs_program_json.ksh
  tests/zfs-tests/tests/functional/pyzfs/pyzfs_unittest.ksh.in
  tests/zfs-tests/tests/functional/rsend/send_encrypted_files.ksh
  tests/zfs-tests/tests/functional/rsend/send_realloc_dnode_size.ksh
Labels: Status: Code Review Needed

#12914 Add ShellCheck's `--enable=all` inside `scripts/`
  scripts/Makefile.am
  scripts/commitcheck.sh
  scripts/kmodtool
  scripts/make_gitrev.sh
  scripts/paxcheck.sh
  scripts/zfs-helpers.sh
  scripts/zfs-tests.sh
  scripts/zfs.sh
  scripts/zimport.sh
  scripts/zloop.sh
Labels: Status: Accepted

#12954 linux: libzfs: mount: fix uninitialised flags
  lib/libzfs/os/linux/libzfs_mount_os.c
Labels: Status: Accepted

#12941 man: zfs.4: miscellaneous cleanup
  man/man4/zfs.4
Labels: Status: Accepted

#12961 FreeBSD: Fix leaked strings in libspl mnttab
  lib/libspl/os/freebsd/mnttab.c
Labels: Status: Accepted, Component: Userspace

#12907 Clarify `failmode=wait` documentation
  man/man7/zpoolprops.7
  man/man8/zpool-clear.8
Labels: Type: Documentation, Status: Accepted

#12969 libefi: remove efi_type()
  include/sys/efi_partition.h
  lib/libefi/rdwr_efi.c
  lib/libzfs/libzfs.abi
Labels: Status: Accepted

#12944 Fix problems with zdb -d <pool>/<objset ID>
  cmd/zdb/zdb.c
  man/man8/zdb.8
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_objset_id.ksh
Labels: Status: Accepted

#12986 libspl: ASSERT*: !! for sizeof
  include/os/freebsd/spl/sys/debug.h
  include/os/linux/spl/sys/debug.h
  lib/libspl/include/assert.h
Labels: Status: Accepted

#12985 Avoid memory allocations in the ARC eviction thread
  include/sys/zthr.h
  module/zfs/arc.c
  module/zfs/zthr.c
Labels: Component: Memory Management, Status: Accepted

#12981 Introduce a flag to skip comparing the local mac when raw sending
  module/os/freebsd/zfs/zio_crypt.c
  module/os/linux/zfs/zio_crypt.c
  module/zfs/dnode_sync.c
  module/zfs/dsl_crypt.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/userquota/Makefile.am
  tests/zfs-tests/tests/functional/userquota/userspace_send_encrypted.ksh
Labels: Status: Accepted, Component: Send/Recv, Component: Encryption

#12964 Fix handling of errors from dmu_write_uio_dbuf() on FreeBSD
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#12995 Minimal #12990
  tests/test-runner/bin/test-runner.py.in
Labels: Status: Accepted

#12999 Add explicit timeout to test in order to collect artifacts on timeout
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
Labels: Status: Accepted

#13009 libspl: cast to uintptr_t instead of !!ing
  include/os/freebsd/spl/sys/debug.h
  include/os/linux/spl/sys/debug.h
  lib/libspl/include/assert.h
Labels: Status: Accepted

#13006 The first arg of submit_bio is used for block dump
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#13001 RPM: Add missing BuildRequires for PAM component
  rpm/generic/zfs.spec.in
Labels: Component: Packaging, Status: Accepted

#13016 FreeBSD: Fix zvol_cdev_open locking
  module/os/freebsd/zfs/zvol_os.c
Labels: Status: Accepted

#12906 libzfs: sendrecv: fix unused, remove argsused
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Code Review Needed

#13032 tests: explicitly strip whitespace for broken wc(1) implementations
  tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_events/zpool_events_clear.ksh
  tests/zfs-tests/tests/functional/mv_files/mv_files_common.kshlib
Labels: Component: Test Suite, Status: Accepted

#13019 spl: Don't check FreeBSD rwlocks for double initialization
  include/os/freebsd/spl/sys/rwlock.h
Labels: Status: Accepted
