Repository openzfs/zfs, pull requests merged in 2022-02, with the labels that each got.

#13052 Fix trivial calloc(3) arguments order
  cmd/zpool_influxdb/zpool_influxdb.c
  tests/zfs-tests/cmd/draid/draid.c
Labels: Status: Accepted

#12998 Notice if the test-runner dies
  scripts/zfs-tests.sh
Labels: Status: Accepted

#13014 Report dnodes with faulty bonuslen
  cmd/zstream/zstream_dump.c
  module/zfs/dmu_send.c
  module/zfs/dnode_sync.c
  module/zfs/dsl_scan.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/rsend/Makefile.am
  tests/zfs-tests/tests/functional/rsend/send_raw_spill_block.ksh
Labels: Status: Accepted

#13031 Add enumerated vdev names to 'zpool iostat -v' and 'zpool list -v'
  cmd/zpool/zpool_main.c
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/redundancy/redundancy.kshlib
Labels: Status: Accepted

#13049 zed-functions.sh: escape newline to produce valid json.
  cmd/zed/zed.d/zed-functions.sh
Labels: Status: Accepted

#12928 Add `--enable-asan` and `--enable-ubsan` switches
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  .github/workflows/zloop.yml
  cmd/zdb/zdb.c
  cmd/zfs/zfs_main.c
  cmd/zpool/zpool_main.c
  cmd/ztest/ztest.c
  cmd/zvol_id/zvol_id_main.c
  config/Rules.am
  config/Substfiles.am
  config/always-compiler-options.m4
  config/zfs-build.m4
  include/zfs_fletcher.h
  lib/libnvpair/libnvpair.abi
  lib/libspl/assert.c
  lib/libspl/include/assert.h
  lib/libuutil/libuutil.abi
  lib/libuutil/uu_pname.c
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_mount.c
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs_core/libzfs_core.abi
  module/icp/algs/modes/gcm.c
  module/icp/io/sha2_mod.c
  module/zcommon/zfs_fletcher.c
  module/zcommon/zfs_fletcher_aarch64_neon.c
  module/zcommon/zfs_fletcher_avx512.c
  module/zcommon/zfs_fletcher_intel.c
  module/zcommon/zfs_fletcher_sse.c
  module/zcommon/zfs_fletcher_superscalar.c
  module/zcommon/zfs_fletcher_superscalar4.c
  module/zfs/btree.c
  module/zfs/vdev.c
  module/zstd/lib/zstd.c
  module/zstd/zfs_zstd.c
  rpm/generic/zfs.spec.in
  scripts/zfs-tests.sh
  scripts/zloop.sh
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/include/default.cfg.in
  tests/zfs-tests/tests/functional/alloc_class/alloc_class_013_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs/zfs_002_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool/zpool_002_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool/zpool_003_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_trim/zpool_trim_start_and_cancel_pos.ksh
  tests/zfs-tests/tests/functional/pam/pam_basic.ksh
  tests/zfs-tests/tests/functional/pam/pam_nounmount.ksh
  tests/zfs-tests/tests/functional/pam/pam_short_password.ksh
  tests/zfs-tests/tests/functional/pyzfs/pyzfs_unittest.ksh.in
  tests/zfs-tests/tests/functional/tmpfile/tmpfile_002_pos.c
Labels: Status: Accepted

#13027 Fix clearing set-uid and set-gid bits on a file when replying a write.
  module/zfs/zfs_vnops.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/suid/Makefile.am
  tests/zfs-tests/tests/functional/suid/suid_write_to_file.c
  tests/zfs-tests/tests/functional/suid/suid_write_to_none.ksh
  tests/zfs-tests/tests/functional/suid/suid_write_to_sgid.ksh
  tests/zfs-tests/tests/functional/suid/suid_write_to_suid.ksh
  tests/zfs-tests/tests/functional/suid/suid_write_to_suid_sgid.ksh
  tests/zfs-tests/tests/functional/suid/suid_write_zil_replay.ksh
Labels: Status: Accepted

#13060 ZTS: Update enospc_002_pos test case
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/functional/no_space/enospc_002_pos.ksh
Labels: Component: Test Suite, Status: Code Review Needed

#13056 dsl_dir_tempreserve_impl: remove unused `deferred` variable
  module/zfs/dsl_dir.c
Labels: Status: Accepted

#12963 zfs_set_prop_nvlist: make it easier to spot the call to dsl_props_set
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#13022 Add more control/visibility and speedup spa_load_verify().
  include/sys/fs/zfs.h
  module/zfs/spa.c
Labels: Status: Accepted

#12965 zvol: make calls to platform ops static
  include/sys/zvol_impl.h
  module/os/freebsd/zfs/zvol_os.c
  module/os/linux/zfs/zvol_os.c
  module/zfs/zvol.c
Labels: Status: Accepted

#13037 Extract workflows dependencies
  .github/workflows/build-dependencies.txt
  .github/workflows/checkstyle.yaml
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  .github/workflows/zloop.yml
Labels: Status: Accepted

#13020 Add `--enable=all` to ShellCheck by default
  cmd/Makefile.am
  cmd/fsck_zfs/Makefile.am
  cmd/zed/Makefile.am
  cmd/zed/zed.d/Makefile.am
  cmd/zpool/Makefile.am
  cmd/zvol_wait/Makefile.am
  config/Shellcheck.am
  contrib/Makefile.am
  contrib/bash_completion.d/Makefile.am
  contrib/bpftrace/Makefile.am
  contrib/dracut/02zfsexpandknowledge/Makefile.am
  contrib/dracut/90zfs/Makefile.am
  contrib/initramfs/Makefile.am
  contrib/initramfs/hooks/Makefile.am
  contrib/initramfs/scripts/Makefile.am
  contrib/initramfs/scripts/local-top/Makefile.am
  etc/Makefile.am
  etc/default/Makefile.am
  etc/init.d/Makefile.am
  etc/zfs/Makefile.am
  scripts/Makefile.am
Labels: Status: Accepted

#13021 `mount.zfs -o zfsutil` leverages `zfs_mount_at()`
  cmd/mount_zfs/mount_zfs.c
Labels: Status: Accepted

#13066 Remove unused files from GitHub runners
  .github/workflows/scripts/reclaim_disk_space.sh
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
Labels: Status: Accepted

#13059 Linux 5.16 compat: don't use XSTATE_XSAVE to save FPU state
  config/kernel-fpu.m4
  config/toolchain-simd.m4
  configure.ac
  include/os/linux/kernel/linux/simd_x86.h
  module/zcommon/zfs_prop.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/functional/Makefile.am
  tests/zfs-tests/tests/functional/simd/Makefile.am
  tests/zfs-tests/tests/functional/simd/simd_supported.ksh
Labels: Status: Accepted

#12802 Move EMPTY_TASKQ into taskq
  include/os/linux/spl/sys/taskq.h
  include/sys/zfs_context.h
  lib/libzpool/taskq.c
  module/icp/core/kcf_sched.c
  module/os/linux/spl/spl-taskq.c
Labels: Status: Accepted

#13076 module: zfs: receive checks should allow unencrypted child datasets.
  module/zfs/dmu_recv.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_-wR-encrypted-mix.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_to_encrypted.ksh
Labels: Status: Accepted

#13044 Add dataset_kstats_update.. to mmap read/write path on Linux
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#13075 ZTS: Fix zvol_misc_volmode test
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_volmode.ksh
Labels: Component: Test Suite, Status: Accepted

#13072 Correct a typo in zfs-receive.8
  man/man8/zfs-receive.8
Labels: Type: Documentation, Status: Accepted

#13081 zpoolprops.7: document leaked
  man/man7/zpoolprops.7
Labels: Type: Documentation, Status: Accepted

#13089 Fix gcc warning in kfpu_begin()
  include/os/linux/kernel/linux/simd_x86.h
Labels: Status: Accepted

#13091 ZTS: Fix zpool_expand_001_pos
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/functional/cli_root/zpool_expand/zpool_expand_001_pos.ksh
Labels: Component: Test Suite, Status: Accepted

#13092 ZTS: Fix checkpoint_ro_rewind.ksh
  tests/zfs-tests/tests/functional/pool_checkpoint/checkpoint_ro_rewind.ksh
Labels: Component: Test Suite, Status: Accepted

#13097 Upstream: rename fallthrough to zfs_fallthrough
  cmd/mount_zfs/mount_zfs.c
  cmd/zdb/zdb.c
  cmd/zpool_influxdb/zpool_influxdb.c
  include/os/freebsd/linux/compiler.h
  include/os/linux/kernel/linux/compiler_compat.h
  lib/libspl/include/sys/feature_tests.h
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs/libzfs_util.c
  lib/libzfsbootenv/lzbe_device.c
  lib/libzutil/zutil_import.c
  module/icp/core/kcf_prov_tabs.c
  module/icp/io/aes.c
  module/lua/lgc.c
  module/lua/llex.c
  module/lua/lstrlib.c
  module/lua/ltable.c
  module/os/freebsd/zfs/zfs_acl.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_acl.c
  module/os/linux/zfs/zfs_znode.c
  module/zfs/abd.c
  module/zfs/dsl_prop.c
  module/zfs/spa.c
  module/zfs/vdev_label.c
  module/zfs/vdev_raidz_math_scalar.c
  module/zfs/zfs_replay.c
  tests/zfs-tests/cmd/mkbusy/mkbusy.c
Labels: Status: Code Review Needed

#13098 Avoid dirtying the final TXGs when exporting a pool
  module/zfs/spa.c
Labels: Status: Accepted

#12801 Add spa _os() hooks
  include/sys/spa.h
  lib/libzpool/kernel.c
  module/os/freebsd/zfs/spa_os.c
  module/os/linux/zfs/spa_misc_os.c
  module/zfs/spa.c
Labels: Status: Accepted

#11919 Cross-platform compatible xattr user namespace
  include/sys/fs/zfs.h
  man/man4/zfs.4
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zpl_xattr.c
  tests/runfiles/common.run
  tests/runfiles/sanity.run
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/functional/xattr/Makefile.am
  tests/zfs-tests/tests/functional/xattr/xattr_compat.ksh
Labels: Status: Accepted

#13047 libzfs: calculate receive times with sub-second precision
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#13000 Color the Github test output
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  scripts/Makefile.am
  scripts/zfs-tests-color.sh
Labels: Component: Test Suite, Status: Accepted

#13104 `checkabi`/`storeabi` relevant only to x86_64
  Makefile.am
  config/Abigail.am
Labels: Status: Accepted

#13074 Enable encrypted raw sending to pools with greater ashift
  module/zfs/zio.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/rsend/Makefile.am
  tests/zfs-tests/tests/functional/rsend/send_raw_ashift.ksh
Labels: Status: Accepted

#13096 Fix Linux kernel directories detection
  config/kernel.m4
Labels: Status: Accepted

#13112 ZTS: Fix vdev_zaps_004_pos.ksh
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/functional/vdev_zaps/vdev_zaps_004_pos.ksh
Labels: Component: Test Suite, Status: Accepted

#13077 libzfs: Fail making a dataset handle gracefully
  lib/libzfs/libzfs_dataset.c
Labels: Status: Accepted

#13103 Correct compilation errors reported by GCC 10/11
  cmd/zfs/zfs_iter.c
  cmd/zpool_influxdb/zpool_influxdb.c
  include/sys/fs/zfs.h
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs/os/freebsd/libzfs_compat.c
  lib/libzutil/os/linux/zutil_import_os.c
  module/zfs/zcp_get.c
Labels: Status: Accepted

#13119 ZTS: Retry in import_rewind_config_changed.ksh
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/functional/cli_root/zpool_import/import_rewind_config_changed.ksh
Labels: Component: Test Suite, Status: Accepted

#12946 systemd: read initconfdir
  etc/systemd/system/zfs-import-cache.service.in
  etc/systemd/system/zfs-import-scan.service.in
  etc/systemd/system/zfs-mount.service.in
  etc/systemd/system/zfs-scrub@.service.in
  etc/systemd/system/zfs-share.service.in
  etc/systemd/system/zfs-volume-wait.service.in
  etc/systemd/system/zfs-zed.service.in
Labels: Status: Accepted

#9078 ZFS fix to make xattr=sa logging to ZIL on create/remove/update.
  cmd/zdb/zdb_il.c
  cmd/ztest/ztest.c
  include/sys/zfs_sa.h
  include/sys/zfs_znode.h
  include/sys/zil.h
  include/zfeature_common.h
  lib/libzfs/libzfs.abi
  man/man4/zfs.4
  man/man7/zpool-features.7
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zpl_xattr.c
  module/zcommon/zfeature_common.c
  module/zfs/zfs_log.c
  module/zfs/zfs_replay.c
  module/zfs/zfs_sa.c
  module/zfs/zil.c
  tests/runfiles/common.run
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
  tests/zfs-tests/tests/functional/slog/Makefile.am
  tests/zfs-tests/tests/functional/slog/slog_016_pos.ksh
Labels: Type: Feature, Status: Accepted

#13147 Linux 5.11 compat: x86 SIMD: fix kernel_fpu_{begin,end}() detection
  config/kernel-fpu.m4
Labels: Status: Accepted

#13084 Add Linux kmemleak support to ZTS
  scripts/zfs-tests.sh
  tests/test-runner/bin/test-runner.py.in
  tests/test-runner/man/test-runner.1
Labels: Component: Test Suite, Status: Accepted

#13141 Fix directory detection in `dkms.mkconf`
  scripts/dkms.mkconf
Labels: Type: Building, Status: Accepted

#13023 zed: Misc multipath autoreplace fixes
  cmd/zed/agents/zfs_mod.c
  cmd/zed/zed_disk_event.c
  lib/libzutil/os/linux/zutil_device_path_os.c
Labels: Component: ZED, Status: Accepted

#13155 ztest: Fix ASSERT in ztest_objset_destroy_cb()
  cmd/ztest/ztest.c
Labels: Component: Test Suite, Status: Accepted

#13154 Fix erroneous zstreamdump warning
  cmd/zstream/zstream_dump.c
Labels: Status: Accepted, Component: Send/Recv

#13121 Do not run zfsexpandknoweldge if zfs_devs function is present in dracut
  contrib/dracut/02zfsexpandknowledge/module-setup.sh.in
Labels: Component: Dracut, Status: Accepted
