Repository openzfs/zfs, pull requests merged in 2022-10, with the labels that each got.

#13971 Fix userland dereference NULL return value bugs
  cmd/zstream/zstream_token.c
  cmd/ztest.c
  lib/libzfs/libzfs_dataset.c
Labels: Status: Code Review Needed

#13977 Avoid unnecessary metaslab_check_free calling
  module/zfs/zio.c
Labels: Status: Accepted

#13985 Remove ambiguity on demand vs prefetch stats reported by arc_summary
  cmd/arc_summary
Labels: Status: Accepted

#13979 Handle possible null pointers from malloc/strdup/strndup()
  cmd/zed/agents/fmd_serd.c
  cmd/zed/agents/zfs_mod.c
  cmd/zed/zed_exec.c
  cmd/ztest.c
  lib/libzfs/libzfs_sendrecv.c
  lib/libzutil/zutil_import.c
  tests/zfs-tests/cmd/badsend.c
  tests/zfs-tests/cmd/btree_test.c
  tests/zfs-tests/cmd/file/largest_file.c
  tests/zfs-tests/cmd/nvlist_to_lua.c
Labels: Status: Accepted

#13998 zvol_wait logic may terminate prematurely
  cmd/zvol_wait
Labels: Status: Accepted

#14003 Stop ganging due to past vdev write errors
  module/zfs/metaslab.c
Labels: Status: Accepted

#14001 FreeBSD: Fix a pair of bugs in zfs_fhtovp()
  module/os/freebsd/zfs/zfs_vfsops.c
Labels: Status: Accepted

#14012 scripts/enum-extract.pl should not hard code perl path
  scripts/enum-extract.pl
Labels: Status: Accepted

#14020 etc: mask zfs-load-key.service [2.1.7]
  etc/systemd/system/Makefile.am
Labels: Status: Accepted

#14023 kcfpool_alloc() should have its argument list marked void
  module/icp/core/kcf_sched.c
Labels: Status: Accepted

#13987 cstyle: Allow URLs in C++ comments
  scripts/cstyle.pl
Labels: Status: Accepted

#14025 zfs_domount: fix double-disown of dataset / double-free of zfsvfs_t
  module/os/linux/zfs/zfs_vfsops.c
Labels: Status: Accepted

#14008 Fix potential NULL pointer dereference in lzc_ioctl()
  lib/libzfs_core/libzfs_core.c
Labels: Status: Accepted

#13986 Cleanup: Address Clang's static analyzer's unused code complaints
  cmd/raidz_test/raidz_test.c
  cmd/zfs/zfs_main.c
  lib/libefi/rdwr_efi.c
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_diff.c
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs/libzfs_util.c
  lib/libzutil/os/linux/zutil_device_path_os.c
  module/icp/algs/blake3/blake3.c
  module/icp/algs/modes/ccm.c
  module/icp/algs/modes/ctr.c
  module/icp/algs/modes/gcm.c
  module/lua/ldo.c
  module/os/freebsd/zfs/zfs_znode.c
  module/os/freebsd/zfs/zio_crypt.c
  module/os/linux/zfs/zfs_znode.c
  module/os/linux/zfs/zio_crypt.c
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dsl_bookmark.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_pool.c
  module/zfs/mmp.c
  module/zfs/spa.c
  module/zfs/vdev.c
  module/zfs/zcp_get.c
  tests/zfs-tests/cmd/btree_test.c
  tests/zfs-tests/cmd/ctime.c
  tests/zfs-tests/cmd/draid.c
  tests/zfs-tests/cmd/mkbusy.c
  tests/zfs-tests/cmd/user_ns_exec.c
Labels: Status: Accepted

#13997 zstream: allow decompress to fix metadata for uncompressed records
  cmd/zstream/zstream_decompress.c
  man/man8/zstream.8
Labels: Status: Accepted

#13947 Fix theoretical array overflow in lua_typename()
  module/lua/lapi.c
Labels: Status: Code Review Needed

#13970 Fix declarations of non-global variables
  cmd/zdb/zdb.c
  cmd/zstream/zstream_dump.c
  cmd/ztest.c
  module/os/linux/spl/spl-condvar.c
  module/os/linux/spl/spl-err.c
  module/os/linux/spl/spl-generic.c
  module/os/linux/spl/spl-kmem-cache.c
  module/os/linux/zfs/abd_os.c
  module/os/linux/zfs/zfs_debug.c
  module/os/linux/zfs/zvol_os.c
  module/zfs/zio.c
  module/zfs/zio_compress.c
  tests/zfs-tests/cmd/btree_test.c
  tests/zfs-tests/cmd/checksum/edonr_test.c
  tests/zfs-tests/cmd/checksum/sha2_test.c
  tests/zfs-tests/cmd/checksum/skein_test.c
  tests/zfs-tests/cmd/mmap_libaio.c
Labels: Status: Accepted

#14048 Coverity model file update
  contrib/coverity/model.c
Labels: Status: Accepted

#14040 Linux 6.1 regression: Fix failure to compile due to mutex_init() macro in Linux 6.1-rc1
  module/os/linux/spl/spl-procfs-list.c
  module/os/linux/spl/spl-zone.c
Labels: Status: Accepted

#14047 ZED: Fix uninitialized value reads
  cmd/zed/agents/fmd_api.c
  cmd/zed/agents/zfs_mod.c
Labels: Status: Accepted

#13973 Fix memory leaks in dmu_send()/dmu_send_obj()
  module/zfs/dmu_send.c
Labels: Status: Accepted

#13671 Support idmapped mount
  config/kernel-idmap_mnt_api.m4
  config/kernel.m4
  include/os/freebsd/spl/sys/types.h
  include/os/freebsd/zfs/sys/zfs_vnops_os.h
  include/os/linux/spl/sys/cred.h
  include/os/linux/spl/sys/types.h
  include/os/linux/zfs/sys/policy.h
  include/os/linux/zfs/sys/zfs_vnops_os.h
  include/os/linux/zfs/sys/zpl.h
  include/sys/zfs_acl.h
  module/os/freebsd/zfs/zfs_acl.c
  module/os/freebsd/zfs/zfs_dir.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/freebsd/zfs/zfs_znode.c
  module/os/linux/zfs/policy.c
  module/os/linux/zfs/zfs_acl.c
  module/os/linux/zfs/zfs_dir.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_znode.c
  module/os/linux/zfs/zpl_ctldir.c
  module/os/linux/zfs/zpl_file.c
  module/os/linux/zfs/zpl_inode.c
  module/os/linux/zfs/zpl_super.c
  module/os/linux/zfs/zpl_xattr.c
  module/zfs/zfs_replay.c
  module/zfs/zfs_vnops.c
  tests/runfiles/linux.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/cmd/.gitignore
  tests/zfs-tests/cmd/Makefile.am
  tests/zfs-tests/cmd/idmap_util.c
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/idmap_mount/cleanup.ksh
  tests/zfs-tests/tests/functional/idmap_mount/idmap_mount.cfg
  tests/zfs-tests/tests/functional/idmap_mount/idmap_mount_001.ksh
  tests/zfs-tests/tests/functional/idmap_mount/idmap_mount_002.ksh
  tests/zfs-tests/tests/functional/idmap_mount/idmap_mount_003.ksh
  tests/zfs-tests/tests/functional/idmap_mount/idmap_mount_004.ksh
  tests/zfs-tests/tests/functional/idmap_mount/idmap_mount_common.kshlib
  tests/zfs-tests/tests/functional/idmap_mount/setup.ksh
Labels: Type: Feature, Status: Accepted

#14050 Fix draid2+2s metadata error on simultaneous 2 drive failures
  module/zfs/vdev_rebuild.c
Labels: Status: Accepted

#13680 Add option none to zfs redundant_metadata property
  include/sys/dmu.h
  include/sys/fs/zfs.h
  man/man7/zfsprops.7
  module/zcommon/zfs_prop.c
  module/zfs/dmu.c
  module/zfs/dmu_objset.c
  module/zfs/dsl_prop.c
  tests/zfs-tests/include/properties.shlib
  tests/zfs-tests/tests/functional/inheritance/inherit_001_pos.ksh
Labels: Status: Accepted

#14045 Fix userland memory leak in zfs_do_send()
  cmd/zfs/zfs_main.c
Labels: Status: Accepted

#14058 Fix multiple definitions of struct mount_attr on recent glibc versions
  tests/zfs-tests/cmd/idmap_util.c
Labels: Status: Accepted

#13983 Linux: Upgrade random_get_pseudo_bytes() to xoshiro256++ 1.0
  module/os/linux/spl/spl-generic.c
Labels: Status: Accepted

#14061 Silence new static analyzer defect reports from idmap_util.c
  tests/zfs-tests/cmd/idmap_util.c
Labels: Status: Accepted

#13968 Linux: Fix big endian and partial read bugs in get_system_hostid()
  lib/libspl/os/linux/gethostid.c
Labels: Status: Accepted

#14052 Add delay between zpool add zvol and zpool destroy
  tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_004_pos.ksh
Labels: Status: Accepted

#14062 zed: Avoid core dump if wholedisk property does not exist
  cmd/zed/agents/zfs_mod.c
Labels: Status: Accepted

#14063 Fix sequential resilver drive failure race condition
  module/zfs/vdev_rebuild.c
Labels: Status: Code Review Needed

#14091 Linux 6.0 compat: META
  META
Labels: Status: Accepted

#14068 Silence objtool warnings from 55d7afa4adbb4ca569e9c4477a7d121f4dc0bfbd
  include/os/freebsd/spl/sys/debug.h
  include/os/linux/spl/sys/debug.h
Labels: Status: Accepted

#14069 FreeBSD: Fix a pair of bugs in zfs_fhtovp()
  module/os/freebsd/zfs/zfs_vfsops.c
Labels: Status: Accepted

#14079 [FreeBSD] vn_flush_cached_data: observe vnode locking contract
  include/os/freebsd/spl/sys/vnode.h
Labels: Status: Accepted

#14059 Aligned free for aligned alloc
  lib/libspl/include/umem.h
  lib/libzutil/zutil_import.c
  module/os/linux/zfs/abd_os.c
Labels: Status: Accepted

#14087 Add CodeQL workflow
  .github/workflows/codeql.yml
Labels: Status: Accepted

#14086 Convert enum zio_flag to uint64_t
  include/os/linux/zfs/sys/trace_common.h
  include/sys/dbuf.h
  include/sys/zio.h
  module/os/linux/zfs/vdev_disk.c
  module/zfs/dmu.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/dmu_send.c
  module/zfs/dmu_traverse.c
  module/zfs/vdev_queue.c
  module/zfs/zil.c
  module/zfs/zio.c
Labels: Status: Accepted

#14095 FreeBSD: vn_flush_cached_data: observe vnode locking contract
  include/os/freebsd/spl/sys/vnode.h
Labels: Status: Accepted

#14051 Process `script` directory for all configs
  Makefile.am
  scripts/Makefile.am
Labels: Component: Packaging, Status: Accepted

#14100 Fix zio_flag_t print format
  include/os/linux/zfs/sys/trace_common.h
Labels: Status: Accepted

#14094 codeQL Fix multiplication converted to larger type
  cmd/raidz_test/raidz_test.c
  lib/libefi/rdwr_efi.c
  module/zfs/arc.c
  tests/zfs-tests/cmd/stride_dd.c
Labels: Status: Accepted

#14077 Propagate extent_bytes change to autotrim thread.
  module/zfs/vdev_trim.c
Labels: Status: Accepted

#14093 Reclaim metadata when arc_available_memory < 0 even if meta_used is not bigger than arc_meta_limit
  module/zfs/arc.c
Labels: Status: Accepted

#13839 quota: extend quota for dataset
  module/zfs/dsl_dir.c
Labels: Status: Accepted

#14099 debug: fix output from VERIFY0 assertion
  include/os/freebsd/spl/sys/debug.h
  include/os/linux/spl/sys/debug.h
Labels: Status: Accepted

#14104 Revert "Cleanup: Delete dead code from send_merge_thread()"
  module/zfs/dmu_send.c
Labels: Type: Regression, Status: Accepted

#14103 Avoid null pointer dereference in dsl_fs_ss_limit_check()
  module/zfs/dsl_dir.c
Labels: Status: Accepted
