Repository openzfs/zfs, pull requests merged in 2022-04, with the labels that each got.

#13237 Use generic_permission() on Linux if ACL is trivial
  config/kernel-inode-permission.m4
  config/kernel.m4
  module/os/linux/zfs/zfs_acl.c
  module/os/linux/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#13267 Pull #12746 into 2.1.5
  man/man4/zfs.4
  module/zfs/dmu.c
Labels: Status: Accepted

#13277 FreeBSD: Use NDFREE_PNBUF if available
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#13286 Fix string/index variables being unflexed by default
  module/zcommon/zprop_common.c
Labels: Status: Accepted

#13293 Prefer ATTR_ in shared codebase over AT_
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#13276 cmd: zed: rc: drop "should be owned by root and 0600"
  cmd/zed/zed.d/Makefile.am
  cmd/zed/zed.d/zed.rc
Labels: Component: ZED, Status: Accepted

#13298 Backport of #13277 to the staging branch
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#13296 2.1 backport for #11560
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#13305 initramfs: use `mount.zfs` instead of `mount`
  contrib/initramfs/scripts/zfs
Labels: Status: Accepted

#13320 Fix `zpool history` sometimes fails without reporting any error
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted, Type: Defect

#12780 init.d/zfs-mount: Don't fsck or mount/umount fstab entries
  etc/init.d/zfs-mount.in
Labels: Status: Accepted

#13297 Linux 5.17 compat: GENHD_FL_EXT_DEVT / GENHD_FL_NO_PART_SCAN
  config/kernel-genhd-flags.m4
  config/kernel.m4
  module/os/linux/zfs/zvol_os.c
Labels: Component: ZVOL, Status: Accepted

#13347 Fix style checking error introduced by zfs-mount changes
  etc/init.d/zfs-mount.in
Labels: Status: Accepted

#13334 Improve the inline descriptions of the ARC module parameters
  module/zfs/arc.c
Labels: Status: Accepted

#13321 `zpool_history_unpack` didn't return correct errno on nvlist decoding failure
  lib/libzutil/zutil_pool.c
Labels: Status: Accepted

#13336 rpm -> deb doesn't fail when optional packages are missing
  config/deb.am
Labels: Status: Accepted

#13346 Linux 5.17 compat: GENHD_FL_EXT_DEVT / GENHD_FL_NO_PART_SCAN - 2.1 Backport
  config/kernel-genhd-flags.m4
  config/kernel.m4
  module/os/linux/zfs/zvol_os.c
Labels: Status: Accepted

#13345 FreeBSD: Fix translation from ABD to physical pages.
  module/os/freebsd/zfs/vdev_geom.c
Labels: Status: Accepted

#13351 Strengthen Linux kernel capabilities detection
  config/kernel-config-defined.m4
  config/kernel-group-info.m4
Labels: Status: Accepted

#13350 [2.1.5] Document zfs inherit -S's interaction with noninheritable properties
  man/man8/zfs-set.8
Labels: Status: Accepted

#13358 [2.1.5] FreeBSD: Fix translation from ABD to physical pages.
  module/os/freebsd/zfs/vdev_geom.c
Labels: Status: Accepted

#10662 zvol_wait: Ignore locked zvols
  cmd/zvol_wait/zvol_wait
Labels: Status: Accepted

#13369 [2.1.5] Linux 5.18 compat: kobj_type.default_attrs replaced with default_groups
  config/kernel-sysfs.m4
  config/kernel.m4
  module/os/linux/zfs/zfs_sysfs.c
Labels: Status: Accepted

#12812 Improved zpool status output, list all affected datasets
  include/sys/dsl_dataset.h
  include/sys/spa.h
  include/sys/zio.h
  include/zfeature_common.h
  lib/libnvpair/libnvpair.abi
  lib/libuutil/libuutil.abi
  lib/libzfs/libzfs.abi
  lib/libzfsbootenv/libzfsbootenv.abi
  man/man4/zfs.4
  man/man7/zpool-features.7
  module/zcommon/zfeature_common.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_destroy.c
  module/zfs/spa_errlog.c
  module/zfs/zfeature.c
  module/zfs/zfs_ioctl.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_status/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_003_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_004_pos.ksh
Labels: Status: Accepted

#12789 Improve log spacemap load time.
  include/sys/dmu.h
  include/sys/metaslab.h
  include/sys/metaslab_impl.h
  include/sys/spa_log_spacemap.h
  man/man4/zfs.4
  module/zfs/dmu.c
  module/zfs/metaslab.c
  module/zfs/spa.c
  module/zfs/spa_log_spacemap.c
  module/zfs/vdev.c
  module/zfs/vdev_removal.c
Labels: Status: Accepted

#13361 autoconf: Pretend `CONFIG_MODULES` is always on
  config/kernel-config-defined.m4
  config/kernel.m4
Labels: Type: Building, Status: Accepted

#13380 Linux 5.18 compat: __set_page_dirty_nobuffers replaced with filemap_dirty_folio
  config/kernel-vfs-filemap_dirty_folio.m4
  config/kernel.m4
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zpl_file.c
Labels: Type: Building, Status: Accepted

#13377 Fix O_APPEND for Linux 3.15 and older kernels
  module/os/linux/zfs/zpl_file.c
Labels: Status: Accepted

#13302 Make zfs_max_recordsize default to 16M
  man/man4/zfs.4
  module/zfs/dsl_dataset.c
  module/zfs/zio.c
  tests/zfs-tests/tests/functional/alloc_class/alloc_class_011_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_create/zfs_create_008_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zfs_set/zfs_set_001_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_023_neg.ksh
Labels: Status: Accepted

#13384 Linux 5.18 compat: replace __set_page_dirty_nobuffers - 2.1 backport
  config/kernel-vfs-filemap_dirty_folio.m4
  config/kernel.m4
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zpl_file.c
Labels: Status: Accepted

#13385 [2.1.5] zfs: holds: dequadratify
  cmd/zfs/zfs_main.c
Labels: Status: Accepted

#13381 Skip spacemaps reading in case of pool readonly import
  cmd/zdb/zdb.c
  include/sys/spa_impl.h
  module/zfs/metaslab.c
  module/zfs/spa.c
  module/zfs/vdev.c
Labels: Status: Accepted

#13382 Silence clang 13.0.0 false positive warnings
  module/zstd/lib/compress/fse_compress.c
  module/zstd/lib/compress/zstd_compress_superblock.c
Labels: Type: Building, Status: Accepted
