Repository openzfs/zfs, pull requests merged in 2022-09, with the labels that each got.

#13807 Alloc zdb_cd_t to fix stack issue
  cmd/zdb/zdb.c
Labels: Status: Accepted

#13832 FreeBSD: Cleanup dead code from VFS
  include/os/freebsd/spl/sys/vfs.h
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#13794 Apply arc_shrink_shift to ARC above arc_c_min.
  module/os/freebsd/zfs/arc_os.c
  module/zfs/arc.c
Labels: Status: Accepted

#13704 Add zilstat script to report zil kstats in a user friendly manner
  cmd/Makefile.am
  cmd/zilstat.in
  rpm/generic/zfs.spec.in
  tests/runfiles/common.run
  tests/runfiles/sanity.run
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_user/misc/zilstat_001_pos.ksh
Labels: Status: Accepted

#13802 add zfs.sync.snapshot_rename
  include/sys/dsl_dataset.h
  man/man8/zfs-program.8
  module/zfs/dsl_dataset.c
  module/zfs/zcp_synctask.c
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.snapshot_rename.ksh
  tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.snapshot_rename.zcp
Labels: Status: Accepted

#13819 DD_FIELD string for snapshots_changed property
  include/sys/dsl_dir.h
  module/zfs/dsl_dir.c
Labels: Status: Accepted

#13811 Fix column width in 'zpool iostat -v' and 'zpool list -v'
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#13834 Cleanup Raid-Z Typo fixes
  include/sys/vdev_raidz_impl.h
  module/zfs/vdev_raidz_math_impl.h
Labels: Status: Accepted

#13824 Add xattr_handler->get() support for Android kernels
  config/kernel-xattr-handler.m4
  include/os/linux/kernel/linux/xattr_compat.h
Labels: Status: Accepted

#13842 dbuf_is_metadata: ensure that it returns B_TRUE or B_FALSE
  include/sys/dmu.h
Labels: Status: Accepted

#13848 Fix build on FreeBSD/powerpc64*
  module/icp/algs/blake3/blake3_x86-64.c
Labels: Status: Accepted

#13694 Add Linux posix_fadvise support
  config/kernel-fadvise.m4
  config/kernel-generic_fadvise.m4
  config/kernel.m4
  module/os/linux/zfs/zpl_file.c
  tests/runfiles/linux.run
  tests/zfs-tests/cmd/.gitignore
  tests/zfs-tests/cmd/Makefile.am
  tests/zfs-tests/cmd/file/file_fadvise.c
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/checksum/filetest_002_pos.ksh
  tests/zfs-tests/tests/functional/fadvise/cleanup.ksh
  tests/zfs-tests/tests/functional/fadvise/fadvise_sequential.ksh
  tests/zfs-tests/tests/functional/fadvise/setup.ksh
  tests/zfs-tests/tests/functional/fault/auto_spare_002_pos.ksh
Labels: Status: Accepted

#13798 Improve too large physical ashift handling.
  include/sys/vdev_impl.h
  man/man4/zfs.4
  module/os/freebsd/zfs/vdev_geom.c
  module/zfs/vdev.c
  module/zfs/vdev_draid.c
  module/zfs/vdev_mirror.c
  module/zfs/vdev_raidz.c
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_add/add-o_ashift.ksh
Labels: Status: Accepted

#13729 zed: Fix config_sync autoexpand flood
  cmd/zed/agents/zfs_mod.c
  cmd/zed/zed_disk_event.c
  include/sys/sysevent/dev.h
Labels: Component: ZED, Status: Accepted

#13854 FreeBSD: Replace legacy make_dev() interface usage
  module/os/freebsd/zfs/kmod_core.c
Labels: Status: Accepted

#13775 make zfs-share service resilient to stale exports
  cmd/zfs/zfs_main.c
  etc/systemd/system/zfs-share.service.in
  include/libzfs.h
  lib/libshare/libshare.c
  lib/libshare/libshare_impl.h
  lib/libshare/nfs.c
  lib/libshare/nfs.h
  lib/libshare/os/freebsd/nfs.c
  lib/libshare/os/linux/nfs.c
  lib/libspl/include/libshare.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_mount.c
Labels: Status: Accepted

#13845 Cleanup: Use OpenSolaris functions to call scheduler
  include/os/freebsd/spl/sys/disp.h
  include/os/freebsd/spl/sys/timer.h
  include/os/freebsd/zfs/sys/zfs_context_os.h
  include/os/linux/spl/sys/disp.h
  include/sys/zfs_context.h
  module/zfs/arc.c
  module/zfs/dnode.c
  module/zfs/fm.c
  module/zfs/spa_log_spacemap.c
Labels: Status: Accepted

#13861 Fix use-after-free in btree code
  module/zfs/btree.c
Labels: Status: Accepted

#13865 vdev_draid_lookup_map() should not iterate outside draid_maps
  module/zfs/vdev_draid.c
Labels: Status: Accepted

#13866 zpool_load_compat() should create strings of length ZFS_MAXPROPLEN
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#13868 Cleanup dead spa_boot code
  include/Makefile.am
  include/sys/spa_boot.h
  lib/libzpool/Makefile.am
  module/Kbuild.in
  module/Makefile.bsd
  module/os/freebsd/zfs/spa_os.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/linux/zfs/zfs_vfsops.c
  module/zfs/spa.c
  module/zfs/spa_boot.c
Labels: Status: Accepted

#13863 Fix memory leak in ztest
  cmd/ztest.c
Labels: Status: Accepted

#13843 Cleanup: Make memory barrier definitions consistent across kernels
  include/os/freebsd/linux/compiler.h
  include/os/freebsd/spl/sys/atomic.h
  include/os/linux/spl/sys/vmsystm.h
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#13864 Remove incorrect free() in zfs_get_pci_slots_sys_path()
  lib/libzutil/os/linux/zutil_device_path_os.c
Labels: Status: Accepted

#13869 Fix theoretical "use-after-free" in dbuf_prefetch_indirect_done()
  module/zfs/dbuf.c
Labels: Status: Accepted

#13872 Add assertion to dsl_dataset_set_compression_sync
  module/zfs/dsl_dataset.c
Labels: Status: Accepted

#13882 FreeBSD: Fix integer conversion for vnlru_free{,_vfsops}()
  module/os/freebsd/zfs/arc_os.c
Labels: Status: Accepted

#13894 CI: revert `--with-config=dist` to hotfix Ubuntu 20.04
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  .github/workflows/zloop.yml
Labels: Status: Accepted

#13881 Fix use-after-free bugs in icp code
  module/icp/core/kcf_mech_tabs.c
  module/icp/core/kcf_prov_tabs.c
Labels: Status: Accepted

#13884 Add coverity model to repository
  contrib/coverity/model.c
Labels: Status: Accepted

#13893 ZTS: parameter expansion in zfs_unshare_006_pos
  tests/zfs-tests/include/libtest.shlib
Labels: Component: Test Suite, Status: Accepted

#13890 Use correct mdoc macros for arguments
  man/man7/zpoolprops.7
Labels: Type: Documentation, Status: Accepted

#13885 Fix incorrect size given to bqueue_enqueue() call in dmu_redact.c
  module/zfs/dmu_redact.c
Labels: Status: Accepted

#13874 Add zfs_btree_verify_intensity kernel module parameter
  cmd/zdb/zdb.c
  man/man4/zfs.4
  module/zfs/btree.c
Labels: Status: Accepted

#13831 zfs_enter rework
  include/os/freebsd/zfs/sys/zfs_znode_impl.h
  include/os/linux/zfs/sys/zfs_znode_impl.h
  include/sys/zfs_znode.h
  module/os/freebsd/zfs/zfs_ctldir.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_acl.c
  module/os/linux/zfs/zfs_ctldir.c
  module/os/linux/zfs/zfs_vfsops.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zpl_ctldir.c
  module/os/linux/zfs/zpl_file.c
  module/os/linux/zfs/zpl_super.c
  module/os/linux/zfs/zpl_xattr.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#13800 Fix unable to export zpool without nfs-utils
  lib/libshare/os/linux/nfs.c
Labels: Status: Accepted

#13901 Update coverity model
  contrib/coverity/model.c
Labels: Status: Accepted

#13855 zfs recv hangs if max recordsize is less than received recordsize
  include/sys/bqueue.h
  include/sys/fs/zfs.h
  module/zfs/bqueue.c
Labels: Status: Accepted

#13898 Handle ECKSUM as new EZFS_CKSUM ‒ "insufficient replicas"
  include/libzfs.h
  lib/libzfs/libzfs_util.c
Labels: Status: Accepted

#13889 Fix null pointer dereferences in PAM
  contrib/pam_zfs_key/pam_zfs_key.c
Labels: Status: Accepted

#13908 FreeBSD: stop passing LK_INTERLOCK to VOP_LOCK
  module/os/freebsd/zfs/zfs_ctldir.c
Labels: Status: Accepted

#13915 FreeBSD: fix static module build broken in 7bb707ffa
  include/os/freebsd/zfs/sys/arc_os.h
  module/os/freebsd/zfs/arc_os.c
  module/os/freebsd/zfs/sysctl_os.c
Labels: Status: Accepted

#13883 Linux: Fix use-after-free in zfsvfs_create()
  module/os/linux/zfs/zfs_vfsops.c
Labels: Status: Accepted

#13888 Fix usage of zed_log_msg() and zfs_panic_recover()
  cmd/zed/agents/fmd_api.c
  cmd/zed/agents/zfs_mod.c
  cmd/zed/zed_conf.c
  cmd/zed/zed_disk_event.c
  cmd/zed/zed_exec.c
  module/zfs/spa_checkpoint.c
Labels: Status: Accepted

#13900 Cleanup: Remove unused uu_pname code
  include/libuutil.h
  lib/libuutil/Makefile.am
  lib/libuutil/libuutil.abi
  lib/libuutil/uu_pname.c
Labels: Status: Accepted

#13923 FreeBSD: Fix uninitialized pointer read in spa_import_rootpool()
  module/os/freebsd/zfs/spa_os.c
Labels: Status: Accepted

#13924 FreeBSD: Cleanup zfs_readdir()
  include/os/freebsd/Makefile.am
  include/os/freebsd/spl/sys/extdirent.h
  include/os/freebsd/spl/sys/vnode_impl.h
  module/os/freebsd/zfs/zfs_dir.c
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#13878 Delay ZFS_PROP_SHARESMB property to handle it for encrypted raw receive
  module/zfs/zfs_ioctl.c
  tests/zfs-tests/tests/functional/rsend/send_encrypted_props.ksh
Labels: Status: Accepted, Component: Send/Recv

#13903 Fix potential NULL pointer dereference in zfsdle_vdev_online()
  cmd/zed/agents/zfs_mod.c
Labels: Status: Accepted

#13904 Call va_end() before return in zpool_standard_error_fmt()
  lib/libzfs/libzfs_util.c
Labels: Status: Accepted

#13909 FreeBSD: catch up to 1400068
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#13910 FreeBSD: handle V_PCATCH
  module/os/freebsd/zfs/zfs_file_os.c
Labels: Status: Accepted

#13918 Fix minor issues in namespace delegation support
  module/os/linux/spl/spl-zone.c
  tests/zfs-tests/tests/functional/user_namespace/user_namespace_002.ksh
  tests/zfs-tests/tests/functional/user_namespace/user_namespace_003.ksh
Labels: Status: Accepted

#13907 Add membar_sync
  include/os/freebsd/spl/sys/atomic.h
  include/os/linux/spl/sys/vmsystm.h
  lib/libspl/atomic.c
  lib/libspl/include/atomic.h
Labels: Status: Accepted

#13906 Retire ZFS_TEARDOWN_TRY_ENTER_READ
  include/os/freebsd/zfs/sys/zfs_vfsops_os.h
  include/os/linux/zfs/sys/zfs_vfsops_os.h
Labels: Status: Accepted

#13914 Cleanup: Change 1 used in bitshifts to 1ULL
  cmd/zdb/zdb.c
  module/zfs/dsl_scan.c
  module/zfs/metaslab.c
Labels: Status: Accepted

#13931 ZTS: fallocate tests fail with hard coded values
  tests/zfs-tests/tests/functional/fallocate/fallocate_punch-hole.ksh
  tests/zfs-tests/tests/functional/fallocate/fallocate_zero-range.ksh
Labels: Component: Test Suite, Status: Accepted

#13930 zpool: Don't print "repairing" on force faulted drives
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#13867 set_global_var_parse_kv() should pass the pointer from strdup()
  lib/libzpool/util.c
Labels: Status: Accepted

#13920 Fix unchecked return values and unused return values
  cmd/zdb/zdb.c
  cmd/zed/agents/zfs_retire.c
  cmd/zpool_influxdb/zpool_influxdb.c
  cmd/ztest.c
  lib/libzfsbootenv/lzbe_device.c
  module/zfs/dmu_recv.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_dir.c
  module/zfs/zfs_fm.c
  module/zfs/zvol.c
  tests/zfs-tests/cmd/draid.c
  tests/zfs-tests/cmd/file/file_fadvise.c
  tests/zfs-tests/cmd/mmap_sync.c
  tests/zfs-tests/cmd/mmapwrite.c
Labels: Status: Accepted

#13921 Fix userland resource leaks
  cmd/zdb/zdb.c
  cmd/zfs/zfs_main.c
  cmd/zhack.c
  cmd/zpool/zpool_main.c
  lib/libzfs/libzfs_dataset.c
  lib/libzutil/os/linux/zutil_device_path_os.c
  tests/zfs-tests/cmd/btree_test.c
  tests/zfs-tests/cmd/draid.c
Labels: Status: Accepted

#13936 Fix double declaration of getauxval() for FreeBSD PPC
  include/os/freebsd/spl/sys/simd_powerpc.h
  lib/libspl/include/sys/simd.h
Labels: Status: Accepted

#13944 Linux: Fix uninitialized variable usage in zio_do_crypt_data()
  module/os/linux/zfs/zio_crypt.c
Labels: Status: Accepted, Component: Encryption

#13871 Cleanup: Remove ineffective unsigned comparisons against 0
  module/icp/algs/blake3/blake3_impl.c
  module/os/freebsd/zfs/zfs_acl.c
  module/os/linux/zfs/zfs_acl.c
  module/os/linux/zfs/zvol_os.c
  module/zfs/arc.c
  module/zfs/dsl_dataset.c
  module/zfs/refcount.c
  module/zfs/vdev_queue.c
Labels: Status: Code Review Needed

#13955 Fix userspace memory leaks found by Clang Static Analyzer
  contrib/pam_zfs_key/pam_zfs_key.c
  module/zfs/zcp_get.c
  tests/zfs-tests/cmd/draid.c
  tests/zfs-tests/cmd/mkfile.c
Labels: Status: Accepted

#13954 Fix bad free in skein code
  module/icp/io/skein_mod.c
Labels: Status: Accepted

#13857 Enforce "-F" flag on resuming recv of full/newfs on existing dataset
  contrib/pyzfs/libzfs_core/_constants.py
  include/libzfs.h
  include/sys/fs/zfs.h
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs/libzfs_util.c
  module/zfs/dmu_recv.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/rsend/rsend_030_pos.ksh
Labels: Status: Accepted, Component: Send/Recv

#13876 Cleanup: Switch to strlcpy from strncpy
  cmd/zfs/zfs_main.c
  cmd/ztest.c
  config/Rules.am
  include/os/freebsd/spl/sys/kstat.h
  include/os/linux/spl/sys/kstat.h
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_diff.c
  lib/libzpool/taskq.c
  module/os/freebsd/spl/callb.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/linux/spl/spl-kmem-cache.c
  module/os/linux/spl/spl-kstat.c
  module/os/linux/spl/spl-thread.c
  module/os/linux/spl/spl-zone.c
  module/zfs/dsl_dir.c
  module/zfs/dsl_prop.c
  module/zfs/spa_misc.c
  module/zfs/zcp_get.c
  module/zfs/zfs_ioctl.c
  module/zfs/zio_inject.c
  tests/zfs-tests/cmd/draid.c
  tests/zfs-tests/cmd/zfs_diff-socket.c
Labels: Status: Accepted

#13875 Cleanup: Specify unsignedness on things that should not be signed
  cmd/zdb/zdb.c
  cmd/ztest.c
  include/sys/arc.h
  include/sys/arc_impl.h
  include/sys/dmu.h
  include/sys/dsl_pool.h
  include/sys/fm/util.h
  include/sys/spa.h
  include/sys/spa_impl.h
  include/sys/txg.h
  include/sys/vdev_impl.h
  include/sys/vdev_removal.h
  man/man4/zfs.4
  module/os/freebsd/zfs/arc_os.c
  module/os/freebsd/zfs/sysctl_os.c
  module/os/freebsd/zfs/zfs_debug.c
  module/os/linux/spl/spl-taskq.c
  module/os/linux/zfs/arc_os.c
  module/os/linux/zfs/zfs_debug.c
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_object.c
  module/zfs/dmu_recv.c
  module/zfs/dmu_send.c
  module/zfs/dmu_traverse.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_pool.c
  module/zfs/dsl_scan.c
  module/zfs/fm.c
  module/zfs/metaslab.c
  module/zfs/multilist.c
  module/zfs/refcount.c
  module/zfs/spa.c
  module/zfs/spa_errlog.c
  module/zfs/spa_misc.c
  module/zfs/spa_stats.c
  module/zfs/txg.c
  module/zfs/vdev.c
  module/zfs/vdev_cache.c
  module/zfs/vdev_indirect.c
  module/zfs/vdev_queue.c
  module/zfs/vdev_removal.c
  module/zfs/zfs_ioctl.c
  module/zfs/zil.c
  module/zfs/zio.c
  module/zstd/zfs_zstd.c
Labels: Status: Code Review Needed

#13949 LUA: Fix CVE-2014-5461
  module/lua/ldo.c
Labels: Status: Accepted

#13905 Cleanup spa_export_common()
  module/zfs/spa.c
Labels: Status: Accepted

#13913 Fix unsafe string operations
  cmd/zdb/zdb.c
  cmd/zfs/zfs_main.c
  cmd/zinject/translate.c
  cmd/ztest.c
  contrib/pam_zfs_key/pam_zfs_key.c
  lib/libshare/nfs.c
  lib/libspl/os/freebsd/mnttab.c
  lib/libzfs/libzfs_sendrecv.c
  lib/libzfs/os/linux/libzfs_util_os.c
  module/zfs/dmu_send.c
  module/zfs/dsl_dataset.c
  tests/zfs-tests/cmd/dir_rd_update.c
  tests/zfs-tests/cmd/mmap_sync.c
Labels: Status: Accepted

#13957 PAM: Fix uninitialized value read
  contrib/pam_zfs_key/pam_zfs_key.c
Labels: Status: Accepted

#13941 btree_test: smatch did detect few issues
  tests/zfs-tests/cmd/btree_test.c
Labels: Status: Accepted

#13938 Bring per_txg_dirty_frees_percent back to 30
  man/man4/zfs.4
  module/zfs/dmu.c
Labels: Status: Accepted

#13797 Fix for hotplug issues
  cmd/zed/agents/zfs_agents.c
  cmd/zed/agents/zfs_retire.c
  cmd/ztest.c
  config/kernel-blkdev.m4
  include/libzfs.h
  include/os/linux/Makefile.am
  include/os/linux/kernel/linux/blkdev_compat.h
  include/os/linux/spl/sys/misc.h
  include/sys/spa.h
  include/sys/vdev.h
  include/sys/vdev_impl.h
  include/sys/zfs_context.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_pool.c
  module/os/linux/spl/spl-generic.c
  module/os/linux/zfs/vdev_disk.c
  module/zfs/spa.c
  module/zfs/spa_config.c
  module/zfs/spa_misc.c
  module/zfs/vdev.c
  module/zfs/zfs_ioctl.c
  module/zfs/zio.c
  tests/zfs-tests/include/libtest.shlib
  tests/zfs-tests/tests/functional/fault/auto_offline_001_pos.ksh
Labels: Status: Accepted

#13943 Miscellaneous ZTS fixes
  tests/zfs-tests/cmd/draid.c
  tests/zfs-tests/cmd/file/file_trunc.c
  tests/zfs-tests/cmd/file/randwritecomp.c
  tests/zfs-tests/cmd/get_diff.c
  tests/zfs-tests/cmd/libzfs_input_check.c
  tests/zfs-tests/cmd/mmapwrite.c
  tests/zfs-tests/cmd/readmmap.c
  tests/zfs-tests/cmd/zed_fd_spill-zedlet.c
Labels: Status: Accepted

#13945 Fix unchecked return values
  cmd/zpool_influxdb/zpool_influxdb.c
  module/zfs/zfs_fm.c
Labels: Status: Accepted

#13939 Fix panic in dsl_process_sub_livelist for EINTR
  module/zfs/dsl_deadlist.c
Labels: Status: Accepted

#13946 Fix unreachable code in zstreamdump
  cmd/zstream/zstream_dump.c
Labels: Status: Accepted, Component: Encryption

#13902 Reduce false positives from Static Analyzers
  cmd/zed/zed_log.h
  contrib/coverity/model.c
  include/libuutil_impl.h
  include/os/freebsd/spl/sys/byteorder.h
  include/os/freebsd/spl/sys/cmn_err.h
  include/os/freebsd/spl/sys/debug.h
  include/os/freebsd/spl/sys/kmem.h
  include/os/linux/spl/sys/byteorder.h
  include/os/linux/spl/sys/cmn_err.h
  include/os/linux/spl/sys/debug.h
  include/os/linux/spl/sys/kmem.h
  include/sys/zfs_context.h
  lib/libspl/assert.c
  lib/libspl/include/assert.h
  lib/libspl/include/os/freebsd/sys/byteorder.h
  lib/libspl/include/os/linux/sys/byteorder.h
  lib/libspl/include/umem.h
  module/os/freebsd/spl/spl_misc.c
  module/os/linux/spl/spl-err.c
Labels: Status: Accepted

#13961 Fix double const qualifier declarations
  include/libzutil.h
  include/sys/dmu.h
  include/sys/zio_checksum.h
  include/sys/zio_compress.h
  lib/libzpool/util.c
  lib/libzutil/zutil_import.c
  lib/libzutil/zutil_import.h
  module/os/linux/zfs/zpl_ctldir.c
  module/zfs/dmu.c
  module/zfs/sa.c
  module/zfs/vdev.c
  module/zfs/zio_checksum.c
  module/zfs/zio_compress.c
Labels: Status: Code Review Needed

#13967 Fix potential NULL pointer dereference in dsl_dataset_promote_check()
  module/zfs/dsl_dataset.c
Labels: Status: Accepted
