Repository openzfs/zfs, pull requests merged in 2022-05, with the labels that each got.

#13395 Add missing replay entry in zvol_replay_vector for TX_SETSAXATTR
  module/zfs/zvol.c
Labels: Status: Accepted

#13400 Clean up the use of ioflags.
  include/os/freebsd/spl/sys/vnode.h
  lib/libspl/include/os/freebsd/sys/file.h
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/freebsd/zfs/zvol_os.c
Labels: Status: Accepted

#12790 Bug fix: Speed up WB_SYNC_NONE writebacks when a WB_SYNC_ALL writeback occurs simultaneously
  include/os/linux/zfs/sys/trace_acl.h
  include/os/linux/zfs/sys/zfs_vnops_os.h
  include/sys/zfs_znode.h
  module/os/freebsd/zfs/zfs_znode.c
  module/os/linux/zfs/zfs_ctldir.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_znode.c
  module/os/linux/zfs/zpl_file.c
  module/zfs/zfs_vnops.c
  tests/runfiles/common.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/cmd/.gitignore
  tests/zfs-tests/cmd/Makefile.am
  tests/zfs-tests/cmd/mmap_sync.c
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/functional/mmap/Makefile.am
  tests/zfs-tests/tests/functional/mmap/mmap_sync_001_pos.ksh
Labels: Status: Accepted

#13405 Reduce dbuf_find() lock contention
  include/sys/dbuf.h
  module/zfs/dbuf.c
  module/zfs/dbuf_stats.c
Labels: Status: Accepted

#13388 Improve mg_aliquot math.
  man/man4/zfs.4
  module/zfs/metaslab.c
Labels: Status: Accepted

#13403 Python 3.10 fixes, part 2 - 2.1 backport
  config/ax_python_devel.m4
Labels: Status: Accepted

#13406 FreeBSD: use zero_region instead of allocating a dedicated page
  module/os/freebsd/zfs/abd_os.c
Labels: Status: Accepted

#13375 Corrected edge case in uncompressed ARC->L2ARC handling
  module/zfs/arc.c
Labels: Status: Accepted

#13412 zpool: guard vs_noalloc and vs_pspace with VDEV_STAT_VALID()
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#13421 fix functions without a prototype
  module/icp/algs/modes/gcm.c
  module/os/linux/spl/spl-kmem-cache.c
  module/zfs/dbuf.c
Labels: Status: Accepted

#13418 Reduce dbuf_find() lock contention - 2.1. backport
  include/sys/dbuf.h
  module/zfs/dbuf.c
  module/zfs/dbuf_stats.c
Labels: Status: Accepted

#13437 man: zpool-import.8: -d -or -c
  man/man8/zpool-import.8
Labels: Status: Accepted

#13429 abd_os: remove redundant refcount creation for abd_children
  module/os/linux/zfs/abd_os.c
Labels: Status: Accepted

#13309 Add workaround for broken Linux pipes
  lib/libzfs_core/libzfs_core.c
  man/man8/zfs.8
Labels: Status: Accepted

#13436 Workaround broken VDEV_UPATH
  cmd/zpool/zpool.d/iostat
  cmd/zpool/zpool.d/lsblk
  cmd/zpool/zpool.d/smart
Labels: Status: Code Review Needed

#13424 Adding ZTS test for O_APPEND
  tests/runfiles/common.run
  tests/runfiles/sanity.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/cmd/.gitignore
  tests/zfs-tests/cmd/Makefile.am
  tests/zfs-tests/cmd/file/file_append.c
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/append/cleanup.ksh
  tests/zfs-tests/tests/functional/append/file_append.ksh
  tests/zfs-tests/tests/functional/append/setup.ksh
  tests/zfs-tests/tests/functional/append/threadsappend_001_pos.ksh
  tests/zfs-tests/tests/functional/threadsappend/.gitignore
Labels: Status: Accepted

#13337 Simplify/modernise/optimise udev/zvol_id
  udev/zvol_id.c
Labels: Status: Accepted

#13450 Added a workaround for Linux KASAN builds
  module/Kbuild.in
Labels: Status: Accepted

#13453 ztest: reduce runtile of zloop.sh in CI
  .github/workflows/zloop.yml
Labels: Component: Test Suite, Status: Accepted

#13454 Add missing AC_MSG_RESULT(no) to configure
  config/kernel-mkdir.m4
Labels: Type: Building, Status: Accepted

#13456 Fix typos in zfs-bookmark examples
  man/man8/zfs-bookmark.8
  man/man8/zfs.8
Labels: Status: Accepted

#13464 Backport fix for issue #13209 and #12988 to 2.1.5-staging
  Makefile.am
  module/zstd/Makefile.in
  module/zstd/include/zstd_compat_wrapper.h
Labels: Status: Accepted

#13467 FreeBSD: Implement hole-punching support - 2.1 backport
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/freebsd/zfs/zfs_znode.c
Labels: Status: Accepted

#13465 linux: Fix compiler warnings about zero-length arrays in inline bitops
  config/kernel-blk-queue.m4
Labels: Status: Accepted

#13466 Expose zpool guids through kstats
  include/sys/spa.h
  module/zfs/spa_stats.c
Labels: Status: Accepted

#13440 Support RFC5322 subject header for zed_notify_email()
  cmd/zed/zed.d/zed-functions.sh
  cmd/zed/zed.d/zed.rc
Labels: Status: Accepted

#13470 linux: libshare: smb: don't swallow net(1) errors
  lib/libshare/os/linux/smb.c
Labels: Status: Accepted

#13482 zdb: Fix handling of nul termination in symlink targets
  cmd/zdb/zdb.c
Labels: Status: Accepted

#13360 Verify BPs as part of spa_load_verify_cb()
  module/zfs/dsl_scan.c
  module/zfs/spa.c
  module/zfs/zio.c
Labels: Status: Accepted

#13499 zed: Take no action on scrub/resilver checksum errors
  cmd/zed/agents/zfs_diagnosis.c
Labels: Component: ZED, Status: Accepted

#13490 Modified ncompress requirement in RPM to exclude RHEL9
  rpm/generic/zfs-dkms.spec.in
  rpm/generic/zfs-kmod.spec.in
  rpm/generic/zfs.spec.in
Labels: Component: Packaging, Status: Accepted

#13484 FreeBSD: libspl: Add locking around statfs globals
  lib/libspl/os/freebsd/mnttab.c
Labels: Status: Accepted, Component: Userspace

#13244 zstd early abort
  include/sys/zstd/zstd.h
  man/man4/zfs.4
  module/zfs/zio_compress.c
  module/zstd/zfs_zstd.c
Labels: Status: Accepted

#13476 Refactor Log Size Limit.
  include/sys/dmu_tx.h
  include/sys/dsl_pool.h
  man/man4/zfs.4
  module/zfs/dmu_tx.c
  module/zfs/dsl_pool.c
Labels: Status: Accepted

#13489 rpm: Use the correct version-release information in dependencies
  rpm/generic/zfs.spec.in
Labels: Component: Packaging, Status: Accepted

#13502 Switch sed -E to -r for better portability
  configure.ac
Labels: Type: Building, Status: Accepted

#13506 Unbreak zstd build on sparc64
  include/sys/zstd/zstd.h
Labels: Status: Accepted

#13501 Standardize RHEL version check in packages
  rpm/generic/zfs-dkms.spec.in
  rpm/generic/zfs-kmod.spec.in
  rpm/generic/zfs.spec.in
Labels: Component: Packaging, Status: Accepted

#13500 Keep debug symbols if configured with '--enable-debuginfo'
  config/zfs-build.m4
Labels: Component: Packaging, Status: Accepted

#13498 Cancel in-progress rebuilds when we finish removal
  module/zfs/vdev_removal.c
Labels: Status: Accepted

#13503 automake: don't install /e/d/zfs or /e/z/zfs-functions +x
  etc/Makefile.am
Labels: Status: Accepted

#13487 dracut fixes - 2.1 backport
  contrib/dracut/90zfs/module-setup.sh.in
Labels: Status: Code Review Needed

#13507 Silence unused-but-set-variable warning
  include/sys/dnode.h
Labels: Type: Building, Status: Accepted

#13505 Replace EXTRA_DIST with dist_noinst_DATA
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  .github/workflows/zloop.yml
  Makefile.am
  cmd/Makefile.am
  cmd/zed/Makefile.am
  cmd/zed/zed.d/Makefile.am
  cmd/zpool/Makefile.am
  config/Substfiles.am
  config/zfs-build.m4
  contrib/bpftrace/Makefile.am
  contrib/dracut/Makefile.am
  contrib/initramfs/Makefile.am
  contrib/pyzfs/Makefile.am
  contrib/zcp/Makefile.am
  etc/Makefile.am
  lib/libnvpair/Makefile.am
  lib/libuutil/Makefile.am
  lib/libzfs/Makefile.am
  lib/libzfs_core/Makefile.am
  lib/libzfsbootenv/Makefile.am
  man/Makefile.am
  rpm/Makefile.am
  scripts/Makefile.am
  tests/Makefile.am
  tests/zfs-tests/cmd/Makefile.am
  tests/zfs-tests/tests/Makefile.am
Labels: Status: Accepted

#12321 Fix inflated quiesce time caused by lwb_tx during zil_commit().
  include/sys/zil_impl.h
  module/zfs/zil.c
Labels: Status: Accepted

#13527 Linux 5.18 compat: META
  META
Labels: Status: Accepted

#13519 Corrected parameters for zstd early abort
  man/man4/zfs.4
Labels: Status: Accepted
