Repository openzfs/zfs, pull requests merged in 2022-12, with the labels that each got.

#14241 autoconf: add support for openEuler
  config/zfs-build.m4
Labels: Status: Accepted

#14235 nopwrites on dmu_sync-ed blocks can result in a panic
  module/zfs/zio.c
  tests/zfs-tests/tests/functional/nopwrite/nopwrite.shlib
  tests/zfs-tests/tests/functional/removal/removal_nopwrite.ksh
Labels: Status: Accepted

#14236 zio can deadlock during device removal
  module/zfs/zio.c
Labels: Status: Accepted

#14261 FreeBSD: zfs_register_callbacks() must implement error check correctly
  module/os/freebsd/zfs/zfs_vfsops.c
Labels: Status: Accepted

#14247 Micro-optimize fletcher4 calculations
  module/zcommon/zfs_fletcher_aarch64_neon.c
  module/zcommon/zfs_fletcher_avx512.c
  module/zcommon/zfs_fletcher_intel.c
  module/zcommon/zfs_fletcher_sse.c
  module/zcommon/zfs_fletcher_superscalar.c
  module/zcommon/zfs_fletcher_superscalar4.c
Labels: Status: Accepted

#14266 ZTS: Add missing tests to Makefile.am
  tests/runfiles/sanity.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/renameat2/Makefile.am
Labels: Component: Test Suite, Status: Accepted

#14271 dracut: skip zfsexpandknoweldge when zfs_devs is present in dracut - Backport
  contrib/dracut/02zfsexpandknowledge/module-setup.sh.in
Labels: Status: Accepted

#14159 Bypass metaslab throttle for removal allocations
  module/zfs/metaslab.c
  module/zfs/vdev_removal.c
Labels: Status: Accepted

#14244 Linux PPC: Fix build failures on kernels built without CONFIG_SPE
  include/os/linux/kernel/linux/simd_powerpc.h
Labels: Status: Accepted

#14242 [2.1.8] Use Ubuntu 20.04 and remove Ubuntu 18.04 from workflows
  .github/workflows/zfs-tests-functional.yml
Labels: Status: Accepted

#14254 Restrict visibility of per-dataset kstats inside FreeBSD jails
  module/os/freebsd/spl/spl_kstat.c
Labels: Status: Accepted

#14220 skip permission checks for extended attributes
  module/os/linux/zfs/zfs_dir.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zpl_xattr.c
  tests/zfs-tests/tests/functional/acl/posix/posix_004_pos.ksh
Labels: Status: Accepted

#14274 initramfs: Fix legacy mountpoint rootfs
  contrib/initramfs/scripts/zfs
Labels: Status: Code Review Needed, Component: Userspace

#14176 Address theoretical uninitialized variable usage in zstream
  cmd/zstream/zstream_decompress.c
  cmd/zstream/zstream_recompress.c
  cmd/zstream/zstream_redup.c
Labels: Status: Accepted

#14272 Change zpool email notifications to display the actual pool name instead of the pool GUID
  cmd/zed/zed.d/statechange-notify.sh
Labels: Component: ZED, Status: Code Review Needed

#14110 zfs list: Allow more fields in ZFS_ITER_SIMPLE mode
  cmd/zfs/zfs_iter.c
  cmd/zfs/zfs_iter.h
  cmd/zfs/zfs_main.c
  cmd/zpool/zpool_main.c
  contrib/pam_zfs_key/pam_zfs_key.c
  include/libzfs.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_changelist.c
  lib/libzfs/libzfs_crypto.c
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_iter.c
  lib/libzfs/libzfs_mount.c
  lib/libzfs/libzfs_sendrecv.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#14251 Cache dbuf_hash() calculation
  include/sys/dbuf.h
  module/zfs/dbuf.c
  module/zfs/dnode_sync.c
Labels: Status: Accepted

#14253 Allow reciever to override encryption property in case of replication
  lib/libzfs/libzfs_sendrecv.c
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_to_encrypted.ksh
Labels: Status: Accepted, Component: Send/Recv

#14255 Zero end of embedded block buffer in dump_write_embedded()
  module/zfs/dmu_send.c
Labels: Status: Accepted

#14265 Add native-deb* targets to build native Debian packages
  .github/workflows/build-dependencies.txt
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  config/deb.am
  config/zfs-build.m4
  configure.ac
  contrib/debian/.gitignore
  contrib/debian/control
  contrib/debian/openzfs-libpam-zfs.postinst
  contrib/debian/openzfs-zfs-zed.postinst
  contrib/debian/openzfs-zfs-zed.prerm
  contrib/debian/openzfs-zfsutils.install
  contrib/debian/openzfs-zfsutils.postinst
  contrib/debian/rules.in
  scripts/debian-packaging.sh
Labels: Component: Packaging, Status: Accepted

#14284 initramfs: Fix legacy mountpoint rootfs [2.1.8]
  contrib/initramfs/scripts/zfs
Labels: Status: Accepted

#14287 FreeBSD: Remove stray debug printf
  module/os/freebsd/zfs/kmod_core.c
Labels: Status: Accepted

#14288 Colorize zfs diff output
  include/libzutil.h
  lib/libzfs/libzfs_diff.c
  lib/libzfs/libzfs_util.c
  man/man8/zfs.8
Labels: Type: Feature, Component: Userspace

#14294 systemd: set restart=always for zfs-zed.service
  etc/systemd/system/zfs-zed.service.in
Labels: Status: Accepted

#14306 Revert "zdb: zdb_ddt_leak_init() reads uninitialized memory..."
  cmd/zdb/zdb.c
Labels: Status: Accepted

#14307 Documentation corrections
  CODE_OF_CONDUCT.md
  contrib/initramfs/scripts/zfs
Labels: Status: Accepted

#14289 deadlock between spa_errlog_lock and dp_config_rwlock
  cmd/zpool/zpool_main.c
  cmd/ztest.c
  include/sys/spa.h
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_status.c
  module/zfs/dsl_scan.c
  module/zfs/spa.c
  module/zfs/spa_errlog.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#14291 FreeBSD: Fix potential boot panic with bad label
  module/os/freebsd/zfs/spa_os.c
Labels: Status: Accepted

#14123 arc_read()/arc_access() refactoring and cleanup.
  include/os/linux/zfs/sys/trace_arc.h
  include/sys/arc.h
  include/sys/arc_impl.h
  module/zfs/arc.c
  module/zfs/dmu_traverse.c
  module/zfs/dmu_zfetch.c
  tests/zfs-tests/tests/functional/cli_root/zfs_property/zfs_written_property_001_pos.ksh
  tests/zfs-tests/tests/functional/l2arc/l2arc_mfuonly_pos.ksh
  tests/zfs-tests/tests/functional/trim/autotrim_config.ksh
  tests/zfs-tests/tests/functional/trim/trim_config.ksh
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_trim.ksh
Labels: Status: Accepted
