Repository openzfs/zfs, pull requests merged in 2023-03, with the labels that each got.

#14544 icp: Prevent compilers from optimizing away memset() in gcm_clear_ctx()
  module/icp/algs/modes/modes.c
  module/icp/include/modes/modes.h
Labels: Status: Accepted

#14508 Makefile.bsd: cleanup and sync with FreeBSD
  module/Makefile.bsd
Labels: Status: Accepted

#14539 man: note that zdb operates directly on pool storage
  man/man8/zdb.8
Labels: Status: Accepted

#14549 mancheck: exclude dotfiles in man dir
  scripts/mancheck.sh
Labels: Status: Accepted

#14532 Handle unexpected errors in zil_lwb_commit() without ASSERT()
  module/zfs/zil.c
Labels: Type: Regression, Status: Accepted

#14554 Update space reclaim script
  .github/workflows/scripts/reclaim_disk_space.sh
Labels: Status: Accepted

#14534 Linux: zfs_fillpage() should handle partial pages from end of file
  module/os/linux/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#14556 Remove bad kmem_free() oversight from previous zfsdev_state_list patch
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#14514 Fix data race between zil_commit() and zil_suspend()
  include/sys/zil_impl.h
  module/zfs/zil.c
Labels: Status: Accepted

#14540 Accommodate debug-kernel stack frame size
  config/kernel-blk-queue.m4
Labels: Type: Building, Status: Accepted

#14516 System-wide speculative prefetch limit.
  include/sys/arc_impl.h
  module/zfs/dmu_zfetch.c
Labels: Status: Accepted

#14503 zdb: add decryption support
  cmd/zdb/Makefile.am
  cmd/zdb/zdb.c
  man/man8/zdb.8
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zdb/zdb_encrypted.ksh
Labels: Status: Accepted

#14569 Restore ASMABI and other Unify work
  module/icp/algs/blake3/blake3_impl.c
  module/icp/algs/sha2/sha256_impl.c
  module/icp/algs/sha2/sha512_impl.c
  module/icp/asm-x86_64/sha2/sha256-x86_64.S
  module/icp/asm-x86_64/sha2/sha512-x86_64.S
Labels: Status: Accepted

#14583 Fix memory leak in ztest
  cmd/ztest.c
Labels: Status: Accepted

#14563 Optimize the is_l2cacheable functions
  module/zfs/dbuf.c
  module/zfs/dmu_objset.c
Labels: Status: Accepted

#14565 [FreeBSD] zfs_znode_alloc: lock the vnode earlier
  module/os/freebsd/zfs/zfs_znode.c
Labels: Status: Accepted

#14576 Fix detection of IBM Power8 machines (ISA 2.07)
  module/icp/algs/sha2/sha256_impl.c
  module/icp/algs/sha2/sha512_impl.c
Labels: Status: Accepted

#14572 initramfs: fix zpool get argument order
  contrib/initramfs/scripts/zfs
Labels: Status: Accepted

#14588 [2.1.10] Optimize the is_l2cacheable functions
  module/zfs/dbuf.c
  module/zfs/dmu_objset.c
Labels: Status: Code Review Needed

#14587 [2.1.10] Add missing increment to dsl_deadlist_move_bpobj()
  module/zfs/dsl_deadlist.c
Labels: Status: Code Review Needed

#14567 spl: Add cmn_err_once() to log a message only on the first call
  include/os/freebsd/spl/sys/cmn_err.h
  include/os/linux/spl/sys/cmn_err.h
  lib/libspl/include/sys/cmn_err.h
Labels: Status: Accepted

#14566 [FreeBSD] fix false assert in cache_vop_rmdir when replaying ZIL
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#14592 Fix a typo in ac2038a
  cmd/zdb/zdb.c
Labels: Status: Accepted

#14595 [2.1.10] Turn default_bs and default_ibs into ZFS_MODULE_PARAMs
  man/man4/zfs.4
  module/os/freebsd/zfs/sysctl_os.c
  module/zfs/dnode.c
Labels: Status: Accepted

#14577 Better handling for future crypto parameters
  cmd/zdb/zdb.c
  contrib/pyzfs/libzfs_core/_constants.py
  include/sys/fs/zfs.h
  lib/libzfs/libzfs_crypto.c
  lib/libzfs/libzfs_sendrecv.c
  module/zfs/dsl_crypt.c
Labels: Status: Accepted

#14591 Failed to build on powerpc* if Linux was configured without CONFIG_ALTIVEC or CONFIG_VSX
  include/os/linux/kernel/linux/simd_powerpc.h
Labels: Status: Accepted

#14589 [2.1.10] initramfs: fix zpool get argument order
  contrib/initramfs/scripts/zfs
Labels: Status: Code Review Needed

#14519 Do not hold spa_config in ZIL while blocked on IO
  module/zfs/zil.c
Labels: Status: Accepted

#14529 ICP: AES-GCM: Unify gcm_init_ctx() and gmac_init_ctx()
  module/icp/algs/modes/gcm.c
Labels: Status: Accepted

#14359 More adaptive ARC eviction.
  cmd/arc_summary
  cmd/zdb/zdb.c
  include/sys/arc.h
  include/sys/arc_impl.h
  man/man4/zfs.4
  module/os/freebsd/zfs/arc_os.c
  module/os/freebsd/zfs/sysctl_os.c
  module/os/linux/zfs/arc_os.c
  module/zfs/arc.c
  tests/zfs-tests/tests/perf/perf.shlib
Labels: Status: Accepted, Status: Design Review Needed

#14564 GitHub actions updated for zfs-2.1.10-staging
  .github/workflows/build-dependencies.txt
  .github/workflows/checkstyle-dependencies.txt
  .github/workflows/checkstyle.yaml
  .github/workflows/scripts/reclaim_disk_space.sh
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  .github/workflows/zloop.yml
  contrib/initramfs/scripts/Makefile.am
  scripts/Makefile.am
  tests/Makefile.am
Labels: Status: Code Review Needed

#14283 txg_sync should handle write errors in ZIL
  module/zfs/dbuf.c
Labels: Status: Accepted

#13392 Block Cloning
  cmd/zdb/zdb_il.c
  cmd/ztest.c
  include/Makefile.am
  include/os/freebsd/zfs/sys/zfs_znode_impl.h
  include/os/linux/kernel/linux/mod_compat.h
  include/os/linux/zfs/sys/zfs_znode_impl.h
  include/sys/bitmap.h
  include/sys/brt.h
  include/sys/dbuf.h
  include/sys/ddt.h
  include/sys/dmu.h
  include/sys/dmu_tx.h
  include/sys/fs/zfs.h
  include/sys/spa_impl.h
  include/sys/zfs_debug.h
  include/sys/zfs_vnops.h
  include/sys/zfs_znode.h
  include/sys/zil.h
  include/sys/zio.h
  include/sys/zio_impl.h
  include/zfeature_common.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_pool.c
  lib/libzpool/Makefile.am
  man/man7/zpool-features.7
  man/man7/zpoolprops.7
  module/Kbuild.in
  module/Makefile.bsd
  module/os/freebsd/zfs/sysctl_os.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/freebsd/zfs/zfs_znode.c
  module/zcommon/zfeature_common.c
  module/zcommon/zpool_prop.c
  module/zfs/brt.c
  module/zfs/dbuf.c
  module/zfs/ddt.c
  module/zfs/dmu.c
  module/zfs/dmu_tx.c
  module/zfs/dsl_scan.c
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/zfs_ioctl.c
  module/zfs/zfs_log.c
  module/zfs/zfs_quota.c
  module/zfs/zfs_replay.c
  module/zfs/zfs_vnops.c
  module/zfs/zil.c
  module/zfs/zio.c
  module/zfs/zvol.c
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
Labels: Status: Accepted

#14605 ABI files: sync with new Ubuntu release in CI
  lib/libnvpair/libnvpair.abi
  lib/libuutil/libuutil.abi
  lib/libzfs/libzfs.abi
  lib/libzfs_core/libzfs_core.abi
  lib/libzfsbootenv/libzfsbootenv.abi
Labels: Status: Accepted

#14600 zcommon: Refactor FPU state handling in fletcher4
  include/zfs_fletcher.h
  lib/libzfs/libzfs.abi
  module/zcommon/zfs_fletcher.c
  module/zcommon/zfs_fletcher_aarch64_neon.c
  module/zcommon/zfs_fletcher_avx512.c
  module/zcommon/zfs_fletcher_intel.c
  module/zcommon/zfs_fletcher_sse.c
  module/zcommon/zfs_fletcher_superscalar.c
  module/zcommon/zfs_fletcher_superscalar4.c
Labels: Status: Accepted

#13368 ZFS_IOC_COUNT_FILLED does unnecessary txg_wait_synced()
  module/zfs/dnode.c
Labels: Status: Accepted

#14625 Replace dead opensolaris.org license link #2
  include/sys/bitmap.h
  include/sys/brt.h
  module/zfs/brt.c
  tests/zfs-tests/cmd/renameat2.c
  tests/zfs-tests/tests/functional/renameat2/cleanup.ksh
  tests/zfs-tests/tests/functional/renameat2/renameat2_exchange.ksh
  tests/zfs-tests/tests/functional/renameat2/renameat2_noreplace.ksh
  tests/zfs-tests/tests/functional/renameat2/renameat2_whiteout.ksh
  tests/zfs-tests/tests/functional/renameat2/setup.ksh
  tests/zfs-tests/tests/functional/snapshot/snapshot_018_pos.ksh
Labels: Status: Accepted

#13618 Remove unused Edon-R variants
  include/sys/edonr.h
  module/icp/algs/edonr/edonr.c
  module/icp/algs/edonr/edonr_byteorder.h
  module/zfs/edonr_zfs.c
  tests/zfs-tests/cmd/checksum/edonr_test.c
Labels: Status: Accepted

#14604 initramfs: fix for mountpoint=legacy check
  contrib/initramfs/scripts/zfs
Labels: Status: Accepted

#14078 Split functional testings via github action matrix
  .github/workflows/README.md
  .github/workflows/scripts/generate-summary.sh
  .github/workflows/scripts/reclaim_disk_space.sh
  .github/workflows/scripts/setup-dependencies.sh
  .github/workflows/scripts/setup-functional.sh
  .github/workflows/zfs-linux-tests.yml
  .github/workflows/zfs-linux.yml
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  .github/workflows/zloop.yml
  tests/zfs-tests/callbacks/zfs_dbgmsg.ksh
  tests/zfs-tests/callbacks/zfs_dmesg.ksh
  tests/zfs-tests/callbacks/zfs_mmp.ksh
Labels: Status: Accepted

#14631 Failed to build on Debian Sid PowerPC using GCC 12.2
  lib/libspl/include/sys/simd.h
Labels: Status: Accepted

#14627 [2.1.10] ZFS_IOC_COUNT_FILLED does unnecessary txg_wait_synced()
  module/zfs/dnode.c
Labels: Status: Code Review Needed

#14628 [2.1.10] Fix for mountpoint=legacy
  contrib/initramfs/scripts/zfs
Labels: Status: Code Review Needed

#14629 spl: cmn_err_once() should be usable in brace-less if else statements
  include/os/freebsd/spl/sys/cmn_err.h
  include/os/linux/spl/sys/cmn_err.h
  lib/libspl/include/sys/cmn_err.h
Labels: Status: Accepted

#14634 Fix: add git repo checkout to testing workflows
  .github/workflows/zfs-linux-tests.yml
Labels: Status: Accepted

#14637 Refine some details for the github actions update
  .github/workflows/scripts/setup-dependencies.sh
  .github/workflows/zfs-linux-tests.yml
  .github/workflows/zfs-linux.yml
Labels: Status: Accepted

#14632 QAT: Fix uninitialized seed in QAT compression
  module/os/linux/zfs/qat_compress.c
Labels: Status: Accepted

#14618 Fix possible bad bit shift in dnode_next_offset_level()
  module/zfs/dnode.c
Labels: Status: Accepted

#14639 FreeBSD: Remove extra arc_reduce_target_size() call.
  module/os/freebsd/zfs/arc_os.c
Labels: Status: Accepted

#14617 Fix kmodtool for packaging mainline Linux
  scripts/kmodtool
Labels: Component: Packaging, Status: Code Review Needed

#14656 Fix build on FreeBSD.
  module/os/freebsd/zfs/spa_os.c
  module/os/freebsd/zfs/vdev_geom.c
  module/os/freebsd/zfs/zfs_ioctl_os.c
Labels: Status: Accepted

#14663 [2.1.10] Improve arc_read() error reporting
  module/zfs/arc.c
Labels: Status: Accepted

#14655 Fix cloning into already dirty dbufs.
  include/sys/dbuf.h
  module/zfs/dbuf.c
  module/zfs/dmu.c
Labels: Status: Accepted

#14652 panic loop when removing slog device
  include/sys/vdev.h
  module/zfs/vdev_label.c
Labels: Status: Accepted

#14648 [2.1.10] FreeBSD: Remove extra arc_reduce_target_size() call
  module/os/freebsd/zfs/arc_os.c
Labels: Status: Accepted

#14653 Update vdev state for spare vdev
  module/zfs/spa.c
Labels: Status: Accepted

#14668 Add another bdev_io_acct case for Linux 6.3+ compat
  config/kernel-generic_io_acct.m4
  include/os/linux/kernel/linux/blkdev_compat.h
Labels: Type: Building, Status: Accepted

#14672 [zfs-2.1.10] Update vdev state for spare vdev
  module/zfs/spa.c
Labels: Status: Accepted

#14669 config: don't link libudev on FreeBSD
  config/user.m4
Labels: Status: Accepted

#14677 [2.1.10] linux 6.3 compat: add another bdev_io_acct case
  config/kernel-generic_io_acct.m4
  include/os/linux/kernel/linux/blkdev_compat.h
Labels: Status: Accepted

#14641 Additional limits on hole reporting
  module/os/freebsd/zfs/zvol_os.c
  module/zfs/dmu.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#12194 Fix short-lived txg caused by autotrim
  include/sys/vdev_impl.h
  include/sys/vdev_trim.h
  module/zfs/spa.c
  module/zfs/vdev.c
  module/zfs/vdev_trim.c
Labels: Status: Accepted

#14633 Fixes in persistent error log
  include/sys/spa.h
  include/sys/spa_impl.h
  include/sys/zio.h
  man/man7/zpool-features.7
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu_send.c
  module/zfs/dsl_scan.c
  module/zfs/spa_errlog.c
  module/zfs/zio.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_003_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_005_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_006_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_007_pos.ksh
Labels: Status: Accepted

#14683 [2.1.10] Additional limits on hole reporting
  module/os/freebsd/zfs/zvol_os.c
  module/zfs/dmu.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#14689 Linux 6.2 compat: META
  META
Labels: Status: Accepted

#14694 Use vmem_zalloc to silence allocation warning
  module/os/linux/zfs/zfs_vfsops.c
Labels: Status: Accepted

#14695 kernel 6.3 compat: REQ_PREFLUSH without REQ_OP_WRITE returns error
  include/os/linux/kernel/linux/blkdev_compat.h
Labels: Status: Accepted

#14690 contrib: dracut: fix race with root=zfs:dset when necessities required
  contrib/dracut/90zfs/module-setup.sh.in
  contrib/dracut/90zfs/zfs-env-bootfs.service.in
  contrib/dracut/90zfs/zfs-generator.sh.in
  contrib/dracut/90zfs/zfs-lib.sh.in
  contrib/dracut/90zfs/zfs-nonroot-necessities.service.in
  contrib/dracut/90zfs/zfs-rollback-bootfs.service.in
  contrib/dracut/90zfs/zfs-snapshot-bootfs.service.in
  contrib/dracut/Makefile.am
  man/man7/dracut.zfs.7
Labels: Status: Accepted
