Repository openzfs/zfs, pull requests merged in 2023-08, with the labels that each got.

#15128 This fix an always false `if` in the `clonefile.c` test.
  tests/zfs-tests/cmd/clonefile.c
Labels: Status: Accepted

#15098 Linux 6.5 compat: register_sysctl_table removed in Linux 6.5
  config/kernel-register_sysctl_table.m4
  config/kernel.m4
  module/os/linux/spl/spl-proc.c
Labels: Status: Accepted

#15101 Linux 6.5: Define zfs_check_media_change when disk_check_media_change exists
  include/os/linux/kernel/linux/blkdev_compat.h
Labels: Status: Accepted

#15099 Linux 6.5 blkdev change fixes
  config/kernel-blkdev.m4
  config/kernel-block-device-operations.m4
  include/os/linux/kernel/linux/blkdev_compat.h
  module/os/linux/zfs/vdev_disk.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zpl_ctldir.c
  module/os/linux/zfs/zvol_os.c
Labels: Status: Accepted

#15117 linux: zfs: ctldir: set [amc]time to snapshot's creation property
  module/os/linux/zfs/zfs_ctldir.c
Labels: Status: Accepted

#15123 zdb: include cloned blocks in block statistics
  cmd/zdb/zdb.c
  include/sys/brt.h
  module/zfs/brt.c
Labels: Status: Accepted

#15130 readmmap.c: fix building with MUSL libc
  tests/zfs-tests/cmd/readmmap.c
Labels: Status: Accepted

#15131 linux/copy_file_range: properly request a fallback copy on Linux <5.3
  module/os/linux/zfs/zpl_file_range.c
  tests/runfiles/linux.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/block_cloning/block_cloning_copyfilerange_fallback.ksh
Labels: Status: Accepted

#15129 zpool_vdev_remove() should handle EALREADY error return
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#15134 Revert "Linux 6.5 compat: register_sysctl_table removed"
  config/kernel-register_sysctl_table.m4
  config/kernel.m4
  module/os/linux/spl/spl-proc.c
Labels: Status: Accepted

#15125 [2.1] Linux 6.4 compat: META
  META
Labels: Status: Accepted

#15135 [2.2] readmmap.c: fix building with MUSL libc
  tests/zfs-tests/cmd/readmmap.c
Labels: Status: Accepted

#15136 [2.2] linux: zfs: ctldir: set [amc]time to snapshot's creation property
  module/os/linux/zfs/zfs_ctldir.c
Labels: Status: Accepted

#15137 [2.2] zpool_vdev_remove() should handle EALREADY error return
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#15138 register_sysctl_table removed in Linux 6.5 (try to fix #2)
  config/kernel-register_sysctl_table.m4
  config/kernel.m4
  module/os/linux/spl/spl-proc.c
Labels: Status: Accepted

#15141 Fix some typos
  include/sys/metaslab_impl.h
  module/zfs/metaslab.c
Labels: Status: Accepted

#15076 Refactor dmu_prefetch().
  include/sys/dmu.h
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/zfs/dmu.c
  module/zfs/dsl_deadlist.c
  module/zfs/spa_log_spacemap.c
  module/zfs/zvol.c
Labels: Type: Performance, Status: Accepted

#15144 linux/spl/kmem_cache: undefine `kmem_cache_alloc` before defining it
  include/os/linux/spl/sys/kmem_cache.h
Labels: Status: Accepted

#15155 Linux 6.5: Replace generic_file_splice_read with filemap_splice_read
  config/kernel-filemap-splice-read.m4
  config/kernel-vfs-iov_iter.m4
  config/kernel.m4
  module/os/linux/zfs/zpl_file.c
Labels: Status: Accepted

#15113 libzfs: sendrecv: send_progress_thread: handle SIGINFO/SIGUSR1
  lib/libzfs/Makefile.am
  lib/libzfs/libzfs_sendrecv.c
  man/man8/zfs-send.8
Labels: Status: Accepted

#15148 zfs_clone_range should return a more descriptive return value
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zpl_file_range.c
  module/zfs/brt.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#15149 dracut: support mountpoint=legacy for root dataset
  contrib/dracut/90zfs/zfs-env-bootfs.service.in
Labels: Status: Accepted

#15160 Packaging: Move zinject from openzfs-zfs-test to openzfs-zfsutils package
  contrib/debian/openzfs-zfs-test.install
  contrib/debian/openzfs-zfsutils.install
Labels: Status: Accepted

#15164 [Linux 6.5] Use copy_splice_read instead of filemap_splice_read
  config/kernel-filemap-splice-read.m4
  config/kernel.m4
  module/os/linux/zfs/zpl_file.c
Labels: Status: Accepted

#15153 ZIL: Avoid dbuf_read() before dmu_sync().
  include/sys/dmu.h
  include/sys/dmu_impl.h
  module/zfs/dmu.c
  module/zfs/zfs_vnops.c
  module/zfs/zvol.c
Labels: Status: Accepted

#15132 ZIL: Replay blocks without next block pointer.
  module/zfs/zil.c
Labels: Status: Accepted

#15172 copy_file_range: fix fallback when source create on same txg
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zpl_file_range.c
  module/zfs/zfs_vnops.c
  tests/runfiles/linux.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/block_cloning/block_cloning_copyfilerange_fallback_same_txg.ksh
Labels: Status: Accepted

#15122 ZIL: Second attempt to reduce scope of zl_issuer_lock.
  cmd/ztest.c
  include/sys/zil_impl.h
  module/zfs/zfs_vnops.c
  module/zfs/zil.c
  module/zfs/zio.c
  module/zfs/zvol.c
Labels: Status: Code Review Needed

#15187 Cherrypick 2 snapshot fixes for 2.1.13
  module/os/linux/zfs/zfs_ctldir.c
Labels: Status: Accepted

#15180 Update outdated assertion from zio_write_compress
  module/zfs/zio.c
Labels: Status: Accepted

#15210 zed: update zed.d/statechange-slot_off.sh
  cmd/zed/zed.d/Makefile.am
  cmd/zed/zed.d/statechange-slot_off.sh
Labels: Status: Accepted

#15168 Avoid save/restoring AMX registers to avoid a SPR erratum
  include/os/linux/kernel/linux/simd_x86.h
Labels: Status: Accepted

#15179 Try to clarify wording to reduce zpool add incidents
  man/man8/zpool.8
Labels: Status: Accepted

#15018 Increase limit of redaction list by using spill block
  cmd/zdb/zdb.c
  cmd/zfs/zfs_main.c
  include/sys/dsl_bookmark.h
  include/zfeature_common.h
  lib/libzfs/libzfs.abi
  man/man7/zpool-features.7
  module/zcommon/zfeature_common.c
  module/zfs/dmu_redact.c
  module/zfs/dnode.c
  module/zfs/dsl_bookmark.c
  module/zfs/dsl_destroy.c
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
  tests/zfs-tests/tests/functional/redacted_send/redacted_many_clones.ksh
Labels: Status: Accepted

#15220 checkstyle: fix action failures
  cmd/zed/zed.d/statechange-slot_off.sh
  man/man8/zpool.8
Labels: Status: Accepted
