Repository openzfs/zfs, pull requests merged in 2023-10, with the labels that each got.

#15331 Report ashift of L2ARC devices in zdb
  cmd/zdb/zdb.c
  module/zfs/vdev_label.c
Labels: Status: Accepted

#15333 Fix invalid pointer access in trace_dbuf.h
  include/os/linux/zfs/sys/trace_dbuf.h
Labels: Status: Accepted

#15322 Add '-u' - nomount flag for zfs set
  cmd/zfs/zfs_main.c
  include/libzfs.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_changelist.c
  lib/libzfs/libzfs_dataset.c
  man/man7/zfsprops.7
  man/man8/zfs-set.8
  tests/runfiles/common.run
  tests/runfiles/sanity.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_set/zfs_set_nomount.ksh
Labels: Status: Accepted

#15339 Add BTI landing pads to the AArch64 SHA2 assembly
  module/icp/asm-aarch64/sha2/sha256-armv8.S
  module/icp/asm-aarch64/sha2/sha512-armv8.S
Labels: Status: Accepted

#15348 [2.2] Add BTI landing pads to the AArch64 SHA2 assembly
  module/icp/asm-aarch64/sha2/sha256-armv8.S
  module/icp/asm-aarch64/sha2/sha512-armv8.S
Labels: Status: Accepted

#15340 ARC: Remove b_cv from struct l1arc_buf_hdr
  include/sys/arc_impl.h
  module/zfs/arc.c
Labels: Status: Accepted

#15332 CI: add FreeBSD build with Cirrus CI
  .cirrus.yml
  .gitignore
Labels: Status: Code Review Needed

#15350 ARC: Remove b_bufcnt/b_ebufcnt from ARC headers
  include/os/linux/zfs/sys/trace_arc.h
  include/sys/arc_impl.h
  module/zfs/arc.c
Labels: Status: Accepted

#15319 Reduce number of metaslab preload taskq threads.
  include/sys/metaslab_impl.h
  include/sys/spa_impl.h
  man/man4/zfs.4
  module/os/freebsd/zfs/sysctl_os.c
  module/zfs/metaslab.c
  module/zfs/spa.c
Labels: Status: Accepted

#15362 zfsconcepts: add description of block cloning
  man/man7/zfsconcepts.7
Labels: Type: Documentation, Status: Accepted

#15365 rpm: Fix `make rpm` on Debian/Ubuntu
  config/zfs-build.m4
  rpm/generic/zfs.spec.in
Labels: Status: Accepted

#15353 ZIL: Reduce maximum size of WR_COPIED to 7.5KB
  man/man4/zfs.4
  module/zfs/zil.c
Labels: Status: Accepted

#15372 config/zfs-build.m4: add Gentoo's bash-completion path
  config/zfs-build.m4
Labels: Status: Accepted

#15368 FreeBSD: Reduce divergence from in-tree sources
  include/os/freebsd/spl/sys/atomic.h
  include/os/freebsd/spl/sys/ccompat.h
  include/os/freebsd/spl/sys/ctype.h
  include/os/freebsd/spl/sys/spl_condvar.h
  include/os/freebsd/zfs/sys/arc_os.h
  include/os/freebsd/zfs/sys/freebsd_event.h
  include/os/freebsd/zfs/sys/zfs_context_os.h
  include/sys/zfs_context.h
  module/os/freebsd/zfs/event_os.c
  module/os/freebsd/zfs/kmod_core.c
  tests/zfs-tests/cmd/dosmode_readonly_write.c
Labels: Status: Accepted

#15377 Move zpool_import_hostid_changed* tests to Linux runfile
  tests/runfiles/common.run
  tests/runfiles/linux.run
Labels: Status: Accepted

#15376 ZTS: Fix verify_fs_mount in delegate_common.kshlib
  tests/zfs-tests/tests/functional/delegate/delegate_common.kshlib
Labels: Status: Accepted

#15378 zvol: Temporally disable blk-mq
  man/man4/zfs.4
  module/os/linux/zfs/zvol_os.c
  tests/zfs-tests/include/tunables.cfg
Labels: Status: Accepted

#15386 Ensure we call fput when cloning fails due to different devices.
  module/os/linux/zfs/zpl_file_range.c
Labels: Status: Accepted

#15392 CI: Move perl script to dist_noinst_DATA
  scripts/Makefile.am
Labels: Status: Accepted

#15379 ZTS: Debug zfs_share_concurrent_shares failure
  tests/zfs-tests/tests/functional/cli_root/zfs_share/zfs_share_concurrent_shares.ksh
Labels: Status: Accepted

#15371 DMU: Do not pre-read holes during write
  module/zfs/dmu_tx.c
Labels: Status: Accepted

#15396 spec: define _bashcompletiondir if undefined
  rpm/generic/zfs.spec.in
Labels: Status: Code Review Needed

#15395 Zpool can start allocating from metaslab before TRIMs have completed
  module/zfs/vdev_trim.c
Labels: Status: Accepted

#15356 FreeBSD: Improve taskq wrapper
  include/os/freebsd/spl/sys/taskq.h
  module/os/freebsd/spl/spl_taskq.c
Labels: Status: Accepted

#14378 Large sync writes perform worse with slog
  man/man4/zfs.4
  module/zfs/zil.c
Labels: Type: Performance, Status: Accepted

#15405 Set spa_ccw_fail_time=0 when expanding a vdev.
  module/zfs/vdev.c
Labels: Status: Code Review Needed

#15416 FreeBSD: taskq: Remove unused declaration
  module/os/freebsd/spl/spl_taskq.c
Labels: Status: Accepted

#15417 fix typo in tests/zfs-tests/tests/functional/cli_user/misc/misc.cfg
  tests/zfs-tests/tests/functional/cli_user/misc/misc.cfg
Labels: Status: Accepted

#15402 Properly pad struct tx_cpu to cache line
  include/sys/txg_impl.h
Labels: Status: Accepted

#15364 run-zts test procfs/pool_state failed with uncorrectable I/O failure
  tests/zfs-tests/tests/functional/procfs/pool_state.ksh
Labels: Component: Test Suite, Status: Code Review Needed

#15390 Remove lock from dsl_pool_need_dirty_delay()
  module/zfs/dsl_pool.c
Labels: Status: Accepted

#15397 Trust ARC_BUF_SHARED() more
  module/zfs/arc.c
Labels: Status: Accepted

#14721 Do not persist user/group/project quota zap objects when unneeded
  module/zfs/zfs_quota.c
Labels: Type: Performance, Status: Accepted

#15406 spa: document HAVE_SPA_THREAD and use it in more places
  module/zfs/spa.c
Labels: Status: Accepted

#15438 Revert "Do not persist user/group/project quota zap objects when unneeded
  module/zfs/zfs_quota.c
Labels: Status: Accepted

#15427 arc_summary: "ARC prefetch metadata accesses:" appears twice in the output.
  cmd/arc_summary
Labels: Status: Accepted

#15436 Add prefetch property
  include/sys/dmu_objset.h
  include/sys/fs/zfs.h
  lib/libzfs/libzfs.abi
  man/man7/zfsprops.7
  module/zcommon/zfs_prop.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_zfetch.c
Labels: Status: Accepted

#15428 ABD: Be more assertive in iterators
  module/zfs/abd.c
Labels: Status: Accepted

#15381 ZIL: Detect single-threaded workloads
  include/sys/zil_impl.h
  man/man4/zfs.4
  module/zfs/zil.c
Labels: Status: Accepted

#15398 ZIO: Remove READY pipeline stage from root ZIOs
  cmd/zdb/zdb.c
  include/sys/zio_impl.h
  module/zfs/zil.c
  module/zfs/zio.c
Labels: Type: Performance, Status: Accepted

#15437 arc_default_max on Linux should match FreeBSD.
  man/man4/zfs.4
  module/os/linux/zfs/arc_os.c
Labels: Status: Accepted

#15360 Add mutex_enter_interruptible() for interruptible sleeping IOCTLs
  include/os/freebsd/spl/sys/mutex.h
  include/os/linux/spl/sys/mutex.h
  include/sys/spa.h
  include/sys/zfs_context.h
  lib/libzpool/kernel.c
  module/zfs/spa_config.c
  module/zfs/zfs_ioctl.c
Labels: Status: Accepted

#15451 Read prefetched buffers from L2ARC
  module/zfs/arc.c
Labels: Type: Performance, Status: Accepted

#15366 ZIL: Cleanup sync and commit handling
  include/os/freebsd/zfs/sys/zfs_vfsops_os.h
  include/sys/zfs_ioctl.h
  include/sys/zfs_znode.h
  include/sys/zvol_impl.h
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/freebsd/zfs/zvol_os.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zvol_os.c
  module/zfs/zfs_ioctl.c
  module/zfs/zfs_log.c
  module/zfs/zfs_vnops.c
  module/zfs/zvol.c
Labels: Status: Accepted

#15448 RAIDZ: Use cache blocking during parity math
  include/sys/abd.h
  module/zfs/abd.c
  module/zfs/vdev_raidz_math_impl.h
Labels: Type: Performance, Status: Accepted

#15452 Tune zio buffer caches and their alignments
  module/zfs/zio.c
Labels: Status: Accepted

#15456 Unify arc_prune_async() code
  include/os/linux/zfs/sys/zpl.h
  include/sys/arc.h
  include/sys/arc_impl.h
  module/os/freebsd/zfs/arc_os.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/linux/zfs/arc_os.c
  module/os/linux/zfs/zpl_super.c
  module/zfs/arc.c
Labels: Status: Accepted

#15459 Add all read-only compatible zpool features to grub2 compatibility
  cmd/zpool/compatibility.d/grub2
Labels: Status: Accepted

#15465 Fix block cloning between unencrypted and encrypted datasets
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#15468 Fix nfs_truncate_shares without /etc/exports.d
  lib/libshare/os/linux/nfs.c
Labels: Status: Accepted
