Repository openzfs/zfs, pull requests merged in 2023-01, with the labels that each got.

#14243 Implement uncached prefetch
  include/os/linux/zfs/sys/trace_arc.h
  include/sys/arc.h
  include/sys/arc_impl.h
  include/sys/dbuf.h
  include/sys/dnode.h
  module/os/freebsd/zfs/sysctl_os.c
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_tx.c
Labels: Type: Performance, Status: Accepted

#14320 Update arc_summary and arcstat outputs
  cmd/arc_summary
  cmd/arcstat.in
  man/man1/arcstat.1
Labels: Status: Code Review Needed

#14317 Pack zrlock_t by 8 bytes.
  include/sys/zrlock.h
Labels: Status: Accepted

#14349 [2.1.8] Add workaround for broken Linux pipes
  lib/libzfs/os/linux/libzfs_sendrecv_os.c
  man/man8/zfs.8
Labels: Status: Accepted

#14328 FreeBSD: catch up to 1400077
  module/os/freebsd/zfs/zfs_znode.c
Labels: Status: Accepted

#14316 [2.1.8] FreeBSD: Fix potential boot panic with bad label
  module/os/freebsd/zfs/spa_os.c
Labels: Status: Accepted

#14297 removal of LegacyVersion broke ax_python_dev.m4
  config/ax_python_devel.m4
Labels: Status: Code Review Needed

#14334 [2.1.8] zed: unclean disk attachment faults the vdev
  cmd/zed/agents/zfs_mod.c
  module/zfs/vdev.c
Labels: Status: Accepted

#14335 [2.1.8] Allow receiver to override encryption properties in case of replication
  lib/libzfs/libzfs_sendrecv.c
  tests/zfs-tests/tests/functional/cli_root/zfs_receive/zfs_receive_to_encrypted.ksh
Labels: Status: Accepted

#14336 [2.1.8] skip permission checks for extended attributes
  module/os/linux/zfs/zfs_dir.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zpl_xattr.c
  tests/zfs-tests/tests/functional/acl/posix/posix_004_pos.ksh
Labels: Status: Accepted

#14341 contrib: dracut: Do not timeout waiting for pw
  contrib/dracut/90zfs/zfs-load-key.sh.in
Labels: Status: Accepted

#14353 [ZTS] fclose in mmapwrite.c
  tests/zfs-tests/cmd/mmapwrite.c
Labels: Status: Accepted

#14340 Remove some dead ARC code.
  include/sys/arc.h
  module/zfs/arc.c
Labels: Status: Accepted

#14295 zed: add hotplug support for spare vdevs
  cmd/zed/agents/zfs_agents.c
  cmd/zed/agents/zfs_mod.c
  cmd/zed/agents/zfs_retire.c
  include/sys/fs/zfs.h
  lib/libzfs/libzfs_pool.c
  module/zfs/spa_config.c
Labels: Component: ZED, Status: Code Review Needed

#14360 libzpool: fix ddi_strtoull to update nptr
  lib/libzpool/kernel.c
Labels: Status: Accepted

#14356 ztest fails assertion in zio_write_gang_member_ready()
  module/zfs/zio.c
Labels: Status: Accepted

#14366 2.1.8-staging: ztest fails assertion in zio_write_gang_member_ready()
  module/zfs/zio.c
Labels: Status: Accepted

#14121 Batch enqueue/dequeue for bqueue
  include/sys/bqueue.h
  module/zfs/bqueue.c
Labels: Type: Performance, Status: Accepted, Component: Send/Recv

#14327 etc/systemd/zfs-mount-generator: avoid strndupa
  etc/systemd/system-generators/zfs-mount-generator.c
Labels: Status: Accepted

#14292 Add tunable to allow changing micro ZAP's max size
  man/man4/zfs.4
  module/zfs/dmu_tx.c
  module/zfs/zap_micro.c
Labels: Status: Accepted

#14371 Update META to 6.1 kernel
  META
Labels: Status: Accepted

#14311 zpool: do guid-based comparison in is_vdev_cb()
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#14374 CI: remove unused packages/snaps
  .github/workflows/scripts/reclaim_disk_space.sh
Labels: Component: Test Suite, Status: Accepted

#14304 Activate filesystem features only in syncing context
  module/zfs/dmu_objset.c
  module/zfs/dsl_dataset.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/rsend/send_encrypted_incremental.ksh
  tests/zfs-tests/tests/functional/rsend/send_raw_large_blocks.ksh
Labels: Status: Accepted

#14377 change how d_alias is replaced by du.d_alias
  include/os/linux/kernel/linux/dcache_compat.h
Labels: Status: Accepted

#14384 Linux ppc64le ieee128 compat: Do not redefine __asm on external headers
  module/zfs/vdev_raidz_math_powerpc_altivec_common.h
Labels: Status: Accepted

#14387 CI: Reclaim space after package operations
  .github/workflows/scripts/reclaim_disk_space.sh
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
Labels: Status: Accepted

#14380 Cleanup of dead code suggested by Clang Static Analyzer
  include/os/linux/spl/sys/kmem.h
  include/os/linux/spl/sys/kmem_cache.h
  module/os/freebsd/zfs/zfs_acl.c
  module/os/freebsd/zfs/zfs_znode.c
  module/os/linux/spl/spl-kmem-cache.c
  module/os/linux/spl/spl-thread.c
  module/os/linux/zfs/vdev_disk.c
  module/os/linux/zfs/zfs_acl.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_znode.c
  module/zcommon/zfs_fletcher.c
  module/zfs/fm.c
  module/zfs/zfs_ioctl.c
  module/zfs/zvol.c
  module/zstd/include/zstd_compat_wrapper.h
  module/zstd/lib/common/fse_decompress.c
Labels: Status: Accepted

#14376 Use setproctitle to report progress of zfs send
  cmd/zfs/zfs_main.c
  include/libzfs.h
  include/libzutil.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_sendrecv.c
  lib/libzutil/Makefile.am
  lib/libzutil/os/linux/zutil_setproctitle.c
  man/man8/zfs-send.8
  tests/zfs-tests/tests/functional/cli_root/zfs_send/zfs_send_006_pos.ksh
Labels: Status: Accepted

#14228 Unify linux assembly files
  include/Makefile.am
  include/os/freebsd/Makefile.am
  include/os/freebsd/spl/sys/ia32/asm_linkage.h
  include/os/linux/Makefile.am
  include/os/linux/spl/sys/ia32/asm_linkage.h
  include/sys/asm_linkage.h
  lib/libicp/Makefile.am
  lib/libspl/include/Makefile.am
  lib/libspl/include/os/freebsd/sys/ia32/asm_linkage.h
  lib/libspl/include/os/linux/sys/ia32/asm_linkage.h
  lib/libspl/include/sys/asm_linkage.h
  module/Kbuild.in
  module/icp/algs/aes/aes_impl_aesni.c
  module/icp/algs/blake3/blake3_impl.h
  module/icp/algs/blake3/blake3_x86-64.c
  module/icp/algs/modes/gcm.c
  module/icp/algs/modes/gcm_pclmulqdq.c
  module/icp/algs/sha2/sha2.c
  module/icp/asm-x86_64/aes/aes_amd64.S
  module/icp/asm-x86_64/blake3/blake3_avx2.S
  module/icp/asm-x86_64/blake3/blake3_avx512.S
  module/icp/asm-x86_64/blake3/blake3_sse2.S
  module/icp/asm-x86_64/blake3/blake3_sse41.S
  module/icp/asm-x86_64/modes/aesni-gcm-x86_64.S
  module/icp/asm-x86_64/modes/ghash-x86_64.S
  module/icp/asm-x86_64/sha2/sha256_impl.S
  module/icp/asm-x86_64/sha2/sha512_impl.S
  module/icp/include/aes/aes_impl.h
  module/icp/include/sys/ia32/stack.h
  module/icp/include/sys/ia32/trap.h
  module/lua/ldo.c
  module/lua/setjmp/setjmp_x86_64.S
Labels: Status: Accepted

#14400 Man: fix defaults for zfs_dirty_data_max_max
  man/man4/zfs.4
Labels: Status: Accepted

#14364 Fix unprotected zfs_znode_dmu_fini
  include/sys/zfs_znode.h
  module/os/freebsd/zfs/zfs_dir.c
  module/os/freebsd/zfs/zfs_znode.c
  module/os/linux/zfs/zfs_dir.c
  module/os/linux/zfs/zfs_znode.c
Labels: Status: Code Review Needed

#14408 Cleanup ->dd_space_towrite should be unsigned
  include/sys/dsl_dir.h
  module/zfs/dsl_dir.c
Labels: Status: Accepted

#14379 zfs_receive_one: Check for the more likely error first
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#14404 Fix reading uninitialized variable in receive_read
  module/zfs/dmu_recv.c
Labels: Status: Accepted

#14407 free_blocks(): Fix reports from 2016 PVS Studio FreeBSD report
  module/zfs/dnode_sync.c
Labels: Status: Accepted

#13805 configure zed's diagnosis engine with vdev properties
  cmd/zed/agents/zfs_diagnosis.c
  include/sys/fm/fs/zfs.h
  include/sys/fs/zfs.h
  include/sys/vdev_impl.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_util.c
  man/man7/vdevprops.7
  module/zcommon/zpool_prop.c
  module/zfs/vdev.c
  module/zfs/zfs_fm.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/events/zed_cksum_config.ksh
  tests/zfs-tests/tests/functional/events/zed_io_config.ksh
Labels: Component: ZED, Status: Accepted

#14285 Reject streams that set ->drr_payloadlen to unreasonably large values
  cmd/zstream/zstream_decompress.c
  cmd/zstream/zstream_recompress.c
  cmd/zstream/zstream_redup.c
  lib/libzfs/libzfs_sendrecv.c
  module/zfs/dmu_recv.c
Labels: Status: Accepted

#14358 Wait for txg sync if the last DRR_FREEOBJECTS might result in a hole
  module/zfs/dmu_recv.c
  tests/runfiles/common.run
  tests/runfiles/sanity.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/rsend/send_encrypted_freeobjects.ksh
Labels: Status: Accepted, Component: Send/Recv

#14418 Introduce minimal ZIL block commit delay.
  man/man4/zfs.4
  module/zfs/zil.c
Labels: Status: Accepted

#14415 Linux 6.2 compat: set_acl arg2 is "struct dentry *" and no longer "struct inode *"
  config/kernel-acl.m4
  include/os/linux/zfs/sys/zpl.h
  module/os/linux/zfs/zpl_xattr.c
Labels: Status: Accepted

#14410 Improve resilver ETAs
  cmd/zpool/zpool_main.c
  man/man4/zfs.4
  module/zfs/dsl_scan.c
  module/zfs/spa_misc.c
Labels: Status: Accepted

#14402 Prefetch on deadlists merge.
  include/sys/bpobj.h
  module/zfs/bpobj.c
  module/zfs/dsl_deadlist.c
Labels: Type: Performance, Status: Accepted
