Repository openzfs/zfs, pull requests merged in 2023-07, with the labels that each got.

#15048 [2.1.13] Fix remount when setting multiple properties.
  lib/libzfs/libzfs_dataset.c
Labels: Status: Accepted

#15054 Update changelog for 2.2 for native Debian packages
  contrib/debian/changelog
Labels: Status: Accepted

#15036 FreeBSD: catch up to __FreeBSD_version 1400093
  include/os/freebsd/spl/sys/vnode.h
Labels: Status: Accepted

#15024 Add missed DMU_PROJECTUSED_OBJECT prefetch.
  module/zfs/dsl_scan.c
Labels: Status: Accepted

#15056 Avoid extra snprintf() in dsl_deadlist_merge().
  module/zfs/dsl_deadlist.c
Labels: Type: Performance, Status: Accepted

#15049 Fix the ZFS checksum error histograms with larger record sizes
  module/zfs/zfs_fm.c
Labels: Status: Accepted

#15039 Fix raw receive with different indirect block size.
  module/zfs/dmu_recv.c
  module/zfs/dnode.c
Labels: Status: Accepted

#15058 6.5-compat: intptr_t definition should be(?) signed but was unsigned
  include/os/linux/spl/sys/types.h
Labels: Type: Building, Status: Accepted

#15059 6.5-compat: BLK_STS_NEXUS is renamed to BLK_STS_RESV_CONFLICT
  config/kernel-blkdev.m4
  include/os/linux/kernel/linux/blkdev_compat.h
Labels: Status: Accepted

#15073 [2.1] Fix raw receive with different indirect block size.
  module/zfs/dmu_recv.c
  module/zfs/dnode.c
Labels: Status: Accepted

#15079 set autotrim default to 'off' everywhere
  include/sys/spa.h
  module/zcommon/zpool_prop.c
Labels: Status: Accepted

#15060 6.5-compat: disk_check_media_change() replaces bdev_check_media_change
  config/kernel-blkdev.m4
  include/os/linux/kernel/linux/blkdev_compat.h
Labels: Status: Accepted

#15029 Do not request data L1 buffers on scan prefetch.
  module/zfs/dsl_scan.c
Labels: Status: Accepted

#15025 Rollback before zfs root is mounted
  contrib/dracut/90zfs/zfs-rollback-bootfs.service.in
Labels: Status: Accepted

#15061 Ignore pool ashift property during vdev attachment
  include/sys/vdev_impl.h
  module/zfs/vdev.c
  tests/zfs-tests/tests/functional/cli_root/zpool_attach/attach-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_replace/replace-o_ashift.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_replace/replace_prop_ashift.ksh
Labels: Status: Accepted

#15063 Don't panic if setting vdev properties is unsupported for this vdev type
  module/zfs/vdev.c
Labels: Status: Accepted

#15067 spa_min_alloc should be GCD, not min
  include/sys/spa_impl.h
  module/zfs/spa_misc.c
  module/zfs/vdev.c
  module/zfs/zio.c
Labels: Status: Code Review Needed

#15077 Fix zpl_test_super race with zfs_umount
  module/os/linux/zfs/zfs_vfsops.c
  module/os/linux/zfs/zpl_super.c
Labels: Status: Accepted

#15084 zed: Fix zed ASSERT on slot power cycle
  cmd/zed/agents/zfs_retire.c
Labels: Status: Accepted

#15071 Add explicit prefetches to bpobj_iterate().
  include/sys/bpobj.h
  module/zfs/bpobj.c
Labels: Type: Performance, Status: Accepted

#15072 Adjust prefetch parameters.
  include/sys/dmu_zfetch.h
  man/man4/zfs.4
  module/zfs/dmu.c
  module/zfs/dmu_zfetch.c
Labels: Status: Accepted

#15088 metaslab: tuneable to better control force ganging
  man/man4/zfs.4
  module/zfs/metaslab.c
Labels: Status: Accepted

#15089 shellcheck: disable "unreachable command" check [SC2317]
  config/Shellcheck.am
Labels: Status: Accepted

#15095 Linux 6.4 compat: META
  META
Labels: Status: Accepted

#15080 ZIL: Fix config lock deadlock.
  module/zfs/zil.c
Labels: Status: Accepted

#15092 [2.1] zed: Fix zed ASSERT on slot power cycle
  cmd/zed/agents/zfs_retire.c
Labels: Status: Code Review Needed

#15104 Update changelog for OpenZFS 2.2.0 release
  contrib/debian/changelog
Labels: Status: Accepted

#15103 Remove zl_issuer_lock from zil_suspend().
  module/zfs/zil.c
Labels: Status: Accepted

#15094 zed: Reduce log noise for large JBODs
  cmd/zed/agents/zfs_mod.c
Labels: Status: Code Review Needed

#15108 [2.1] zed: Reduce log noise for large JBODs
  cmd/zed/agents/zfs_mod.c
Labels: Component: ZED, Status: Code Review Needed

#15096 Avoid waiting in dmu_sync_late_arrival().
  module/zfs/dmu.c
Labels: Status: Accepted

#15097 BRT EOPNOTSUPP more speaking return value
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#15116 BRT should return EOPNOTSUPP
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#15107 Remove fastwrite mechanism.
  include/sys/metaslab.h
  include/sys/vdev_impl.h
  include/sys/zil_impl.h
  include/sys/zio.h
  module/zfs/metaslab.c
  module/zfs/vdev.c
  module/zfs/zil.c
  module/zfs/zio.c
Labels: Status: Accepted
