Repository openzfs/zfs, pull requests merged in 2023-04, with the labels that each got.

#14699 Linux 6.3 compat: writepage_t first arg struct folio*
  config/kernel-writepage_t.m4
  config/kernel.m4
  module/os/linux/zfs/zpl_file.c
Labels: Status: Accepted

#14692 Fix some signedness issues in arc_evict().
  module/zfs/arc.c
Labels: Status: Code Review Needed

#14145 Storage device expansion "silently" fails on degraded vdev
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#14718 vdev: expose zfs_vdev_def_queue_depth as a module parameter
  man/man4/zfs.4
  module/os/freebsd/zfs/sysctl_os.c
  module/zfs/vdev_queue.c
Labels: Status: Accepted

#14674 Miscellaneous FreeBSD compilation bugfixes
  include/os/freebsd/spl/sys/simd_aarch64.h
  include/os/freebsd/spl/sys/simd_arm.h
  include/os/freebsd/spl/sys/simd_x86.h
  include/os/freebsd/spl/sys/vnode.h
  module/icp/algs/blake3/blake3.c
  module/icp/algs/blake3/blake3_generic.c
  module/icp/algs/blake3/blake3_impl.c
  module/icp/algs/sha2/sha256_impl.c
  module/icp/algs/sha2/sha512_impl.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/zcommon/zfs_fletcher.c
  module/zcommon/zfs_prop.c
  module/zfs/vdev_raidz_math.c
Labels: Status: Accepted

#14700 ZTS: Use inbuilt monotonic time
  tests/test-runner/bin/test-runner.py.in
Labels: Status: Accepted

#14701 ZTS: add existing tests to runfiles
  tests/runfiles/common.run
  tests/runfiles/linux.run
  tests/zfs-tests/tests/Makefile.am
Labels: Status: Accepted

#14702 Fix typo in check_clones()
  module/zfs/spa_errlog.c
Labels: Status: Accepted

#14719 vdev: expose zfs_vdev_max_ms_shift as a module parameter
  man/man4/zfs.4
  module/zfs/vdev.c
Labels: Status: Accepted

#14597 libzfs: add v2 iterator interfaces
  cmd/zfs/zfs_iter.c
  cmd/zfs/zfs_main.c
  cmd/zpool/zpool_main.c
  contrib/pam_zfs_key/pam_zfs_key.c
  include/libzfs.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_changelist.c
  lib/libzfs/libzfs_crypto.c
  lib/libzfs/libzfs_dataset.c
  lib/libzfs/libzfs_iter.c
  lib/libzfs/libzfs_mount.c
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#14682 Support idmapped mount for kernel 6.3
  config/kernel-acl.m4
  config/kernel-generic_fillattr.m4
  config/kernel-inode-create.m4
  config/kernel-inode-getattr.m4
  config/kernel-inode-permission.m4
  config/kernel-inode-setattr.m4
  config/kernel-is_owner_or_cap.m4
  config/kernel-mkdir.m4
  config/kernel-mknod.m4
  config/kernel-rename.m4
  config/kernel-setattr-prepare.m4
  config/kernel-symlink.m4
  config/kernel-tmpfile.m4
  config/kernel-xattr-handler.m4
  config/kernel.m4
  include/os/freebsd/spl/sys/types.h
  include/os/freebsd/zfs/sys/zfs_vnops_os.h
  include/os/linux/kernel/linux/vfs_compat.h
  include/os/linux/kernel/linux/xattr_compat.h
  include/os/linux/spl/sys/cred.h
  include/os/linux/spl/sys/types.h
  include/os/linux/zfs/sys/policy.h
  include/os/linux/zfs/sys/zfs_vnops_os.h
  include/os/linux/zfs/sys/zpl.h
  include/sys/zfs_acl.h
  module/os/freebsd/zfs/zfs_acl.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/spl/spl-cred.c
  module/os/linux/zfs/policy.c
  module/os/linux/zfs/zfs_acl.c
  module/os/linux/zfs/zfs_dir.c
  module/os/linux/zfs/zfs_ioctl_os.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_znode.c
  module/os/linux/zfs/zpl_ctldir.c
  module/os/linux/zfs/zpl_file.c
  module/os/linux/zfs/zpl_inode.c
  module/os/linux/zfs/zpl_xattr.c
  module/zfs/zfs_replay.c
  module/zfs/zfs_vnops.c
Labels: Status: Code Review Needed

#14716 Trim needless zeroes from checksum events
  module/zfs/zfs_fm.c
Labels: Status: Accepted

#14733 initramfs: source user/vendor scripts from /etc/zfs/initramfs-tools-load-key{,.d/*}
  contrib/initramfs/README.md
  contrib/initramfs/hooks/zfs.in
  contrib/initramfs/scripts/zfs
Labels: Status: Accepted

#14739 Fix data corruption when cloning embedded blocks.
  module/zfs/dmu.c
Labels: Status: Accepted

#14758 Fix VERIFY(!zil_replaying(zilog, tx)) panic.
  module/zfs/zfs_log.c
Labels: Status: Accepted

#14747 Work around Raspberry Pi kernel packaging oddities
  contrib/debian/control.modules.in
Labels: Status: Accepted

#14761 Revert "ZFS_IOC_COUNT_FILLED does unnecessary txg_wait_synced()"
  module/zfs/dnode.c
Labels: Status: Accepted

#14751 Values printed by zpool-iostat(8) should be right-aligned
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#14764 Silence clang warning of flexible array not at end
  include/sys/dmu_objset.h
Labels: Status: Accepted

#14765 zfsprops.7: update mandlock FUD
  man/man7/zfsprops.7
Labels: Status: Accepted

#14722 Fix "Detach spare vdev in case if resilvering does not happen"
  include/sys/spa.h
  module/zfs/spa.c
  module/zfs/vdev.c
Labels: Status: Accepted

#14767 zfs test send-c_volume is flaky
  tests/zfs-tests/tests/functional/rsend/send-c_volume.ksh
Labels: Status: Accepted

#14659 Allow MMP to bypass waiting for other threads
  include/sys/spa.h
  module/zfs/mmp.c
  module/zfs/spa_misc.c
Labels: Status: Accepted

#14405 create zap for root vdev
  cmd/zdb/zdb.c
  cmd/zpool/zpool_main.c
  include/sys/fs/zfs.h
  include/sys/vdev_impl.h
  include/zfeature_common.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_pool.c
  lib/libzutil/zutil_import.c
  man/man7/zpool-features.7
  module/zcommon/zfeature_common.c
  module/zfs/spa.c
  module/zfs/vdev.c
  module/zfs/vdev_label.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_get/vdev_get.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_get/vdev_get_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
  tests/zfs-tests/tests/functional/cli_root/zpool_set/vdev_set_001_pos.ksh
  tests/zfs-tests/tests/functional/vdev_zaps/vdev_zaps.kshlib
  tests/zfs-tests/tests/functional/vdev_zaps/vdev_zaps_001_pos.ksh
  tests/zfs-tests/tests/functional/vdev_zaps/vdev_zaps_002_pos.ksh
  tests/zfs-tests/tests/functional/vdev_zaps/vdev_zaps_003_pos.ksh
  tests/zfs-tests/tests/functional/vdev_zaps/vdev_zaps_004_pos.ksh
  tests/zfs-tests/tests/functional/vdev_zaps/vdev_zaps_005_pos.ksh
  tests/zfs-tests/tests/functional/vdev_zaps/vdev_zaps_006_pos.ksh
  tests/zfs-tests/tests/functional/vdev_zaps/vdev_zaps_007_pos.ksh
Labels: Status: Accepted

#14769 ZTS: zvol_misc_trim retry busy export
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_trim.ksh
Labels: Component: Test Suite, Status: Accepted

#11680 Add support for zpool user properties
  cmd/zpool/zpool_main.c
  include/libzfs.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_pool.c
  lib/libzfs/libzfs_util.c
  man/man7/zpoolprops.7
  module/zfs/spa.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_set/user_property_001_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_set/user_property_002_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_set/zpool_set_common.kshlib
Labels: Status: Accepted

#14776 FreeBSD: make zfs_vfs_held() definition consistent with declaration
  module/os/freebsd/zfs/zfs_ioctl_os.c
Labels: Status: Accepted

#14780 [zfs-2.1.12] Fix "Detach spare vdev in case if resilvering does not happen"
  include/sys/spa.h
  module/zfs/spa.c
  module/zfs/vdev.c
Labels: Status: Accepted

#14788 FreeBSD: add missing vop_fplookup assignments
  module/os/freebsd/zfs/zfs_ctldir.c
Labels: Status: Accepted

#14746 Taught zdb -bb to print metadata totals
  cmd/zdb/zdb.c
Labels: Status: Accepted

#13422 Add LoongArch support
  include/os/linux/spl/sys/isa_defs.h
  lib/libspl/include/sys/isa_defs.h
  module/lua/ldo.c
  module/lua/setjmp/setjmp.S
  module/lua/setjmp/setjmp_loongarch64.S
Labels: Type: Architecture, Status: Accepted

#14790 Revert "Fix data race between zil_commit() and zil_suspend()"
  include/sys/zil_impl.h
  module/zfs/zil.c
Labels: Status: Accepted

#14796 zdb: Fix minor memory leak
  cmd/zdb/zdb.c
Labels: Status: Accepted

#14799 Fix checkstyle warning
  module/os/freebsd/zfs/zfs_ctldir.c
Labels: Status: Accepted

#14728 Fix BLAKE3 freebsd aarch64
  module/icp/asm-aarch64/blake3/b3_aarch64_sse2.S
  module/icp/asm-aarch64/blake3/b3_aarch64_sse41.S
Labels: Status: Accepted

#14789 PAM: support the authentication facility
  contrib/pam_zfs_key/pam_zfs_key.c
Labels: Status: Accepted

#14798 Mark TX_COMMIT transaction with TXG_NOTHROTTLE
  module/zfs/zil.c
Labels: Status: Code Review Needed
