Repository openzfs/zfs, pull requests merged in 2023-02, with the labels that each got.

#14448 Fix console progress reporting for recursive send
  cmd/zfs/zfs_main.c
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#14430 rootdelay on zfs should be adaptive
  contrib/initramfs/scripts/zfs
Labels: Status: Accepted

#14439 Resolve WS-2021-0184 vulnerability in zstd
  module/zstd/lib/compress/zstd_double_fast.c
  module/zstd/lib/compress/zstd_fast.c
  module/zstd/lib/compress/zstd_lazy.c
Labels: Status: Accepted

#14441 zfs_main.c: fix unused variable error with GCC
  cmd/zfs/zfs_main.c
  include/libzutil.h
Labels: Status: Accepted

#14442 Teach zdb about DMU_OT_ERROR_LOG objects
  cmd/zdb/zdb.c
Labels: Status: Accepted

#14450 Prevent error messages when running tests with no timeout
  tests/test-runner/bin/test-runner.py.in
Labels: Status: Accepted

#14452 Fix variable shadowing in libzfs_mount
  lib/libzfs/libzfs_mount.c
Labels: Status: Accepted

#14460 Restore FreeBSD to use .rodata
  include/os/freebsd/spl/sys/ia32/asm_linkage.h
  lib/libspl/include/os/freebsd/sys/ia32/asm_linkage.h
Labels: Status: Accepted

#14440 EIO caused by encryption + recursive gang
  module/zfs/zio.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/no_space/enospc_ganging.ksh
Labels: Status: Accepted

#14455 initramfs: Make mountpoint=none work
  contrib/initramfs/scripts/zfs
Labels: Status: Accepted

#14464 zdb: zero-pad checksum output
  cmd/zdb/zdb.c
Labels: Status: Accepted

#14468 rpm: Use libtirpc-devel and /usr/lib on SUSE
  rpm/generic/zfs.spec.in
Labels: Status: Accepted

#14473 initramfs: Make mountpoint=none work [2.1.10]
  contrib/initramfs/scripts/zfs
Labels: Status: Accepted

#14474 Reduce need for contiguous memory for ioctls
  module/os/freebsd/zfs/kmod_core.c
  module/os/linux/zfs/zfs_ioctl_os.c
Labels: Status: Accepted

#13816 Fix a race condition in dsl_dataset_sync() when activating features
  include/sys/dsl_dataset.h
  module/zfs/dmu_send.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_scan.c
Labels: Status: Accepted

#14462 Quick fix for lingering snapdir unmount problems
  module/os/linux/zfs/zfs_ctldir.c
Labels: Status: Accepted

#14493 Linux: use filemap_range_has_page()
  config/kernel-filemap.m4
  config/kernel.m4
  include/os/freebsd/zfs/sys/zfs_znode_impl.h
  include/os/linux/zfs/sys/trace_acl.h
  include/os/linux/zfs/sys/zfs_znode_impl.h
  include/sys/zfs_znode.h
  module/os/linux/zfs/zfs_ctldir.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_znode.c
  module/os/linux/zfs/zpl_file.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#14472 Suppress Clang static analyzer complaint in zfs_replay_create()
  module/zfs/zfs_replay.c
Labels: Status: Accepted

#14497 zdb: zero-pad checksum output follow up
  include/sys/spa.h
Labels: Status: Accepted

#14479 zfs redact fails when dnodesize=auto
  module/zfs/dmu_object.c
Labels: Status: Accepted

#14282 Sync thread should avoid holding the spa config write lock when possible
  module/zfs/spa.c
Labels: Status: Accepted

#14502 Partially revert eee9362a7
  module/zfs/dmu_objset.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_scan.c
Labels: Status: Accepted

#14509 Fix per-jail zfs.mount_snapshot setting
  module/os/freebsd/zfs/zfs_vfsops.c
Labels: Status: Accepted

#14501 FreeBSD: don't verify recycled vnode for zfs control directory
  module/os/freebsd/zfs/zfs_ctldir.c
Labels: Status: Accepted

#14496 improve error message of zfs redact
  cmd/zfs/zfs_main.c
Labels: Status: Accepted

#14517 Use rw_tryupgrade() in dmu_bonus_hold_by_dnode()
  module/zfs/dmu.c
Labels: Status: Accepted

#14469 Fix NULL pointer dereference in zio_ready()
  module/zfs/zio.c
Labels: Status: Accepted

#14498 Fix buffered/mmap I/O race
  include/os/linux/zfs/sys/zfs_vnops_os.h
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zpl_file.c
  tests/runfiles/common.run
  tests/zfs-tests/cmd/mmap_sync.c
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/mmap/mmap_mixed.ksh
Labels: Status: Accepted

#14515 ZTS: Minor fixes
  tests/runfiles/common.run
  tests/zfs-tests/tests/functional/migration/migration_012_pos.ksh
Labels: Status: Accepted

#14526 Use .section .rodata instead of .rodata on FreeBSD
  include/os/freebsd/spl/sys/ia32/asm_linkage.h
  lib/libspl/include/os/freebsd/sys/ia32/asm_linkage.h
Labels: Status: Accepted

#14530 Workaround GitHub Action failure
  .github/workflows/checkstyle.yaml
  .github/workflows/zfs-tests-functional.yml
  .github/workflows/zfs-tests-sanity.yml
  .github/workflows/zloop.yml
Labels: Status: Code Review Needed

#14524 Ignore too large stack in case of dsl_deadlist_merge
  module/zfs/dsl_deadlist.c
Labels: Status: Accepted

#14528 ICP: AES-GCM: Refactor gcm_clear_ctx()
  module/icp/algs/modes/gcm.c
  module/icp/algs/modes/modes.c
  module/icp/include/modes/modes.h
  module/icp/io/aes.c
Labels: Status: Accepted

#14500 Skip memory allocation when compressing holes
  include/sys/zio_compress.h
  module/zfs/arc.c
  module/zfs/dmu_recv.c
  module/zfs/zio.c
  module/zfs/zio_compress.c
Labels: Type: Performance, Status: Accepted

#14527 man: Add vdevprops.7 to the Makefile
  man/Makefile.am
Labels: Status: Accepted

#14546 Revert zfeature_active() to static
  include/sys/dsl_dataset.h
  module/zfs/dsl_dataset.c
Labels: Status: Accepted
