Repository openzfs/zfs, pull requests merged in 2023-06, with the labels that each got.

#14919 [2.1.12] Fix NULL pointer dereference when doing concurrent 'send' operations
  module/zfs/dmu_send.c
Labels: Status: Accepted

#14921 [2.1.12] Move zap_attribute_t to the heap in dsl_deadlist_merge
  module/zfs/dsl_deadlist.c
Labels: Status: Accepted

#14910 ZIL: Allow to replay blocks of any size.
  module/zfs/zil.c
Labels: Status: Accepted

#14756 zfs-create(8): ZFS for swap: caution, grammar
  man/man8/zfs-create.8
Labels: Status: Accepted

#14929 [2.1.12] ZIL: Allow to replay blocks of any size.
  module/zfs/zil.c
Labels: Status: Accepted

#14930 Linux 6.3 compat: META
  META
Labels: Status: Code Review Needed

#14934 Introduce zfs_refcount_(add|remove)_few().
  include/sys/zfs_refcount.h
  module/zfs/dmu_zfetch.c
  module/zfs/metaslab.c
  module/zfs/refcount.c
Labels: Status: Accepted

#14924 [2.1.12] Fix Clang 15 compilation errors
  config/always-compiler-options.m4
  config/zfs-build.m4
  module/Kbuild.in
  module/icp/algs/edonr/edonr.c
  module/icp/algs/skein/skein_block.c
  module/lua/ldo.c
  module/os/linux/spl/spl-generic.c
  module/zcommon/Makefile.in
  module/zfs/Makefile.in
Labels: Status: Accepted

#14939 Fix the L2ARC write size calculating logic
  module/zfs/arc.c
Labels: Status: Accepted

#14945 Revert "systemd: Use non-absolute paths in Exec* lines"
  etc/systemd/system/zfs-import-cache.service.in
  etc/systemd/system/zfs-import-scan.service.in
  etc/systemd/system/zfs-mount.service.in
  etc/systemd/system/zfs-scrub@.service.in
  etc/systemd/system/zfs-share.service.in
  etc/systemd/system/zfs-trim@.service.in
  etc/systemd/system/zfs-volume-wait.service.in
  etc/systemd/system/zfs-zed.service.in
Labels: Status: Accepted

#14959 ZIL: Fix race introduced by f63811f0721.
  module/zfs/zil.c
Labels: Status: Accepted

#14955 Use list_remove_head() where possible.
  cmd/zed/agents/zfs_agents.c
  cmd/zed/agents/zfs_mod.c
  module/os/freebsd/zfs/zfs_acl.c
  module/os/linux/zfs/zfs_acl.c
  module/zfs/arc.c
  module/zfs/bplist.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_tx.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_dir.c
  module/zfs/dsl_scan.c
  module/zfs/fm.c
  module/zfs/refcount.c
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/vdev_indirect.c
  module/zfs/zfs_fm.c
  module/zfs/zfs_fuid.c
  module/zfs/zfs_onexit.c
  module/zfs/zvol.c
Labels: Status: Accepted

#14946 Improve l2arc reporting in arc_summary.
  cmd/arc_summary
Labels: Status: Accepted

#14952 ZTS: Skip checkpoint_discard_busy
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/functional/pool_checkpoint/checkpoint_discard_busy.ksh
Labels: Status: Accepted

#14953 Finally drop long disabled vdev cache.
  cmd/arc_summary
  cmd/zdb/zdb.c
  include/os/linux/kernel/linux/mod_compat.h
  include/sys/spa.h
  include/sys/vdev.h
  include/sys/vdev_impl.h
  include/sys/zio.h
  lib/libzpool/Makefile.am
  man/man4/zfs.4
  man/man8/zpool-events.8
  module/Kbuild.in
  module/Makefile.bsd
  module/os/freebsd/zfs/sysctl_os.c
  module/zfs/arc.c
  module/zfs/dmu_recv.c
  module/zfs/spa_misc.c
  module/zfs/vdev.c
  module/zfs/vdev_cache.c
  module/zfs/vdev_queue.c
  module/zfs/zio.c
Labels: Status: Accepted

#14954 Fix the L2ARC write size calculating logic (2)
  module/zfs/arc.c
Labels: Status: Accepted

#14970 Switch refcount tracking from lists to AVL-trees.
  include/sys/zfs_refcount.h
  module/zfs/refcount.c
Labels: Status: Accepted

#14961 ZTS: send_raw_ashift
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/tests/functional/rsend/send_raw_ashift.ksh
Labels: Component: Test Suite, Status: Accepted

#14948 Remove ARC/ZIO physdone callbacks.
  include/sys/arc.h
  include/sys/arc_impl.h
  include/sys/zio.h
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_objset.c
  module/zfs/zio.c
Labels: Status: Accepted, Status: Design Review Needed

#14981 Shorten arcstat_quiescence sleep time
  tests/zfs-tests/include/libtest.shlib
Labels: Status: Accepted

#14987 Fix memory leak in zil_parse().
  module/zfs/zil.c
Labels: Status: Accepted

#14938 Add a delay to tearing down threads on Linux.
  include/os/linux/spl/sys/taskq.h
  man/man4/spl.4
  module/os/linux/spl/spl-taskq.c
Labels: Status: Accepted

#14998 [2.1.13] Fix memory leak in zil_parse().
  module/zfs/zil.c
Labels: Status: Accepted

#14925 Another set of vdev queue optimizations.
  include/sys/vdev.h
  include/sys/vdev_impl.h
  include/sys/zio.h
  man/man4/zfs.4
  module/zfs/spa_misc.c
  module/zfs/txg.c
  module/zfs/vdev.c
  module/zfs/vdev_queue.c
Labels: Status: Accepted

#15011 Minor: Remove unnecessary commas in zpool-create.8
  man/man8/zpool-create.8
Labels: Status: Accepted

#14964 Use big transactions for small recordsize writes.
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#14999 ZIL: Fix another use-after-free.
  module/zfs/zil.c
Labels: Status: Accepted

#15016 spa.h: use IN_BASE instead of IN_FREEBSD_BASE
  include/sys/spa.h
Labels: Status: Accepted

#14992 contrib: dracut: Conditionalize copying of libgcc_s.so.1 to glibc only
  contrib/dracut/90zfs/module-setup.sh.in
Labels: Status: Accepted

#15000 Fix remount when setting multiple properties.
  lib/libzfs/libzfs_dataset.c
Labels: Status: Accepted

#15003 Don't use hard-coded 'size' value in snprintf()
  cmd/zfs/zfs_main.c
Labels: Status: Accepted

#15007 Do not report bytes skipped by scan as issued.
  cmd/zpool/zpool_main.c
  cmd/zpool_influxdb/zpool_influxdb.c
  include/sys/dsl_scan.h
  include/sys/fs/zfs.h
  include/sys/vdev_rebuild.h
  man/man8/zpool-scrub.8
  module/zfs/dsl_scan.c
  module/zfs/spa_misc.c
  module/zfs/vdev_rebuild.c
Labels: Status: Code Review Needed

#14985 Some ZIO micro-optimizations.
  include/sys/zio.h
  module/zfs/zio.c
Labels: Status: Accepted

#14979 Again fix race between zil_commit() and zil_suspend().
  module/zfs/zil.c
Labels: Status: Accepted

#15004 ddt_addref: remove unnecessary phys fill when refcount is 0
  module/zfs/ddt.c
Labels: Status: Accepted

#14654 Pack our DDT ZAPs a bit denser.
  man/man4/zfs.4
  module/zfs/ddt_zap.c
Labels: Status: Accepted

#15023 Enable tuning of ZVOL open timeout value
  module/os/linux/zfs/zvol_os.c
Labels: Status: Accepted
