Repository openzfs/zfs, pull requests merged in 2024-01, with the labels that each got.

#15711 compact: add check for kernel_neon_* availability
  config/kernel-fpu.m4
  include/os/linux/kernel/linux/simd_aarch64.h
  include/os/linux/kernel/linux/simd_arm.h
Labels: Type: Architecture, Status: Accepted

#15730 ZIL: Update Linux tracing after #15635
  include/os/linux/zfs/sys/trace_zil.h
Labels: Status: Accepted

#15727 zpoolprops.7: Remove unnecessary .Ns
  man/man7/zpoolprops.7
Labels: Status: Accepted

#15733 make zdb_decompress_block check its decompression reliably
  cmd/zdb/zdb.c
Labels: Status: Accepted

#15735 Improve block sizes checks during cloning
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#15732 Fix livelist assertions for dedup and cloning
  module/zfs/dsl_deadlist.c
Labels: Status: Accepted

#15693 Add Gotify notification support to ZED.
  cmd/zed/zed.d/zed-functions.sh
  cmd/zed/zed.d/zed.rc
Labels: Component: ZED, Status: Accepted

#15660 fix(mount): do not truncate shares not zfs mount
  cmd/zfs/zfs_main.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_share/zfs_share_after_mount.ksh
Labels: Status: Accepted

#15721 Stop wasting time on malloc in snprintf_zstd_header
  cmd/zdb/zdb.c
Labels: Status: Accepted

#15744 zfs-kmod.spec: preserve signature in linux kmod built by make rpm-kmod
  rpm/generic/zfs-kmod.spec.in
  rpm/redhat/zfs-kmod.spec.in
Labels: Component: Packaging, Status: Accepted

#15747 Fix "out of memory" error
  lib/libzfs/libzfs_import.c
  lib/libzutil/zutil_import.c
Labels: Status: Accepted

#15748 [2.2] Linux 6.2 compat: add check for kernel_neon_* availability
  config/kernel-fpu.m4
  include/os/linux/kernel/linux/simd_aarch64.h
  include/os/linux/kernel/linux/simd_arm.h
Labels: Status: Code Review Needed

#15761 [2.1] compat: add check for kernel_neon_* availability
  config/kernel-fpu.m4
  include/os/linux/kernel/linux/simd_aarch64.h
Labels: Status: Accepted

#15717 Test for clone, mmap and write for block cloning
  tests/runfiles/common.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/cmd/.gitignore
  tests/zfs-tests/cmd/Makefile.am
  tests/zfs-tests/cmd/clone_mmap_write.c
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/block_cloning/block_cloning_clone_mmap_write.ksh
Labels: Status: Accepted

#15723 zdb -R doesn't always print the full output.
  cmd/zdb/zdb.c
Labels: Status: Accepted

#15767 [2.2] compact: workaround for GPL-only symbols on riscv from Linux 6.2
  config/kernel-flush_dcache_page.m4
  config/kernel.m4
  include/os/linux/kernel/linux/dcache_compat.h
Labels: Status: Accepted

#15757 Make spl_kmem_cache size check consistent
  module/os/linux/spl/spl-kmem-cache.c
Labels: Status: Accepted

#15756 Make sure all necessary RPM path macros are defined
  config/rpm.am
Labels: Component: Packaging, Status: Accepted

#15773 zfs_setattr: fix atime update
  module/os/linux/zfs/zfs_vnops_os.c
  tests/zfs-tests/cmd/ctime.c
Labels: Status: Accepted

#15772 Fix cloning into mmaped and cached file.
  module/zfs/zfs_vnops.c
  tests/runfiles/common.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/cmd/.gitignore
  tests/zfs-tests/cmd/Makefile.am
  tests/zfs-tests/cmd/clone_mmap_cached.c
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/block_cloning/block_cloning_clone_mmap_cached.ksh
  tests/zfs-tests/tests/functional/block_cloning/setup.ksh
Labels: Status: Accepted

#15774 [2.2] zfs_setattr: fix atime update
  module/os/linux/zfs/zfs_vnops_os.c
  tests/zfs-tests/cmd/ctime.c
Labels: Status: Accepted

#15781 Autotrim High Load Average Fix
  module/zfs/vdev_trim.c
Labels: Status: Accepted

#15782 linux spl: fix typo in top comment of spl-condvar.c
  module/os/linux/spl/spl-condvar.c
Labels: Status: Accepted

#15783 Fix: variable type with zfs-tests/cmd/clonefile.c
  tests/zfs-tests/cmd/clonefile.c
Labels: Status: Accepted

#15789 [2.2] backport autotrim high load average fix
  module/zfs/vdev_trim.c
Labels: Status: Accepted

#15780 freebsd: fix bootstrapping tools under Linux/musl
  lib/libspl/include/os/freebsd/sys/stat.h
Labels: Type: Building, Status: Accepted

#15796 ZTS: Apply zfs_bclone_enabled to bclone tests
  tests/zfs-tests/tests/functional/bclone/cleanup.ksh
  tests/zfs-tests/tests/functional/bclone/setup.ksh
Labels: Status: Accepted

#15797 [2.2] ZTS: Apply zfs_bclone_enabled to bclone tests
  tests/zfs-tests/tests/functional/bclone/cleanup.ksh
  tests/zfs-tests/tests/functional/bclone/setup.ksh
Labels: Status: Accepted

#15630 FreeBSD: Fix file descriptor leak on pool import.
  module/os/freebsd/zfs/zfs_file_os.c
Labels: Status: Accepted

#15811 ZTS: Apply small changes for speeding up the tests
  .github/workflows/scripts/setup-dependencies.sh
Labels: Status: Accepted

#15813 [2.2] FreeBSD: Fix file descriptor leak on pool import
  module/os/freebsd/zfs/zfs_file_os.c
Labels: Status: Accepted

#15819 Switch to CodeQL to detect prohibited function use
  .github/codeql-cpp.yml
  .github/codeql-python.yml
  .github/codeql/custom-queries/cpp/deprecatedFunctionUsage.ql
  .github/codeql/custom-queries/cpp/qlpack.yml
  .github/workflows/codeql.yml
  config/Rules.am
Labels: Status: Accepted

#15820 ZTS: Update deprecated Github Action version numbers
  .github/workflows/README.md
  .github/workflows/checkstyle.yaml
  .github/workflows/codeql.yml
  .github/workflows/scripts/generate-summary.sh
  .github/workflows/zfs-linux-tests.yml
  .github/workflows/zfs-linux.yml
Labels: Status: Accepted

#15816 Update vdev devid and physpath if changed between imports
  module/zfs/vdev.c
Labels: Status: Accepted

#15825 zpool wait: print timestamp before the header
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#15812 Remove list_size struct member from list implementation
  include/os/freebsd/spl/sys/list_impl.h
  include/os/linux/spl/sys/list.h
  lib/libspl/include/sys/list_impl.h
  lib/libspl/list.c
  module/os/freebsd/spl/list.c
Labels: Status: Accepted

#15826 ZTS: Allow longer run time for zdb_args_pos
  tests/runfiles/common.run
Labels: Status: Accepted

#15823 Update to man pages for zpool-iostat, zpool-list, zpool-status and zpool-wait to resolve time(2) -> time(1)
  man/man8/zpool-iostat.8
  man/man8/zpool-list.8
  man/man8/zpool-status.8
  man/man8/zpool-wait.8
Labels: Status: Accepted

#15798 libnvpair.c: replace strstr() with strchr() for a single character
  lib/libnvpair/libnvpair.c
Labels: Status: Accepted

#15818 Don't assert mg_initialized due to device addition race
  module/zfs/metaslab.c
Labels: Status: Accepted

#15833 Linux 6.7 compat: META
  META
Labels: Status: Accepted
