Repository openzfs/zfs, pull requests merged in 2024-05, with the labels that each got.

#16131 Slightly improve dnode hash
  module/zfs/dmu_objset.c
Labels: Status: Accepted

#16130 Improve write issue taskqs utilization
  include/sys/spa.h
  include/sys/spa_impl.h
  include/sys/zio.h
  man/man4/zfs.4
  module/zfs/dmu_objset.c
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/zio.c
Labels: Status: Accepted

#16148 vdev_disk: disable flushes if device does not support it
  include/os/linux/kernel/linux/blkdev_compat.h
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#16146 Disable high priority ZIO threads on FreeBSD and Linux
  man/man4/zfs.4
  module/zfs/spa.c
  module/zfs/zio.c
Labels: Status: Accepted

#16150 Replace usage of schedule_timeout with schedule_timeout_interruptible
  module/os/linux/spl/spl-taskq.c
  module/os/linux/zfs/vdev_disk.c
  module/os/linux/zfs/zvol_os.c
Labels: Status: Accepted

#16152 zdb: cleanup
  cmd/zdb/zdb.c
Labels: Status: Accepted

#16162 Fix scn_queue races on very old pools
  include/sys/dsl_scan.h
  module/zfs/dsl_scan.c
Labels: Status: Accepted

#16165 Fix ZIL clone records for legacy holes
  module/zfs/zfs_log.c
Labels: Status: Accepted

#16167 Unbreak FreeBSD cross-build on MacOS broken in 051460b8b
  lib/libspl/assert.c
Labels: Status: Accepted

#16168 libspl_assert: always link -lpthread on FreeBSD
  lib/libspl/Makefile.am
Labels: Status: Accepted

#15940 Bug fix: Replace P2ALIGN with P2ALIGN_TYPED and delete P2ALIGN.
  cmd/zdb/zdb.c
  cmd/ztest.c
  include/os/freebsd/spl/sys/ccompile.h
  include/os/freebsd/spl/sys/sysmacros.h
  include/os/linux/spl/sys/sysmacros.h
  lib/libefi/rdwr_efi.c
  lib/libspl/include/os/linux/sys/sysmacros.h
  lib/libzfs/os/linux/libzfs_pool_os.c
  module/os/freebsd/zfs/vdev_geom.c
  module/os/linux/zfs/zvol_os.c
  module/zcommon/zfs_fletcher.c
  module/zfs/btree.c
  module/zfs/dmu.c
  module/zfs/dmu_object.c
  module/zfs/metaslab.c
  module/zfs/vdev.c
  module/zfs/vdev_raidz.c
Labels: Status: Accepted

#16159 ZAP: Fix leaf references on zap_expand_leaf() errors
  module/zfs/zap.c
Labels: Status: Accepted

#16186 [2.2.5] Replace P2ALIGN with P2ALIGN_TYPED and delete P2ALIGN.
  cmd/zdb/zdb.c
  cmd/ztest.c
  include/os/freebsd/spl/sys/ccompile.h
  include/os/freebsd/spl/sys/sysmacros.h
  include/os/linux/spl/sys/sysmacros.h
  lib/libefi/rdwr_efi.c
  lib/libspl/include/os/linux/sys/sysmacros.h
  lib/libzfs/os/linux/libzfs_pool_os.c
  module/os/freebsd/zfs/vdev_geom.c
  module/os/linux/zfs/zvol_os.c
  module/zcommon/zfs_fletcher.c
  module/zfs/btree.c
  module/zfs/dmu.c
  module/zfs/dmu_object.c
  module/zfs/metaslab.c
  module/zfs/vdev.c
Labels: Status: Accepted

#16188 Linux: disable lockdep for a couple of locks
  module/os/linux/spl/spl-procfs-list.c
  module/zfs/dbuf.c
Labels: Status: Accepted

#16191 dbuf: separate refcount calls for dbuf and dbuf_user
  module/zfs/dbuf.c
Labels: Status: Accepted

#16198 Correct level handling in zstream recompress.
  cmd/zstream/zstream_recompress.c
Labels: Status: Accepted

#16138 FreeBSD: Add zfs_link_create() error handling
  module/os/freebsd/zfs/zfs_dir.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/freebsd/zfs/zfs_znode.c
  tests/test-runner/bin/zts-report.py.in
Labels: Status: Accepted

#16203 Avoid a gcc -Wint-to-pointer-cast warning
  module/zfs/spa.c
Labels: Status: Accepted

#16201 linux: detect if kernel defines intptr_t
  config/kernel-types.m4
  config/kernel.m4
  include/os/linux/spl/sys/types.h
Labels: Status: Accepted

#16206 Use memset to zero stack allocations containing unions
  cmd/zstream/zstream_redup.c
  lib/libzfs/libzfs_sendrecv.c
  module/icp/io/aes.c
  tests/zfs-tests/cmd/libzfs_input_check.c
Labels: Status: Accepted

#16207 Fix assertion in Persistent L2ARC
  module/zfs/arc.c
Labels: Status: Accepted

#16216 Destroy ARC buffer in case of fill error
  module/zfs/dbuf.c
Labels: Status: Code Review Needed

#16214 Some improvements to metaslabs eviction
  module/zfs/metaslab.c
  module/zfs/spa.c
Labels: Status: Accepted

#16226 zed: Add deadman-slot_off.sh zedlet
  cmd/zed/zed.d/Makefile.am
  cmd/zed/zed.d/deadman-slot_off.sh
  cmd/zed/zed.d/zed.rc
  man/man4/zfs.4
  module/zfs/vdev.c
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/functional/deadman/deadman_ratelimit.ksh
Labels: Component: ZED, Status: Accepted

#16225 Simplify issig().
  include/os/freebsd/spl/sys/sig.h
  include/os/linux/spl/sys/signal.h
  include/sys/zfs_context.h
  module/os/linux/spl/spl-thread.c
  module/zfs/dmu_diff.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/dmu_redact.c
  module/zfs/dmu_send.c
  module/zfs/zcp.c
  module/zfs/zfs_ioctl.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#16229 spl: fix compilation without HAVE_BACKTRACE
  lib/libspl/backtrace.c
Labels: Status: Accepted

#16218 zpool import output is not formated properly.
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#16232 [2.2] Fix assertion in Persistent L2ARC
  module/zfs/arc.c
Labels: Status: Accepted

#16210 FreeBSD: Add const qualifier to members of struct opensolaris_utsname
  include/os/freebsd/spl/sys/misc.h
  module/os/freebsd/spl/spl_misc.c
Labels: Status: Accepted

#16224 ZTS: Fix redacted_send failures on FreeBSD
  tests/zfs-tests/tests/functional/redacted_send/redacted_deleted.ksh
  tests/zfs-tests/tests/functional/redacted_send/redacted_mounts.ksh
Labels: Status: Accepted
