Repository openzfs/zfs, pull requests merged in 2024-04, with the labels that each got.

#16042 Improve dbuf_read() error reporting
  module/zfs/dbuf.c
Labels: Status: Accepted

#16051 xdr: header cleanup
  include/os/freebsd/Makefile.am
  include/os/freebsd/spl/rpc/xdr.h
  include/os/linux/Makefile.am
  include/os/linux/spl/rpc/types.h
  include/os/linux/spl/rpc/xdr.h
  module/nvpair/nvpair.c
  module/os/linux/spl/spl-xdr.c
Labels: Status: Accepted

#16049 vdev_disk: don't touch vbio after its handed off to the kernel
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#15943 Makefile.bsd: sort and cleanup source file list
  module/Makefile.bsd
Labels: Status: Accepted

#15942 Give a better message from 'zpool get' when an invalid pool name is provided
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#15964 zap_leaf: make l_hash[] variable length to silence UBSAN
  include/sys/zap_leaf.h
Labels: Status: Accepted

#15969 [2.1 backport] Avoid save/restoring AMX registers to avoid a SPR erratum
  include/os/linux/kernel/linux/simd_x86.h
Labels: Status: Accepted

#15968 vdev props comment and manpage should include zfsd and FreeBSD mentions
  include/sys/vdev_impl.h
  man/man7/vdevprops.7
Labels: Status: Accepted

#15979 man: move `zfs_prepare_disk.8` to `nodist_man_MANS`
  man/Makefile.am
Labels: Status: Accepted

#15992 zvol: use multiple taskqs
  man/man4/zfs.4
  module/os/linux/zfs/zvol_os.c
Labels: Status: Accepted

#16059 [2.2] vdev_disk: don't touch vbio after its handed off to the kernel
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#16069 zvol_os: fix compile with blk-mq on Linux 4.x
  config/kernel-blk-queue.m4
  module/os/linux/zfs/zvol_os.c
Labels: Status: Accepted

#16070 vdev_disk: ensure trim errors are returned immediately
  config/kernel-blkdev.m4
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#16061 zinject: inject device errors into ioctls
  cmd/zinject/zinject.c
  include/sys/zio_impl.h
  man/man8/zinject.8
  man/man8/zpool-events.8
  module/zfs/zio.c
  module/zfs/zio_inject.c
Labels: Status: Accepted

#16052 Fix read errors race after block cloning
  module/zfs/dbuf.c
Labels: Status: Accepted

#16022 Speculative prefetch for reordered requests
  cmd/arc_summary
  include/sys/dmu_zfetch.h
  man/man4/zfs.4
  module/zfs/dmu.c
  module/zfs/dmu_zfetch.c
Labels: Type: Performance, Status: Accepted

#16057 Remove db_state DB_NOFILL checks from syncing context
  module/zfs/dbuf.c
Labels: Status: Accepted

#15879 Fix locale-specific time
  cmd/zpool/zpool_main.c
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#15977 Make init scripts work properly for Debian+OpenRC setup (again)
  config/Substfiles.am
  config/zfs-build.m4
  etc/init.d/README.md
  etc/init.d/zfs-import.in
  etc/init.d/zfs-load-key.in
  etc/init.d/zfs-mount.in
  etc/init.d/zfs-share.in
  etc/init.d/zfs-zed.in
Labels: Status: Accepted

#16072 Small fix to prefetch ranges aggregation
  module/zfs/dmu_zfetch.c
Labels: Status: Accepted

#16040 L2ARC: Relax locking during write
  include/sys/multilist.h
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu_objset.c
  module/zfs/metaslab.c
  module/zfs/multilist.c
Labels: Status: Accepted

#15980 config/Substfiles.am: restrict to the dedicated list.
  config/Substfiles.am
Labels: Status: Accepted

#15792 Add custom debug printing for your asserts
  include/os/freebsd/spl/sys/debug.h
  include/os/linux/spl/sys/debug.h
  lib/libspl/include/assert.h
  module/zfs/arc.c
Labels: Status: Accepted

#16074 return NULL at end of send_progress_thread
  lib/libzfs/libzfs_sendrecv.c
Labels: Status: Accepted

#16081 [2.2] vdev_disk: ensure trim errors are returned immediately
  config/kernel-blkdev.m4
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#16015 Add support for zfs mount -R <filesystem>
  cmd/zfs/zfs_main.c
  man/man8/zfs-mount.8
  tests/runfiles/common.run
  tests/runfiles/sanity.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount.cfg
  tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_recursive.ksh
Labels: Status: Accepted

#16083 [2.1] Unify arc_prune_async() code
  include/os/linux/zfs/sys/zpl.h
  include/sys/arc.h
  include/sys/arc_impl.h
  module/os/freebsd/zfs/arc_os.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/linux/zfs/arc_os.c
  module/os/linux/zfs/zpl_super.c
  module/zfs/arc.c
Labels: Status: Accepted

#16084 [2.2] vdev_disk: fix alignment check when buffer has non-zero starting offset
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#16082 bdev_discard_supported: understand discard_granularity=0
  include/os/linux/kernel/linux/blkdev_compat.h
Labels: Status: Accepted

#16088 zts: allow running a single test by name only
  scripts/zfs-tests.sh
Labels: Status: Accepted

#16085 zinject: "no-op" error injection
  cmd/zinject/zinject.c
  man/man8/zinject.8
  module/zfs/zio.c
  tests/zfs-tests/tests/functional/cli_root/zinject/zinject_args.ksh
Labels: Status: Accepted

#16086 Add the BTI elf note to the AArch64 SHA2 assembly
  module/icp/asm-aarch64/sha2/sha256-armv8.S
  module/icp/asm-aarch64/sha2/sha512-armv8.S
Labels: Status: Code Review Needed

#15784 Fix: do no use .cfi_negate_ra_state within the assembly on Arm64
  module/icp/asm-aarch64/blake3/b3_aarch64_sse2.S
  module/icp/asm-aarch64/blake3/b3_aarch64_sse41.S
Labels: Status: Accepted

#16096 zts: add a debug option to get full test output
  scripts/zfs-tests.sh
  tests/test-runner/bin/test-runner.py.in
Labels: Status: Accepted

#16094 Add zfetch stats in arcstats
  cmd/arcstat.in
Labels: Status: Accepted

#16111 [2.2] bdev_discard_supported: understand discard_granularity=0
  include/os/linux/kernel/linux/blkdev_compat.h
Labels: Status: Accepted

#16110 Handle FLUSH errors as "expected"
  module/zfs/zio.c
Labels: Status: Code Review Needed

#16108 abd_iter_page: rework to handle multipage scatterlists
  module/os/linux/zfs/abd_os.c
Labels: Status: Accepted

#16093 parallel pool import
  cmd/zinject/zinject.c
  cmd/zpool/zpool_main.c
  include/libzutil.h
  include/sys/spa.h
  include/sys/spa_impl.h
  include/sys/zfs_ioctl.h
  include/sys/zio.h
  man/man8/zinject.8
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/vdev_initialize.c
  module/zfs/vdev_rebuild.c
  module/zfs/vdev_trim.c
  module/zfs/zio_inject.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import_parallel_admin.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import_parallel_neg.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import_parallel_pos.ksh
Labels: Status: Accepted

#16113 Add newline to two zpool messages
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#16114 Avoid error in cleanup if test if unsupported
  tests/zfs-tests/tests/functional/user_namespace/user_namespace_004.ksh
Labels: Status: Accepted

#16115 ztest: use ASSERT3P to compare pointers
  cmd/ztest.c
Labels: Status: Accepted

#16117 zfs get: add '-t fs' and '-t vol' options
  cmd/zfs/zfs_main.c
  man/man8/zfs-set.8
Labels: Status: Accepted

#16104 Refactor dbuf_read() for safer decryption
  module/zfs/dbuf.c
Labels: Status: Accepted

#16121 zfs-kmod: fix empty rpm requires/conflicts
  rpm/redhat/zfs-kmod.spec.in
Labels: Status: Accepted

#16038 L2ARC: Cleanup buffer re-compression
  module/zfs/arc.c
Labels: Status: Accepted

#16118 Make more taskq parameters writable
  man/man4/zfs.4
  module/zfs/spa.c
Labels: Status: Accepted

#15888 Fast Dedup: ZAP Shrinking
  man/man4/zfs.4
  module/zfs/zap.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/zap_shrink/cleanup.ksh
  tests/zfs-tests/tests/functional/zap_shrink/setup.ksh
  tests/zfs-tests/tests/functional/zap_shrink/zap_shrink_001_pos.ksh
Labels: Status: Accepted

#16128 Fix updating the zvol_htable when renaming a zvol
  module/os/freebsd/zfs/zvol_os.c
  module/os/linux/zfs/zvol_os.c
Labels: Status: Accepted

#16125 GCC: Fixes for gcc 14 on Fedora 40
  cmd/zpool/os/linux/zpool_vdev_os.c
  lib/libuutil/uu_list.c
  module/zfs/vdev_raidz.c
Labels: Status: Accepted

#15996 Overflowing refreservation is bad
  lib/libzfs/libzfs_dataset.c
Labels: Status: Accepted

#15839 vdev probe to slow disk can stall mmp write checker
  cmd/zpool/zpool_main.c
  include/sys/spa.h
  include/sys/uberblock_impl.h
  include/sys/vdev_impl.h
  man/man8/zpool-clear.8
  module/zfs/mmp.c
  module/zfs/spa.c
  module/zfs/txg.c
  module/zfs/vdev.c
  module/zfs/vdev_label.c
  module/zfs/zfs_ioctl.c
  module/zfs/zio.c
  module/zfs/zio_inject.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/mmp/mmp_write_slow_disk.ksh
Labels: Status: Accepted

#16134 zio: try to execute TYPE_NULL ZIOs on the current task
  module/zfs/zio.c
Labels: Status: Accepted
