Repository openzfs/zfs, pull requests merged in 2024-10, with the labels that each got.

#16586 Linux 6.11 compat: META
  META
Labels: Status: Accepted

#15454 send/recv: open up additional stream feature flags
  include/sys/zfs_ioctl.h
Labels: Status: Accepted

#16569 Restrict raidz faulted vdev count
  module/zfs/vdev.c
  tests/runfiles/linux.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/fault/fault_limits.ksh
Labels: Component: ZED, Status: Accepted

#16592 Force ABI generation for update
  lib/libnvpair/libnvpair.abi
  lib/libuutil/libuutil.abi
  lib/libzfs/libzfs.abi
  lib/libzfs_core/libzfs_core.abi
Labels: Status: Accepted

#16584 Avoid computing strlen() inside loops
  cmd/zdb/zdb.c
  cmd/ztest.c
  lib/libzfs/libzfs_util.c
  module/zcommon/zfs_prop.c
  module/zcommon/zpool_prop.c
  udev/zvol_id.c
Labels: Status: Accepted

#16587 snapdir: add 'disabled' value to make .zfs inaccessible
  include/os/freebsd/zfs/sys/zfs_ctldir.h
  include/os/freebsd/zfs/sys/zfs_vfsops_os.h
  include/os/linux/zfs/sys/zfs_ctldir.h
  include/os/linux/zfs/sys/zfs_vfsops_os.h
  include/sys/zfs_ioctl.h
  man/man4/zfs.4
  man/man7/zfsconcepts.7
  man/man7/zfsprops.7
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_ctldir.c
  module/os/linux/zfs/zfs_dir.c
  module/os/linux/zfs/zfs_vfsops.c
  module/os/linux/zfs/zpl_ctldir.c
  module/zcommon/zfs_prop.c
  module/zfs/dsl_prop.c
  tests/zfs-tests/include/properties.shlib
Labels: Status: Accepted

#16597 Temporarily disable Direct IO by default
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#16593 feature: large_microzap
  include/sys/fs/zfs.h
  include/sys/zap_impl.h
  include/sys/zfs_ioctl.h
  include/zfeature_common.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_sendrecv.c
  man/man4/zfs.4
  man/man7/zpool-features.7
  man/man8/zfs-send.8
  module/zcommon/zfeature_common.c
  module/zfs/dmu_recv.c
  module/zfs/dmu_send.c
  module/zfs/dmu_tx.c
  module/zfs/zap_micro.c
  tests/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_features_005_pos.ksh
  tests/zfs-tests/tests/functional/cli_root/zpool_get/zpool_get.cfg
Labels: Status: Accepted

#16588 Update compatibility.d files
  cmd/zpool/Makefile.am
  cmd/zpool/compatibility.d/openzfs-2.3
Labels: Status: Accepted

#16599 ZTS: Fix summary page creation
  .github/workflows/scripts/qemu-9-summary-page.sh
Labels: Status: Accepted

#15810 Defer resilver only when progress is above a threshold
  man/man4/zfs.4
  module/zfs/dsl_scan.c
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/functional/replacement/resilver_restart_001.ksh
Labels: Status: Accepted

#16605 ARC: Cache arc_c value during arc_evict()
  module/zfs/arc.c
Labels: Status: Accepted

#16606 ZAP: Align za_name in zap_attribute_t to 8 bytes
  include/sys/zap.h
Labels: Status: Accepted

#16610 ZTS: Remove FreeBSD 13.4-STABLE
  .github/workflows/scripts/qemu-2-start.sh
  .github/workflows/zfs-qemu.yml
Labels: Status: Accepted

#16611 ZTS: Fix summary page creation again - second try
  .github/workflows/scripts/qemu-9-summary-page.sh
Labels: Status: Accepted

#16600 issue #14223: fix generation of kernel uevents for snapshot rename on linux
  module/zfs/dsl_dataset.c
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_snapdev.ksh
Labels: Status: Accepted

#16613 Return boolean_t in inline functions of lib/libspl/include/sys/uio.h
  lib/libspl/include/sys/uio.h
Labels: Status: Accepted

#16617 zpool/zfs: restore `--version` & `-V` options
  cmd/zfs/zfs_main.c
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#16622 Only serialize native-deb* targets
  config/deb.am
Labels: Status: Accepted

#16618 ZTS: resilver_restart_001.ksh restore defaults
  tests/zfs-tests/tests/functional/replacement/resilver_restart_001.ksh
Labels: Status: Accepted

#16603 vdev_id: multi-lun disks & slot num zero pad
  man/man5/vdev_id.conf.5
  udev/vdev_id
Labels: Status: Code Review Needed

#16627 ztest: Fix scrub check in ztest_raidz_expand_check()
  cmd/ztest.c
  lib/libzfs/libzfs_pool.c
Labels: Component: Test Suite, Status: Accepted

#16616 FreeBSD: exclude some includes when building libsa
  include/os/freebsd/zfs/sys/abd_os.h
Labels: Status: Accepted

#16598 Always validate checksums for Direct I/O reads
  cmd/zpool/zpool_main.c
  include/sys/fm/fs/zfs.h
  include/sys/vdev_raidz.h
  include/sys/zio.h
  man/man4/zfs.4
  man/man8/zpool-events.8
  man/man8/zpool-status.8
  module/os/freebsd/zfs/abd_os.c
  module/os/linux/zfs/abd_os.c
  module/zcommon/zfs_valstr.c
  module/zfs/dmu_direct.c
  module/zfs/vdev_draid.c
  module/zfs/vdev_indirect.c
  module/zfs/vdev_mirror.c
  module/zfs/vdev_raidz.c
  module/zfs/zfs_vnops.c
  module/zfs/zio.c
  tests/runfiles/common.run
  tests/zfs-tests/cmd/manipulate_user_buffer.c
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/direct/dio.kshlib
  tests/zfs-tests/tests/functional/direct/dio_read_verify.ksh
  tests/zfs-tests/tests/functional/direct/dio_write_stable_pages.ksh
  tests/zfs-tests/tests/functional/direct/dio_write_verify.ksh
Labels: Status: Accepted

#16632 zpool/zfs: allow `--json` wherever `-j` is allowed
  cmd/zfs/zfs_main.c
  cmd/zpool/zpool_main.c
  man/man8/zfs-list.8
  man/man8/zfs-mount.8
  man/man8/zfs-program.8
  man/man8/zfs-set.8
  man/man8/zpool-get.8
  man/man8/zpool-list.8
  man/man8/zpool-status.8
  tests/zfs-tests/tests/functional/cli_root/json/json_sanity.ksh
Labels: Status: Accepted

#16635 zdb: fix printf format in dump_zap()
  cmd/zdb/zdb.c
Labels: Status: Accepted

#16639 CI: Stick with ubuntu-22.04 for CodeQL analysis
  .github/workflows/codeql.yml
Labels: Component: Test Suite, Status: Accepted

#16637 ZTS: Slightly increase dedup_quota limit
  tests/zfs-tests/tests/functional/dedup/dedup_quota.ksh
Labels: Component: Test Suite, Status: Accepted

#16638 ZTS: Increase zpool_import_parallel_pos import margin
  tests/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import_parallel_pos.ksh
Labels: Component: Test Suite, Status: Accepted

#16640 Fallback to strerror() when strerror_l() isn't available
  config/user.m4
  include/libzutil.h
Labels: Type: Building, Status: Accepted

#16629 Revert "Temporarily disable Direct IO by default"
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#16650 freebsd: Use compiler.h from FreeBSD's base's linuxkpi
  include/os/freebsd/linux/compiler.h
  include/os/freebsd/spl/sys/ccompat.h
  include/os/freebsd/spl/sys/debug.h
Labels: Status: Accepted

#16646 Fix inconsistent mount options for ZFS root
  contrib/initramfs/scripts/zfs
  include/os/linux/zfs/sys/zfs_vfsops_os.h
  module/os/linux/zfs/zfs_ctldir.c
  module/os/linux/zfs/zfs_vfsops.c
Labels: Status: Accepted

#16664 zfs_debug: Restore log size limit for userspace
  lib/libzpool/zfs_debug.c
Labels: Status: Accepted

#16665 Fix compile-time warnings caused by duplicate struct typedefs
  include/os/linux/spl/sys/taskq.h
  include/os/linux/zfs/sys/abd_os.h
Labels: Status: Accepted

#16667 zdb: show bp in uberblock dump
  cmd/zdb/zdb.c
Labels: Status: Accepted

#16666 config: fix dequeue_signal check for kernels <4.20
  config/kernel-kthread.m4
  module/os/linux/spl/spl-thread.c
Labels: Status: Accepted

#16670 ZTS: Add additional exceptions
  tests/test-runner/bin/zts-report.py.in
Labels: Component: Test Suite, Status: Accepted

#16678 Workaround issue of Linux vdev_disk.c
  module/zfs/zio.c
Labels: Status: Code Review Needed

#16684 Pack dmu_buf_impl_t by 16 bytes
  include/sys/dbuf.h
Labels: Status: Accepted

#16681 ZTS: Add LUKS sanity test
  .github/workflows/scripts/qemu-3-deps.sh
  tests/runfiles/linux.run
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/luks/luks_sanity.ksh
Labels: Status: Accepted

#16688 Fix gcc uninitialized warning in FreeBSD zio_crypt.c
  module/os/freebsd/zfs/zio_crypt.c
Labels: Status: Accepted

#16690 On the first vdev open ignore impossible ashift hints
  module/zfs/vdev.c
Labels: Status: Accepted

#16698 Add warning for external consumers of dmu_tx_callback_register
  module/zfs/dmu_tx.c
Labels: Status: Accepted
