Repository openzfs/zfs, pull requests merged in 2025-06, with the labels that each got.

#17415 Relax zfs_vnops_read_chunk_size limitations
  man/man4/zfs.4
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#17410 Linux build: silence objtool warnings
  config/kernel-objtool.m4
  include/sys/frame.h
  module/icp/asm-x86_64/modes/aesni-gcm-x86_64.S
  module/icp/asm-x86_64/sha2/sha256-x86_64.S
  module/icp/asm-x86_64/sha2/sha512-x86_64.S
Labels: Status: Code Review Needed

#17413 zpl: handle suspend from two remaining calls to `txg_wait_synced()`
  module/os/linux/zfs/zfs_vnops_os.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#17432 scrub: generate scrub_finish event
  module/zfs/dsl_scan.c
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_events/zpool_events_scrub_txg_continue_from_last.ksh
Labels: Status: Accepted

#17447 ZTS: Enable io_uring on CentOS Stream 9 and 10 also
  .github/workflows/scripts/qemu-6-tests.sh
Labels: Status: Accepted

#17438 Make TX abort after assign safer
  module/zfs/dmu_tx.c
  module/zfs/zfs_vnops.c
Labels: Status: Accepted

#17441 Polish db_rwlock scope
  module/zfs/dbuf.c
  module/zfs/dnode.c
Labels: Status: Accepted

#17434 Reduce zfs_dmu_offset_next_sync penalty
  module/zfs/dmu.c
Labels: Status: Accepted

#17431 Improve block cloning transactions accounting
  include/sys/dmu.h
  module/zfs/dbuf.c
  module/zfs/dmu_tx.c
  module/zfs/zfs_vnops.c
  module/zfs/zvol.c
Labels: Status: Accepted

#17458 ZIL: Relax parallel write ZIOs processing
  module/zfs/zil.c
Labels: Status: Accepted

#17462 ZTS: Use FreeBSD cloudinit images
  .github/workflows/scripts/qemu-2-start.sh
  .github/workflows/zfs-qemu.yml
Labels: Status: Accepted

#17473 Fix TestGroup warning due to missing tags
  tests/runfiles/linux.run
Labels: Status: Accepted

#17463 Clarify and restrict dmu_tx_assign() errors
  cmd/ztest.c
  module/zfs/dmu_tx.c
  module/zfs/dsl_dir.c
Labels: Component: Test Suite, Status: Accepted

#17443 Linux 6.16 compat
  config/kernel-pagemap-readahead-page.m4
  config/kernel-vfs-readpages.m4
  config/kernel-vfs-writepage.m4
  config/kernel.m4
  include/os/linux/Makefile.am
  include/os/linux/kernel/linux/pagemap_compat.h
  module/os/linux/zfs/zpl_file.c
Labels: Status: Accepted

#17484 Ensure that gang_copies is always at least as large as copies
  module/zfs/dmu.c
Labels: Status: Accepted

#17488 `vdev_raidz_asize_to_psize`: return `psize`, not `asize`
  module/zfs/vdev_raidz.c
Labels: Status: Accepted

#17491 Missing tests in make pkg
  tests/zfs-tests/tests/Makefile.am
Labels: Status: Code Review Needed
