Repository openzfs/zfs, pull requests merged in 2025-03, with the labels that each got.

#17049 Add more DDT tests
  cmd/zdb/zdb.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/dedup/dedup_prune.ksh
  tests/zfs-tests/tests/functional/dedup/dedup_zap_shrink.ksh
Labels: Status: Code Review Needed

#17005 Add 'zfs-qemu-packages' workflow for RPM building
  .github/workflows/checkstyle.yaml
  .github/workflows/scripts/qemu-2-start.sh
  .github/workflows/scripts/qemu-3-deps-vm.sh
  .github/workflows/scripts/qemu-3-deps.sh
  .github/workflows/scripts/qemu-4-build-vm.sh
  .github/workflows/scripts/qemu-4-build.sh
  .github/workflows/scripts/qemu-5-setup.sh
  .github/workflows/scripts/qemu-7-prepare.sh
  .github/workflows/scripts/qemu-prepare-for-build.sh
  .github/workflows/scripts/qemu-test-repo-vm.sh
  .github/workflows/scripts/qemu-wait-for-vm.sh
  .github/workflows/scripts/replace-dupes-with-symlinks.sh
  .github/workflows/zfs-qemu-packages.yml
  .github/workflows/zfs-qemu.yml
  .github/workflows/zloop.yml
Labels: Component: Test Suite, Status: Accepted

#17122 Check portable objset MAC even if local is zeroed
  module/zfs/dsl_crypt.c
Labels: Status: Accepted

#17124 zed: Print return code on failed zpool_prepare_disk
  cmd/zed/agents/zfs_mod.c
Labels: Status: Accepted

#17131 linux: zvols: correctly detect flush requests
  include/os/linux/kernel/linux/blkdev_compat.h
Labels: Status: Accepted

#16972 Implement `statx(STATX_DIOALIGN)` so applications can discover correct `O_DIRECT` alignment
  include/sys/zfs_vnops.h
  module/os/linux/zfs/zpl_inode.c
  module/zfs/zfs_vnops.c
  tests/runfiles/common.run
  tests/test-runner/bin/zts-report.py.in
  tests/zfs-tests/cmd/.gitignore
  tests/zfs-tests/cmd/Makefile.am
  tests/zfs-tests/cmd/statx.c
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/stat/statx_dioalign.ksh
Labels: Status: Accepted

#17113 Prefer embedded blocks to dedup
  module/zfs/zio.c
  tests/zfs-tests/tests/functional/cli_root/zpool_prefetch/zpool_prefetch_001_pos.ksh
  tests/zfs-tests/tests/functional/dedup/dedup_quota.ksh
Labels: Status: Accepted

#17120 Fix deduplication of overridden blocks
  cmd/zdb/zdb.c
  include/sys/ddt.h
  module/zfs/ddt.c
  module/zfs/zio.c
Labels: Status: Accepted

#17139 Update FreeBSD CI images
  .cirrus.yml
Labels: Status: Accepted

#17015 Add receive:append permission for limited receive
  cmd/zfs/zfs_main.c
  include/sys/dsl_deleg.h
  man/man8/zfs-allow.8
  module/zcommon/zfs_deleg.c
  module/zfs/zfs_ioctl.c
  tests/zfs-tests/tests/functional/delegate/delegate_common.kshlib
  tests/zfs-tests/tests/functional/delegate/zfs_allow_010_pos.ksh
Labels: Status: Accepted

#17150 ZTS: Remove TXG_TIMEOUT from dedup_quota test
  tests/zfs-tests/tests/functional/dedup/dedup_quota.ksh
Labels: Status: Code Review Needed

#17143 dmu_tx: rename `dmu_tx_assign()` flags from `TXG_*` to `DMU_TX_*`
  cmd/ztest.c
  include/sys/dmu.h
  module/os/freebsd/zfs/zfs_acl.c
  module/os/freebsd/zfs/zfs_dir.c
  module/os/freebsd/zfs/zfs_vfsops.c
  module/os/freebsd/zfs/zfs_vnops_os.c
  module/os/freebsd/zfs/zfs_znode_os.c
  module/os/freebsd/zfs/zvol_os.c
  module/os/linux/zfs/zfs_acl.c
  module/os/linux/zfs/zfs_dir.c
  module/os/linux/zfs/zfs_vfsops.c
  module/os/linux/zfs/zfs_vnops_os.c
  module/os/linux/zfs/zfs_znode_os.c
  module/os/linux/zfs/zvol_os.c
  module/zfs/dmu.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/dmu_redact.c
  module/zfs/dmu_tx.c
  module/zfs/dsl_scan.c
  module/zfs/dsl_synctask.c
  module/zfs/spa.c
  module/zfs/spa_history.c
  module/zfs/vdev_indirect.c
  module/zfs/vdev_initialize.c
  module/zfs/vdev_raidz.c
  module/zfs/vdev_rebuild.c
  module/zfs/vdev_removal.c
  module/zfs/vdev_trim.c
  module/zfs/zfs_quota.c
  module/zfs/zfs_replay.c
  module/zfs/zfs_sa.c
  module/zfs/zfs_vnops.c
  module/zfs/zil.c
  module/zfs/zvol.c
Labels: Status: Code Review Needed

#17126 Some arc_release() cleanup
  module/zfs/arc.c
Labels: Status: Accepted

#17136 Always perform bounds-checking in metaslab_free_concrete
  module/zfs/metaslab.c
Labels: Status: Accepted

#17101 spl_vfs: fix vrele task runner signature mismatch
  module/os/freebsd/spl/spl_vfs.c
Labels: Status: Accepted

#17145 Fix deadlock on I/O errors during device removal
  module/zfs/vdev_removal.c
Labels: Status: Accepted

#16830 Updating dio_read_verify ZTS test
  tests/zfs-tests/tests/functional/direct/dio_read_verify.ksh
Labels: Status: Accepted

#17073 Make ganging redundancy respect redundant_metadata property
  cmd/zdb/zdb.c
  include/sys/dbuf.h
  include/sys/zio.h
  module/zfs/arc.c
  module/zfs/dbuf.c
  module/zfs/dmu.c
  module/zfs/dmu_recv.c
  module/zfs/zio.c
  tests/runfiles/common.run
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/gang_blocks/cleanup.ksh
  tests/zfs-tests/tests/functional/gang_blocks/gang_blocks.kshlib
  tests/zfs-tests/tests/functional/gang_blocks/gang_blocks_redundant.ksh
  tests/zfs-tests/tests/functional/gang_blocks/setup.ksh
Labels: Status: Code Review Needed

#17162 CI: Remove FreeBSD 13.3 and 14.1 tests
  .github/workflows/scripts/qemu-2-start.sh
  .github/workflows/zfs-qemu.yml
Labels: Status: Accepted

#17020 Unified allocation throttling
  include/sys/dsl_pool.h
  include/sys/metaslab.h
  include/sys/metaslab_impl.h
  include/sys/spa_impl.h
  include/sys/vdev_impl.h
  man/man4/zfs.4
  module/zfs/metaslab.c
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/vdev_queue.c
  module/zfs/vdev_removal.c
  module/zfs/zio.c
Labels: Status: Code Review Needed, Status: Design Review Needed

#17121 Linux: Fix zfs_prune panics v2
  config/kernel-sb-dying.m4
  config/kernel.m4
  module/os/linux/zfs/zpl_super.c
Labels: Status: Accepted

#17180 Block remap for cloned blocks on device removal
  module/zfs/metaslab.c
Labels: Status: Accepted

#17187 zed: Ensure spare activation after kernel-initiated device removal
  cmd/zed/agents/zfs_retire.c
  include/sys/spa.h
  module/zfs/spa.c
  module/zfs/vdev.c
  module/zfs/zfs_fm.c
Labels: Status: Accepted

#17192 Remove mg_allocators
  include/sys/metaslab.h
  include/sys/metaslab_impl.h
  module/zfs/metaslab.c
  module/zfs/vdev.c
Labels: Status: Accepted

#17189 kstat: silence "maybe uninitialized" warnings
  module/os/linux/spl/spl-kstat.c
Labels: Status: Accepted
