Repository openzfs/zfs, pull requests merged in 2025-04, with the labels that each got.

#17191 simd_powerpc.h: enable FPU on FreeBSD
  include/os/freebsd/spl/sys/simd_powerpc.h
Labels: Status: Accepted

#17164 Fix lock reversal on device removal cancel
  module/zfs/vdev_removal.c
Labels: Status: Code Review Needed

#17199 Multiple printf() size fixes
  cmd/zinject/zinject.c
  tests/zfs-tests/cmd/clonefile.c
  tests/zfs-tests/tests/functional/vdev_disk/page_alignment.c
Labels: Status: Accepted

#17213 Added fix for zpool get state segfaults with two or more vdevs (#15972).
  cmd/zpool/zpool_main.c
Labels: Status: Code Review Needed

#17208 Fix memory leaks in pool properties handling
  lib/libzfs/libzfs_pool.c
Labels: Status: Accepted

#17219 freebsd: unbreak module/Makefile.bsd build on 15-CURRENT-arm64
  module/Makefile.bsd
Labels: Status: Accepted

#17217 Linux 6.14 compat: Check for migratepage VFS
  config/kernel-vfs-migratepage.m4
  config/kernel.m4
  module/os/linux/zfs/zpl_file.c
Labels: Status: Code Review Needed

#17236 config: fix ZFS_LINUX_TEST_RESULT_SYMBOL with --enable-linux-builtin
  config/kernel.m4
Labels: Status: Accepted

#17238 Fixed zfs_notify_email for programs like sendmail by including a separating empty line between email header and body
  cmd/zed/zed.d/zed-functions.sh
Labels: Status: Accepted

#17228 vdev_to_nvlist_iter: ignore draid parameters when matching names
  lib/libzfs/libzfs_pool.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_get/vdev_get_all.ksh
Labels: Status: Code Review Needed

#17215 nvlist: Add nvlist_snprintf() and zfs_dbgmsg_nvlist()
  include/sys/nvpair.h
  include/sys/zfs_debug.h
  lib/libnvpair/libnvpair.abi
  lib/libnvpair/libnvpair.c
  lib/libuutil/libuutil.abi
  lib/libzfs/libzfs.abi
  lib/libzfs_core/libzfs_core.abi
  lib/libzfsbootenv/libzfsbootenv.abi
  lib/libzpool/Makefile.am
  module/Kbuild.in
  module/nvpair/nvpair.c
  module/zfs/zfs_debug_common.c
Labels: Status: Accepted

#17250 ZTS: Remove ashift setting from dedup_quota test
  tests/zfs-tests/tests/functional/dedup/dedup_quota.ksh
Labels: Status: Code Review Needed

#17123 Handle interaction between gang blocks, copies, and FDT.
  include/sys/ddt.h
  module/zfs/ddt.c
  module/zfs/zio.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/gang_blocks/gang_blocks_ddt_copies.ksh
Labels: Status: Accepted

#17259 ZTS: Polish online_offline tests
  tests/zfs-tests/tests/functional/online_offline/online_offline_001_pos.ksh
  tests/zfs-tests/tests/functional/online_offline/online_offline_002_neg.ksh
  tests/zfs-tests/tests/functional/online_offline/online_offline_003_neg.ksh
Labels: Status: Code Review Needed

#17257 ZTS: Remove fixed sleeps from slog_006_pos
  tests/zfs-tests/tests/functional/slog/slog_006_pos.ksh
Labels: Status: Code Review Needed

#17260 ZTS: Update FreeBSD version numbers
  .github/workflows/scripts/qemu-2-start.sh
  .github/workflows/scripts/qemu-3-deps-vm.sh
  .github/workflows/zfs-qemu.yml
Labels: Status: Accepted

#17267 ZTS: Fix 256MB file leak in zed_cksum_reported
  tests/zfs-tests/tests/functional/events/zed_cksum_reported.ksh
Labels: Status: Accepted

#17234 Added a more descriptive error message due the destroy failure
  lib/libzfs/libzfs_dataset.c
Labels: Status: Accepted

#17256 Export correct symbols for Lustre Direct I/O
  module/os/linux/zfs/abd_os.c
  module/zfs/abd.c
  module/zfs/dmu_direct.c
Labels: Status: Accepted

#17268 ZTS: Reduce extra caching in pool_checkpoint
  tests/zfs-tests/tests/functional/pool_checkpoint/checkpoint_capacity.ksh
  tests/zfs-tests/tests/functional/pool_checkpoint/pool_checkpoint.kshlib
Labels: Status: Code Review Needed

#17270 ZTS: Make zvol_stress write some more
  tests/zfs-tests/tests/functional/zvol/zvol_stress/zvol_stress.ksh
Labels: Status: Accepted

#17278 ZTS: Use Ubuntu default url for cloud-image
  .github/workflows/scripts/qemu-2-start.sh
Labels: Status: Accepted

#17247 ZTS: Optimize KSM on Linux and remove it for FreeBSD
  .github/workflows/scripts/generate-ci-type.py
  .github/workflows/scripts/qemu-1-setup.sh
  .github/workflows/scripts/qemu-2-start.sh
  .github/workflows/scripts/qemu-5-setup.sh
  .github/workflows/scripts/qemu-6-tests.sh
  .github/workflows/scripts/qemu-7-prepare.sh
  .github/workflows/scripts/qemu-8-summary.sh
Labels: Status: Accepted

#17273 cred: properly pass and test creds on other threads
  include/os/freebsd/spl/sys/policy.h
  include/os/linux/zfs/sys/policy.h
  include/sys/dmu_recv.h
  include/sys/dsl_dataset.h
  include/sys/dsl_dir.h
  include/sys/zcp.h
  include/sys/zfs_context.h
  lib/libzpool/kernel.c
  module/os/freebsd/spl/spl_policy.c
  module/os/linux/zfs/policy.c
  module/zfs/dmu_objset.c
  module/zfs/dmu_recv.c
  module/zfs/dsl_dataset.c
  module/zfs/dsl_dir.c
  module/zfs/zcp.c
  module/zfs/zcp_synctask.c
Labels: Status: Accepted

#17271 RPM: Hold back incompatible kernel packages on Fedora
  rpm/generic/zfs-dkms.spec.in
Labels: Component: Packaging, Status: Accepted
