Repository openzfs/zfs, pull requests merged in 2025-09, with the labels that each got.

#17684 config: Fix LLVM-21 -Wuninitialized-const-pointer warning
  config/kernel-blkdev.m4
Labels: Type: Building, Status: Accepted

#17680 Add configure warning message if ARCH environment variable is set
  config/always-arch.m4
  config/zfs-build.m4
Labels: Status: Accepted

#17697 CI: Increase 'Setup QEMU' timeout to 15 minutes
  .github/workflows/zfs-qemu.yml
Labels: Status: Accepted

#17375 tunables: remove legacy FreeBSD aliases
  module/os/freebsd/zfs/sysctl_os.c
  module/zfs/arc.c
  module/zfs/dmu_zfetch.c
  module/zfs/vdev.c
  module/zfs/vdev_queue.c
  module/zfs/vdev_removal.c
  tests/zfs-tests/include/tunables.cfg
Labels: Status: Accepted

#17706 Fix the build on 32-bit FreeBSD with GCC
  include/sys/zio.h
Labels: Status: Accepted

#17704 Fix warnings about sha2_is_supported on FreeBSD/i386
  module/icp/algs/sha2/sha256_impl.c
  module/icp/algs/sha2/sha512_impl.c
Labels: Status: Accepted

#17719 vdev_disk_close: take disk write lock before destroying it
  module/os/linux/zfs/vdev_disk.c
Labels: Status: Accepted

#17708 Fix atomic-alignment warnings in libspl on FreeBSD/i386
  config/always-arch.m4
  config/always-compiler-options.m4
  config/zfs-build.m4
  lib/libspl/Makefile.am
Labels: Status: Accepted

#17794 CI: Remove Buildbot references
  .github/PULL_REQUEST_TEMPLATE.md
  contrib/pyzfs/libzfs_core/test/test_libzfs_core.py
Labels: Type: Documentation, Status: Accepted

#17795 CI: Switch FreeBSD 15 to 15.0-ALPHA3
  .github/workflows/scripts/qemu-2-start.sh
Labels: Component: Test Suite, Status: Accepted

#17765 zvol: Fix blk-mq sync
  include/os/linux/kernel/linux/blkdev_compat.h
  module/os/linux/zfs/zvol_os.c
  tests/zfs-tests/tests/functional/zvol/zvol_misc/zvol_misc_fua.ksh
Labels: Status: Code Review Needed

#17797 manuals: fix typos in zpool-upgrade man page
  man/man8/zpool-upgrade.8
Labels: Status: Accepted
