Repository openzfs/zfs, pull requests merged in 2025-08, with the labels that each got.

#17561 Don't call dbuf_evict_one from dbuf_evict_notify for kswapd
  include/os/freebsd/spl/sys/misc.h
  include/os/linux/spl/sys/misc.h
  include/sys/zfs_context.h
  module/os/freebsd/spl/spl_misc.c
  module/os/linux/spl/spl-thread.c
  module/zfs/dbuf.c
Labels: Status: Accepted

#16853 Add TXG timestamp database
  cmd/zpool/zpool_main.c
  include/Makefile.am
  include/libzfs.h
  include/sys/dmu.h
  include/sys/spa_impl.h
  include/zfs_crrd.h
  lib/libzfs/libzfs.abi
  lib/libzfs/libzfs_pool.c
  lib/libzpool/Makefile.am
  man/man4/zfs.4
  man/man8/zpool-scrub.8
  module/Kbuild.in
  module/Makefile.bsd
  module/zfs/spa.c
  module/zfs/spa_misc.c
  module/zfs/zfs_crrd.c
  module/zfs/zfs_ioctl.c
  tests/runfiles/common.run
  tests/zfs-tests/include/tunables.cfg
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/cli_root/zpool_scrub/zpool_scrub_date_range_001.ksh
Labels: Status: Accepted

#17592 Some documentation polishing for log vdevs
  man/man4/zfs.4
  man/man7/zfsprops.7
  man/man7/zpoolconcepts.7
Labels: Status: Accepted

#17585 Document the new 'zpool scrub -a' option
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#17605 zvol: cleanup error handling and passthrough
  module/os/linux/zfs/zvol_os.c
  module/zfs/zvol.c
Labels: Status: Accepted

#17578 Linux 6.16 compat: META
  META
Labels: Status: Accepted

#17619 Better pack struct zio_prop
  include/sys/zio.h
Labels: Status: Accepted

#17617 FreeBSD 15.0 is now "PRERELEASE"
  .github/workflows/scripts/qemu-2-start.sh
Labels: Status: Accepted

#17626 contrib/initramfs/scripts/zfs: shellcheck fixup
  contrib/initramfs/scripts/zfs
Labels: Status: Accepted

#17166 zdb: better handling for corrupt block pointers
  cmd/zdb/zdb.c
  man/man8/zdb.8
Labels: Status: Code Review Needed

#17602 Fix Assert in dbuf_undirty, which triggers during usage zap shrink
  module/zfs/dbuf.c
Labels: Status: Accepted

#17613 ZIL: Make allocations more flexible
  include/sys/zil_impl.h
  include/sys/zio.h
  module/zfs/zil.c
  module/zfs/zio.c
Labels: Status: Accepted

#17642 Make zpool_find_config() report errors
  lib/libzutil/zutil_import.c
Labels: Status: Accepted

#17648 CI: Add Debian 13 to the FULL_OS runner list
  .github/workflows/scripts/qemu-2-start.sh
  .github/workflows/scripts/qemu-3-deps-vm.sh
  .github/workflows/scripts/qemu-5-setup.sh
  .github/workflows/zfs-qemu.yml
Labels: Status: Accepted

#17655 Fixes for VOP_READDIR on FreeBSD
  module/os/freebsd/zfs/zfs_ctldir.c
  module/os/freebsd/zfs/zfs_vnops_os.c
Labels: Status: Accepted

#17662 prompt user to unlock when login from dropbear
  contrib/initramfs/hooks/zfsunlock.in
Labels: Status: Accepted

#17329 ZTS: add mount_loopback to test zfs behind loop dev
  tests/runfiles/linux.run
  tests/zfs-tests/include/commands.cfg
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/mount/mount_loopback.ksh
Labels: Status: Accepted

#15869 Add description of default sorting behavior to zfs_list.8
  man/man8/zfs-list.8
Labels: Type: Documentation, Status: Accepted

#17673 Update compatibility.d files for v2.4.0
  cmd/zpool/Makefile.am
  cmd/zpool/compatibility.d/openzfs-2.4
Labels: Status: Accepted

#17675 linux: use sys/stat.h instead of linux/stat.h
  config/user-statx.m4
  include/os/linux/spl/sys/stat.h
  lib/libspl/include/os/linux/sys/stat.h
Labels: Status: Accepted
