Repository openzfs/zfs, pull requests merged in 2025-02, with the labels that each got.

#17013 Avoid unnecessary transform operations during prefetch
  module/zfs/arc.c
Labels: Status: Accepted

#17016 zio: lock parent zios when updating wait counts on reexecute
  module/zfs/zio.c
Labels: Status: Accepted

#17021 Clarify documentation of `zfs destroy` on snapshots
  man/man8/zfs-destroy.8
Labels: Status: Code Review Needed

#17028 Fix typos in zpool_do_scrub() error messages
  cmd/zpool/zpool_main.c
Labels: Status: Accepted

#16986 Expand fragmentation table to reflect larger possibile allocation sizes
  man/man4/zfs.4
  module/zfs/metaslab.c
Labels: Status: Accepted

#17003 Add kstats tracking gang allocations
  module/zfs/zio.c
Labels: Status: Accepted

#16929 optimize recv_fix_encryption_hierarchy()
  lib/libzfs/libzfs_sendrecv.c
  tests/zfs-tests/tests/functional/rsend/send_encrypted_hierarchy.ksh
Labels: Status: Accepted

#16995 Fix "make install" with DESTDIR set
  module/Makefile.in
Labels: Status: Accepted

#17029 zio: do no-op injections just before handing off to vdevs
  module/zfs/zio.c
Labels: Status: Accepted

#17041 Free memory in an error path in spl-kmem-cache.c
  module/os/linux/spl/spl-kmem-cache.c
Labels: Status: Accepted

#17037 Fix metaslab group fragmentation math
  module/zfs/metaslab.c
Labels: Status: Code Review Needed

#17046 vdev_file: unify FreeBSD and Linux implementations
  lib/libzpool/Makefile.am
  module/Kbuild.in
  module/Makefile.bsd
  module/os/freebsd/zfs/vdev_file.c
  module/zfs/vdev_file.c
Labels: Status: Accepted

#17079 Fix wrong free function in arc_hdr_decrypt
  module/zfs/arc.c
Labels: Status: Accepted

#17064 vdev_file: make FLUSH and TRIM asynchronous
  module/zfs/vdev_file.c
Labels: Status: Accepted

#17066 include: move zio_priority_t into zfs.h
  include/Makefile.am
  include/sys/dmu.h
  include/sys/fs/zfs.h
  include/sys/zio.h
  include/sys/zio_priority.h
Labels: Status: Accepted

#17054 suspend_resume_single: clear pool errors on fail
  tests/zfs-tests/tests/functional/fault/suspend_resume_single.ksh
Labels: Status: Accepted

#17081 Better fill empty metaslabs
  module/zfs/metaslab.c
Labels: Status: Accepted

#17088 spa: fix signature mismatch for spa_boot_init as eventhandler required
  include/sys/spa.h
  module/zfs/spa_misc.c
Labels: Status: Accepted

#17080 Don't try to get mg of hole vdev in removal
  module/zfs/vdev_removal.c
  tests/runfiles/common.run
  tests/zfs-tests/tests/Makefile.am
  tests/zfs-tests/tests/functional/removal/removal_with_hole.ksh
Labels: Status: Accepted

#17071 arc: avoid possible deadlock in arc_read
  cmd/zdb/zdb.c
  include/sys/zio.h
  module/zfs/arc.c
  module/zfs/dsl_scan.c
  module/zfs/spa.c
  module/zfs/zio.c
Labels: Status: Accepted

#17042 zpool: allow relative vdev paths
  lib/libzutil/zutil_device_path.c
Labels: good first issue, Status: Accepted

#17098 Linux 6.13 compat: META
  META
Labels: Status: Accepted
